### ISSUE TITLE
General improvements & tweaks for MSVC

### ISSUE THREAD

**Issue by jamboree** [fnc12/sqlite_orm#1]
This is almost a copy/paste from [reddit](https://www.reddit.com/r/cpp/comments/5m894w/check_out_a_new_c_sqlite3_orm_library/dc24vic/), as requested.

General improvements:
* ~~Don't use exception specification anymore, it's deprecated.~~
* ~~Your use of `std::enable_if` in template arg is wrong - it should be `class = std::enable_if_t<cond>` or `std::enable_if_t<cond, bool> = true`, I suggest the latter~~.
* ~~Don't use `template` keyword if the method does not follow by `<..>`, e.g. `obj.f(...)` instead of `obj.template f(...)`~~.
* ~~Mark method `const` if it is, even if it's `constexpr`~~.
* ~~You forgot to include `<cctype>`~~.

Tweaks for MSVC:
* Don't name a variable with the something that's already declared. e.g. you have template `table` and local variable `table`, this confuses MSVC.
* ~~Don't use `decltype(this)`, use the type directly.~~
* ~~Explicitly capture the variables in lambda expr, otherwise MSVC will have problem in finding the variables~~.

**Comment by fnc12** [comment]
removed exception specifications

**Comment by fnc12** [comment]
refactored `enable_if` to optional argument like `typename std::enable_if<cond>:type * = nullptr`

**Comment by fnc12** [comment]
@jamboree didn't find this things in code "Don't name a variable with the something that's already declared. e.g. you have template table and local variable table, this confuses MSVC.". I changed `table` member call with `this->table` to be safe and it turned out that there is no local variable called `table` at all. Could you please provide line number in last commit? Thanks

**Comment by jamboree** [comment]
@fnc12 Sorry it's indeed a data member, didn't look carefully. I think I can just make a pull request to fix the issues.

**Comment by fnc12** [comment]
@jamboree I merged your pull request. I fixed the only thing: replaced `std::bool_constant` with `std::integral_cosntant<bool>` cause `std::bool_constant` is C++17 feature

**Comment by jamboree** [comment]
Yes `this->table` fixed the problem.
