### ISSUE TITLE
about table rowid

### ISSUE THREAD

**Issue by paineZhang** [fnc12/sqlite_orm#100]
Hi!
The sqlite_orm is so cool.
I have a dilemma on branch master, from last commit about rowid.
there is two structure ,that was nested relationship.
example:
![default](https://user-images.githubusercontent.com/36295721/36144256-783b4420-10e8-11e8-80aa-2e1ddcfb7276.png)
The person_attr is not entity.So it has not "id".
I create a relation table for storage person table's id and person_attr table's rowid,when person record inserted into table,that table named as person_attr_relation.
When I get a person record,and get person_attr use code as:

![default](https://user-images.githubusercontent.com/36295721/36144337-b7c898cc-10e8-11e8-8d66-5ba0707976a4.png)

You can imagine, that I got an error is "column not found". Because "rowid()" produce a "rowid" without any table's name.
So,i learned the way to get the table's name .
I add semo methods, as:
![default](https://user-images.githubusercontent.com/36295721/36144132-11152810-10e8-11e8-9e4a-a7e5d2cf4d45.png)

![default](https://user-images.githubusercontent.com/36295721/36144167-30abfd98-10e8-11e8-9b28-ebf25b98d848.png)

![default](https://user-images.githubusercontent.com/36295721/36144191-45162c40-10e8-11e8-99af-e8a087a9f2a6.png)

Then I change "rowid()" to "rowid<person_attr>()", and it works. haha
![default](https://user-images.githubusercontent.com/36295721/36144370-ce4c336a-10e8-11e8-9db3-33c94ac4a49e.png)

I need use rowid, and some times  have to let it with table name.
Is there has an other way? Or I did the right thing? /:P

**Comment by fnc12** [comment]
Nice case. What is your target sqlite raw query? I mean, can you describe image https://user-images.githubusercontent.com/36295721/36144337-b7c898cc-10e8-11e8-8d66-5ba0707976a4.png as SQL query please? I would help me to get more info about your case in common to understand how can I add this feature in the lib. Thanks

**Comment by fnc12** [comment]
@paineZhang also please provide your `make_storage` call

**Comment by paineZhang** [comment]
A ha! Ofcourse.
Sql query is:
```
SELECT  'person_attr'."mail" 
FROM  'person_attr'  
LEFT JOIN  'person_attr_relation' 
ON rowid =  'person_attr_relation'."r_id"
WHERE ( 28 =  'person_attr_relation'."l_id")
```
And I expect it like that:
```
SELECT  'person_attr'."mail" 
FROM  'person_attr'  
LEFT JOIN  'person_attr_relation' 
ON 'person_attr'.rowid =  'person_attr_relation'."r_id"
WHERE ( 28 =  'person_attr_relation'."l_id")
```
The make_storage call is :
![default](https://user-images.githubusercontent.com/36295721/36182914-dccbd02a-1166-11e8-8540-460e778e4627.png)

person_attr_relation was a simple template class :

![default](https://user-images.githubusercontent.com/36295721/36183090-b8465a08-1167-11e8-931e-c03b13feabcf.png)

Hopefully that helps. /:)

**Comment by fnc12** [comment]
This makes sense. I'll add `rowid` with table name in the evening

**Comment by fnc12** [comment]
@paineZhang please check out the latest commit - I've added `table_rowid_t`
