### ISSUE TITLE
Can't  std::shared_ptr be used for updates?

### ISSUE THREAD

**Issue by liwei1024** [fnc12/sqlite_orm#1004]
```c++
struct Table {
    std::shared_ptr<u64> id;
    std::shared_ptr<std::string> filed1;
};

make_table<Table>("table",
        make_column("id", &SettleModel::id, autoincrement(), primary_key()),
        make_column("filed1", &Table::filed1)
        )


//There is no user-defined transformation operator that can be used to perform the transformation, or the operator cannot be invoked  

storage.update_all<Table>(
set(
    assign(&Table::filed1, "123456") 
    )
);

assign(&Table::filed1, "123456") 

assign(&Table::filed1, std::make_shared<std::string>(std::string("123456"))

C(&Table::filed1) = "123456"

C(&Table::filed1) = std::make_shared<std::string>(std::string("123456")
```

**Comment by fnc12** [comment]
Not sure. Why don't you just create a shared pointer and pass a dereferenced shared pointer into your statement? It will work for sure and you'll have your shared pointer

**Comment by liwei1024** [comment]
> Not sure. Why don't you just create a shared pointer and pass a dereferenced shared pointer into your statement? It will work for sure and you'll have your shared pointer
I'm sorry, I didn't catch your meaning

**Comment by fnc12** [comment]
You question is: I have `std::shared_ptr` and it doesn't work as an ordinary values. Can I use `std::shared_ptr` as ordinary value in `sqlite_orm` statement?

You can get an ordinary value by dereferencing `std::shared_ptr` using prefix `*` operator.

Also did you test `assign(&Table::filed1, "123456")`? it also must work

**Comment by liwei1024** [comment]
storage.update_all<Table>(); Can't work


storage.update_all();Can work

**Comment by fnc12** [comment]
please provide the whole code to reproduce

**Comment by liwei1024** [comment]
Thank you for your prompt reply
My problem is solved
It is my Visual Studio that has a problem. It does not prompt an error in time
