### ISSUE TITLE
> If you want to know whether something is wrong inside a storage please use SQLite return codes instead.

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#1025]
> If you want to know whether something is wrong inside a storage please use SQLite return codes instead.

Please tell me how I can know SQLITE return code from the following code:

```C++
                 bool started_local_transaction = false;
                try {
                    started_local_transaction = this->start_migration();

                    this->create_table(db, backupTableName, tableImpl);

                    this->copy_table(db, tableImpl.table.name, backupTableName, tableImpl, columnsToIgnore);

                    this->drop_table_internal(tableImpl.table.name, db);

                    this->rename_table(db, backupTableName, tableImpl.table.name);

                    this->commit_migration(started_local_transaction);

                } catch(const std::exception&) {
                    this->abort_migration(started_local_transaction);
                    if(!started_local_transaction) {
                        // restore DB state
                        if(this->table_exists(backupTableName)) {
                            this->drop_table_internal(backupTableName, db);
                        }
                    }
                    throw;
                }
```

In this case we create a table with backup name, then attempt to copy from main table, which can easily throw exceptions when a DB constraint is violated... if this exception isn't trapped then we leave backup tables in the database all over! this is why we call rollback() or if you insist in no transaction (even when the user calls sync_schema from outside a transaction) is used, then we can manually drop the backup table..

What's wrong with using exceptions inside a library?? I don't see it..

we need to call rollback() because we dropped a table and we need to undo that.. if that throws something really bad is hapenning to the DB and no amount of exception handling will be sufficient: the user is with a big problem in his hands!!

_Originally posted by @juandent in https://github.com/fnc12/sqlite_orm/pull/1019#discussion_r861271035_

**Comment by fnc12** [comment]
please stop posing new issues as comments. You have a PR. I will report SPAM and you'll get blocked if you go on with it

**Comment by juandent** [comment]
No need to get agressive Eugene 

I just wanted to highlight a comment 

Juan

Sent from my iPhone
