### ISSUE TITLE
Tests and examples bad include path

### ISSUE THREAD

**Issue by jeresch** [fnc12/sqlite_orm#103]
I am building from the root directory with:
```
cmake .
make
```
I'm getting the error
```
fatal error: 'sqlite_orm.h' file not found
#include "sqlite_orm.h"
```

I believe this is because in the root `CMakeLists.txt`, line 7, the include directory is set to `${CMAKE_CURRENT_SOURCE_DIR}/include`, so examples and tests should be trying to include `sqlite_orm/sqlite_orm.h`.  When I change the inclusions to this, it works.

I'm happy to make the necessary change and make a pull request, but I'm wondering, is it better to change the inclusion path in the example and test files, or is it better to change the path in the root `CMakeLists.txt` file?

**Comment by fnc12** [comment]
It is better to change the inclusion path in the example and test files. Thanks
