### ISSUE TITLE
Delete Row by rowid

### ISSUE THREAD

**Issue by zhangjp0405** [fnc12/sqlite_orm#1035]
How I delete a row in a table according rowid using sqlite-orm

**Comment by fnc12** [comment]
Hi. How would you write it with a raw SQLite?

**Comment by zhangjp0405** [comment]
DELETE FROM tbTempTable WHERE rowid=1;

**Comment by fnc12** [comment]
```c++
storage.remove_all<Type>(where(rowid() == 1));
```

**Comment by zhangjp0405** [comment]
I use it，but error C2678: 二进制“==”: 没有找到接受“sqlite_orm::internal::rowid_t”类型的左操作数的运算符(或没有可接受的转换)

**Comment by zhangjp0405** [comment]
storage.remove_all<tbTemplateTable>(where(rowid() == 1));
I use it ,but vs2017 msvc say it error!

**Comment by zhangjp0405** [comment]
storage.remove_all<Type>(where(is_equal(rowid(), 1)));
I use it，msvc build success, but i find orm could not delete row 1, why?

**Comment by zhangjp0405** [comment]
![微信截图_20220512211213](https://user-images.githubusercontent.com/48978473/168082889-1ea0b1ba-83b6-46b2-9f03-b53f5364675e.png)
![微信截图_20220512211127](https://user-images.githubusercontent.com/48978473/168082894-b0b07ca2-07ae-4bc9-beb1-91efb3fa8860.png)
![微信截图_20220512211017](https://user-images.githubusercontent.com/48978473/168082905-43b64909-5d2d-411e-8ab5-cf1eb2b877df.png)

**Comment by fnc12** [comment]
dunno. Check with a third party SQLite client

**Comment by zhangjp0405** [comment]
I want to update a row data by rowid, but msvc build fail
![微信截图_20220513091346](https://user-images.githubusercontent.com/48978473/168192191-f28d41a9-7db4-43bd-a697-d1dac423bc9c.png)
How would i write it with a sqlite orm

**Comment by fnc12** [comment]
yes because `replace` expected one argument - and object to replace. If you want to call `UPDATE` with `WHERE` use `update_all` instead https://github.com/fnc12/sqlite_orm/blob/master/examples/update.cpp#L70

**Comment by zhangjp0405** [comment]
storage.update_all<tbTemplateTable>(templateItem, where(is_equal(rowid(), iRowId)));
msvc build error, say it syntax error
How would i write it

**Comment by zhangjp0405** [comment]
I deal with it success, your sqlite-orm is no problem, thank you very much! @fnc12

**Comment by zhangjp0405** [comment]
storage.update_all(set(c(&tbTemplateTable::strTemplateName) = pLabDeviceInfo->strTemplateName),
		where(c(&tbTemplateTable::strGUID) == guids[0]));
strTemplateName is std::wstring type
i use it, find can not build success, but std::string type can build success , why

**Comment by fnc12** [comment]
cause if encryption. wstring can be encrypted in different ways. That is why it is up to user. Or you can use built in support which is available if you remove `SQLITE_ORM_OMITS_CODECVT` macro
