### ISSUE TITLE
<codecvt> header are deprecated in C++17.  

### ISSUE THREAD

**Issue by I-love-study** [fnc12/sqlite_orm#1036]
Hi, After I install this library by using `vcpkg` and try to use it in my project (Writing by MSVC), It raise Error:

>'std::codecvt_utf8_utf16<wchar_t,1114111,(std::codecvt_mode)0>': warning STL4017: std::wbuffer_convert, std::wstring_convert, and the <codecvt> header (containing std::codecvt_mode, std::codecvt_utf8, std::codecvt_utf16, and std::codecvt_utf8_utf16) are deprecated in C++17. (The std::codecvt class template is NOT deprecated.) The C++ Standard doesn't provide equivalent non-deprecated functionality; consider using MultiByteToWideChar() and WideCharToMultiByte() from <Windows.h> instead. You can define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.	DormitoryManager	E:\Code\vcpkg\installed\x64-windows\include\sqlite_orm\sqlite_orm.h	8077	

I think it's the same issue with #845 , but It doesn't fix in `No CMake` method.

**Comment by fnc12** [comment]
Hi. Yes `<codecvt>` is deprecated in C++17. You can also control it's appearance in `sqlite_orm` with `#define SQLITE_ORM_OMITS_CODECVT`

**Comment by I-love-study** [comment]
Yes, it's working. Thank you.
