### ISSUE TITLE
Is there a workaround to compile  a big table in 4GB memory device for release version

### ISSUE THREAD

**Issue by yushb0602** [fnc12/sqlite_orm#1038]
I have a table with 18 columns,  It works well in debug version with gcc 11.1, C++ 20 standard. but when I switch to release version,   get a compiling error:
c++: fatal error: Killed signal terminated program cc1plus.
The 4Gb memory is not enough,  When I remove some columns or enlarge into 16GB memory, these cases are workable.

There is a workaround to compile it in 4GB memory hardware ?

```
    auto log =   make_table("Log1",
        make_column("timestamp", &LogRecord::timestamp),
        make_column("trend", &LogRecord::trend),
        make_column("pen1", &LogRecord::pen1),
        make_column("pen2", &LogRecord::pen2),
        make_column("pen3", &LogRecord::pen3),
        make_column("pen4", &LogRecord::pen4),
        make_column("pen5", &LogRecord::pen5),
        make_column("pen6", &LogRecord::pen6),
        make_column("pen7", &LogRecord::pen7),
        make_column("pen8", &LogRecord::pen8),
        make_column("pen9", &LogRecord::pen9),
        make_column("pen10", &LogRecord::pen10),
        make_column("pen11", &LogRecord::pen11)
        /*make_column("pen12", &LogRecord::pen12)
        make_column("pen13", &LogRecord::pen13),
        make_column("pen14", &LogRecord::pen14),
        make_column("pen15", &LogRecord::pen15),
        make_column("pen16", &LogRecord::pen16)
        */
    );

 
    auto storage = make_storage("ogic3.db", tabAlarm, tabEvent,  log);

    storage.sync_schema();
```

**Comment by trueqbit** [comment]
sqlite_orm is of course very template-heavy.

A few questions:
* Does this also happen in a sample program or only in a larger context?
* Are options for multi-processor/parallel compilation in effect?
* Just to see something - did you check the memory usage during compilation?
* Which version of sqlite_orm do you use?
* Could you try the latest dev branch, please?

**Comment by fnc12** [comment]
@yushb0602 are you there?

**Comment by fnc12** [comment]
@yushb0602 are you there?

**Comment by yushb0602** [comment]
Good news, I have tried  the latest dev branch. This issue doesn't exist anymore.

This exists in  the latest in main branch v1.7.1.  The memory grows gradually to more than 16Gb when I monitor by top command. only make it with `make -j1`

**Comment by yushb0602** [comment]
Furthmore,  It takes me about seconds compile for dev branch version, but  about  3 mins for the v1.71 main branch.
Thanks for big improvement!

**Comment by fnc12** [comment]
wow it is very nice. Thanks to @trueqbit for his improvement

**Comment by trueqbit** [comment]
@yushb0602 Would be interesting whether things are still the same for you with the branch from PR #1039!

**Comment by fnc12** [comment]
@Zvicii sorry for delay. Much stuff appear in my life. Let me make a release during this week
