### ISSUE TITLE
How do I do this, having members of typeof (make_storage)

### ISSUE THREAD

**Issue by marriusco** [fnc12/sqlite_orm#1046]
Hi,
How do I do this ?

`
class myclass
{
      ???                                    _Storage1;
      ???                                   _Storage2;
}

myclass:myclass(){
    _Storage1 = make_storage(...);
    _Storage2 = make_storage(...);
}
`

**Comment by marriusco** [comment]
Resolved, I found my solution:

https://github.com/fnc12/sqlite_orm/blob/master/examples/cross_join.cpp

**Comment by vanehu** [comment]
> Resolved, I found my solution:
> 
> https://github.com/fnc12/sqlite_orm/blob/master/examples/cross_join.cpp

useless

**Comment by fnc12** [comment]
@marriusco @vanehu https://github.com/fnc12/sqlite_orm/wiki/FAQ

**Comment by vanehu** [comment]
> @marriusco @vanehu https://github.com/fnc12/sqlite_orm/wiki/FAQ

how to be a class member？ must be a global value?
