### ISSUE TITLE
Operators should be in internal namespace

### ISSUE THREAD

**Issue by kiwixz** [fnc12/sqlite_orm#1047]
Operators defined [here](https://github.com/fnc12/sqlite_orm/blob/fdcc1da46fbd90feb886c0588462a62d29eb5a06/include/sqlite_orm/sqlite_orm.h#L3344) should be in the `internal` namespace (the same one as `expression`) so they can be found by ADL.
Or in the global namespace if you prefer.

Goldbolt if you want to play with it: https://godbolt.org/z/9ofP3rvd4.

Thanks for the awesome library !

**Comment by fnc12** [comment]
@kiwixz please check `dev` branch. It has to be fixed

**Comment by kiwixz** [comment]
Its fixed indeed, thanks!
