### ISSUE TITLE
Add non-const getters to iterator

### ISSUE THREAD

**Issue by kiwixz** [fnc12/sqlite_orm#1048]
Iterator has const operators since #685 (see [here](https://github.com/fnc12/sqlite_orm/blob/fdcc1da46fbd90feb886c0588462a62d29eb5a06/include/sqlite_orm/sqlite_orm.h#L9540)).

This makes it impossible to do in-place update (modify the value and pass it to `update`) when iterating the database.
I think we should add non-const overloads.

Thanks!

**Comment by fnc12** [comment]
hi. Can you provide a small code snippet to repro it please?

**Comment by kiwixz** [comment]
Sure !  Here you go:
```cpp
struct S {
    int id;
    int value;
    int some_other_information;
};

void f() {
    auto db = make_storage(path,
                        make_table("currency",
                                    make_column("id", &S::id, primary_key()),
                                    make_column("value", &S::code),
                                    make_column("some_other_information", &S::some_other_information)));

    for (auto& s : db.iterate<S>()) {
        // get a new value here for the id, so we want to update it in database
        int new_value = 42;

        // easy way (not working, s is actually a const&)
        s.value = new_value;
        db.update(s);

        // longer way (working)
        db.update(S{s.id, new_value, s.some_other_information});
    }
}
```

**Comment by kiwixz** [comment]
I would not want to do that, if I'm allowed to modify the value then it should not be returned to me as a const&.  `const_cast` says "I dont care if I'm not supposed to, I will modify this anyway".

**Comment by fnc12** [comment]
PR https://github.com/fnc12/sqlite_orm/pull/1229

**Comment by fnc12** [comment]
merged. Please check `dev` branch. Also it will be merged into `master` on the next release

**Comment by kiwixz** [comment]
Works great, thanks!
