### ISSUE TITLE
Insert method fails with table with only one string primary key column

### ISSUE THREAD

**Issue by jeresch** [fnc12/sqlite_orm#105]
```
    struct Data {
        std::string str;
    };

    auto storage = make_storage("",
            make_table("data",
                make_column("str", &Data::str, primary_key())
            )
    );

    storage.sync_schema();

    Data d{"hello"};
    storage.insert(d);
```
 gives
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: near "VALUES": syntax error
Abort trap: 6
```
It looks to me like in the insert method around line 6385, the column isn't getting added to the query `columnNames` for some reason.

**Comment by fnc12** [comment]
try `replace` instead of select. `insert` ignores `PRIMARY KEY` column but `replace` inserts all columns. `insert` is created for objects with primary key created by database.

**Comment by fnc12** [comment]
fixed your case for `int` primary key

**Comment by jeresch** [comment]
`replace` works, thanks!

**Comment by fnc12** [comment]
you're welcome. More info can be found [here](https://github.com/fnc12/sqlite_orm/wiki/storage_t%3A%3Areplace)
