### ISSUE TITLE
how can i add a new table into storage

### ISSUE THREAD

**Issue by godLoveY** [fnc12/sqlite_orm#1050]
forexample 

auto storage1 = make_storage(...);
storage1.addTable(make_table("t2", make_column("id", &Employee::id ));

**Comment by fnc12** [comment]
there is no way of changing schema of existing storage at runtime. You can modify `make_storage` call instead. `sqlite_orm` is designed to use static defined schema. Otherwise it would not have such rich features with C++ templates

**Comment by godLoveY** [comment]
您好，邮件已收到

**Comment by fnc12** [comment]
don't know what it is. Any conversation on open source must be performed in English
