### ISSUE TITLE
template function error 

### ISSUE THREAD

**Issue by fool404** [fnc12/sqlite_orm#1059]
std::enable_if_t<std::is_class_v<U>, std::vector<U>>get_rec(W predicate) {
        static_assert(std::is_class_v<U>, "Type U should be class");
        return m_ptrStorage->get_all<U>(predicate);
    }

 const auto vRec = dv.get_rec<status_type>(where(c(&status_type::Get_m_nWorkStationID) == m_nId));

   sqlite_orm.h(1714): error C2679: binary '<<': no operator found that accepts a right-hand operand of type 'const T' (or no acceptable conversion)

**Comment by fool404** [comment]
I found that all the places where the template function is called are getting an error

**Comment by fool404** [comment]
update , get, delelte template function

**Comment by fnc12** [comment]
what's your compiler?

**Comment by fool404** [comment]
vs2017

**Comment by fnc12** [comment]
what C++ standard do you use during compilation?

**Comment by fool404** [comment]
c++14

**Comment by fnc12** [comment]
what branch do you use? Also try to comment out `get_rec` function and try it

**Comment by fool404** [comment]
sqlite_orm v1.3

**Comment by fool404** [comment]
hello, i found this error because my type is not converted.
thanks.
