### ISSUE TITLE
cannot use ‘typeid’ with ‘-fno-rtti’

### ISSUE THREAD

**Issue by namdvt** [fnc12/sqlite_orm#1067]
I cannot build my project with sqlite_orm using cmake due to the issue:
`/usr/local/include/sqlite_orm/sqlite_orm.h:9118:77: error: cannot use ‘typeid’ with ‘-fno-rtti’
 9118 |                 std::type_index thisTypeIndex{typeid(typename H::object_type)};
`
I am using jetson device, Ubuntu 20.04.4 LTS. Please help me to fix.

**Comment by fnc12** [comment]
you need to remove `-fno-rtti` cause `typeid` operator is used in `sqlite_orm` for mapping classes to tables

**Comment by namdvt** [comment]
How can I remove it, I have checked the source code of sqlite_orm and my project, there is no `-fno-rtti`.

**Comment by fnc12** [comment]
Please provide exact steps

**Comment by fnc12** [comment]
@namdvt are you here?

**Comment by namdvt** [comment]
Sorry for late reply. I have already built the sqlite_orm follow the instruction. However I faced that error while compiling my project. Here is the Cmake file
```
cmake_minimum_required(VERSION 3.9.4)

set(PROJECT_NAME my_project)
project(${PROJECT_NAME} VERSION 0.1 LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "-lstdc++fs")

find_package(Qt5 COMPONENTS Core Gui Multimedia MultimediaWidgets Widgets Concurrent REQUIRED)
find_package(OpenCV REQUIRED)
find_package(ncnn REQUIRED)
find_package(SqliteOrm REQUIRED)

set(JSON_BuildTests OFF CACHE INTERNAL "")
# If you only include this third party in PRIVATE source files, you do not
# need to install it when your main project gets installed.
# set(JSON_Install OFF CACHE INTERNAL "")

# Don't use include(nlohmann_json/CMakeLists.txt) since that carries with it
# unintended consequences that will break the build.  It's generally
# discouraged (although not necessarily well documented as such) to use
# include(...) for pulling in other CMake projects anyways.
add_subdirectory(libs/json)

include_directories(
    ${CMAKE_CURRENT_SOURCE_DIR}/include
    ${ncnn_INCLUDE}
    # include sql
    ${SQLite3_INCLUDE_DIRS}
  )

file(GLOB HEADERS ${CMAKE_CURRENT_SOURCE_DIR}/include/*.h)

file(GLOB SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
                  ${CMAKE_CURRENT_SOURCE_DIR}/src/*/*.cpp)

file(GLOB GUIS ${CMAKE_CURRENT_SOURCE_DIR}/src/*.ui 
                ${CMAKE_CURRENT_SOURCE_DIR}/src/ui/*.ui)

add_executable(${PROJECT_NAME} ${SOURCES} ${HEADERS} ${GUIS} ${RESOURCE})

target_link_libraries(${PROJECT_NAME} Qt5::Widgets Qt5::Core Qt5::Gui Qt5::Multimedia Qt5::MultimediaWidgets Qt5::Widgets Qt5::Concurrent)
target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS})
target_link_libraries(${PROJECT_NAME} ncnn)
target_link_libraries(${PROJECT_NAME} nlohmann_json::nlohmann_json)
target_link_libraries(${PROJECT_NAME} sqlite3 sqlite_orm::sqlite_orm)
target_link_libraries(${PROJECT_NAME} stdc++fs)
```
I have tried to fix the error by
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -frtti")
set(LLVM_ENABLE_RTTI ON) 
set(LLVM_ENABLE_EH ON)
target_compile_options(${PROJECT_NAME} PRIVATE "-frtti")
```
But none of these works. However, I only face this issue on Jetpack 5.0 DP.

**Comment by trueqbit** [comment]
Since this is not related to sqlite_orm directly, I don't see how we could be of any help here, unless somebody has already dealt with Jetpack?
To me it seems like default settings in your environment automatically set "-fno-rtti" somewhere, perhaps via system-wide compiler flags (`CXX` environment variable) or a framework that you are using.

**Comment by fnc12** [comment]
@namdvt I agree with Klaus. Looks like you have `-fno-rtti`. It is the only reason of such an error. Also I am sure it is related to Jetpack 5.0 DP

**Comment by namdvt** [comment]
I think so, since I can compile and run my project correctly on other environments. thanks for your support!
