### ISSUE TITLE
Retrieve DOUBLE value from database without rounding off.

### ISSUE THREAD

**Issue by Paras-97** [fnc12/sqlite_orm#1068]
Hi,

In my database I have stored the values of Longitude and Latitude which are, Latitude: -36.407245992265, Longitude: 145.498065019084. Both of them have DOUBLE data type.

To retrieve these values I am using "storage.dump(logs)" but the output for these variable ares rounded off to Latitude: -36.4072 and Longitude: 145.498.

How do I retrieve the values in there exact form, without rounding them off?

Thanks

**Comment by Paras-97** [comment]
I am using storage.dump() to print the values, 
std::cout<<storage.dump(logs)<<std::endl;

Otherwise, to get the data from the table I am using this command.
auto all_logs = log_storage.get_all<BaseLog_>(where(c(&BaseLog_::Id)==id ));
where, log_storage is storage and BaseLog_ is struct.

**Comment by trueqbit** [comment]
Unless you wrap your floating point field in a custom structure, this is currently not possible. The [`field_printer`](https://github.com/fnc12/sqlite_orm/blob/86847fe91c903f4b105c82ec3398ad0c64979fe6/dev/field_printer.h#L38) for arithmetic types uses a `std::stringstream` with the default precision.

**Comment by fnc12** [comment]
```c++
auto all_logs = log_storage.get_all<BaseLog_>(where(c(&BaseLog_::Id)==id ));
for (auto& log : all_logs) {
    double latitude = log.latitude;
    double longitude = log.longitude;
    // next print latitude and longitude variables in any way you want
}
```

**Comment by fnc12** [comment]
@Paras-97 did it work?

**Comment by Paras-97** [comment]
I changed the data type from double to string, to get the exact values.
