### ISSUE TITLE
expand "update_all"

### ISSUE THREAD

**Issue by paineZhang** [fnc12/sqlite_orm#107]
Hi !
I want to update the whole record with rowid, and the table without key.
The `update_all` method is cumbersome.
It usually looks like this：
```
db.update_all(set(assign(&XXX::XXX, XXX),
                            assign(&XXX::XXX, XXX),
                            ..... ),
	where(c(rowid<table>())= rowid));
```
I have to enumerate all the fields in `set` method.
So,is it could expand the `update_all` method to support the update of the whole record?Or, is there an other way for easy coding?

By the way,I really want to see a roadmap for development.  /:)

**Comment by fnc12** [comment]
Please provide SQL query you want to call in your program - it will help me to understand what you want more clearly. And show me your `make_storage` call. Thanks

**Comment by paineZhang** [comment]
My test code：
```
struct person_detail_info {
	string mail;
	int age;
};

struct person {
	int identity; //key
	string name;
	person_detail_info detail_info; // 1 v 1
};

auto create_db() {
	auto db = sqlite_orm::make_storage(
		"./test.sqlite",
		sqlite_orm::make_table(
			"person",
			sqlite_orm::make_column(
				"identity",
				&person::identity,
				sqlite_orm::primary_key()),
			sqlite_orm::make_column(
				"name",
				&person::name)
		),
		sqlite_orm::make_table(
			"person_detail_info",
			sqlite_orm::make_column(
				"mail",
				&person_detail_info::mail),
			sqlite_orm::make_column(
				"age",
				&person_detail_info::age)
		),
		sqlite_orm_make_relational_table(person, person_detail_info) //expand
	);


	auto schema = db.sync_schema();

	db.open_forever();

	return move(db);
}



void test_orm(){

	auto db = create_db();


	db.remove_all<person>();
	db.remove_all<person_detail_info>();
	db.remove_all<sqlite_orm::relation_table<person, person_detail_info>>();

	person p{0,"p0",{"p0@mail.com",0}};

	//单条添加
	db.transaction([&]() mutable {

		try {
			sqlite_orm::relation_table<person, person_detail_info> person_rel;

			//先插入数据
			person_rel.l_id = db.insert(p);

			person_rel.r_id = db.insert(p.detail_info);

			//插入关系
			db.insert(person_rel);

			//判断变更
			bool success = (0 != db.changes());
			assert(success);

			return success;//true commit, false rollback

		} catch (std::runtime_error& error) {
			cout << error.what() << endl;
			return false;
		} catch (...) {
			return false;
		}
	});

	//单条获取
	db.transaction([&]() mutable {

		try {

			//取记录主体
			p = move(db.get<person>(0));

			//取记录主体的rowid
			auto person_rowids = db.select(sqlite_orm::rowid<person>(),
										   sqlite_orm::where(sqlite_orm::c(&person::identity) = p.identity));
			if (1 != person_rowids.size()) {
				assert(0);
				return false;
			}
			
			//取关系对象rowid
			auto rel_rowids = db.select(&sqlite_orm::relation_table<person, person_detail_info>::r_id,
										sqlite_orm::where(sqlite_orm::c(&sqlite_orm::relation_table<person, person_detail_info>::l_id) = person_rowids[0]));
			if (1 != rel_rowids.size()) {
				assert(0);
				return false;
			}

			//取关系数据
			p.detail_info = move(db.get<person_detail_info>(rel_rowids[0]));
			
			return true;//true commit, false rollback

		} catch (std::runtime_error& error) {
			cout << error.what() << endl;
			return false;
		} catch (...) {
			return false;
		}
	});

	//单条更新
	db.transaction([&]() mutable {

		p.name = "p01";
		p.detail_info.mail = "p01@mail.com";
		p.detail_info.age = 2;

		//按整条记录更新
		try {

			db.update(p);

			//取记录主体的rowid
			auto person_rowids = db.select(sqlite_orm::rowid<person>(),
										   sqlite_orm::where(sqlite_orm::c(&person::identity) = p.identity));
			if (1 != person_rowids.size()) {
				assert(0);
				return false;
			}

			//取关系对象rowid
			auto rel_rowids = db.select(&sqlite_orm::relation_table<person, person_detail_info>::r_id,
										sqlite_orm::where(sqlite_orm::c(&sqlite_orm::relation_table<person, person_detail_info>::l_id) = person_rowids[0]));
			if (1 != rel_rowids.size()) {
				assert(0);
				return false;
			}

			//更新关系对象
			db.update_all(sqlite_orm::set(sqlite_orm::assign(&person_detail_info::mail, p.detail_info.mail),
										  sqlite_orm::assign(&person_detail_info::age, p.detail_info.age)),
						  sqlite_orm::where(sqlite_orm::c(sqlite_orm::rowid<person_detail_info>())= rel_rowids[0]));

			bool success = (0 != db.changes());

			assert(success);
			return success;//true commit, false rollback

		} catch (std::runtime_error& error) {
			cout << error.what() << endl;
			return false;
		} catch (...) {
			return false;
		}
	});
}
```

When I use `update_all` on update a person_detail_info record.

About `roadmap`,I mean is:The features release plan。When will it be released for the first time?
We are looking forward to using it in our production environment. /:)

**Comment by fnc12** [comment]
If I understand you right you want to store `person` class and `person_detail_info` with 1 to 1 relation and chain them with `ROWID`. Why don't you chain them with `person` id? It would look like this:
```c++
#include <cassert>

struct person_detail_info {
    std::string mail;
    int age;
    int person_id;
};

struct person {
    int identity; //key
    std::string name;
    person_detail_info detail_info; // 1 v 1
};

using namespace sqlite_orm;

auto storage = make_storage("storage.sqlite",
                            make_table("person",
                                       make_column("identity",
                                                   &person::identity,
                                                   primary_key()),
                                       make_column("name",
                                                   &person::name)),
                            make_table("person_detail_info",
                                       make_column("mail",
                                                   &person_detail_info::mail),
                                       make_column("age",
                                                   &person_detail_info::age),
                                       make_column("person_id",
                                                   &person_detail_info::person_id,
                                                   primary_key()),
                                       foreign_key(&person_detail_info::person_id).references(&person::identity)));

int main() {
    
    storage.sync_schema();
    
    person p{0,"p0",{"p0@mail.com",0}};
    
    //  insert person with his/her details
    auto pId = storage.insert(p);
    p.detail_info.person_id = pId;
    storage.replace(p.detail_info);
    
    //  get person with details
    auto p2 = storage.get<person>(pId);
    p2.detail_info = storage.get<person_detail_info>(p2.identity);
    
    assert(p2.detail_info.mail == p.detail_info.mail && p2.detail_info.age == p.detail_info.age);
    
    return 0;
}
```

About roadmap: there is a brief [TODO list](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md) in the repo. It doesn't contain dates but you can leave there a desired feature with PR and just email me. Right now I'm working at [error code issue](https://github.com/fnc12/sqlite_orm/issues/46) and once it is done I'll make a release of 1.0 version. I can tell you nothing about dates cause I have a primary job and `sqlite_orm` is a free time work. Please stay subscribed to know about new commits and PRs. Thanks

**Comment by fnc12** [comment]
@paineZhang is the question still actual?

**Comment by paineZhang** [comment]
Sorry for the delay！！！
Your suggestion is beyond dispute on the question.
Use `ROWID` to chain them ，that the reasons behind it are a bit complicated.
The data that needs to be persisted is usually as part of the interface of a module.
Some data structure is not entity，that is nested in other different data structures.
For example：
```
struct address{
string country;
string province;
string city;
};

struct person{
int id；
address home_address ;
};

struct company{
int id；
address office address;
};

```
And other reasons:
Foreign keys and reactions can cause more problems.this is not allowed in most cases,in the company.
An update method provided by an interface is usually faced with a record, rather than a field.
Sometimes there may be some design mistakes.
Blah blah blah.  /:(

So,I have to consider some more general and easy to understand usage.
Of course, it would be very exciting if the library could provide automated relationship processing. /:)

Oh,of course.The question is not vitally important. /:)

About roadmap,I see.Pay tribute to your work again. /:)

**Comment by paineZhang** [comment]
Well. The second point.
In fact, that's what I've been trying to do.

**Comment by fnc12** [comment]
Ok. But I still cannot understand why implicit relationship settings can be better than explicit relationship settings. Explicit relationship settings add clarity to your code and allow you interacting with your database file with any sqlite client without unexpected schema artifacts easily.

**Comment by paineZhang** [comment]
Frankly that is related to my work environment and content.
The application is  embedded software.It only involves simple persistence.Unlike that server provide data to client as data module.Although explicit relationship settings can control more complicate.
Most of my team members don't master database technology.I would like to focus more effort on the develop business functions of module.So,the know less is better what details of the data persistence process.This is very helpful to improve the efficiency of work.

In fact, the deeper meaning of this topic is “provide more high level APIs”,that means try to hide all the details and make it easier to use.Like `insert(const O &o)` 、`update(const O &o)` and `replace(const O &o)`.
The reason for this suggestion is that：
When I use the library to get familiar with it.With all due respect,the usage of most API that looks a bit like the translation of the SQL syntax.It means that the user still need to master some SQL syntax.

I tried to pack SQL syntax in a chain call style. It is like `select().from().where().limit()`.This style guides the user to what they want.It can also achieve that goal of not require users to master the SQL syntax.But I failed because of circular references. HAHA...


That's all. /:)
Thanks!

**Comment by fnc12** [comment]
Ok, now I see your wishes. If it turned out that you're the only one SQL master in your team you can easily create you own storage derived class with higher level APIs. First of all make `inline auto initStorage()` function that returns `make_storage` result. Next make `using _Storage = decltype(initStorage());`. Now you have `_Storage` type that is equal to `sqlite_orm` storage type for your schema. Next create your own class that inherits from `_Storage` and implement your custom `insert`, `update`, `remove` etc:
```c++
class Storage: public _Storage {
    using super = _Storage;

    int update(const person &p) {
        auto personId = this->super.update(p);
        this->super.remove_all<address>(where(is_equal(&address::person_id, personId));
        this->super.replace(p.address);
    }
};
```

And now your colleagues can just `update` person without understanding how this sh*t works inside and it will update both person and its address.

**Comment by paineZhang** [comment]
Yeah!That's exactly what I'm doing.

Thanks again！
