### ISSUE TITLE
IN operator can support list?

### ISSUE THREAD

**Issue by tocky0** [fnc12/sqlite_orm#1070]
when use `in` operator in where conditions,as flow, 
```
std::list<int> user_ids;
getStorage().get_all<User, std::list<User>>(where(in(&User::m_user_id, user_ids)));
```
the where conditions `user_ids` type is `std::list`, will build code fail, exception like,
```
SqliteTools.hpp:9535:29: error: ‘sqlite_orm::internal::statement_serializator<std::__cxx11::list<int>, void> serializator’ has incomplete type
   statement_serializator<T> serializator;
```
when replace with `std::vector<int> user_ids`, build ok.  
so how to fix it?  
thinks~

**Comment by fnc12** [comment]
we need to add either support for `std::list<T>` or for generic STL container

**Comment by fnc12** [comment]
@tocky0 I am working on it

**Comment by fnc12** [comment]
@tocky0 PR is on its way https://github.com/fnc12/sqlite_orm/pull/1226

**Comment by fnc12** [comment]
@tocky0 please check `dev` branch - now `std::list` is supported by `in` function
