### ISSUE TITLE
How to set default value with current timestamp?

### ISSUE THREAD

**Issue by tocky0** [fnc12/sqlite_orm#1071]
For field `modified`, sql statements may like this,
```
CREATE TABLE Persons (
  // id or other, etc
  `modified` datetime  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'modify timestamp',
);
```
When update it, will trigger update field `modified` with current timestamp. 
so use `sqlite_orm`, the `default_value` can resolve it ?

**Comment by tocky0** [comment]
That is,  
1 when first insert, will `DEFAULT CURRENT_TIMESTAMP`  
2 when update record later, will `ON UPDATE CURRENT_TIMESTAMP`  
`sqlite_orm` can do this?
Thanks~

**Comment by fnc12** [comment]
@tocky0 what is `COMMENT 'modify timestamp'`? What does `COMMENT` mean here?

**Comment by fnc12** [comment]
@tocky0 PR is on its way https://github.com/fnc12/sqlite_orm/pull/1232

**Comment by fnc12** [comment]
@tocky0 done in `dev` branch. `default_value(current_timestamp())` will do the trick
