### ISSUE TITLE
MSVC 2019 Compile error

### ISSUE THREAD

**Issue by masoudr** [fnc12/sqlite_orm#1072]
Hi,
I'm trying to build the project (dev branch) against MSVC 2019, but after I generate the CMAKE and open the solution, at the build time I get the following error for `sqlite_orm.h`.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3493	'ss' cannot be implicitly captured because no default capture mode has been specified (compiling source file C:\Users\Masoud\Desktop\sqlite_orm-dev\tests\storage_tests.cpp)	unit_tests	C:\Users\Masoud\Desktop\sqlite_orm-dev\include\sqlite_orm\sqlite_orm.h	18458	
Error	C3481	'ss': lambda capture variable not found (compiling source file C:\Users\Masoud\Desktop\sqlite_orm-dev\tests\storage_tests.cpp)	unit_tests	C:\Users\Masoud\Desktop\sqlite_orm-dev\include\sqlite_orm\sqlite_orm.h	18458	
```

**Comment by fnc12** [comment]
Hi. This is a phantom error which must be fixed but cannot be repro by me. Please show me IDE screenshot to provide more information

**Comment by masoudr** [comment]
If you need more information let me know:
![Capture](https://user-images.githubusercontent.com/6974428/183250638-05f99b52-70c7-4021-b3c7-a92f2a88e3a5.PNG)

**Comment by fnc12** [comment]
nice. Please show me sources with error highlight.

**Comment by masoudr** [comment]
![Capture](https://user-images.githubusercontent.com/6974428/183250783-7431e7b1-546d-4ec1-911a-7111cb3823ef.PNG)

**Comment by fnc12** [comment]
please try `msvc-fix` branch and tell me whether error is appearing

**Comment by fnc12** [comment]
@masoudr please pull and try again

**Comment by masoudr** [comment]
![Capture](https://user-images.githubusercontent.com/6974428/183625552-6b28b606-77fb-4422-94d7-ea6b7a7d1ed5.PNG)

**Comment by fnc12** [comment]
@masoudr please pull the branch and try again

**Comment by masoudr** [comment]
@fnc12 I tried to build the solution, and it was built without any errors, but the output folder is empty. It seems that it only builds the test solution. Which solution do I need to build to access header and linker files?

**Comment by fnc12** [comment]
you don't need to build anything cause it is header only library. If you want to use `sqlite_orm` in your project just add `include` folder from the repo in the path where you store project 3rd party libs or just add path to `include` folder to header search path in your project settings
