### ISSUE TITLE
`order_by()` sorting integers as strings

### ISSUE THREAD

**Issue by minorsecond** [fnc12/sqlite_orm#1091]
I have a class set up like so:

```
class Drink {
private:
    int id;
    std::string name;
    int rating;

 friend class Database;
}
```

and the DB instance is set up like so:

```
inline auto initStorage(std::string &file_name) {
  return sqlite_orm::make_storage(file_name,
             sqlite_orm::make_table("Drinks",
                 sqlite_orm::make_column("id", &Drink::id, sqlite_orm::autoincrement(), sqlite_orm::primary_key()),
                 sqlite_orm::make_column("name", &Drink::name),
                 sqlite_orm::make_column("rating", &Drink::rating));
}
```

Elsewhere in my code, I'm trying to do a selection based on some columns and order by the rating:

```
auto result = storage.get_all<Drink>(where(c(&Drink::rating) >= rating
    and c(&Drink::sort_date) >= start_date
    and c(&Drink::sort_date) <= end_date
    group_by(&Drink::name),
    order_by(&Drink::rating).asc());
```

It's sorting the ratings like so:

```
9
8
8
8
10
```

Is there a way to fix this?

**Comment by fnc12** [comment]
it depends on how to fix this with raw SQLite. It is not related to `sqlite_orm`. Try to google how to do it with raw SQLite. Example v

**Comment by minorsecond** [comment]
Is `CAST` available in sqlite_orm?

**Comment by fnc12** [comment]
yes. try `cast<int>(...)`

**Comment by minorsecond** [comment]
That's what I've tried.,. `order_by(cast<int>(&Drink::rating))` but still get `10` at the end and not at the beginning like I would expect.

**Comment by fnc12** [comment]
try it out with raw SQLite first to be sure what you want to implement with `sqlite_orm`. This is how I fix SQLite issues during work. Once it is done I can help you adapting SQL to C++ with `sqlite_orm`

**Comment by minorsecond** [comment]
Thanks. The issue ended up actually being a sorting feature in the GUI widget I was displaying the results in. When debugging, the results vector was in the correct order after adding `cast`. So, thanks for your help!
