### ISSUE TITLE
How to deal with “The database disk image is malformed” exception？

### ISSUE THREAD

**Issue by jimmy930513** [fnc12/sqlite_orm#1095]
I found that somtimes my device crashed because this exception.
But I can't deal with simple catch this exception.How can I recovery this db file?

**Comment by fnc12** [comment]
I don't know. You better ask this question on SQLite forum not `sqlite_orm` cause `sqlite_orm` is just a frontend for SQLite

**Comment by fnc12** [comment]
closing cause it cannot be fixed within `sqlite_orm`. If you have any useful info you can always post it here or you can reopen this bug if you are sure that something can be done within `sqlite_orm`
