### ISSUE TITLE
The count of column

### ISSUE THREAD

**Issue by SmileWangYu** [fnc12/sqlite_orm#1097]
hello，
I found g++ would report error **[internal command error: segmentation fault signal terminated program cc1plus]** while **the count of column is more than 20(the count may be larger)**, I guess that template recursive may cause the problem.
![1666251539714](https://user-images.githubusercontent.com/67865209/196886562-d3d42143-934b-430a-9267-4eccdf6d4458.jpg)
![1666251526646](https://user-images.githubusercontent.com/67865209/196886583-ee1b2644-04c4-42ec-b997-33679c6f105b.jpg)
![1666251605596](https://user-images.githubusercontent.com/67865209/196886683-c75dc7e8-2f8e-4a60-b30d-bff5a8bc02be.jpg)

**Comment by fnc12** [comment]
ok looks like you have to report it go gcc team. The only thing I can advice you is to use clang instead

**Comment by trueqbit** [comment]
@SmileWangYu You might want to try v1.8.1 or the latest dev branch.
