### ISSUE TITLE
library integration with fetch_content throws at submodule update

### ISSUE THREAD

**Issue by Alex-dev02** [fnc12/sqlite_orm#1099]
Hi! I tried to replicate the installation process from examples/fetch_content, but with a few modifications which I find nonrelatable to my problem (but if someone thinks they are necessary, I will update my issue, but all I have done was to modify the hierarchy of the folder a little bit). 
When I try to run cmake configure, it throws the following error (I am running the build on windows 10 btw):

```
cmake ..
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Performing update step for 'sqliteorm-populate'
  HEAD is now at feb237d Merge pull request #1076 from fnc12/removed-has-dependent-rows
  fatal: No url found for submodule path 'tests/_deps/catch2-src' in .gitmodules
  CMake Error at C:/myproject/build/_deps/sqliteorm-subbuild/sqliteorm-populate-prefix/tmp/sqliteorm-populate-gitupdate.cmake:272 (execute_process):
    execute_process failed command indexes:
  
      1: "Child return code: 128"
  
  
  
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(245,5): error MSB8066: Custom build for 'C:\myproject\build\_deps\sqliteorm-subbuild\CMakeFiles\77adcca34d425fa652be5b2cbcacc50c\sqliteorm-populate-update.rule;C:\myproject\build\_deps\sqliteorm-subbuild\CMakeFiles\77adcca34d425fa652be5b2cbcacc50c\sqliteorm-populate-patch.rule;C:\myproject\build\_deps\sqliteorm-subbuild\CMakeFiles\77adcca34d425fa652be5b2cbcacc50c\sqliteorm-populate-configure.rule;C:\myproject\Desktop\Intrebator\build\_deps\sqliteorm-subbuild\CMakeFiles\77adcca34d425fa652be5b2cbcacc50c\sqliteorm-populate-build.rule;C:\myproject\build\_deps\sqliteorm-subbuild\CMakeFiles\77adcca34d425fa652be5b2cbcacc50c\sqliteorm-populate-install.rule;C:\myproject\build\_deps\sqliteorm-subbuild\CMakeFiles\77adcca34d425fa652be5b2cbcacc50c\sqliteorm-populate-test.rule;C:\myproject\build\_deps\sqliteorm-subbuild\CMakeFiles\fc6fab01aac355c7d3ea1e3a3b0496f2\sqliteorm-populate-complete.rule;C:\myproject\build\_deps\sqliteorm-subbuild\CMakeFiles\0ba4a3fce33ce475aeca1a1280dc576f\sqliteorm-populate.rule' exited with code 1. [C:\myproject\build\_deps\sqliteorm-subbuild\sqliteorm-populate.vcxproj]

CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FetchContent.cmake:1087 (message):
  Build step for sqliteorm failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.22/Modules/FetchContent.cmake:1216:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.22/Modules/FetchContent.cmake:1216 (cmake_language)
  C:/Program Files/CMake/share/cmake-3.22/Modules/FetchContent.cmake:1259 (FetchContent_Populate)
  db/dependencies/sqlite_orm/CMakeLists.txt:3 (FetchContent_MakeAvailable)


-- Configuring incomplete, errors occurred!
```
How may I fix it?

**Comment by fnc12** [comment]
@Alex-dev02 dunno. I need help of folks here

**Comment by Alex-dev02** [comment]
> @Alex-dev02 dunno. I need help of folks here

Also, sorry for bothering. I know this is not related to this issue, but what else do I have to do in order to use the library along with cmake and find_package, beside adding sqlite3 to path?

**Comment by fnc12** [comment]
Actually I don't know how `find_package` works cause I am not a cmake pro. Most people usually use conan, vcpkg, cmake without `find_package` or manual including single header

**Comment by Alex-dev02** [comment]
> Actually I don't know how `find_package` works cause I am not a cmake pro. Most people usually use conan, vcpkg, cmake without `find_package` or manual including single header

Oh, got it. Actually the problem wasn t related to find_package itself, I tried to add sqlite3 to path (and it works) and now if I want to run "cmake -B build"  after clonning the repo, I get this error ```CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message): Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)```

**Comment by fnc12** [comment]
https://stackoverflow.com/a/41642102/1927176 point 2 from here looks perfect for your case and doesn't use `find_package`

**Comment by trueqbit** [comment]
@Alex-dev02 As for your other question how to use sqlite_orm with cmake.

First of all, you can of course use a C++ library package manager like vcpkg, and take it from there.

Otherwise, when you build and install sqlite_orm, _packaging/CMakeLists.txt_ copies _cmake/SqliteOrmConfig.cmake.in_ to cmake's package directory. Then it should be just a matter of using the right targets.
I recommend reading the [readme](../blob/master/README.md), and taking a look at the ['find package'](../blob/master/examples/find_package) and ['fetch content'](../blob/master/examples/fetch_content) examples.

This is the output of vcpkg after installing the sqlite-orm port:
```
sqlite-orm provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(SqliteOrm CONFIG REQUIRED)
    target_link_libraries(main PRIVATE sqlite_orm::sqlite_orm)
```

BTW, there's also great documentation available on how [finding packages](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Finding%20Packages.html) works.
