### ISSUE TITLE
for update database version

### ISSUE THREAD

**Issue by nut799** [fnc12/sqlite_orm#11]
Hi, Thanks for this library. 
I wonder that is there some function could handle  database migrations  case.
I add or del a column in my table in next version.
So when my app started, I need check table version.
migration old data into new table. like this.
[http://www.electronic-designer.co.uk/visual-cpp-cli-dot-net/databases/sqlite/pragma/user_version-pragma](url)

**Comment by fnc12** [comment]
Hi. I'm very pleased this library is useful for you. You can perform add/remove column migration without deleting data with `storage.sync_schema(true);` call.

**Comment by fnc12** [comment]
You can copy and paste your storage code here with new version of a desired storage and I can assist you how to perform migration with no losing data.

**Comment by fnc12** [comment]
@nut799 your link gives 404

**Comment by fnc12** [comment]
Bump. Is the issue still actual? Add or del column if perfectly handled by `sync_schema(true)` without hitting your data. So please if there is still some issues left type it here or close the issue. Thanks

**Comment by fnc12** [comment]
closing as answered
