### ISSUE TITLE
How to cross compile on arm arch?

### ISSUE THREAD

**Issue by kexinmm** [fnc12/sqlite_orm#1104]
lihuili@soft114:~/sqlite_orm/sqlite_orm-master$ cmake -B build-rv1109
-- CROSS_COMPILE is arm-linux-gnueabihf-
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /home/lihuili/pl2117/prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /home/lihuili/pl2117/prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/lihuili/pl2117/prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /home/lihuili/pl2117/prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SQLITE_ORM: Build with C++14 features
-- Configuring sqlite_orm 1.6.0
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SQLite3 (missing: SQLite3_LIBRARY) (found version "3.31.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindSQLite3.cmake:52 (find_package_handle_standard_args)
  dependencies/sqlite3/CMakeLists.txt:2 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/lihuili/sqlite_orm/sqlite_orm-master/build-rv1109/CMakeFiles/CMakeOutput.log".

**Comment by denzor200** [comment]
Have you tried to cross compile an application with raw SQLite, without sqlite_orm?

**Comment by fnc12** [comment]
I agree. Looks like you have issues with linking to SQLite. It is not related to `sqlite_orm`

**Comment by kexinmm** [comment]
yes, I have successful to cross compile an application with raw sqlite3 .h/.so files, without sqlite_orm. But I don't know how to modify the CMakeLists.txt, to use my sqlite3 files:
find_package(SQLite3 REQUIRED)
target_link_libraries(sqlite_orm INTERFACE SQLite::SQLite3)

here my file:
lihuili@soft114:/usr/local/share/compiler/rv1109/sysroot$ ls usr/include/sqlite3* -l
-rwxrwxrwx+ 1 root root  31022 八月   26 09:31 usr/include/sqlite3ext.h
-rwxrwxrwx+ 1 root root 510272 八月   26 09:31 usr/include/sqlite3.h
lihuili@soft114:/usr/local/share/compiler/rv1109/sysroot$ ls usr/lib/libsqlite3* -l
-rwxrwxrwx+ 1 root root   1046 八月   26 09:31 usr/lib/libsqlite3.la
lrwxrwxrwx  1 root root     19 八月   26 09:32 usr/lib/libsqlite3.so -> libsqlite3.so.0.8.6
lrwxrwxrwx  1 root root     19 八月   26 09:32 usr/lib/libsqlite3.so.0 -> libsqlite3.so.0.8.6
-rwxrwxrwx+ 1 root root 733652 八月   26 09:31 usr/lib/libsqlite3.so.0.8.6

**Comment by kexinmm** [comment]
I resolved this problem through only using sqlite_orm.h file.
