### ISSUE TITLE
Prepared statements for classes with private members

### ISSUE THREAD

**Issue by Alex-dev02** [fnc12/sqlite_orm#1105]
Hi!
Does this library support prepared statements for objects having private members?
For example, I have this class:
```
class User {
public:
 User() = default;
 ...
 int GetId() const;
 std::string GetName() const;
 void SetId(int id);
 void SetName(std::string name);
private:
 int id;
 std::string name;
}
```
And the corresponding working database definition.
How can I run a prepared statement so I can find a user by its id?
I tried:
```auto res = database.prepare(select(&User::GetId, where(c(&User::GetName == searched_name))));```
But I get an error saying that "argument of type int(User::*)() const is incompatible with parameter of type int" (at the User::GetId reference).
Same for comparing &User::GetName == searched_name, can t compare a ref to a function with a string.

**Comment by fnc12** [comment]
Hi. Looks like a bug. Could you provide minimum code for reproducing it? Thanks

**Comment by Alex-dev02** [comment]
Sure. Here I writed some code to reproduce the bug:
```
#include <sqlite_orm/sqlite_orm.h>

#include <string>

class User {
public:
	User(const std::string& name)
		: 
		m_id(-1),
		m_name(name)
	{}
	void SetId(int id) { m_id = id; }
	void SetName(const std::string& name) { m_name = name; }

	int GetId() { return m_id; }
	std::string GetName() { return m_name; }

private:
	int m_id;
	std::string m_name;
};

int main() {
	using namespace sqlite_orm;
	auto storage = make_storage("test",
		make_table("user",
			make_column("id", &User::GetId, &User::SetId, autoincrement(), primary_key()),
			make_column("name", &User::GetName, &User::SetName,unique())
		));
	storage.sync_schema();
	std::string searched_name = "andrew";
	auto res = storage.prepare(select(&User::GetId, where(c(&User::GetName != searched_name))));

}
```
Apparently, I forgot to use the namespace for select in my own environment, but the problem with comparing &User::GetName and searched_name still persists.

**Comment by Alex-dev02** [comment]
Extremely sorry, it was just a namespace problem. Sorry for wasting your time :(
