### ISSUE TITLE
"Fetch Content" doesn't work because of catch2-src

### ISSUE THREAD

**Issue by zafirovicmilan2** [fnc12/sqlite_orm#1107]
I tried to open "fetch_content" (opened CMakeLists.txt from "fetch_content") and cmake configuration failed because it cannot fetch "catch2-src":

```
fatal: No url found for submodule path 'tests/_deps/catch2-src' in .gitmodules
CMake Error at sqliteorm-subbuild/sqliteorm-populate-prefix/tmp/sqliteorm-populate-gitclone.cmake:62 (message):
  Failed to update submodules in:
  '/home/zafirovicmilan2/Downloads/build-fetch_content-Desktop_Qt_6_4_1_gcc-Debug/_deps/sqliteorm-src'
```

cmake 3.25.1
g++/gcc 11.3.0

**Comment by rotolof** [comment]
It seems to be a dangling submodule path that has no entry in `.gitmodules`.
@fnc12 I think it can be fixed in the repo with `git rm --cached tests/_deps/catch2-src`.

@zafirovicmilan2 A quick fix for you is pass the `GIT_SUBMODULES` parameter with an empty string to FetchContent:

```cmake
FetchContent_Declare(
  sqlite_orm
  GIT_REPOSITORY https://github.com/fnc12/sqlite_orm.git
  GIT_TAG v1.8
  GIT_SUBMODULES ""
)
```

**Comment by trueqbit** [comment]
@zafirovicmilan2 Does PR https://github.com/fnc12/sqlite_orm/pull/1121 (into dev) or the v1.8.1 release solve the problem?

**Comment by rotolof** [comment]
@trueqbit I'm using v1.8.1, it does solve the issue (at least for me).

I'm using the following code in my CMakeLists.txt:
```cmake
  FetchContent_Declare(
    sqlite_orm
    GIT_REPOSITORY https://github.com/fnc12/sqlite_orm.git
    GIT_TAG v1.8.1
    GIT_SHALLOW true
  )
```
