### ISSUE TITLE
[Question/Suggestion] Throw Error If Data Will Be Deleted

### ISSUE THREAD

**Issue by jakemumu** [fnc12/sqlite_orm#1109]
Hey -- revisiting this library after a long time and continuing to research it for a project. 

I noticed as I'm working on a local db, if I change a field, the database can have its data ruthlessly dropped which is quite scary. 

Is there a way to have sync_schema tell me if I've coded things in such a way it will drop data when updating the local DB? Perhaps like:

sync_schema(preserve, throw_error_on_deletion)

I think if I say preserve is true, sqlite_orm should never delete information, opting to throw an error instead of deleting data. This gives the developer to fix their instructions, perhaps a default value is needed etc, before creating an irreversible action. 

Also -- my feedback would be to pick a sensible default for the user if none is provided, instead of dropping an entire table

**Comment by fnc12** [comment]
Hi @jakemumu . You have two options.
1. Call `storage.sync_schema_simulate` to know what happens if you call `sync_schema`.
2. Use `sqlite_orm_plus` proprietary library which is `sqlite_orm` with real migrations API. Using it costs 1k$ per year per project

**Comment by fnc12** [comment]
@jakemumu do you have anything else here or we can close the issue?

**Comment by juandent** [comment]
Dear Eugene Last time I checked sync_schema_simulate does not always return an accurate response as to if it is going to be data loss if executedIt is my recommendation that you either correct this or advice to users of how this is not always reliableRegardsJuanSent from my iPhoneOn 8 Oct 2023, at 8:35 AM, Yevgeniy Zakharov ***@***.***> wrote:﻿
@jakemumu do you have anything else here or we can close the issue?

**Comment by juandent** [comment]
At the very least I would warn users to do one schema change at a time if they want to have some degree of reliability to the schema simulate function In my tests multiple changes to the schema bring dificulty to figuring out if data will be deletedRegardsJuanSent from my iPhoneOn 8 Oct 2023, at 2:19 PM, Juan Dent ***@***.***> wrote:﻿Dear Eugene Last time I checked sync_schema_simulate does not always return an accurate response as to if it is going to be data loss if executedIt is my recommendation that you either correct this or advice to users of how this is not always reliableRegardsJuanSent from my iPhoneOn 8 Oct 2023, at 8:35 AM, Yevgeniy Zakharov ***@***.***> wrote:﻿
@jakemumu do you have anything else here or we can close the issue?

**Comment by juandent** [comment]
This is sent with all my good intentions Please say hi to assel from Leslie and I RegardsJuanSent from my iPhoneOn 8 Oct 2023, at 2:19 PM, Juan Dent ***@***.***> wrote:﻿Dear Eugene Last time I checked sync_schema_simulate does not always return an accurate response as to if it is going to be data loss if executedIt is my recommendation that you either correct this or advice to users of how this is not always reliableRegardsJuanSent from my iPhoneOn 8 Oct 2023, at 8:35 AM, Yevgeniy Zakharov ***@***.***> wrote:﻿
@jakemumu do you have anything else here or we can close the issue?

**Comment by fnc12** [comment]
@juandent let's fix the difference between `sync_schema` and `sync_schema_simulate`. How can I repro the difference?
