### ISSUE TITLE
Compile errors: sqlite_orm_VERSION "1.8.0",  use not_single_header_include

### ISSUE THREAD

**Issue by kexinmm** [fnc12/sqlite_orm#1113]
When I choose use not_single_header_include, I got many errors, please help me:
/usr/local/lihuili/pl2117/src/libdatasync/../../sysroot/../prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ --sysroot=/usr/local/lihuili/pl2117/src/libdatasync/../../sysroot -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -D_TARGET_DEVICE -I/usr/local/lihuili/pl2117/build/libdatasync -I/usr/local/lihuili/pl2117/src/libdatasync -I/usr/local/lihuili/pl2117/build/libdatasync/datasync_autogen/include -I/usr/local/lihuili/pl2117/src/libdatasync/../include -I/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5 -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtWidgets -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtGui -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtCore -isystem /usr/local/lihuili/pl2117/sysroot/usr/../qt/mkspecs/devices/linux-buildroot-g++ -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtDBus -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unused-result -O3 -Wno-psabi -fPIC -std=gnu++17 -O0 -MD -MT CMakeFiles/datasync.dir/DataBaseUtil_O0.cpp.o -MF CMakeFiles/datasync.dir/DataBaseUtil_O0.cpp.o.d -o CMakeFiles/datasync.dir/DataBaseUtil_O0.cpp.o -c /usr/local/lihuili/pl2117/src/libdatasync/DataBaseUtil_O0.cpp
In file included from /usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/./ast_iterator.h:12,
                 from /usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/./view.h:11,
                 from /usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/./storage.h:43,
                 from /usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/sqlite_orm.h:33,
                 from /usr/local/lihuili/pl2117/src/libdatasync/DataBaseUtil.h:8,
                 from /usr/local/lihuili/pl2117/src/libdatasync/DataBaseUtil.cpp:15:
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/./prepared_statement.h:25:13: error: ‘connection_ref’ does not name a type
             connection_ref con;
             ^~~~~~~~~~~~~~
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/./prepared_statement.h:79:70: error: ‘connection_ref’ has not been declared
             prepared_statement_t(T expression_, sqlite3_stmt* stmt_, connection_ref con_) :
                                                                      ^~~~~~~~~~~~~~
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/./prepared_statement.h:135:29: error: ‘set_t’ was not declared in this scope
         struct update_all_t<set_t<Args...>, Wargs...> {
                             ^~~~~

**Comment by fnc12** [comment]
what are the steps you are performing for this?

**Comment by kexinmm** [comment]
[libdatasync-1.8.0.tar.gz](https://github.com/fnc12/sqlite_orm/files/10302081/libdatasync-1.8.0.tar.gz)
1. I copied all sqlite_orm-1.8/dev files to my sqlite_orm\
2. I modified  not_single_header_include/sqlite_orm/sqlite_orm.h, and cp sqlite_orm.h to my sqlite_orm\
3. cd libdatasync and make
sqlite_orm\

**Comment by kexinmm** [comment]
Can I cp the content of dev/*.h to sqlite_orm.h of single header include, when lack something?For example, connection_holder.h

**Comment by kexinmm** [comment]
I trid to use single header include sqlite_orm.h, but there were many errors, but they were defined, for example, internal::count_tuple, defined at line 1183, why?

1.6.0 is ok
1.8.0 is not ok

following part of log:
/usr/local/lihuili/pl2117/src/libdatasync/../../sysroot/../prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ --sysroot=/usr/local/lihuili/pl2117/src/libdatasync/../../sysroot -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -D_TARGET_DEVICE -I/usr/local/lihuili/pl2117/build/libdatasync -I/usr/local/lihuili/pl2117/src/libdatasync -I/usr/local/lihuili/pl2117/build/libdatasync/datasync_autogen/include -I/usr/local/lihuili/pl2117/src/libdatasync/../include -I/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5 -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtWidgets -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtGui -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtCore -isystem /usr/local/lihuili/pl2117/sysroot/usr/../qt/mkspecs/devices/linux-buildroot-g++ -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtDBus -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unused-result -O3 -Wno-psabi -fPIC -std=gnu++17 -MD -MT CMakeFiles/datasync.dir/datatables.cpp.o -MF CMakeFiles/datasync.dir/datatables.cpp.o.d -o CMakeFiles/datasync.dir/datatables.cpp.o -c /usr/local/lihuili/pl2117/src/libdatasync/datatables.cpp
In file included from /usr/local/lihuili/pl2117/src/libdatasync/DataBaseUtil.h:8,
                 from /usr/local/lihuili/pl2117/src/libdatasync/DataBaseUtil_O0.cpp:15:
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/sqlite_orm.h: In function ‘sqlite_orm::sqlite_orm::internal::insert_raw_t<Args ...> sqlite_orm::sqlite_orm::insert(Args ...)’:
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/sqlite_orm.h:11506:25: error: ‘sqlite_orm::sqlite_orm::internal::count_tuple’ has not been declared
         using internal::count_tuple;
                         ^~~~~~~~~~~
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/sqlite_orm.h:11507:25: error: ‘sqlite_orm::sqlite_orm::internal::is_columns’ has not been declared
         using internal::is_columns;
                         ^~~~~~~~~~
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/sqlite_orm.h:11509:25: error: ‘sqlite_orm::sqlite_orm::internal::is_into’ has not been declared
         using internal::is_into;
                         ^~~~~~~
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/sqlite_orm.h:11510:25: error: ‘sqlite_orm::sqlite_orm::internal::is_select’ has not been declared
         using internal::is_select;
                         ^~~~~~~~~
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/sqlite_orm.h:11511:25: error: ‘sqlite_orm::sqlite_orm::internal::is_upsert_clause’ has not been declared
         using internal::is_upsert_clause;
                         ^~~~~~~~~~~~~~~~
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/sqlite_orm.h:11512:25: error: ‘sqlite_orm::sqlite_orm::internal::is_values’ has not been declared
         using internal::is_values;
                         ^~~~~~~~~
/usr/local/lihuili/pl2117/src/libdatasync/sqlite_orm/sqlite_orm.h:11514:37: error: ‘count_tuple’ was not declared in this scope

**Comment by fnc12** [comment]
> I copied all sqlite_orm-1.8/dev files to my sqlite_orm\

why did you do that? What target you want to use: single header or not single header?

**Comment by kexinmm** [comment]
I have used sqlite_orm for many years since 2019. I always only used single header file sqlite_orm.h to feed my need of reading or writing sqlite database. Here is my first file, it is very useful:
[sqlite_orm.zip](https://github.com/fnc12/sqlite_orm/files/10305534/sqlite_orm.zip)

**Comment by fnc12** [comment]
if you want to use single header then you don't have to touch contents of `dev` folder. Just use `include` folder

**Comment by kexinmm** [comment]
When I just use include folder, there are many errors.

**Comment by fnc12** [comment]
> When I just use include folder, there are many errors.

What kind of errors?

**Comment by kexinmm** [comment]
[make_error_1.8.0.log](https://github.com/fnc12/sqlite_orm/files/10334434/make_error_1.8.0.log)
Please read file make_error_1.8.0.log

**Comment by kexinmm** [comment]
Please help me, or I will can not use the following new versions.

**Comment by fnc12** [comment]
looks like you misuse something with header path. Step `I copied all sqlite_orm-1.8/dev files to my sqlite_orm\` is wrong. You have to either include `sqlite_orm` as a cmake submodule if your project is cmake based or just include single header in a header search path.

**Comment by kexinmm** [comment]
I have tried these two method, any one has many errors. Make_error_1.8.0.log is  just include single header in a header search path.

**Comment by fnc12** [comment]
ok. Looks like you are missing some steps in the message where you posted your steps cause everyone has it working. Which steps you are performing exactly?

**Comment by kexinmm** [comment]
Can I support my source code base on v1.6.0 sqlite_orm.h which can complile ok on x64 arch? And please you replace with v1.8.0 sqlite_orm.h, to find reason of not work?

**Comment by fnc12** [comment]
you can try. I can't say what happens in this case cause I don't know how your project uses `sqlite_orm`

**Comment by kexinmm** [comment]
I have tried and got some results, I think the problem is the differance between compilers?
1) do not change my project source codes
2) use V1.8.0 single header sqlite_orm.h
3) compile on ubuntu22.04 using GCC 11.3.0 x86_64-linux-gnu, it works!
4)  compile on arm using gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf, it generates many errors, the first error is:
/usr/local/lihuili/pl2117/src/libdatasync-1.8.0/../../sysroot/../prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ --sysroot=/usr/local/lihuili/pl2117/src/libdatasync-1.8.0/../../sysroot -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -D_TARGET_DEVICE -I/usr/local/lihuili/pl2117/build/libdatasync-1.8.0 -I/usr/local/lihuili/pl2117/src/libdatasync-1.8.0 -I/usr/local/lihuili/pl2117/build/libdatasync-1.8.0/datasync_autogen/include -I/usr/local/lihuili/pl2117/src/libdatasync-1.8.0/../include -I/usr/local/lihuili/pl2117/src/libdatasync-1.8.0/sqlite_orm -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5 -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtWidgets -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtGui -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtCore -isystem /usr/local/lihuili/pl2117/sysroot/usr/../qt/mkspecs/devices/linux-buildroot-g++ -isystem /usr/local/lihuili/pl2117/sysroot/usr/include/qt5/QtDBus -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unused-result -O3 -Wno-psabi -fPIC -std=gnu++17 -O0 -MD -MT CMakeFiles/datasync.dir/DataBaseUtil_O0.cpp.o -MF CMakeFiles/datasync.dir/DataBaseUtil_O0.cpp.o.d -o CMakeFiles/datasync.dir/DataBaseUtil_O0.cpp.o -c /usr/local/lihuili/pl2117/src/libdatasync-1.8.0/DataBaseUtil_O0.cpp
In file included from /usr/local/lihuili/pl2117/src/libdatasync-1.8.0/DataBaseUtil.h:8,
                 from /usr/local/lihuili/pl2117/src/libdatasync-1.8.0/DataBaseUtil.cpp:15:
/usr/local/lihuili/pl2117/src/libdatasync-1.8.0/sqlite_orm/sqlite_orm.h:11068:17: error: ‘connection_ref’ does not name a type
                 connection_ref con;
                 ^~~~~~~~~~~~~~
/usr/local/lihuili/pl2117/src/libdatasync-1.8.0/sqlite_orm/sqlite_orm.h:11122:78: error: ‘connection_ref’ has not been declared
                     prepared_statement_t(T expression_, sqlite3_stmt* stmt_, connection_ref con_) :

**Comment by fnc12** [comment]
well looks like compiler is the reason. Cal you try clang as well?

**Comment by kexinmm** [comment]
I cannot try clang on  gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf, because there is no clang for arm.

**Comment by fnc12** [comment]
IDK how can I help you here cause this issue is not related to `sqlite_orm` but to compiler

**Comment by kexinmm** [comment]
The sqlite_orm.h of V1.6.0 is ok on  gcc-arm-8.3, but V1.8.0 is not ok, you used some new features of GCC?

**Comment by fnc12** [comment]
I know nothing about gcc. I test the lib with clang on Xcode locally and run CI on clang and vc++

**Comment by fnc12** [comment]
quick googling tells me that clang exists for ARM https://llvm.org/docs/HowToBuildOnARM.html . Otherwise how Xcode works on mac m1?

**Comment by kexinmm** [comment]
![微信截图_20230117091603](https://user-images.githubusercontent.com/18020542/212788714-b9f407fc-d8d9-4ffc-a9d8-6c2740ba10f3.png)
I mean there are no clang-xx files on my arm prebuilts.

**Comment by fnc12** [comment]
well I can't help you with your prebuilts whatever you. Compiler exists, it works, you don't use it. Nothing related to `sqlite_orm` here actually

**Comment by kexinmm** [comment]
Thank you very much! I will try more to resolve this problem.
