### ISSUE TITLE
Compile error: catch2 too old

### ISSUE THREAD

**Issue by KoNekoD** [fnc12/sqlite_orm#1114]
ERROR:
In file included from /home/autumn/Downloads/sqlite_orm-1.8/tests/tests.cpp:5:
/home/autumn/Downloads/sqlite_orm-1.8/build/_deps/catch2-src/single_include/catch2/catch.hpp:10877:45: ошибка: размер массива «altStackMem» не является целочисленным константным выражением
10877 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
gmake[2]: *** [tests/CMakeFiles/unit_tests.dir/build.make:494: tests/CMakeFiles/unit_tests.dir/tests.cpp.o] Ошибка 1
gmake[2]: выход из каталога «/home/autumn/Downloads/sqlite_orm-1.8/build»
gmake[1]: *** [CMakeFiles/Makefile2:941: tests/CMakeFiles/unit_tests.dir/all] Ошибка 2
gmake[1]: выход из каталога «/home/autumn/Downloads/sqlite_orm-1.8/build»
gmake: *** [Makefile:149: all] Ошибка 2

HOW I FIXRD:
> [sqlite_orm](https://github.com/fnc12/sqlite_orm)/[dependencies](https://github.com/fnc12/sqlite_orm/tree/master/dependencies)/CMakeLists.txt

`catch2
        GIT_REPOSITORY https://github.com/catchorg/Catch2.git
-        GIT_TAG v2.13.2
+       GIT_TAG v2.13.5
    )`

Please fix this problem

**Comment by fnc12** [comment]
I'll do it soon. Thanks

**Comment by trueqbit** [comment]
@fn12 I am in the process of updating to Catch2 v3 as part of the vcpkg port update.

**Comment by trueqbit** [comment]
@KoNekoD Does PR #1121 (into dev) and the v1.8.1 release solve your problem?
