### ISSUE TITLE
How to not set "NOT NULL" when create a table?

### ISSUE THREAD

**Issue by kexinmm** [fnc12/sqlite_orm#1116]
I don't want all cols are "NOT NULL", but why now?
make_table("TB_FACE_INFO",
						make_column("face_id", &Tb_face_info::face_id, primary_key()),
						make_column("user_name", &Tb_face_info::user_name),
						make_column("user_code", &Tb_face_info::user_code),
						make_column("user_ext_code", &Tb_face_info::user_ext_code),
						make_column("face_filename", &Tb_face_info::face_filename),
						make_column("face_feature", &Tb_face_info::face_feature),						
						make_column("create_time", &Tb_face_info::create_time),
						make_column("status", &Tb_face_info::status),
						make_column("nickname", &Tb_face_info::nickname),
						make_column("englishname", &Tb_face_info::englishname),
						make_column("idcard", &Tb_face_info::idcard),
						make_column("nation", &Tb_face_info::nation),
						make_column("birth", &Tb_face_info::birth),
						make_column("sex", &Tb_face_info::sex),
						make_column("addr", &Tb_face_info::addr),
						make_column("agency", &Tb_face_info::agency),
						make_column("valid_date", &Tb_face_info::valid_date),
						make_column("idwlt", &Tb_face_info::idwlt),
						make_column("idcard_cid", &Tb_face_info::idcard_cid),
						make_column("empcard", &Tb_face_info::empcard),
						make_column("tel", &Tb_face_info::tel),
						make_column("remark1", &Tb_face_info::remark1),
						make_column("remark2", &Tb_face_info::remark2),
						make_column("remark3", &Tb_face_info::remark3),
						make_column("feature_url", &Tb_face_info::feature_url),
						make_column("feature_md5", &Tb_face_info::feature_md5)

create_table CREATE TABLE 'TB_FACE_INFO_VERSION' ( 'ver_id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL , 'version' TEXT NOT NULL , 'total_number' INTEGER NOT NULL , 'create_time' TEXT NOT NULL , 'remark1' TEXT NOT NULL , 'remark2' TEXT NOT NULL , 'remark3' TEXT NOT NULL )

**Comment by fnc12** [comment]
in that case you have yo specify nullable type: `std::unique_ptr`, `std::shared_ptr`, `std::optional` or to bind your custom type

**Comment by kexinmm** [comment]
Can I set "NOT NULL" or unset "NOT NULL"  when make_column?  Add a new and explicit constraint？

**Comment by fnc12** [comment]
right now - no. But I can add it. Why do you need it?

**Comment by kexinmm** [comment]
Because only part of cols need NOT NULL in my project, but I can‘t  set now.

**Comment by kexinmm** [comment]
[sqlite_orm-1.6.tgz.zip](https://github.com/fnc12/sqlite_orm/files/10390703/sqlite_orm-1.6.tgz.zip)
I tried to add not null myself, please read sqlite_orm-1.6.tgz.zip, find key word "lihuili".

**Comment by fnc12** [comment]
does it work? if yes just post a PR to `dev` branch

**Comment by kexinmm** [comment]
Sorry, I tried the code, it didn't work.

**Comment by kexinmm** [comment]
> right now - no. But I can add it. Why do you need it?

If you will, please add a new and explicit constraint of "NOT NULL".

**Comment by fnc12** [comment]
@kexinmm ok I'll do it soon

**Comment by Brouilles** [comment]
Same, 80% of my columns are optional. How I can do the migration to allow nullable?

**Comment by fnc12** [comment]
@kexinmm @Brouilles PR is fresh and hot https://github.com/fnc12/sqlite_orm/pull/1230

**Comment by fnc12** [comment]
@kexinmm @Brouilles check `dev` branch. Not one can use `null()` and `not_null()` constraints explicitly
