### ISSUE TITLE
Map two types to the same table object

### ISSUE THREAD

**Issue by acidtonic** [fnc12/sqlite_orm#1123]
I am dealing with a framework that gives me a DTO object that has the fields I am mapping into sqlite_orm.

When mapping and doing many operations I have the object itself as MyDTO. Thus I have mapping MyDTO::id, MyDTO::name, etc.

In another area of the framework I get the same object but it has a wrapper type around it called DTOWrapper<MyDTO> and I cannot cast directly but this type has all of the exact same methods and functions as MyDTO.

Is there a way to tell sqlite_orm to simply let me pass either object and have it treated the same?

Otherwise I have to manually create another MyDTO and manually go through and assign each DTOWrapper<MyDTO> field to the class. Is this possible?

**Comment by fnc12** [comment]
you can try to add two tables to the storage with the same names. But it is not designed to work like that actually. Also you can try to make two storages with tables mapped to different types but with the same names

**Comment by fnc12** [comment]
@acidtonic did it work?
