### ISSUE TITLE
Use calculated values of fields in where clause

### ISSUE THREAD

**Issue by jmorrill** [fnc12/sqlite_orm#113]
Curious if using calculated values in the where class is supported.

What I want to accomplish is this in code:

select rowid, timestamp from events where **(timestamp + duration) >= 1518603970462706**

The pseudo code I'm trying to do is this:

`where(c(&eventdb_record_internal::timestamp) + &eventdb_record_internal::duration >= start_time`

**Comment by fnc12** [comment]
It is bad idea cause ORM must transfer query to the database as is. In your case you expect ORM to place timestamp instead of sending `CURRENT_TIMESTAMP` function. This is incorrect cause my code doesn't know what timestamp SQLite is gonna return cause it is different code.

P.S. I can add plus and other arithmetic operations cause it looks like you need them

**Comment by jmorrill** [comment]
I may not have given a great description of what I'm trying to do.  
I do not want to use the sqlite "CURRENT_TIMESTAMP" function.  The "timestamp" stuff is just an int column I have.

I want to use a two (or more) row's column values in an expression.

For instance the raw sql would look like this:
`select price, tax from orders where **price + tax** > 5.00`

I would imagine your ORM code would look something like this (but does not currently work):
storage.iterate<order>(where(c(&order::price) + c(&order::text) >5.00)

**Comment by fnc12** [comment]
Ok, I see. Your wish exists in [todo](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md) and you're the first who's asking about it. So I'm gonna add this thing in `dev` branch today or tomorrow maybe.

**Comment by jmorrill** [comment]
You are awesome. Thanks a bunch for all your work here!

**Comment by fnc12** [comment]
You're welcome. Let's leave the issue opened until the job is done

**Comment by fnc12** [comment]
please check out `dev` branch. I've merged `+`, `-`, `*`, `/` and `%` operators with tests in https://github.com/fnc12/sqlite_orm/pull/118.

**Comment by jmorrill** [comment]
Wow you work fast :)!

Looks like it is working, with my limited testing for my specific case!

`where(lesser_or_equal(sub(start_time, &eventdb_record_internal::duration), &eventdb_record_internal::timestamp)`...

The intent of my query is that I have an "event" that is timestamped and has a duration.  When I query for events, I want to take the "duration" into account.  So if an "event" was timestamped at "12:05" and the duration was for 10 minutes, a query for timestamp of 12:06 would pick up that event.
 
Thank you so much, this is VERY cool!
