### ISSUE TITLE
This will result in an error. Why

### ISSUE THREAD

**Issue by liwei1024** [fnc12/sqlite_orm#1133]
````
auto sets =  set(c(&CardModel::if_online) = 0);
auto wheres =  where( is_equal(&CardModel::if_online, true));
update_all(sets, wheres);
````

auto sets =  set(c(&CardModel::if_online) = 0); // Syntax error
auto sets =  set(c(&CardModel::if_online) = 1); // Syntax normal

auto sets =  set(c(&CardModel::if_online) = false); // Syntax error
auto sets =  set(c(&CardModel::if_online) = true); // Syntax normal

**Comment by trueqbit** [comment]
Hi @liwei1024,

did you read your compiler's error messages?
`0` is convertible to multiple things. Why do you want to use integer values when you can use boolean?
BTW, ` set(c(&CardModel::if_online) = false)` compiles.

**Comment by fnc12** [comment]
@liwei1024 what compiler errors do you get?

**Comment by liwei1024** [comment]
> @liwei1024你得到什么编译器错误？

I'm sorry, it's my fault. The IDE prompt had an error, but it actually compiled successfully

**Comment by liwei1024** [comment]
![image](https://user-images.githubusercontent.com/24514245/216087608-731cac6c-8504-4bc7-a7c8-fbab10a6e036.png)
