### ISSUE TITLE
Primary key as general constraint is wonky

### ISSUE THREAD

**Issue by BardurArantsson** [fnc12/sqlite_orm#114]
Hi!

It seems that the primary key support is kind of wonky if you don't specify the primary_key() directly on a column/columns.

For example `remove<C>(id)` produces the broken SQL 
```
DELETE FROM "FOO" WHERE 
```

i.e. it omits the key columns. I believe that's because it simply iterates over the columns looking for the primary key "flag" rather than using `impl.table.primary_key_column_names()`. However, just changing that naïvely doesn't work either, I *think* because the loop that is supposed to bind the query parameters has the same issue. *EDIT*: Update() looks like it might suffer from a similar problem with the parameter binding.

Here's a small commit which reproduces the problem with `remove` in the unit test code:

https://github.com/BardurArantsson/sqlite_orm/commit/7f0c9de95b8e3d12f6318f28543fa8be722f1051

**Comment by fnc12** [comment]
fixed in `dev` branch. Please leave it open until fix isn't merged in master (until next release)

**Comment by fnc12** [comment]
merged in 1.1 release
