### ISSUE TITLE
GCC Compatability

### ISSUE THREAD

**Issue by yotamkr** [fnc12/sqlite_orm#1145]
I worked on a code using GCC 10, and now am required to compile it in GCC 6.4.

I have a compilation error regarding adding new rows (the insert function). It seems the "table" member is not added, and then I have an error that the object does not have this member.
There are no errors when using "get" or "update" functions.

Has someone encountered this before?
On which GCC versions was the code validated on?

Thanks,
Yotam

**Comment by fnc12** [comment]
please show the errors

**Comment by yotamkr** [comment]
For exmaple,
I created a class called Level.

I added the class to the db, and get the following error in compilation:

sqlite_orm/include/sqlite_orm/sqlite_orm.h:16064:21: error: binding ‘const Level’ to reference of type ‘Level&’ discards qualifiers
                     [&table, &ss, &context, &object = get_ref(statement.object), first = true](auto& column) mutable {

**Comment by fnc12** [comment]
and you say that the same code works well with GCC16?

**Comment by yotamkr** [comment]
I tried it now with G++ 7.4 and it works (thought it was a GCC issue, but looks like a G++ one).
Seems that in g++ 6.4 it does not, and when forcing CMAKE to use 7.4 it works fine and the error vanishes.

**Comment by fnc12** [comment]
it looks weird. Could you provide your code which produces the error?

**Comment by yotamkr** [comment]
[sqlite_compilation_test.zip](https://github.com/fnc12/sqlite_orm/files/10782384/sqlite_compilation_test.zip)

**Comment by yotamkr** [comment]
Any updates?

**Comment by trueqbit** [comment]
Hi @yotamkr,

Since the error happens with a now quite old gcc compiler, I suspect it's a compiler bug? You said it compiles fine with a later version, right?

- Can you please create a minimally reproducible example similar to the one below?
- Can you please provide the full error message stack?
- It's also important to know which version or commit of sqlite_orm you are using.

BTW on a entirely other note, the primary key column may never be null, except for historical reasons?


```c++
#include <sqlite_orm/sqlite_orm.h>

using namespace sqlite_orm;

int main() {
    struct Level {
        int64 _id;
        int _levelInd;
    };

    auto levelTable = make_table<Level>("Level",
                                        make_column("id", &Level::_id, primary_key().autoincrement()),
                                        make_column("level_ind", &Level::_levelInd));
    auto dbStorage = make_storage("", levelTable);

    Level level1 = {1, 1};
    auto expression = update(level1);

    std::string sql = dbStorage.dump(expression);

    return 0;
}
```

**Comment by yotamkr** [comment]
I attached the log file.
Regarding the primary key, I just assume it is auto-incremented after insertion, which is why I did not give it a value manually.

[log.txt](https://github.com/fnc12/sqlite_orm/files/10919525/log.txt)

**Comment by trueqbit** [comment]
It seems this is a bug of gcc 6 and earlier, see test example on [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:2,positionColumn:1,positionLineNumber:2,selectionStartColumn:1,selectionStartLineNumber:2,startColumn:1,startLineNumber:2),source:'int+main()+%7B%0A++++const+int+i+%3D+5%3B%0A++++%5B%26object+%3D+i%5D()%7B%7D%3B%0A%0A++++return+0%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:56.42973412913727,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:g64,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B14',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+6.4+(Editor+%231)',t:'0')),k:49.68966776108964,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+6.4',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'0'),l:'5',n:'0',o:'Output+of+x86-64+gcc+6.4+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:43.57026587086273,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

**Comment by trueqbit** [comment]
Regarding the primary key I was just wondering that you are using a `unique_ptr`.
