### ISSUE TITLE
UpdateOrInsert() method?

### ISSUE THREAD

**Issue by mmuruev** [fnc12/sqlite_orm#116]
Cant find updateOrInsert method, like in hibernate .saveOrUpdate().  Will be useful have it.

**Comment by fnc12** [comment]
[storage::replace](https://github.com/fnc12/sqlite_orm/wiki/storage_t%3A%3Areplace)

**Comment by mmuruev** [comment]
So weird name why?

**Comment by fnc12** [comment]
cause it exists in SQLite ([link](https://www.sqlite.org/lang_replace.html)) as a shorter version of `

**Comment by fnc12** [comment]
When I was adding `UPSERT` command I faced is that SQLite version of this query is `INSERT OR REPLACE` or just `REPLACE`. That's why. I know that `REPLACE` doesn't exist in other SQL relations databases but `sqlite_orm` is about SQLite only. [link](https://www.sqlite.org/lang_replace.html)

**Comment by fnc12** [comment]
@mmuruev is the issue actual?
