### ISSUE TITLE
Update failed if the table has no any fields, but primary key.

### ISSUE THREAD

**Issue by aksenofo** [fnc12/sqlite_orm#1162]
If we use a table with **no extra fields but primary key**, we cannot use update.
Exception shows native sqlite error:
_near "WHERE": syntax error: SQL logic error_

 
 line 12195: auto query = serialize(upd, context);
indicates in variable **query** follow string:
_"UPDATE 'LtPlRegular' SET WHERE \"id\" = ? "_
I think **SET WHERE**  is wrong.

**Comment by fnc12** [comment]
yes. What is desired behavior from your side in this case?

**Comment by fnc12** [comment]
> Is there the way to distinguish fields but unique key ?

yes we can do it at runtime and compile time

> But, I would delete word SET if there is no any SET-able fields. That will bring another type of error, but it possible make understanding more obvious.

If we add static asset then we'll not have to change serialization cause we'll never get to the point of serialization of this ill-formed query. So I'd fix it with static assert. Better catch this error at compile time

**Comment by fnc12** [comment]
@aksenofo  PR is on its way https://github.com/fnc12/sqlite_orm/pull/1238

**Comment by fnc12** [comment]
hey @aksenofo . Please check how it works: it perfectly produces `static_assert` in your case. Thanks for reporting. You are making `sqlite_orm` even better!
