### ISSUE TITLE
Can we just use single quote?

### ISSUE THREAD

**Issue by omnine** [fnc12/sqlite_orm#1168]
```
#include <iostream>
#include "sqlite_orm.h"
//#include "sqlite3.h"
//#include "sqlite3mc.h"

using namespace sqlite_orm;

struct User {
    int id;
    std::string name;
    int age;
};

int main() {
    auto storage = make_storage("test.db",
                                make_table("users",
                                    make_column("id", &User::id, primary_key()),
                                    make_column("name", &User::name),
                                    make_column("age", &User::age)
                                ));
    storage.sync_schema();
    return 0;
}
```

The piece of code above will generate this query string,

`"SELECT COUNT(*) FROM sqlite_master WHERE type = \"table\" AND name = 'users'"`

I just wonder if we can use single quote on `type='table'` as well, instead of escaping the double quote?

Please see the details in 

[no such column: table: SQL logic error](https://github.com/utelle/SQLite3MultipleCiphers/issues/106)

**Comment by fnc12** [comment]
@omnine I see. Let me fix this

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/pull/1169

**Comment by fnc12** [comment]
@omnine please check `dev` branch

**Comment by omnine** [comment]
@fnc12 thank you for the quick action. Now I see,

`"SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = 'users'"`

which is what I expected.
