### ISSUE TITLE
VS2015 build failed

### ISSUE THREAD

**Issue by FarafontovDmitriy** [fnc12/sqlite_orm#117]
In VS2015 build failed. I tried to compile the following example
```
#include <sqlite_orm.h>

using namespace sqlite_orm;

struct UserType 
{
	int id;
	std::string name;
};

int main()
{
	UserType t = { -1, "name" };

	auto storage = make_storage("db.sqlite",
		make_table("user_types",
			make_column("id",
				&UserType::id),
			make_column("name",
				&UserType::name)));

	storage.sync_schema();

	t.id = storage.insert(t);

	cout << t.id << endl;

	system("pause");
	return 0;
}
```
I get the following error : Error	C1001	An internal error has occurred in the compiler (sqlite_orm.h	line 2814)
Tell me what could be wrong ...

**Comment by fnc12** [comment]
which branch do you use? Try `dev` branch

**Comment by FarafontovDmitriy** [comment]
I use master. Well, now I'll try!

**Comment by FarafontovDmitriy** [comment]
Did not help ... The error remained ...

**Comment by fnc12** [comment]
what C++ standard do you use in compilation?

**Comment by FarafontovDmitriy** [comment]
I use c++14. I also tried to build a library in VS2017 (supports with C++17). Assembly is also failed.

**Comment by fnc12** [comment]
please try `dev` again and please tell me which line of source code fails.

**Comment by FarafontovDmitriy** [comment]
The problem is solved. As it turned out in VS2015 (Update 1-2) does not fully support with c++14. Full support only in VS2015 (Update 3).
