### ISSUE TITLE
Unable To Create Statement 

### ISSUE THREAD

**Issue by jakemumu** [fnc12/sqlite_orm#1172]
Hi! 

I've been struggling all night be able to create this statement and I'm starting to feel I'm going crazy : / 

In SQL: 

``` sql
SELECT "wavetable"."uuid", "tag"."name"
FROM "wavetable"
JOIN "tagging" ON ("tagging"."taggable_uuid" = "wavetable"."uuid")  
JOIN "tag" ON ("tag"."uuid" = "tagging"."tag_uuid")
WHERE  "tag"."name" = ? AND "wavetable"."wavetable_pack_id" = ?
```

^ this is working in raw SQL

In sqlite_orm: 

``` c++
auto statement = db->getStorage()->prepare(
    select(columns(&STORABLE::uuid, &STORABLE::display_name),
        inner_join<MKUDBTagging>(on(c(&MKUDBTagging::taggable_uuid) == &STORABLE::uuid)),
        inner_join<MKUDBTag>(on(c(&MKUDBTag::uuid) == &MKUDBTagging::tag_uuid)),
        where(c(&MKUDBTag::name) == tag.name) and c(&STORABLE::pack_id) == pack.uuid));
```

This is creating errors: near "(": syntax error: SQL logic error

It's hard because I can't figure out how to print the statement, I just get the error

**Comment by jakemumu** [comment]
Missing a ()!!!

**Comment by fnc12** [comment]
@jakemumu 
to print a statement write
```c++
cout << db->dump(statement) << endl;
```

**Comment by jakemumu** [comment]
> BTW, in such cases I recommend to dump the expression before even preparing it, so that you can get the SQL string before an error is thrown:
> 
> ```c++
> 
> auto expression = select(/**/);
> 
> std::string sql = db->getStorage()->dump(expression);
> 
> ```

This is what I was missing thanks so much gonna write my queries like that!
