### ISSUE TITLE
how many fd opened if i make_storage() same database several times?

### ISSUE THREAD

**Issue by Ssscy** [fnc12/sqlite_orm#1173]
Hi,
if i use make_storage() to open same database file, like "test.db"
`auto storage1 = make_storage("test.db",make_table("t1"...)...)`
`auto storage2 = make_storage("test.db",make_table("t2"...)...)`
sqlite_orm will open one fd or more?

if i want only use one fd to operate database, how can i do?
`auto storage = make_storage("test.db",make_table("t1"...),make_table("t2"...)...)`
make all tables during initialization storage?
 
thanks

**Comment by fnc12** [comment]
> if i use make_storage() to open same database file, like "test.db"
auto storage1 = make_storage("test.db",make_table("t1"...)...)
auto storage2 = make_storage("test.db",make_table("t2"...)...)
sqlite_orm will open one fd or more?

more. Amount of `sqlite3*` connections equals to amount of storages.

> if i want only use one fd to operate database, how can i do?

You can use one instance of storage
