### ISSUE TITLE
 How to map a nested structure to a table

### ISSUE THREAD

**Issue by Ssscy** [fnc12/sqlite_orm#1181]
```
struct A{
 int z;
};

struct B{
int x;
int y;
A  a;
};
```

hello, if  i want map struct B to a table, how can i make_table() ?
```
make_table("B",
make_column("bx",&B::x,primary_key()),
make_column("bx",&B::y),
make_column("by",&A::z)
);
```

but it doesn't work , and will cause compile error

in my project, struct B is already exist

if i want use sqlite_orm , i have to change struct B ?
```
struct B {
 int x;
 int y;
 int z;
}
```
```
make_table("B",
make_column("bx",&B::x,primary_key()),
make_column("bx",&B::y),
make_column("by",&B::z)
);
```

**Comment by fnc12** [comment]
@Ssscy how would you do it with raw SQLite?

**Comment by Ssscy** [comment]
> @Ssscy how would you do it with raw SQLite?

maybe handwritten SQL statement,like
```
char sql[] = "create table if not exists B (x integer primary key, y integer, z integer);";
sqlite3_exec(db,sql,NULL,NULL,NULL);
```
```
char sql[] = "select * from B";
sqlite3_exec(db,sql,NULL,NULL,NULL);
```
then, convert rows to struct B.

I want to know , there are some nested structures in my project like `struct B`, 
sqlite_ orm is there a way to create only one table without modifying the structure, in order to achieve conversion between the table and the structure? i read the document,it seems like no example
thanks

**Comment by fnc12** [comment]
> maybe handwritten SQL statement,like

How would you implemented nested structure with raw SQLite? not a simple query but a nested structure

**Comment by Ssscy** [comment]
> > maybe handwritten SQL statement,like
> 
> How would you implemented nested structure with raw SQLite? not a simple query but a nested structure

sorry i didn‘t understand what you mean

does it means struct B need two tables?

**Comment by fnc12** [comment]
@Ssscy I mean imagine `sqlite_orm` doesn't exist and no ORM exists. All you have is `libsqlite3`. How would you make a nested structure with it?

**Comment by Ssscy** [comment]
> @Ssscy I mean imagine `sqlite_orm` doesn't exist and no ORM exists. All you have is `libsqlite3`. How would you make a nested structure with it?

blob？

**Comment by fnc12** [comment]
@Ssscy what schema you expect to have for nested structure?

**Comment by Ssscy** [comment]
> @Ssscy what schema you expect to have for nested structure?

i expect to `"create table if not exists B (x integer primary key, y integer, z integer);"`
then use orm can direct coversion to `struct B`
```
struct A {
 int z;
};
struct B {
 int x;
 int y;
 A a;
};
```
like ,
`auto rows = storage.select(obejct<B>());`
rows type is `std::vector<B>`,and i can visit `rows[0].a,z` value

**Comment by spoyler** [comment]
I think what we're talking about here is that we have structs like:
```CPP
struct A{
 int z;
 int zz;
};

struct B{
int x;
int y;
A  a;
};
```

And then have database with one table:
```SQL
CREATE TABLE "AB" (
	"id" INTEGER NOT NULL,
	"x" INTEGER NOT NULL,
        "y" INTEGER NOT NULL,
        "z" INTEGER NOT NULL,
        "zz", INTEGER NOT NULL
);
```

Or  have database with two tables:

```SQL
CREATE TABLE "A" (
	"id" INTEGER NOT NULL,
	"x" INTEGER NOT NULL,
        "y" INTEGER NOT NULL
);
CREATE TABLE "B" (
        "id" INTEGER NOT NULL,
         "z" INTEGER NOT NULL,
         "zz", INTEGER NOT NULL,
         FOREIGN KEY("id") REFERENCES "A"("id")
);
```
