### ISSUE TITLE
movable iterator

### ISSUE THREAD

**Issue by jmorrill** [fnc12/sqlite_orm#119]
I am pumping the results of storage.iterate<> over a tcp socket asynchronously.  Because of this, I need to store the iterator_t from view_t::begin() for future use after a callback.

Unfortunately it seems the iterator is being copied, and the original iterator clears the SQLite resources in the dtor, leaving the copy in an invalid state causing the application to crash on usage.

Adding a move/assignment ctor around [here ](https://github.com/fnc12/sqlite_orm/blob/5c051eb7b39cb0e954a0404eec7c2138e1c16b83/include/sqlite_orm/sqlite_orm.h#L4347) fixes this problem (msvc 2017) and everything works great:

```
iterator_t(iterator_t&&) = default;
iterator_t& operator=(iterator_t&&) = default;
```
I'm not sure this is full fix you'd want to have (just worked for me).  Maybe you might want to explicitly delete the copy ctor and only have it movable?  Also, I have not looked at it close enough to see if I missed any side-effects, so grain of salt with my suggestions here.

**Comment by fnc12** [comment]
Ok, but I need a little test code with threads and with join probably. Can you write one?

**Comment by jmorrill** [comment]
I'm not doing any threads on this particular database, yet, but can make a reproducible w/o.

And upon making a reproducible, I found a work-around that makes this not such a blocking issue.  It seems if I am putting the iterator in a unique_ptr, that triggers the bug, (copy ctor, then a destroy of SQLite resources of the iterator).  If I simply store it as a field and initialize the iterator at construction, there is no crash.

**Comment by fnc12** [comment]
@jmorrill sorry for long response. Looks like you are right. But how this thing worked? I thought that default move operators are created by compiler by default if class has no const fields. But we did not modify fields' constness, just added default move operators and everything worked. How?

**Comment by fnc12** [comment]
fixed in `dev` branch
