### ISSUE TITLE
Can I run SELECT /UPDATE sql string with sqlite_orm, witch api? 

### ISSUE THREAD

**Issue by liulover5** [fnc12/sqlite_orm#1191]
example:
1, UPDATE tab_template SET valid = CASE id WHEN 539 THEN 1 ELSE 0 END;
2, SELECT t.* FROM tab_template  t JOIN tab_testitem  p, json_each(p.itemlist, '$.list') j WHERE p.id=539 AND t.id=j.value AND t.valid=1;

I hope to run string and dot care sql efffact result...
storage.excute("UPDATE...");
storage.excute("SELECT ..."); // without care result return...

**Comment by fnc12** [comment]
no `sqlite_orm` is not designed to use raw string API cause in that case `sqlite_orm` cannot prevent syntax errors. To run raw string SQL you can always use raw `sqlite3` API instead.

BTW both of your examples can be implemented with `sqlite_orm` API

**Comment by fnc12** [comment]
closing cause it is not an issue it is a question with no further work required. If I am wrong and you still have anything to work on it here please feel free top open it
