### ISSUE TITLE
How to do a CHECK?

### ISSUE THREAD

**Issue by Brouilles** [fnc12/sqlite_orm#1192]
Hi,
I need to convert this existing code 
```
company_type TEXT CHECK(company_type IN ('individual','company')) NOT NULL DEFAULT 'individual',
```
to sqlite_orm migration. But I don't find anything about `CHECK` in the wiki. It is supported? This migration only allow the strings 'individual','company' in the company_type column.

Thanks.

**Comment by fnc12** [comment]
hi. `CHECK` is supported:
```c++
make_column("company_type", &Company::type, check(in(&Company::type, {"individual", "company"}))
```
