### ISSUE TITLE
how to use qmake to use sqlite orm in Mingw and Qt creator environments

### ISSUE THREAD

**Issue by wanghuqiang123** [fnc12/sqlite_orm#1199]
I am a novice and I don't know how to use qmake to use sqlite orm in Mingw and Qt creator environments

**Comment by fnc12** [comment]
this is a good question which has to be addressed to qmake community

**Comment by fnc12** [comment]
I can help you with nothing here cause all we know is how to use sqlite_orm not qmake/mingw/qt-creator/whatever you use in your own work sorry

**Comment by fnc12** [comment]
closing cause this repo is not qmake responsible
