### ISSUE TITLE
how to read db from this library?

### ISSUE THREAD

**Issue by jonike** [fnc12/sqlite_orm#12]
Hi, I'm a newbie to c++. This orm c++ library is aswsome.
I have a stupid question. how to use function make_storage("exists.db",null) to read a exists sqlite db file.
I don't want to use make_storage("exists.db", make_table("blabla..")) on this format. I just want to use:
auto storage = read_storage("exists.db");
storage.select(...) to query my data.
How to do it. Thanks.

**Comment by fnc12** [comment]
Hi. Nice to see the lib is popular.
You got to write `make_storage("exists.db", make_table("blabla.."))` anyway because this is how you tell lib about your schema. Even if db exists storage must know what tables you want to read with what columns. That is why you have to call `make_storage` with all tables you have in existing db. You can find more information about making storage in [making storage tutorial](https://github.com/fnc12/sqlite_orm/wiki/Making-a-storage).

Or type here your existing db schema  - I'll provide you an example how to read existing db. It's easy

**Comment by fnc12** [comment]
Note that `make_storage` doesn't create db actually. It just tells creates storage object with [table -> class] mapping

**Comment by jonike** [comment]
Hi, Thanks for the quick response,sir.
I see what you mean, Thanks.
Have you considered adding the sqlite vfs feature to your library?
Link: https://github.com/spsoft/spmemvfs
I want to add this feature in my work to use your library.

**Comment by jonike** [comment]
code like this:
#include "sqlite_orm.h"
#include "spmemvfs.h"

using namespace sqlite_orm;

spmemvfs_db_t vfs_db;
char* sqlite_data;
size_t  data_size;

auto write_storage = make_storage(vfs_db,make_table("schema description..."));
// write_storage operate insert, update.
write_storage.save_data(sqlite_data); // save vfs_db->mem->data to sqlite_data buffer and set data_size = mem->data->used.
// then save sqlite_data in my custom file.


/* and then read this from char* buffer */

char* sqlite_data = read_sqlite_data_section(my_custom_file);
size_t  data_size = sqlite_data_size;
auto read_storage = make_storage(char* sqlite_data, size_t data_size,make_table("schema description..."));
// can operate storage to query

How to implement this feature?
Thanks again.

**Comment by fnc12** [comment]
I don't understand what profit can we get with vfs. As far as I know vfs is an OS Interface layer in SQLite (https://www.sqlite.org/vfs.html). It is stored inside libsqlite3 and doesn't intersect with the lib cause lib is just an sqlite frontend.
And what do you expect to have in `sqlite_data` var (type here please), I cannot understand it quite right.

**Comment by jonike** [comment]
Hi, sqlite_data is actually sqlite database file, I need to store it into a char * array, and then use the spmemvfs library to read this character array instead of the file to read.

**Comment by jonike** [comment]
Because I need to embed sqlite data into my own file format, read it as a character stream, and then use your library to easily manipulate them.

**Comment by fnc12** [comment]
Ok, now I see. This lib cannot help you with this low level stuff. This lib is a frontend for sqlite and gives a simple high-level interface for interaction like `storage.insert(User{ 1, "John" });`.
Storage has `std::shared_ptr<database_connection>` member (where `database_connection` is a class that holds `sqlite3*` and closes it in destructor). But there is no public access to it cause developer can interact with db without it if he/she uses this lib.

**Comment by jonike** [comment]
Ok,I see. I will change your code to suit my purpose. anyway thanks.

**Comment by fnc12** [comment]
@jonike you can fork it and I'll assist you once you need some help or explanation
