### ISSUE TITLE
Using rowid for desired class.

### ISSUE THREAD

**Issue by spiritEcosse** [fnc12/sqlite_orm#1200]
Hello everybody, i have a question regarding rowid.
i have such request 
`
        auto &&data = m_db->storage->select(columns(
            rowid(),
            &Book::m_bookNumber,
            &Book::m_shortName,
            &Book::m_longName,
            &Book::m_bookColor,
            &Book::m_isPresent,
            sqlite_orm::max(&Verse::m_chapter)
            ),
                                            inner_join<Verse>(on(c(&Book::m_bookNumber) == &Verse::m_bookNumber)),
                                                group_by(&Book::m_bookNumber),
                                                order_by(&Book::m_bookNumber));`
                                                
and i have got error 
` no such column: rowid: SQL logic error`
i guess it happens because i have join
is it possible to use rowid in that request with join ?
It would be great to pass the Book as desired class to rowid.

PS: i spent some time to find answer in the 'issues' and the 'examples' but i didn't get the answer. Please, help, thanks a lot.

**Comment by fnc12** [comment]
Hello. Did you try to run the same SQL query with raw SQLite?

**Comment by spiritEcosse** [comment]
i was trying 
`select ROWID,* from books inner join verses on(books.book_number=verses.book_number);`
and it gave me the same issue:
`Execution finished with errors.
Result: no such column: ROWID`

and 
`select books.ROWID,* from books inner join verses on(books.book_number=verses.book_number);`
worked well 
`Execution finished without errors.
Result: 31163 rows returned in 41ms`

**Comment by spiritEcosse** [comment]
i forgot  to mention, that i use 1.7.1 version of sqlite_orm.

**Comment by fnc12** [comment]
if you get the same error without sqlite_orm it means the error is not related to sqlite_orm and cannot be fixed by applying a patch to it. So I would google what is wrong with `select ROWID,* from books inner join verses on(books.book_number=verses.book_number);` SQLite query

**Comment by fnc12** [comment]
@spiritEcosse ok I see. Does `column<User>(rowid())` work?

**Comment by spiritEcosse** [comment]
Let me check it tonight.

**Comment by spiritEcosse** [comment]
i checked it
`        auto &&data = m_db->storage->select(columns(
            column<Book>(rowid()),
            &Book::m_bookNumber,
            &Book::m_shortName,
            &Book::m_longName,
            &Book::m_bookColor,
            &Book::m_isPresent,
            sqlite_orm::max(&Verse::m_chapter)
            ),
                                            inner_join<Verse>(on(c(&Book::m_bookNumber) == &Verse::m_bookNumber)),
                                                group_by(&Book::m_bookNumber),
                                                order_by(&Book::m_bookNumber));
`

it gave me : 

`In template: no matching member function for call to 'column_name_simple' error occurred here in instantiation of function template specialization 'sqlite_orm::internal::statement_serializator<sqlite_orm::internal::column_pointer<modules::Book, sqlite_orm::internal::rowid_t>>::operator()<sqlite_orm::internal::serializator_contex... in instantiation of function template specialization 'sqlite_orm::internal::serialize<sqlite_orm::internal::column_pointer<modules::Book, sqlite_orm::internal::rowid_t>, sqlite_orm::internal::serializator_context<sqlite_orm::internal::s... in instantiation of function template specialization 'sqlite_orm::tuple_helper::iterator_impl<0, sqlite_orm::internal::column_pointer<modules::Book, sqlite_orm::internal::rowid_t>, int modules::Book::*, QString modules::Book::*, QString... in instantiation of function template specialization 'sqlite_orm::tuple_helper::iterator_impl<1, sqlite_orm::internal::column_pointer<modules::Book, sqlite_orm::internal::rowid_t>, int modules::Book::*, QString modules::Book::*, QString... in instantiation of function template specialization 'sqlite_orm::tuple_helper::iterator_impl<2, sqlite_orm::internal::column_pointer<modules::Book, sqlite_orm::internal::rowid_t>, int modules::Book::*, QString modules::Book::*, QString... (skipping 7 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all) in instantiation of function template specialization 'sqlite_orm::internal::statement_serializator<sqlite_orm::internal::select_t<sqlite_orm::internal::columns_t<sqlite_orm::internal::column_pointer<modules::Book, sqlite_orm::internal::... in instantiation of function template specialization 'sqlite_orm::internal::serialize<sqlite_orm::internal::select_t<sqlite_orm::internal::columns_t<sqlite_orm::internal::column_pointer<modules::Book, sqlite_orm::internal::rowid_t>, int... in instantiation of function template specialization 'sqlite_orm::internal::storage_t<sqlite_orm::internal::index_t<sqlite_orm::internal::indexed_column_t<QString modules::Verse::*>>, sqlite_orm::internal::index_t<sqlite_orm::internal::... in instantiation of function template specialization 'sqlite_orm::internal::storage_t<sqlite_orm::internal::index_t<sqlite_orm::internal::indexed_column_t<QString modules::Verse::*>>, sqlite_orm::internal::index_t<sqlite_orm::internal::... in instantiation of function template specialization 'sqlite_orm::internal::storage_t<sqlite_orm::internal::index_t<sqlite_orm::internal::indexed_column_t<QString modules::Verse::*>>, sqlite_orm::internal::index_t<sqlite_orm::internal::... candidate template ignored: could not match 'F O::*' against 'field_type' (aka 'sqlite_orm::internal::rowid_t')`

**Comment by fnc12** [comment]
man I really forgot. One can use `rowid<User>()`

**Comment by spiritEcosse** [comment]
Great, it works.

**Comment by spiritEcosse** [comment]
Thanks a lot.
