### ISSUE TITLE
Templated Storage Schema - Compilation Issues

### ISSUE THREAD

**Issue by revred** [fnc12/sqlite_orm#1225]
I am trying to create a table storage schema type by using the code below. Here the temple argument is the record type that I would like to store. I am getting an issue in the Reset function. The errors on MSVC (visual studio 2022) is shown below.
```
template<typename T>
class TableStore : public ITable
{
public:

	TableStore(const std::string& aPath) : schema_(T::InitStore(aPath))
	{
	}

	virtual bool UpdateTable(T* input) { return false; }

	virtual bool UpdateTable(const std::vector<T>& inputs)
	{
		return false;
	}

	virtual std::vector<T> Filter(const std::string& filter)
	{
		return std::vector<T>();
	}

	const char* TableName() const override { return T::TableName; }
	auto* Table() { return &schema_; }

	void Reset()
	{
		schema_.remove_all<T>();  // error
	}

private:
	using Schema = decltype(T::InitStore(""));
	Schema schema_;

};
```

First Error Dump:
1>D:\code\MyProject\Test.Sqlite.Security\src\Schema\Table.hxx(50,25): error C2760: syntax error: ')' was unexpected here; expected 'expression'

**Comment by fnc12** [comment]
which is line 50?

**Comment by revred** [comment]
> which is line 50?

Yes. Thank you for looking at it 👍 !

**Comment by fnc12** [comment]
@revred which line of all the lines is line number 50?

**Comment by revred** [comment]
> @revred which line of all the lines is line number 50?

Sorry for not making it obvious. It is the line that calls 

`schema_.remove_all<T>(); `

**Comment by fnc12** [comment]
I see but I still can't understand what's happening here. Can you share a screenshot of VS windows with error so we can search for more details?

**Comment by revred** [comment]
> I see but I still can't understand what's happening here. Can you share a screenshot of VS windows with error so we can search for more details?

I will make a more detailed post, potentially with a buildable console app.

**Comment by fnc12** [comment]
@revred no news yet?

**Comment by fnc12** [comment]
@revred still no news?

**Comment by revred** [comment]
Apologies, I should have this posted over this weekend. Busy week!

**Comment by fnc12** [comment]
@revred let me close it due to inactivity. It doesn't mean we don't want to solve your issue. Please reopen when you have some news which can be fixed. Thanks
