### ISSUE TITLE
Sub entities in STL other than vector ( like map )

### ISSUE THREAD

**Issue by gminorcoles** [fnc12/sqlite_orm#123]
Is it possible to get the orm to use a collection other than vector for sub Entities? For example I have an object that contains a map of child objects, and the keys of the map are the primary key of the child table.

**Comment by fnc12** [comment]
Hello. What do you mean `child table`? How do you imagine this in raw SQLite schema?

**Comment by gminorcoles** [comment]
In one of the examples, examples/subentities.cpp, there are two tables which have a parent/child relationship. Object A contains a collection of Object B. I would like to populate a std::unordered_map, rather than a vector. It's not difficult to transform the vector in the example, using the primary key of each child object B, as the map key, but I was curious if there is any support for different STL containers.

**Comment by fnc12** [comment]
If you pick `examples/subentities.cpp` and change `std::vector` of marks to `std::unordered_map` it will work the same way (also you'll need to include id as a key)

**Comment by gminorcoles** [comment]
wow that's great thanks

**Comment by fnc12** [comment]
is the issue actual?
