### ISSUE TITLE
include directive for sqlite3.h

### ISSUE THREAD

**Issue by ntkernelcom** [fnc12/sqlite_orm#125]
First of all thanks for this piece of code which looks pretty useful. 

Although there is a small inconvenience with  #include <sqlite3.h> directive in sqlite_orm.h. When included this way Visual Studio searches for sqlite3.h in include directories and fails unless you add path to the sqlite3.h in the IDE. 
It would be more convenient  to change to #include "sqlite3.h" or just remove this dependency assuming that sqlite3.h will be included before the sqlite_orm.h in the client code.

**Comment by fnc12** [comment]
Hey, thanks for using the lib. I'm glad you like it.
About your question: I think that the correct way will be setting a correct header search path in your project properties. Every project has `Header search paths` (for `<*.h>` files) and `User header search path` (for `"*.h")` files. First is designed for libs which are not a part of your project. `libsqlite3` is a lib that is not a part of your project so you need to specify `Header search path` to point to a folder where your `sqlite3.h` is located.
