### ISSUE TITLE
C:\src\sqlite_orm\tests\schema\virtual_table.cpp(6): exception: no such module: FTS5: SQL logic error

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#1253]
Running unit_tests I get this error...

Is it something missing in the DLL?

Regards,
Juan Dent

**Comment by fnc12** [comment]
you have to have SQLite with FTS5 module to run this unit test. It is runtime feature not compile time feature. More details https://www.sqlite.org/fts5.html

**Comment by juandent** [comment]
great thanks
