### ISSUE TITLE
compile error with gcc 5.3.1

### ISSUE THREAD

**Issue by DanielMues** [fnc12/sqlite_orm#1262]
with this function:
![image](https://github.com/fnc12/sqlite_orm/assets/54837088/1134b45b-c595-4198-92e8-dc78c94bf4db)
I get this error:
[build] ls_charges.cpp:89:44:   required from here
[build] build/_deps/sqlite_orm-src/include/sqlite_orm/sqlite_orm.h:19421:96: error: binding 'const string {aka const std::__cxx11::basic_string<char>}' to reference of type 'std::__cxx11::basic_string<char>&' discards qualifiers
[build]                                  table.for_each_column([this, colInfo, &tableName = table.name, db](auto& column) {

in the library header itself it marks the db paramenter:
![image](https://github.com/fnc12/sqlite_orm/assets/54837088/0f57b17a-7bf8-483b-9b69-b5fb204339a7)

                                               
environment:
compiler: gcc 5.3.1 arm-linux
c++ 14

for development I compile with gcc 10, there is no such error

is there anything known about this, or do you have an idea what it could be?

**Comment by fnc12** [comment]
it looks like a compiler bug. I bet clang also will compile it with no errors. Your compiler (gcc 5.3.1) is sure that capture `&tableName = table.name` has to be non const ref but actually it has to be const ref cause `table` is `const` value. GCC 10 knows it. Try updating your compiler.

**Comment by trueqbit** [comment]
See #1157 and [#1145](https://github.com/fnc12/sqlite_orm/issues/1145#issuecomment-1459967555)

**Comment by DanielMues** [comment]
okay, I will check if an update of the compiler is possible. A workaround is probably not known, or?

**Comment by trueqbit** [comment]
> okay, I will check if an update of the compiler is possible. A workaround is probably not known, or?

Which workaround do you suggest?

**Comment by DanielMues** [comment]
Was just curious if you know one, I don´t have one/did not find one.

**Comment by trueqbit** [comment]
@DanielMues I don't know of any workaround, you'd have to try one and let us know...
