### ISSUE TITLE
Working with databases from several applications

### ISSUE THREAD

**Issue by FarafontovDmitriy** [fnc12/sqlite_orm#127]
Hello!
Tell me, is it possible to work with a database from several applications?

**Comment by fnc12** [comment]
Hello. Yes. But be ready that one can received a busy error in case several apps access db at one moment. Also storage class has a function `busy_timeout`. Also there is an unimplemented feature "busy handler" - a function that is fired once busy timeout is expired. If you need it please tell me - I'll implement it

**Comment by fnc12** [comment]
@FarafontovDmitriy is the issue still actual?

**Comment by fnc12** [comment]
closing due to silence
