### ISSUE TITLE
Failed to compile origin/dev branch using GCC 8.3

### ISSUE THREAD

**Issue by 13927783203** [fnc12/sqlite_orm#1270]
[ 51%] Building CXX object tests/CMakeFiles/unit_tests.dir/static_tests/column_expression_type.cpp.o
cd /home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/build/build/tests && /home/lijz/work2024/V25/gcc-tools/rv1109_linux/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++  -I/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/include -I/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/build/build/_deps/catch2-src/src/catch2/.. -I/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/build/build/generated-includes -isystem /home/lijz/work2024/V25/app/_libsout/rv1109_linux32/sqlite3/include -std=c++14 -Winvalid-pch -include /home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/build/build/tests/CMakeFiles/unit_tests.dir/cmake_pch.hxx -o CMakeFiles/unit_tests.dir/static_tests/column_expression_type.cpp.o -c /home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/tests/static_tests/column_expression_type.cpp
In file included from /home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/build/build/tests/CMakeFiles/unit_tests.dir/cmake_pch.hxx:6,
                 from <command-line>:
/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/include/sqlite_orm/sqlite_orm.h: In instantiation of ‘constexpr auto sqlite_orm::alias_column(F O::*) [with A = sqlite_orm::internal::recordset_alias<CATCH2_INTERNAL_TEST_0()::Org, 'a'>; F = long long int; O = CATCH2_INTERNAL_TEST_0()::Org; typename std::enable_if<sqlite_orm::internal::polyfill::conjunction<sqlite_orm::internal::is_table_alias<A>, sqlite_orm::internal::polyfill::negation<std::integral_constant<bool, is_cte_moniker_v<typename A::type> > > >::value, bool>::type <anonymous> = 1]’:
/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/tests/static_tests/column_expression_type.cpp:49:106:   required from here
/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/include/sqlite_orm/sqlite_orm.h:5240:45: error: braces around scalar initializer for type ‘sqlite_orm::internal::alias_column_t<sqlite_orm::internal::recordset_alias<CATCH2_INTERNAL_TEST_0()::Org, 'a'>, long long int CATCH2_INTERNAL_TEST_0()::Org::*>::column_type’ {aka ‘long long int CATCH2_INTERNAL_TEST_0()::Org::*’}
         return alias_column_t<A, C1>{{field}};
                                             ^
/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/tests/static_tests/column_expression_type.cpp: In function ‘void CATCH2_INTERNAL_TEST_0()’:
/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/tests/static_tests/column_expression_type.cpp:49:107: error: invalid use of void expression
     runTest<db_objects_t, alias_column_t<alias_a<Org>, int64 Org::*>>(alias_column<alias_a<Org>>(&Org::id));
                                                                                                           ^
tests/CMakeFiles/unit_tests.dir/build.make:415: recipe for target 'tests/CMakeFiles/unit_tests.dir/static_tests/column_expression_type.cpp.o' failed
make[2]: *** [tests/CMakeFiles/unit_tests.dir/static_tests/column_expression_type.cpp.o] Error 1
make[2]: Leaving directory '/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/build/build'
CMakeFiles/Makefile2:1034: recipe for target 'tests/CMakeFiles/unit_tests.dir/all' failed
make[1]: *** [tests/CMakeFiles/unit_tests.dir/all] Error 2
make[1]: Leaving directory '/home/lijz/work2024/V25/app/third-party/libsqlite_orm/sqlite_orm/build/build'
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by 13927783203** [comment]
I compiled successfully!Thank you so much for your help!

**Comment by trueqbit** [comment]
You are welcome!
