### ISSUE TITLE
why is this WITH not recursive?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#1276]
```
        constexpr auto cnt = "cnt"_cte;
        constexpr auto x = "x"_col;
        auto ast = with(cnt(x).as(union_all(select(from), select(cnt->*x + 1, limit(end)))), select(cnt->*x));
```

Which produces SQL: WITH "cnt"("x") AS (SELECT 1 UNION ALL SELECT "cnt"."x" + 1 FROM "cnt" LIMIT 10) SELECT "cnt"."x" FROM "cnt"

It should be recursive correct?

**Comment by trueqbit** [comment]
You are right that the example should use `with_recursive` for clarity.
However, SQLite does not care whether a CTE is marked as "recursive" or not. The recursive nature of a CTE depends on the select statement.

**Comment by juandent** [comment]
ok! thanks
