### ISSUE TITLE
sync_schema_simulate when used with triggers

### ISSUE THREAD

**Issue by trevornagy** [fnc12/sqlite_orm#1280]
Hi all,

I'm seeing weird behaviour with `sync_schema_simulate`, it does compile when this trigger is added to a `make_storage`:
```
sqlite_orm::make_trigger(
                "table_insert_InsertTest",
                sqlite_orm::after()
                    .insert()
                    .on<X>()
                    .begin(sqlite_orm::update_all(
                        sqlite_orm::set(
                            sqlite_orm::c(&X::Test) = 5)))
                .end()
            );
```

This is not high priority as when I comment out that trigger it builds fine & I can see the simulation results, and when I run  `sync_schema` the trigger is created successfully & correctly.

The error message is (truncated to what I think are the important bits):
`Error	C2672	'sqlite_orm::internal::storage_t<sqlite_orm::internal::trigger_t<sqlite_orm::internal::trigger_base_t<X,void,sqlite_orm::internal::trigger_type_base_t>,sqlite_orm::internal::update_all_t<sqlite_orm::internal::set_t< ... ::schema_status': no matching overloaded function found`

**Comment by fnc12** [comment]
@trevornagy what kind of error you get?

**Comment by trevornagy** [comment]
Updated the original bug with the error, sorry meant to include that to begin with.

**Comment by fnc12** [comment]
oh kurwa, it is a bug! Looks like we never using triggers with `sync_schema_simulate`. It turned out that `schema_status` override for `trigger_t` doesn't exist. Let me fix it fast

**Comment by fnc12** [comment]
PR is here https://github.com/fnc12/sqlite_orm/pull/1281

**Comment by fnc12** [comment]
merged. Please check

**Comment by trevornagy** [comment]
@fnc12 Works for triggers, but just noticed this exact same issue happens with virtual tables (created with FTS5)

Should I create a new issue or should we reuse this?

**Comment by fnc12** [comment]
@trevornagy this issue is enough. I reopened it. feel free to reopen issues by yourself if you are sure something more has to be committed to the code base to fix the issue. Could you share repro code please?

**Comment by trevornagy** [comment]
Sure, the following can trigger a repro:

```
            auto storage = sqlite_orm::make_storage(
                path,
                sqlite_orm::make_virtual_table(
                "test", 
                sqlite_orm::using_fts5(
                    sqlite_orm::make_column("X", &Test::X))
            )
            );

            auto simulation = storage.sync_schema_simulate(false);
```

**Comment by fnc12** [comment]
PR is here https://github.com/fnc12/sqlite_orm/pull/1283

**Comment by trevornagy** [comment]
That fixes it, will close this issue now. Thanks!
