### ISSUE TITLE
PRAGMA options

### ISSUE THREAD

**Issue by trevornagy** [fnc12/sqlite_orm#1299]
I'm just wondering how to use the `foreign_keys` option, I see it in code but not sure how to enable it. In sqlite it would look like:
`PRAGMA foreign_keys=ON;`

Additionally, would it be possible to get the `recursive_triggers` option? In sqlite: `PRAGMA recursive_triggers=ON;`

Thanks!

**Comment by fnc12** [comment]
1) `foreign_keys` is enabled by storage after every SQLite connection is opened if `make_table` contains at least 1 foreign key;
2) `recursive_triggers` will be added soon.

**Comment by fnc12** [comment]
PR with `recursive_triggers ` https://github.com/fnc12/sqlite_orm/pull/1302

**Comment by trevornagy** [comment]
Awesome, thank you!

**Comment by fnc12** [comment]
@trevornagy merged. Please check `dev` branch

**Comment by juandent** [comment]
This should be possible to allow change in data or structure We go back to a touchy subject but I think we should enable this in a safe manner and being very careful to explain the dangers of it’s unscrupulous useMaybe allow it in sync_schema and disable it afterwardsRegards Juan DentSent from my iPhoneOn 29 May 2024, at 8:44 AM, Yevgeniy Zakharov ***@***.***> wrote:﻿
PR with recursive_triggers #1302

**Comment by trevornagy** [comment]
Works as expected, thanks!
