### ISSUE TITLE
String primary key

### ISSUE THREAD

**Issue by Abusher** [fnc12/sqlite_orm#130]
Hi, I'm trying to create table with string primary key.
After i'm trying insert some element in table, it throws "constraint failed" is there any way to do this without  id field??

**Comment by fnc12** [comment]
String primary key works well. Try `replace` instead of `insert` cause `insert` doesn't insert primary key field but tries to create it but `replace` inserts every field (`REPLACE INTO` SQLite query). More info [here](https://github.com/fnc12/sqlite_orm/wiki/storage_t%3A%3Areplace)

**Comment by Abusher** [comment]
wow, it works) Thank you a lot)
