### ISSUE TITLE
vs2017 build failed

### ISSUE THREAD

**Issue by godmaycrying** [fnc12/sqlite_orm#1301]
sqlite_orm.h(10301): error C3536: 'res': cannot be used before it is initialized
sqlite_orm.h(19794): note: see reference to function template instantiation 'decltype(auto) sqlite_orm::internal::empty_callable<std::integral_constant<bool,false>>(void)' being compiled
sqlite_orm.h(19794): note: see reference to class template instantiation 'sqlite_orm::internal::statement_serializer<sqlite_orm::internal::replace_t<T>,void>' being compiled
sqlite_orm.h(10301): error C2440: 'return': cannot convert from 'int' to 'auto &'
sqlite_orm.h(10302): error C3487: 'void': all return expressions must deduce to the same type: previously it was 'auto &'
sqlite_orm.h(19794): error C3779: 'sqlite_orm::internal::empty_callable': a function that returns 'auto' cannot be used before it is defined
sqlite_orm.h(10297): note: see declaration of 'sqlite_orm::internal::empty_callable'
sqlite_orm.h(19794): note: This diagnostic occurred in the compiler generated function 'std::string sqlite_orm::internal::statement_serializer<sqlite_orm::internal::replace_t<T>,void>::operator ()(const sqlite_orm::internal::replace_t<T> &,const Ctx &) const'

**Comment by trueqbit** [comment]
@godmaycrying Do you have a suggestion on how to solve the compiler error?

And please, give a good error description when you open a ticket. Thank you.

**Comment by trueqbit** [comment]
Hi @godmaycrying, can we close this ticket?

**Comment by godmaycrying** [comment]
> Hi @godmaycrying, can we close this ticket?

yes, thank you!
