### ISSUE TITLE
transaction_guard: Ability to specify transaction type

### ISSUE THREAD

**Issue by trevornagy** [fnc12/sqlite_orm#1305]
By default the `transaction_guard` API calls: `begin_transaction`.

Would it be possible to add to the `transaction_guard` API a way to specify the type of transaction? For example, what if I want to use `transaction_guard` + `begin_immediate_transaction` / `transaction_guard` + `begin_exclusive_transaction`?

Is this possible?

Thanks!

**Comment by fnc12** [comment]
It is not possible but we can think about it. Either to add more functions like `immediate_transaction_guard` or adding `enum` argument to `transaction_guard`

**Comment by fnc12** [comment]
PR is here https://github.com/fnc12/sqlite_orm/pull/1308

**Comment by fnc12** [comment]
@trevornagy please check `dev` branch for new API `deferred_transaction_guard`, `immediate_transaction_guard` and `exclusive_transaction_guard`
