### ISSUE TITLE
Aggregate function in example seems to work incorrectly

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#1312]
Hi,

The aggregate function AcceleratedSumFunction in Example: "user_defined_functions" project, seems to behave incorrectly.
This code:
```
    auto aSumRows =
        storage.select(columns(accelerated_sum(&Table::a), accelerated_sum(&Table::b), accelerated_sum(&Table::c)));
```

produces a vector of 1 element with values like these:

>  (1, 0, 2, 4, 2, 6, 9, 6, 14, 18, 14, 30)
        ()
        ()

so it is adding the values of the 3 columns for all the rows in the table instead of adding the values in column 'a', then the sum of column 'b' and then the sum of column 'c'

It seems only one instance of the function accelerated_sum is used in the query... and it gets all the values in all the columns and rows

**Comment by trueqbit** [comment]
Hi @juandent,

the result seems to be unexpected indeed.

Are you able to test sqlite_orm 1.8.2? Just to make sure that this is not due to changes in the development branch since then.

**Comment by juandent** [comment]
right now I am working in the dev branch -- but the example is in the "user_defined_functions" project so it should be easy to reproduce

**Comment by trueqbit** [comment]
Thx @juandent for reporting this. This has been fixed and is now in the dev branch...
