### ISSUE TITLE
Issue: Incorrect Version Macro Check in `sqlite_orm.h` #define _LIBCPP_VERSION  

### ISSUE THREAD

**Issue by FreeSoaring** [fnc12/sqlite_orm#1317]
#### Description

The macro check for `_LIBCPP_VERSION` in `sqlite_orm.h` is incorrect. The `_LIBCPP_VERSION` macro is defined in the NDK at `$NDK_ROOT/sources/cxx-stl/llvm-libc++/include/__config` as follows:
```cpp
#define _LIBCPP_VERSION 110000
```
This means that the version number is in the format `major * 10000 + minor * 100 + patch`.

#### Problematic Code
In `sqlite_orm.h`, line 7958, the version check is currently:
```cpp
#if (__cplusplus >= 202002L) && ((!_LIBCPP_VERSION || _LIBCPP_VERSION >= 13) && (!_GLIBCXX_RELEASE || _GLIBCXX_RELEASE >= 10))
```

#### Suggested Fix
The version check should be updated to match the format used by `_LIBCPP_VERSION`. The corrected macro should be:
```cpp
#if (__cplusplus >= 202002L) && ((!_LIBCPP_VERSION || _LIBCPP_VERSION >= 130000) && (!_GLIBCXX_RELEASE || _GLIBCXX_RELEASE >= 10))
```

#### Rationale
This change ensures that the version comparison for `_LIBCPP_VERSION` is accurate, reflecting the actual versioning format used by `libc++`.

#### Example
The corrected code should be:
```cpp
#if (__cplusplus >= 202002L) && ((!_LIBCPP_VERSION || _LIBCPP_VERSION >= 130000) && (!_GLIBCXX_RELEASE || _GLIBCXX_RELEASE >= 10))
    // Your code here
#endif
```

**Comment by trueqbit** [comment]
Hi @FreeSoaring
1. Are you sure that the line `#define _LIBCPP_VERSION 110000` is correct? @raidenluikang reported in issue #1139 and @lemourin in PR #1183 that `_LIBCPP_VERSION` was a 5-digit number and that's what I see in the their github repo for [v11](https://github.com/llvm/llvm-project/blob/176249bd6732a8044d457092ed932768724a6f06/libcxx/include/__config#L35). They only changed to 6 digits in [v16](https://github.com/llvm/llvm-project/blob/08d094a0e457360ad8b94b017d2dc277e697ca76/libcxx/include/__config#L40).
2. I assume you are using sqlite_orm 1.8.2? @lemourin fixed this with PR #1183, which came after 1.8.2 and is in the dev branch.

**Comment by FreeSoaring** [comment]
> 你好@FreeSoaring
> 
> 1. 您确定该线路`#define _LIBCPP_VERSION 110000`错了吗？@raidenluikang[问题在Android NDK 25上构建错误](https://github.com/fnc12/sqlite_orm/issues/1139)[ #1139](https://github.com/fnc12/sqlite_orm/issues/1139)中报告了这个问题，[](https://github.com/fnc12/sqlite_orm/issues/1139)@lemourin在 PR [Fix 版本中检查保护 std::identity 的使用情况。 #1183](https://github.com/fnc12/sqlite_orm/pull/1183)是`_LIBCPP_VERSION`一个 5 位数字，这是我在[v11 的 github repo 中看到的。他们只在](https://github.com/llvm/llvm-project/blob/176249bd6732a8044d457092ed932768724a6f06/libcxx/include/__config#L35)[v16](https://github.com/llvm/llvm-project/blob/08d094a0e457360ad8b94b017d2dc277e697ca76/libcxx/include/__config#L40)中将其改为6位数字。
> 2. 我假设我使用 sqlite_orm 1.8.2？@lemourin使用 PR[修复版本检查保护 std::identity 用法问题。 #1183](https://github.com/fnc12/sqlite_orm/pull/1183)，它是在 1.8.2 之后发布的，位于 dev 分支中。


"Oh, I'm sorry, it is indeed a 5-digit number; I typed an extra 0.
I am using the source code of sqlite_orm version 1.8.2 downloaded from the Releases section.
In the source code, line 7958 uses the _LIBCPP_VERSION to determine if it is a 2-digit number.
This can cause compilation issues with the error 'using std::identity; is not defined'.
It should be modified to check for a 5-digit version.
I manually modified it to:
```cpp
#if (__cplusplus >= 202002L) && ((!\_LIBCPP\_VERSION || \_LIBCPP\_VERSION >= 13000) && (!\_GLIBCXX\_RELEASE || \_GLIBCXX\_RELEASE >= 10))}
```
After this change, the NDK compilation completed successfully."

**Comment by fnc12** [comment]
@FreeSoaring can we close it now? https://github.com/fnc12/sqlite_orm/pull/1183 is merged

**Comment by fnc12** [comment]
I think yes we can. Please feel free to reopen in case of anything
