### ISSUE TITLE
SQLITE_VERSION_NUMBER used prior to include

### ISSUE THREAD

**Issue by trevornagy** [fnc12/sqlite_orm#1322]
Updated to the latest version of dev and it doesn't seem to build. The cause looks to be 75a33379723c955052bdeb1bb8d7274ec2061edb as it is referencing `SQLITE_VERSION_NUMBER` before `#include <sqlite3.h>`.

**Comment by trueqbit** [comment]
Hi @trevornagy,

Thank you for reporting this!
We use precompiled headers that include sqlite3.h before sqlite_orm.h, so this went unnoticed in the unit test builds.

#75a3337 is not the cause per se, but uncovered the issue that `SQLITE_VERSION_NUMBER` may be used before sqlite3.h is included.
