### ISSUE TITLE
IF EXISTS: Is it possible?

### ISSUE THREAD

**Issue by trevornagy** [fnc12/sqlite_orm#1324]
How would I write the following using `sqlite_orm`?

`DROP TRIGGER IF EXISTS trigger`
`DROP TABLE IF EXISTS table`

More specifically the `IF EXISTS` / `IF NOT EXISTS` part as I see `drop_table` / `drop_trigger` are part of the library. I see there is a `table_exists(...)` method, but nothing equivalent for triggers.

**Comment by fnc12** [comment]
I see it can be implemented in several ways:
1. `storage.drop_table_if_exists(...);` - one more func
2. `storage.drop_table(if_exists(...));` - one more overload
3. your option

@trevornagy do you have any API preference for this?

**Comment by trevornagy** [comment]
I prefer option 2 as the api would be more consistent for triggers/tables.

**Comment by fnc12** [comment]
I was thinking a lot about which option to pick. So I'd like to stick with option 1 cause it is easier for newbies cause once you type `storage.drop` you see all the options. In the case of option 2 you will type `storage.drop` but how to specify `if_exists` may be not clear from the first sight. I hope you agree

**Comment by juandent** [comment]
I like the overload betterJuan DentSent from my iPhoneOn 23 Jun 2024, at 1:36 AM, Yevgeniy Zakharov ***@***.***> wrote:﻿
I was thinking a lot about which option to pick. So I'd like to stick with option 1 cause it is easier for newbies cause once you type storage.drop you see all the options. In the case of option 2 you will type storage.drop but how to specify if_exists may be not clear from the first sight. I hope you agree

**Comment by trevornagy** [comment]
Hey @fnc12, just wondering if there was any progress on this issue?

**Comment by fnc12** [comment]
@trevornagy in progress

**Comment by fnc12** [comment]
PR https://github.com/fnc12/sqlite_orm/pull/1333

**Comment by fnc12** [comment]
@trevornagy done. Please check `dev` branch

**Comment by trevornagy** [comment]
Much appreciated, testing now!
