### ISSUE TITLE
why sync_schema() allways drop records and recreate table?

### ISSUE THREAD

**Issue by newgolo** [fnc12/sqlite_orm#1328]
when I run my sqlite_orm demo, I found that every time it will drop records and recreate a new table.
I am so confused ..., code like following:
```
#include <sqlite_orm/sqlite_orm.h>
using namespace sqlite_orm; // NOLINT
struct Student {
    int id;
    std::string name;
};

inline auto initStorage(const std::string& path) {
    return make_storage(
        path,
        make_table(
            "table_students",
            make_column("id", &Student::id, primary_key().autoincrement()),
            make_column("name", &Student::name, default_value(""))));
}
using Storage = decltype(initStorage(""));

int main(int argc, char** argv) {
    auto storage = initStorage("test.db");
    storage.sync_schema();
    storage.insert<Student>({0, "Tom"});
    storage.insert<Student>({0, "Jimmy"});
    return 0;
}
```

**Comment by fnc12** [comment]
please show me your original SQLs for all the tables

**Comment by newgolo** [comment]
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> .schema
CREATE TABLE IF NOT EXISTS "table_students" ( "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL , "name" TEXT DEFAULT ('') NOT NULL );
CREATE TABLE sqlite_sequence(name,seq);

**Comment by fnc12** [comment]
@newgolo and if you run `sync_schema` again you'll get `table_students` dropped and recreated?

**Comment by newgolo** [comment]
> @newgolo and if you run `sync_schema` again you'll get `table_students` dropped and recreated?

Yes.

**Comment by fnc12** [comment]
ok. Which lib version you use?

**Comment by fnc12** [comment]
please try `dev` branch instead - we have several fixes in `dev`, probably your bug was already fixed

**Comment by newgolo** [comment]
> please try `dev` branch instead - we have several fixes in `dev`, probably your bug was already fixed

I tried the dev branch, but the problem is still unsolved.
