### ISSUE TITLE
provide "map function"

### ISSUE THREAD

**Issue by paineZhang** [fnc12/sqlite_orm#133]
The library provided enum binding.However, the binding method look a little messy, and not friendly enough.I mean is:I thought it was enough to just provide the transformation functions for enumerations and types of mapping.But,I have to override `type_printer`、`statement_binder`、`field_printer`、`row_extractor`，and them seem to have exposed the implement details of the library.Worse, `statement_binder::bind` exposed the details of sqlite library's usage.Conversely, The `vector<char>' map to `BLOB` is wonderful.
So, Therefore, it is possible to provide a more general solution.
I think ,it looks like this:
```
namespace sqlite_orm {
	//enum class storage_type {
	//	integer,
	//	real,
	//	text,
	//	bolb,
	//	...
	//};

	template<class MapType, class MapTo, class MapFrom, class ToS>
	auto mapper( MapTo& _mt, MapFrom& _mf, ToS& _ts ) {
		return mapper_t;
	}

	or ;

	template<class MapType, class FieldT>
	struct mapper_base {
		MapType map_to(const FieldT& _field);
		FieldT map_from(const MapType& _field);
		string to_string();
	};

}

//def struct
enum class Gender {
	Male,
	Female,
};

struct SuperHero {
	int id;
	std::string name;
	Gender gender;
};

//def mapper banding
struct gender_map_string {
	static string map_to(const Gender&);
	static Gender map_from(const string&);
	static string to_string(const Gender&) {
		return map_to();
	}
};
OR;
struct gender_map_integer {
	static int map_to(const Gender&);
	static Gender map_from(const int&);
	static string to_string(const Gender&);
};
OR;
struct gender_map : public sqlite_orm::mapper_base<int, Gender> {

	int map_to(const Gender& _field);
	Gender map_from(const int& _field);
	string to_string();
}

//usage
make_storage("xxx.sqlite", 
    make_table("xxx_table",
        make_column("xxx_column",
            &xxx::xxx, 
            mapper(&gender_map_integer::map_to,
                &gender_map_integer::map_from,
                &gender_map_integer::to_string)))
);
OR;
make_storage("xxx.sqlite",
     make_table("xxx_table",
       make_column("xxx_column",
            &xxx::xxx,
            mapper<gender_map>()))
);
```

For me, there are two scenarios.

1. 
```
struct position{
    int64_t longitude ;
    int64_t latitude ;
};

struct trajectory_record{
    ...
    vector<position> pos_set;
    ...
};
```
I want to map `vector<position>` to blob.

2.
```
struct user_info{
    ...
    string password;
    ...
};
```
I want to encode the passsword when insert record, and read record with out decode.
I can use the map mechanism to make the code looks elegant,although it is mapping string to string.

**Comment by fnc12** [comment]
Ok but how do you expect to bind a [nullable enum](https://github.com/fnc12/sqlite_orm/blob/master/examples/nullable_enum_binding.cpp)?

**Comment by paineZhang** [comment]
Aah!I didn't think about it. /:<
In my scenario，all field can not be null.Unless it is a composition or aggregation relationship between entities,and distinguish by `shared_ptr`.

**Comment by fnc12** [comment]
So such a detailed traits collection is used to provide an advanced setting of your custom type mapping. And it can map whatever you want to any sqlite type by any rules. Is the issue actual?

**Comment by paineZhang** [comment]
Yeah.That's very accurate.
