### ISSUE TITLE
max_page_count pragma doesn't work

### ISSUE THREAD

**Issue by akrisfx** [fnc12/sqlite_orm#1351]
```cpp
auto storage = orm::make_storage(
            db_filename, 
            orm::make_table("logs"
                , orm::make_column("id", &log_row::id, orm::primary_key())
                , orm::make_column("log", &log_row::log)
                , orm::make_column("service_name", &log_row::service_name)
            )        
        );
        // storage.sync_schema();
        storage.begin_transaction();
        storage.pragma.max_page_count(30); 
        storage.commit();
        std::cout << storage.pragma.max_page_count() << " |" << std::endl; // I still have the default value here
  ```
  
in the listing above, what with wrapping in commit, what without, I have a default value in the form of 4294967294

if I manually set max_page_count in the sqlite browser (I execute `PRAGMA max_page_count = 30;`), sqlite_orm still does not see any changes.

**Comment by akrisfx** [comment]
The funny thing is that I wrote the setter :))

**Comment by fnc12** [comment]
@akrisfx how does it work with raw SQLite lib? I bet it works the same. Probably this value is stored within opened connection. If so try to call `storage.open_forever` right after `make_storage` and check the result. And you'd add unit test to your PR (my bad I missed it)

**Comment by akrisfx** [comment]
@fnc12 yes, it's work with opened connection. Thanks
I will write tests little bit later

**Comment by fnc12** [comment]
I think we can close this issue. Please feel free to reopen it if something appears
