### ISSUE TITLE
Memory buffer instead of a file

### ISSUE THREAD

**Issue by Teles1** [fnc12/sqlite_orm#1352]
Hello,

I looked around and couldn't find anyone running into the same "issue" that I did. 

I currently have a Resource manager that handles multiple files formats, zips, packed, tars, compressed, raw formats etc and I would love to use my Resource manager to grab the sqlite file, read it to a buffer and pass that content along (read only). Is there an easy way to support/do such without modifying the internal functions?

Thanks a lot!

**Comment by fnc12** [comment]
Hello. Looks like it is more task for your file system not SQLite. But probably I don't get it quite right. Anyway how would you implement this if let's say you have only C API with `libsqlite3` without `sqlite_orm`?

**Comment by Teles1** [comment]
sorry, let me try to exemplify it.
Eg: Assuming the following folder structure
Folder -
  - binary_run
  - packed.pkt

My resource manager loads and all files stored inside of packet.pkt are indexed into a hash map that has the file name and it's offset + size. My goal here is to pass on a memory buffer to sqlite_orm as a "char* buffer, uint64_t size" and flag the database as read only obviously since we can't alter the database at all in this state.

**Comment by fnc12** [comment]
ok I see. It more less looks like unarchiving `.apk` and obtaining assets from it. There are two ideas I have in my mind:
1) SQLite has [virtual file systems feature](https://www.sqlite.org/vfs.html). It is one more abstraction layer between SQLite and database representation. Probably it may help. Try to answer my question 'how would you implement this if let's say you have only C API with libsqlite3 without sqlite_orm'.
2) use `:memory:` database but load and save it into file using [backup feature](https://www.sqlite.org/backup.html). This is feature is also supported in `sqlite_orm`. TL;DR it allows you moving all DB contents from one connection to another. So you may have one connection in memory, second in file and you can move the contents between them. It is not exactly what you need but it is a good start.

**Comment by Teles1** [comment]
2. I guess that sort of works. I need to add an extra step to make this work properly which would involve a tmp file to serve as a backup_from into a :memory: database. Good enough compromise vs amount of work.

**Comment by fnc12** [comment]
@Teles1 BTW we have a discord server. You can join and we can talk there https://discord.gg/gq8sdAZt

**Comment by fnc12** [comment]
@Teles1 should we close this issue or you have more questions?

**Comment by trueqbit** [comment]
@Teles1 You may want to have a look at the ["pointer-passing interfaces"](https://www.sqlite.org/bindptr.html) and whether they solve your requirements.
This allows you to create application-defined SQLite functions that generate objects of any kind that you can pass on to other functions. IOW you can create an ad-hoc extension within your application.

sqlite_orm supports this through the `""_pointer_type`, `pointer_arg_t<>`, `pointer_binding_t<>` and `bind_pointer()` API. An [example](https://github.com/fnc12/sqlite_orm/blob/b045f1b9d8be24337a1762e6240deeef5dce994a/examples/pointer_passing_interface.cpp#L1) is available.

**Comment by Teles1** [comment]
> @Teles1 BTW we have a discord server. You can join and we can talk there https://discord.gg/gq8sdAZt

send me the link again. I opened my e-mail on my phone and forgot to check back on this..


> @Teles1 You may want to have a look at the ["pointer-passing interfaces"](https://www.sqlite.org/bindptr.html) and whether they solve your requirements. This allows you to create application-defined SQLite functions that generate objects of any kind that you can pass on to other functions. IOW you can create an ad-hoc extension within your application.
> 
> sqlite_orm supports this through the `""_pointer_type`, `pointer_arg_t<>`, `pointer_binding_t<>` and `bind_pointer()` API. An [example](https://github.com/fnc12/sqlite_orm/blob/b045f1b9d8be24337a1762e6240deeef5dce994a/examples/pointer_passing_interface.cpp#L1) is available.

Yep! That does it for sure. I've been messing with it for the past couple of days.. thank you!

**Comment by fnc12** [comment]
> > @Teles1 BTW we have a discord server. You can join and we can talk there https://discord.gg/gq8sdAZt
>
> send me the link again please! I opened my e-mail on my phone and then completely forgot to check back on it...

https://discord.gg/HNzH8ctU
