### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by Artalus** [fnc12/sqlite_orm#137]
[Conan](https://www.conan.io/) is a decentralized package manager for C++, quickly gaining popularity.

Since SQLite ORM is a header-only library, it'd be rather easy to package it. I believe you could use [Catch2](https://github.com/bincrafters/conan-catch2) package from [Bincrafters](https://bincrafters.readthedocs.io/en/latest/) as a reference.

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/issues/66
please search for similar issues before applying a new one. Thanks
