### ISSUE TITLE
default_value for a column does not seem to work when inserting an object

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#138]
The sample code for void testDefaultValue(), defines a column with a default_value. However I have not been able to insert an object in such a way that the default value is generate. I am using the following code:
```
	User user{};
	user.name = "Juan";
	user.age = 57;
	auto id = storage2.insert(user);
```
Here the email is empty but does not use the default value defined for that column (which is "example@email.com"). This sort of makes sense since the database has no way of knowing that an empty email should be replaced by the default value (I mean the whole "User" is passed to insert so how do we know when we desire the default value applied?).
Maybe a different insert where specified values for each field are given would be more clear that we desire the default value applied...

Please advice

Juan

**Comment by fnc12** [comment]
Hi Juan. Unfortunately the feature you're asking about is missing right now. `default_value` is used for safe migrations only. I can add this feature, it exists in to [TODO.md](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md). What syntax do you expect:
1) `storage.insert(user, columns(&User::name, &User::date));`
2) `storage.insert<User>(values(&User::id, 5, &User::createdAt, current_timestamp()));`
3) your own option

Thanks

**Comment by fnc12** [comment]
@juandent you can try it in `feature/explicit-insert` branch. It is experimental - supports only member pointers without getters and setters

**Comment by fnc12** [comment]
@juandent please check out `dev` branch - I've merge PR with explicit `insert` and covered it with unit tests

**Comment by fnc12** [comment]
@juandent please close the issue once you've checked it out and everything is ok or write what's wrong. Also feel free to post any issue at any time

**Comment by fnc12** [comment]
looks like VC++ cannot evaluate enum value at  compile time. I'll change enum to static const. I like enums as a static consts more cause enum doesn't require any memory

**Comment by juandent** [comment]
instead of enum, we can use constexpr which does not use any memory either!!
I suggest this:
```
constexpr size_t colsCount = sizeof...(Cols);
```
It works.

But, one thing, the defaulted value is assigned to the field in the db but not in the object user. To get the default value we need to read the user from the db -- which is more expensive than it has to be. Couldn't we refresh the fields that take default values?

Regards,
Juan Dent

**Comment by juandent** [comment]
Or:

```
constexpr size_t colsCount = std::tuple_size<std::tuple<Cols...>>::value;
```

Which do you like best? Both work!

**Comment by juandent** [comment]
Forgot the static. So our options are:

```
static constexpr size_t colsCount = std::tuple_size<std::tuple<Cols...>>::value;
```

or
```
static constexpr size_t colsCount = sizeof...(Cols);
```

**Comment by fnc12** [comment]
@juandent  I did it just like you wrote in the second option. And static isn't necessary - my mistake.
About getting value after inserting: to achieve what you want in pure sql you need to call two queries, so everything is ok - `insert` and the `get` your object.

**Comment by juandent** [comment]
Okay! So, it seems we are okay with this feature. Can you move it to master branch?

Thanks for your immediate response!

Regards,
Juan

**Comment by fnc12** [comment]
I will be moved to `master` branch on the next release. 
Thanks for using the lib and reporting a feature requests. Please feel free to ask any question here
