### ISSUE TITLE
Primary key in column does not work

### ISSUE THREAD

**Issue by Ninja-007** [fnc12/sqlite_orm#14]
I have following code. 
    struct Data
    {
        int mDefault; /**< 0=User or 1=Default*/
        std::string mLang1;
    };
    
    return make_storage(DBPath,
                        make_table("UserPreferences",
                                   make_column("IsDefault", &Data::mDefault, primary_key()),
                                   make_column("Lang1", &Data::mLang1)
                                   )
                                        );

* The created database does not create primary key.
* Is there any way to get Data object for specific primary key without using getall function like storage.get<User>(insertedId);? Does storage.get<User>(insertedId); work in this case?

**Comment by fnc12** [comment]
Hi. Thanks for using the lib. Yes, you can get object by primary key with `get` crud member function.
```
auto storage = make_storage(DBPath,
                    make_table("UserPreferences",
                               make_column("IsDefault", &Data::mDefault, primary_key()),
                               make_column("Lang1", &Data::mLang1)));
storage.sync_schema(); // this is optional - call it if you don't have db file at given path - this call will create it with tables you specified in `make_storage` call.
Data data1{ -1, "en" };
auto insertedId = data1.mDefault = storage.insert(data1); // `insert` function inserts all data from a given object except id and returns a new id. If you want to insert with id call `storage.replace` instead
auto insertedData = storage.get(insertedId);
// now insertedData and data1 are the same
```

**Comment by Ninja-007** [comment]
I am not able reproduce it now. If I get same issue again, I shall reopen it.
