### ISSUE TITLE
Are you familiar with Howard Hinnant date library? Can we use it with the current library as is?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#141]
Hi,
Howard Hinnant date library is a minimalistic super efficient date/time header only library (see https://github.com/HowardHinnant/date). Can we use this type in your library as is?  Or do we need to change something?

Regards,
Juan Dent

**Comment by fnc12** [comment]
I don't familiar with this lib. You can store any type in `sqlite_orm` as is. To use a custom type as is in `sqlite_orm` you need to write some traits. Please look through [enum binding example](https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp)

**Comment by fnc12** [comment]
@juandent is the issue still actual?

**Comment by juandent** [comment]
issue resolved!
