### ISSUE TITLE
Can the typemap be extended or how do we deal with objects whose elements are not fundamental C++ types but user defined types?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#142]
to_sqlite_type receives a string and returns a sqlite_type. How do we deal with objects whose elements are not fundamental ? Like so:

```
struct Date
{
   char day;
   char month;
   int year;
};

struct Person
{
    Date birthdate;
    std::string name;
};
```

Now assume we want to store Persons in this database... how can we do it?

Regards,
Juan Dent

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp

**Comment by fnc12** [comment]
@juandent do you need some more consultancy or everything is clear enough?

**Comment by juandent** [comment]
To what type in Sqlite should a date map to?

**Comment by fnc12** [comment]
@juandent you have to decide it by yourself. The better options are formatter string or int (unix timestamp) I guess

**Comment by juandent** [comment]
Decided for an int...
