### ISSUE TITLE
My compiler does not find dl.lib so I can't compile the examples and tests...

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#143]
Where is dl.lib? and pthread.lib?

I am using Visual Studio 2017 version 15.6.6.

Regards,
Juan Dent

**Comment by fnc12** [comment]
dunno. You don't need them to compile tests and examples

**Comment by juandent** [comment]
Well, ok, but the file CMakeLists.txt in directory tests\third_party\sqlite contains a line:

```
target_link_libraries(sqlite3 dl pthread)
```

which makes all Visual Studio projects generated by CMake to link with dl.lib and pthread.lib.

Probably should delete this dependency in there.

**Comment by fnc12** [comment]
try do delete them and tell me whether it compiles

**Comment by fnc12** [comment]
@juandent so? did it work?

**Comment by juandent** [comment]
Will try today
In the meantime I manually deleted the 2 libraries from the visual studio projects 
And I was able to compile a couple of projects 

Will let you know ASAP

Thanks for your immediate responses


Juan Dent

**Comment by juandent** [comment]
It works!! just remove dl and pthread from the line 
```
target_link_libraries(sqlite3 dl pthread)
```

in the file CMakeLists.txt in directory tests\third_party\sqlite

**Comment by fnc12** [comment]
@juandent please apply a PR with this fix
