### ISSUE TITLE
JSON1 extension

### ISSUE THREAD

**Issue by sivabudh** [fnc12/sqlite_orm#150]
Is it possible to enable JSON1 extension with the ORM?

I'm figuring out how to persist Protobuf objects into SQLite.

**Comment by fnc12** [comment]
Nice question. Let me read about it and I answer you later

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/pull/637

**Comment by fnc12** [comment]
@sivabudh I've just merged all JSON1 extension functions support into `dev` except two functions: `json_each` and `json_tree`. Sorry for late response. These two functions will be implemented later cause I need more time to think about the way to implement them.

**Comment by anauta00** [comment]
Hi, 
I switched to the 'dev' branch to try this.
But I cannot work out how to use this new JSON1 functionality.

Here is part of my code:
	`auto storage = make_storage("test.sqlite",
		make_table("targdef",
			make_column("id", &tTargetDef::dbi, primary_key()),
			make_column("tval", &tTargetDef::tv),
			make_column("con", &tTargetDef::con)));`

Here 'id', and 'tval' are defined as 'int' in the tTargetDef class.
'con' however is defined as vector<double>.

So, this does not work (probably no surprise). The vector of doubles are not magically transformed into json to be stored in the database.

I made a (somewhat) tedious workaround, not using the SQLite JSON1 extension at all.
It uses another header only C++ library named 'struct_mapping'.
Here is the code:
`	tTargetDef tdef;
	struct_mapping::reg(&tTargetDef::con, "con");
	std::ostringstream json_data;
	struct_mapping::map_struct_to_json(tdef, json_data, "");
	tdef.js_con = json_data.str();	// tdef.js_con is defined as std::string
`

Can you shed some light onto this?
I would rather not need to create extra class members to carry the json transformed vector<something> data...

Thanks and greetings,
Auke Nauta

**Comment by fnc12** [comment]
vector of doubles does not make serialization out of box cause `sqlite_orm` does not know which serialization type you want to use. `sqlite_orm` is designed to map string fields to text columns. If your text is a cute text with encoded json/xml/yaml then you need to do some extra magic. There are two ways to accomplish what you want:
1) just make a string field then encode/decode it right after/before selecting/inserting.
2) create your custom type which will store a vector, will be a member mapped to sqlite text column and has binding specializations with json encoding. One can see how to do it in enum binding examples in examples folder https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp .

BTW both ways skip using JSON1 extension cause everything is done within your C++ code. If you want to work with JSON1 extension you need to use its functions: https://www.sqlite.org/json1.html

**Comment by fnc12** [comment]
This issue is been opened for a very long time so far. Now I'd like to close it cause JSON1 extension was implemented some time ago except `json_each` and `json_tree` functions. So I'll add a note about these two functions in TODO file and close this issue. If someone facing some issues please feel free to reopen this issue, create a new one or post a new discussion here on github. Thanks to everyone
