### ISSUE TITLE
storing int struct within a struct

### ISSUE THREAD

**Issue by CrackerHax** [fnc12/sqlite_orm#151]
How would one go about storing this? I looked at the enum binding example but couldn't get it to work for this......

    struct Point 
    {
        int x;
        int y;
        int z;
    }

    struct Container
    {
        Point point;  // this is what I want to store
        int some_other_thing;
    }

    inline auto initStorage(const std::string &fileName) {
      return make_storage(fileName+".db",
                          make_table("containers",
                                     make_column("point",
                                                &Container::point),                               
                                     make_column("other_thing",
                                                &Container::some_other_thing),                                     
                                     primary_key(&Container::point)));
    }

It would be nice if you could just do it one of these ways

                                     make_column("pointx",
                                                 &Container.point.x),
                                     make_column("pointx",
                                                 &Container::point.x),
                                     make_column("pointx",
                                                 &Container::Point::x),
                                     make_column("pointx",
                                                 &Container::get_x()),

**Comment by CrackerHax** [comment]
Speaking of which, the enum binding is a pretty bad example since you would be better off storing a enum as a int or a bitflag int.

**Comment by fnc12** [comment]
Binding means converting a member to an sqlite column value.
Also expression `&Container.point.x` is invalid in c++, `&Container::point.x` is also invalid and `&Container::Point::x` is also invalid. There is no way of getting member's member pointer in c++. So the best solution for you is to add setters and getters for every point's member in `Container` class and map them to your storage:
```
struct Container
{
    Point point;  // this is what I want to store
    int some_other_thing;

    const int& get_x() const { return this->point.x; }
    void set_x(int x) { this->point.x = x; }
}
inline auto initStorage(const std::string &fileName) {
  return make_storage(fileName+".db",
                      make_table("containers",
                                 make_column("x",
                                            &Container::get_x,
                                            &Container::set_x),                               
                                 make_column("other_thing",
                                            &Container::some_other_thing),                                     
                                 primary_key(&Container::point)));
}
```

Also you can add id to point and replace `point` in `Container` with `pointId` and store points in a separate table.

Anyway if you gonna use database you have firstly to understand how you going to store you data.

**Comment by fnc12** [comment]
it is possible if you, for example, will serialize it to string in json format. BTW your union example is cool

**Comment by fnc12** [comment]
@CrackerHax is the issue still actual?
