### ISSUE TITLE
What if data class' private members cannot be accessed?

### ISSUE THREAD

**Issue by sivabudh** [fnc12/sqlite_orm#153]
In this nice example:

https://github.com/fnc12/sqlite_orm/blob/master/examples/private_class_members.cpp

It assumes that we own the data `class` and that we can modify the code to have the getters return the private members by reference.

But what if we don't own the data `class`? For example, `Protobuf` getters do not return many of its  private members by reference. Below are sample code taken from my code base.

```
 public:
  ::google::protobuf::uint32 m_tank2_id() const;
  void set_m_tank2_id(::google::protobuf::uint32 value);

 private:
  ::google::protobuf::uint32 m_tank2_id_;
```

If it's not possible to use Protobuf classes, then I might have to create a duplicate data class with public members just for sqlite-orm.

**Comment by fnc12** [comment]
Hello. Thanks for using the lib. I've been thinking about this several days before. You're right - it would be better for `sqlite_orm` to support different types of getters and setters. I think available getters should be:
`T get() const;`
`T get()`
`T& get() const`
`T& get()`.
`const T& get() const`
`const T& get()`.

Setters are:
`void set(T)`
`void set(T&)`
`void set(const T&)`

What do you think?

**Comment by fnc12** [comment]
@sivabudh please check out #155 in `dev` branch. Not different getters/setters mapping is available in `sqlite_orm`. If everything is ok please close the issue or write a feedback. Also please feel free to post any issue if you got one
