### ISSUE TITLE
Lastest version fails in VS 2017

### ISSUE THREAD

**Issue by unclevlad** [fnc12/sqlite_orm#158]
When trying to build the examples in Visual Studio 2017, I get the following errors fro,m sqlite_orm.h:

Error C2672 'std::toupper': no matching overloaded function found (line 135 )

Error C2780 '_Elem std::toupper(_Elem,const std::locale &)': expects 2 arguments - 1 provided (line 135)

Error C2146 syntax error: missing ';' before identifier 'value_type'	 (line 5785)

Error C4430 missing type specifier - int assumed. Note: C++ does not support default-int	 (line 5785)

**Comment by fnc12** [comment]
try to add `#include <cctype>` before including `sqlite_orm.h`. Looks like I forgot to insert this header, it compiles well on mac with clang but fails with msvc++. Tell me please whether `<cctype>` worked or not - I'll make a PR in `dev` branch with fix. Thanks

**Comment by unclevlad** [comment]
#Include <<cctype> solves the first two issues, but not the last two.

**Comment by fnc12** [comment]
Give me 5 minutes - I need to finish my supper and I'll fix it

**Comment by unclevlad** [comment]
No worries. Thanks for the quick response.

**Comment by unclevlad** [comment]
`std::toupper( )` issue resolved

` using collating_function_pair = decltype(collatingFunctions)::value_type;` still complains with same error

**Comment by fnc12** [comment]
please try again

**Comment by unclevlad** [comment]
Perfect! Thank you so very much.

**Comment by fnc12** [comment]
I'll make a pr to `dev`
