### ISSUE TITLE
lifetype of make_storage return instance

### ISSUE THREAD

**Issue by Ninja-007** [fnc12/sqlite_orm#16]
I am little confused about lifetype and usage of make_storage return instance.

1. Is it supposed to be singleton? If yes, how can I open another connection to DB(for long operations) while keeping the instance active for small queries?
2. What is best way from performance and memory perspective? Creating storage instance as per need or keeping it stored it statically? 
3. Is there any way to store the storage instance as class member?

**Comment by fnc12** [comment]
1. Not exactly singleton but the storage instance is designed to life as long as you need it
2. Create one storage per one sqlite db, sync schema right after (optional), not one per call.
3. Yes. The best way it to `typedef` a storage type by `decltype` of a return type of function that makes a storage. You can see example [here](https://github.com/fnc12/sqlite_orm/blob/master/examples/cross_join.cpp)

**Comment by fnc12** [comment]
One more tip: `initStorage` gotta be `inline` if you want to include a header with it in several places

**Comment by Ninja-007** [comment]
Thanks. I shall experiement it and decide. Do you how much memory Storage object takes? How much costly is contruction and destruction of it?

**Comment by fnc12** [comment]
@Ninja-007 storage is very light. It holds data you passed in `make_storage` call - member pointers, column/table names and table constraints objects

**Comment by fnc12** [comment]
@Ninja-007 is the question still actual?

**Comment by Ninja-007** [comment]
No need of further help. So closing it.
Thanks for help.

**Comment by Ninja-007** [comment]
Is it possible to return make_storage as pointer? It can be done by using make_storage_ptr. 
I want to write class method which can call make_storage and return storage object. As return type is not known, it causes complier errors with auto keyword.

**Comment by Ninja-007** [comment]
I found trick to do that without dealing with pointers.

The class member declaration should be
class XYZ 
{
    decltype(auto) GetDB() const;
    decltype(auto) GetStaticDB() const;
};

in cpp of the class is 
decltype(auto) CMuseoDB::GetDB() const
{
    return make_storage(GetDBPath(), ...);
}
decltype(auto) CMuseoDB::GetStaticDB() const
{
    static auto DB = GetDB();
    return DB;
}

**Comment by Ninja-007** [comment]
May be you can document it, it will be great for other users. 
I keep it open, so you can see it easily. You may close it.

**Comment by fnc12** [comment]
Pointers won't help you with type definitions. If you need an explicit storage type used trick from [update.cpp](https://github.com/fnc12/sqlite_orm/blob/master/examples/update.cpp)

**Comment by Ninja-007** [comment]
Thanks. My problem was creating make_storage equivalent function in class. As its return type is not know till runtime or hard to write at compile time, I was looking for pointer alternative. But it was solved by using decltype(auto) as return type. Compiler calculates it. 
The update example also have typedef and dummy call Initstorage function. I cannot do it in class defination.

**Comment by fnc12** [comment]
@Ninja-007 ok. Is the question still actual?
IMHO storage got to be located in a separate .hpp (and optionally .cpp) file located in `Services` folder that contains project services. This header may contain `initStorage` function and custom types bindings if they exist.

**Comment by Ninja-007** [comment]
Issue is solved. Thanks.
