### ISSUE TITLE
duplicate (create) table from schema ?

### ISSUE THREAD

**Issue by lethe555** [fnc12/sqlite_orm#160]
eg.
`struct Message
{
 int msg_id;
 std::string date;
}`

`db.create_table<Message>("MessageOfUser1");`
`db.create_table<Message>("MessageOfUser2");`

`db.get_all<Message>("MessageOfUser1");`
`db.get_all<Message>("MessageOfUser2");`

**Comment by fnc12** [comment]
it is better to store all messages plain in a single `messages` table and every message must have `user_id` field. But if you want to make two tables with the same class by inheriting and explicit columns. Tables can be created only by calling `sync_schema`. Keep in mind that storage is designed to have a static schema not dynamic.

**Comment by lethe555** [comment]
sharding is common with large amounts of data , split data into different tables could improve some performance.
it's a very userful feature ;)

**Comment by fnc12** [comment]
splitting by tables almost doesn't improve performance. Splitting by files does
