### ISSUE TITLE
codecvt.h - no such file or directory

### ISSUE THREAD

**Issue by ptagl** [fnc12/sqlite_orm#161]
Hi everybody!

I tested this interesting ORM on my Windows PC and it worked very well; now I'm trying to bring it on a Qt application developed for an ARM architecture and compiled with **arm-poky-linux-gcc (GCC) 6.3.0**, but when I add the SQLite ORM header I get this error:

`codecvt.h - no such file or directory`

As far as I understood GCC supports codecvt starting from some version 5.x.x, so I guess that the version 6.3.0 should be compatible, but as you can see that is a custom compiler for a specific target and maybe it's missing something.

Is it possible to get rid of this error? Is codecvt only used for WString support?

Thank's a lot!

**Comment by ptagl** [comment]
Thanks for replying! So, if it's just used for `std::wstring`, is it possible to remove that dependency from SQLite Orm in an easy way or is it deeply embedded (I'm asking just to avoid to start an impossible task)?

**Comment by fnc12** [comment]
it is not difficult to remove it but we need to think about people who needs it. THe only way I see is a macro which avoids this code if it is defined. It isn't defined by default but you can define it in your source code or as a compiler flag. What do you think?

**Comment by ptagl** [comment]
It sounds good to me, I'll give it a try and let you know!

In case it works I guess it could be a really useful improvement to extend the compatibility of this ORM. :-)

**Comment by fnc12** [comment]
I can do it by myself in a different branch later today

**Comment by fnc12** [comment]
please check out `codecvt-compilation-key branch. Use `-D SQLITE_ORM_OMITS_CODECVT` as compilation argument or `#define SQLITE_ORM_OMITS_CODECVT` to omit `codecvt` including and functionality using

**Comment by ptagl** [comment]
I just tried it on my Windows environment and it seems to work, I'll try as soon as possible on the ARM target and let you know.

Thank you very much for your help, I really appreciate it.

If it works I'm gonna use this library for some months, so I hope to be able to contribute a little bit and return the favor!

Thanks again! :-)

**Comment by fnc12** [comment]
You're welcome. If everything is fine on your ARM target then I merge https://github.com/fnc12/sqlite_orm/pull/162 into `dev` branch and later into `v1.3` tag

**Comment by fnc12** [comment]
@ptagl so should I merge #162 or not?

**Comment by ptagl** [comment]
Hi, sorry for the delay but we had trouble compiling this version, but it was just a linker flag missing. It seems to work perfectly, so it can be merged! Thanks a lot for the changes you made! :-)

**Comment by fnc12** [comment]
what linker flag?

**Comment by ptagl** [comment]
I had this same problem:

https://stackoverflow.com/questions/29557683/undefined-reference-to-symbol-dlsymglibc-2-4/29563242#29563242

The proposed solution worked!
