### ISSUE TITLE
Bug with toupper() function

### ISSUE THREAD

**Issue by nuttapongCodium** [fnc12/sqlite_orm#164]
![screen shot 2561-07-17 at 16 53 25](https://user-images.githubusercontent.com/41283714/42810378-fdd5a54a-89e1-11e8-83ae-08c92a02aa03.png)

On line 135 in sqlite_orm.h, `toupper()` is used but the correct `toupper()` isn't included as a header and therefore requires 2 arguments instead of the only 1 provided. This can be fixed by including `#include <cctype>`.

**Comment by fnc12** [comment]
It was fixed but wasn't released. Please use `dev` branch until new release is out

**Comment by heilkn** [comment]
Good day, I also ran into this problem. Please do not wait so long and merge this trivial fix back to your release branch as soon as possible. Else, your released version cannot be used at all.

**Comment by fnc12** [comment]
@heilkn please checkout `dev` branch where everything works fine. Release 1.3 will be published in a month
