### ISSUE TITLE
tests/test.cpp does not build in current master

### ISSUE THREAD

**Issue by unclevlad** [fnc12/sqlite_orm#166]
We were looking for a good example of the use of 'and' in a where clause, and tried building the latest test.cpp, which fails.

1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(920): error C2146: syntax error: missing ')' before identifier 'and'
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(920): error C2146: syntax error: missing ';' before identifier 'and'
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(919): error C2065: 'and': undeclared identifier
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(920): error C2146: syntax error: missing ';' before identifier 'greater_than'
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(921): error C2146: syntax error: missing ';' before identifier 'and'
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(920): error C2065: 'and': undeclared identifier
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(921): error C2146: syntax error: missing ';' before identifier 'lesser_than'
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(922): error C2146: syntax error: missing ';' before identifier 'and'
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(921): error C2065: 'and': undeclared identifier
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(922): error C2146: syntax error: missing ';' before identifier 'lesser_than'
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(922): error C2059: syntax error: ')'
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(923): error C2059: syntax error: ')'
1>c:\users\user\development\cppcommon\sqlite_orm\test\test.cpp(1164): warning C4018: '<': signed/unsigned mi

**Comment by fnc12** [comment]
what platform? windows?

**Comment by fnc12** [comment]
@unclevlad bump

**Comment by unclevlad** [comment]
Sorry for the delay.

Windows / Visual Studio 2017 / Latest Update / 32- and 64-bit

(To be honest, we are having problems getting any of the examples with where clauses to build and/or work)

**Comment by fnc12** [comment]
@unclevlad please try `dev` branch - these bug may be fixed already probably

**Comment by unclevlad** [comment]
Same issues with the dev branch

Windows / Visual Studio 2017 / Latest Update / 64-bit

>test.cpp
1>d:\development\cppcommon\sqlite_orm\include\sqlite_orm\sqlite_orm.h(5786): error C2146: syntax error: missing ';' before identifier 'value_type'
1>d:\development\cppcommon\sqlite_orm\include\sqlite_orm\sqlite_orm.h(8574): note: see reference to class template instantiation 'sqlite_orm::internal::storage_t<Ts...>' being compiled
1>d:\development\cppcommon\sqlite_orm\include\sqlite_orm\sqlite_orm.h(5786): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(920): error C2146: syntax error: missing ')' before identifier 'and'
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(920): error C2146: syntax error: missing ';' before identifier 'and'
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(919): error C2065: 'and': undeclared identifier
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(920): error C2146: syntax error: missing ';' before identifier 'greater_than'
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(921): error C2146: syntax error: missing ';' before identifier 'and'
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(920): error C2065: 'and': undeclared identifier
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(921): error C2146: syntax error: missing ';' before identifier 'lesser_than'
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(922): error C2146: syntax error: missing ';' before identifier 'and'
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(921): error C2065: 'and': undeclared identifier
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(922): error C2146: syntax error: missing ';' before identifier 'lesser_than'
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(922): error C2059: syntax error: ')'
1>d:\development\cppcommon\sqlite_orm\test\test.cpp(923): error C2059: syntax error: ')'
1>Done building project "sqliteormtests.vcxproj" -- FAILED.

**Comment by fnc12** [comment]
try to `#include <ciso646>` in test.cpp file.
BTW there is no `test.cpp` file in the repo. There is `tests.cpp`. Did u rename it?

**Comment by unclevlad** [comment]
I had to rename the file, yes. Down to just a handful of errors now.

1>test.cpp
1>d:\development\cppcommon\sqlite_orm\include\sqlite_orm\sqlite_orm.h(5786): error C2146: syntax error: missing ';' before identifier 'value_type'
1>d:\development\cppcommon\sqlite_orm\include\sqlite_orm\sqlite_orm.h(8574): note: see reference to class template instantiation 'sqlite_orm::internal::storage_t<Ts...>' being compiled
1>d:\development\cppcommon\sqlite_orm\include\sqlite_orm\sqlite_orm.h(5786): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

**Comment by fnc12** [comment]
@unclevlad now try `dev` branch - line 5786 is removed in there already - this issue is duplicate

**Comment by fnc12** [comment]
@unclevlad did it work? If yes I'll add `#include <ciso646>` for windows in `dev` branch and in `master` later

**Comment by unclevlad** [comment]
Had to add /bigobj to get it to finish building, but it works now!

**Comment by fnc12** [comment]
@unclevlad thanks for help. I'll leave the issue opened until `#include <ciso646>` is merged in `dev` branch

**Comment by unclevlad** [comment]
Cool. The team is going to cross-compile on Ubuntu 18; I will let you know if there are any issues.

**Comment by fnc12** [comment]
fixed in #170
