### ISSUE TITLE
How can one model 1-many relationships?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#172]
Hi,

Suppose we have an object called Course with N students. How can we create an object that contains the course and the N students as a collection? (maybe a vector)?

Regards,
Juan Dent

**Comment by fnc12** [comment]
Hi. It is implemented in [subentities example](https://github.com/fnc12/sqlite_orm/blob/master/examples/subentities.cpp). Please take a look

**Comment by juandent** [comment]
Thanks!
