### ISSUE TITLE
left_and_inner_join.cpp sample throws exceptions: SQL Logic Error Sqlite error 1

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#173]
The following code segment from the left_and_inner_join.cpp sample source throws an exception:

```
auto rows = storage.select(columns(&Artist::artistId, &Album::albumId),
			left_join<Album>(on(c(&Album::artistId) == &Artist::artistId)),
			order_by(&Album::albumId));
```
This is supposed to help one learn the library so throwing exceptions is bad for learning.
Please help!! -- I am using Visual Studio 2017 version 15.7.6

Regards,
Juan Dent

**Comment by fnc12** [comment]
@juandent please read the comment in the beginning of the sample code file. There is sample database with a bulk of entries that must be placed right near binary with name `chinook.db`

**Comment by juandent** [comment]
Thanks!! That solved it!!
