### ISSUE TITLE
Is it possible to write a full outer join in sqlite_orm?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#175]
I don't see full_outer_join as defined in sqlite_orm ... given 2 tables A,B how can we construct a full_outer_join in sqlite_orm?

Regards,
Juan Dent

**Comment by fnc12** [comment]
@juandent where `FULL OUTER JOIN` is defined in SQLite? SQLite cannot `FULL OUTER JOIN`

**Comment by fnc12** [comment]
`FULL OUTER JOIN` is missing in `sqlite_orm` and still in development state

**Comment by juandent** [comment]
I tried to use UNION to obtain a full_outer_join but ran into a problem:

SELECT d.type, d.color, c.type, c.color
FROM dogs d
LEFT JOIN cats c USING(color)
UNION ALL
SELECT d.type, d.color, c.type, c.color
FROM cats c 
LEFT JOIN dogs d USING(color)
WHERE d.color IS NULL


This cannot be written using 2 left joins, to wit:

This is the first select:
```
auto rowsA = storage.select(columns(&Dog::type, &Dog::color, &Cat::type, &Cat::color),
	left_join<Cat>(using_(&Dog::color))); 
```

but the second select does not correspond to the original SQL:

```
auto rowsB = storage.select(columns(&Cat::type, &Cat::color, &Dog::type, &Dog::color),
			left_join<Dog>(using_(&Dog::color)),where(is_null(&Dog::color)));
```
This last select has the columns in different order...it is the only way to make the inverse left_join...

Any workarounds?

Regards,
Juan

**Comment by fnc12** [comment]
use `union_all` https://github.com/fnc12/sqlite_orm/blob/master/examples/union.cpp

**Comment by fnc12** [comment]
oops. I forgot. `FULL OUTER JOIN` isn't supported in SQLite at all. You can emulate it using existing `sqlite_orm` features http://www.sqlitetutorial.net/sqlite-full-outer-join/
