### ISSUE TITLE
composite_key example does not allow storage.insert(User{2, "Drake", "Singer")!!

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#179]
```
try{
        //  2 and 'Drake' values will be ignored cause they are primary keys
        storage.insert(User{
            2,
            "Drake",
            "Singer",
        });
    }catch(std::system_error e){
        cout << "exception = " << e.what() << endl;
    }
```
Why is this? I am not allowed to give values to the components of a composite_key?
Where would the values for these columns come from then?

I tried ```storage.replace``` and it works!! (why? and how does replace differ from insert?)
Thanks,
Juan

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/wiki/storage_t%3A%3Areplace

**Comment by juandent** [comment]
Not sure why do it this way but now it is clear. Thank you so much!!!!

**Comment by soroshsabz** [comment]
> https://github.com/fnc12/sqlite_orm/wiki/storage_t%3A%3Areplace

@fnc12 I think it is necessary to explicitly add note to this page that for adding composite key column must be used this

**Comment by fnc12** [comment]
@soroshsabz add note where?

**Comment by soroshsabz** [comment]
@fnc12 Add note to replace page in wiki

**Comment by fnc12** [comment]
@soroshsabz But main description in this page explains this already. Note would be just a duplicate

**Comment by soroshsabz** [comment]
@fnc12 I read replace page again, and it is not say anything about composite key explicitly, it is just say `INSERT OR REPLACE query. Does the same that insert does but inserts primary key too. Use insert to create id and replace to update or insert with specified id. If table has no primary key insert and replace work the same way.`

**Comment by fnc12** [comment]
but composite key is a primary key 2 (or more) times. So words `inserts primary key too` mean that composite key also inserted with `replace`. I think it is clear if developer knows how SQL works

**Comment by soroshsabz** [comment]
@fnc12 your rights but I think some developers like me can be wrong and misuse insert function instead of replace function, because we want to insert object into table , and `replace` function makes our mistaken that we expect replace means object ( row ) exist before we want to add to database.

I think ORM must be near to OOP developer instead of use same notations and concepts in relational database

**Comment by soroshsabz** [comment]
related to #18 #268
