### ISSUE TITLE
Composite key

### ISSUE THREAD

**Issue by Ninja-007** [fnc12/sqlite_orm#18]
I want to use composite key which consists of 2 columns. Is there any way to specify in table creation?
If yes, please give me syntax of the command.

I wish you happy weekend.

**Comment by fnc12** [comment]
Hi. Thanks. Composite key isn't supported yet. It will be added soon. The syntax is assumed to be like this:
```c++
make_table("users",
    make_column("id", &User::id),
    make_column("name", &User::name),
    primary_key(&User::id, &User::name));
```

Have a nice weekend too.

**Comment by Ninja-007** [comment]
Is it still on your list?

**Comment by fnc12** [comment]
Yes. Working on it

**Comment by fnc12** [comment]
This thing is too complicated - I need to think more. The thing is that this form
```c++
make_table("users",
    make_column("id", &User::id),
    make_column("name", &User::name),
    primary_key(&User::id, &User::name));
```
is kind of difficult cause `make_table` expects columns and nothing else as arguments. Please tell me what do you expect from composite key feature in `sqlite_orm`?

**Comment by Ninja-007** [comment]
Good morning,
I want use it make sure that there is only one row with given composite key combination is present. 
Methods
1.  get(composite_key)
2. remove(composite_key)
3. is_present(composite_key) //if possible

**Comment by fnc12** [comment]
Ok I see. I guess that I need to get typename template type of primary key by columns passed as parameter pack in `get` function. Now `get` function works another way - it allows you to pass any type and serializes it to sqlite expression. If change any type to primary key type it will be better cause `get` won't throw an exception if user tries to get an object with no `PRIMARY KEY` but won't compile at all cause primary key type will be deduced from columns' types. But what I need is parameter pack filtering. I know how to transform parameter pack, it's easy. But idk how to filter it. Once I know how to perform it I'll go on with the issue.

**Comment by fnc12** [comment]
in a few weeks. Sorry for a long development time

**Comment by Ninja-007** [comment]
Is it still in your ToDo?

**Comment by fnc12** [comment]
@Ninja-007 Yes. I got a lot of primary work and that's why it takes long time for me to complete the issue. I'm going to close it in about 2 weeks

**Comment by fnc12** [comment]
@Ninja-007 working on it right now. I have `get` and `get_no_throw` implemented already

**Comment by fnc12** [comment]
@Ninja-007 please check out `get`, `get_no_throw` and `replace`. `insert` also works but it ignores composite key and works just like `replace`.

**Comment by fnc12** [comment]
No cause `insert` works in a way it mustn't work. But you can use it already

**Comment by fnc12** [comment]
@Ninja-007 is it ok for you? I don't know whether I need to add `insert` support which will insert only non-primary key columns. What do u think?

**Comment by boodkb** [comment]
If I use a composite primary key, the table is always recreated while syncing the schema.

At line 6037 impl->schema_status always returns "sync_schema_result::dropped_and_recreated".

```
        template<class ...Tss, class ...Cs>
        sync_schema_result sync_table(storage_impl<table_t<Cs...>, Tss...> *impl, sqlite3 *db, bool preserve) {
            auto res = sync_schema_result::already_in_sync;
            
            auto schema_stat = impl->schema_status(db, preserve);
            if(schema_stat != decltype(schema_stat)::already_in_sync) {
```

**Comment by boodkb** [comment]
```

struct Record
{
    int year;
    int month;

    int amount;
};


    auto storage = make_storage("test.db",
                            make_table("records",
                                       make_column("year", &Record::year),
                                       make_column("month", &Record::month),
                                       make_column("amount", &Record::amount),

                                       primary_key(&Record::year, &Record::month)));

    storage.sync_schema();

```

**Comment by fnc12** [comment]
fixed bug with `sync_schema` and added to `tests.cpp` to prevent such a bug in future. I'm leaving the issue opened until I fix `insert` - make it ignore composite key columns

**Comment by fnc12** [comment]
fixed. Now composite keys are totally supported by this lib. Specially thanks to @Ninja-007 and @boodkb .

**Comment by fnc12** [comment]
added working example https://github.com/fnc12/sqlite_orm/blob/master/examples/composite_key.cpp

**Comment by soroshsabz** [comment]
> Good morning,
> I want use it make sure that there is only one row with given composite key combination is present.
> Methods
> 
> get(composite_key)
> remove(composite_key)
> is_present(composite_key) //if possible

@fnc12 I think it is good to provide example that covers all above concepts and it is better to add specific page for composite key and describe CRUD functionalities for this

thanks a lot 👍

**Comment by soroshsabz** [comment]
related to #268
