### ISSUE TITLE
How to check if column is present?

### ISSUE THREAD

**Issue by NikitaFeodonit** [fnc12/sqlite_orm#185]
There are the several similar databases, one of the tables in which can differ by the presence of the optional column "title":
```
CREATE TABLE table_a (number NUMERIC, color TEXT, title TEXT)
or
CREATE TABLE table_a (number NUMERIC, color TEXT)
```
Before querying the table "table_a", I need to check the presence of the column "title" to form the request accordingly with SELECT.

How to check if the column "title" is present?

**Comment by fnc12** [comment]
No way. `sqlite_orm` is designed to use static schema. It means that columns are 100% defined. If you are not sure that your database file's schema matches your storage schema you can call `sync_schema(true)` storage's function. It will fix schema if it differs

**Comment by fnc12** [comment]
there can be some dirty workarounds: make a storage with 2 columns, try select. If exception is thrown then you have 3 columns (or something else is wrong)

**Comment by NikitaFeodonit** [comment]
All databases are read-only with the several tables, which contain the many optional columns because of the historical development of the data storage format. So I can not apply sync_schema(true).

Similar functionality in the Android API:
https://developer.android.com/reference/android/database/sqlite/SQLiteCursor.html#getColumnNames()

**Comment by NikitaFeodonit** [comment]
> there can be some dirty workarounds: make a storage with 2 columns, try select. If exception is thrown then you have 3 columns (or something else is wrong)

Since there are many optional columns, there are many possible combinations.

**Comment by fnc12** [comment]
ok, but first of all you need to define `storage` at first. How do you expect to define it?

**Comment by fnc12** [comment]
there is a function `std::vector<std::string> table_names()` which returns a vector of table names actually existing in database file. One can add something like `pragma table_info(%s);` where `%s` is your table name. There is already some kind of this as a private API in storage. I can make it cute and make public. E.g. `std::vector<table_info> tableInfo = storage.pragma.table_info("my_table");` where 
```c++
struct table_info {
        int cid;
        std::string name;
        std::string type;
        bool notnull;
        std::string dflt_value;
        int pk;
    };
```

**Comment by NikitaFeodonit** [comment]
> What do you think about my way from the upper message?

I'm not a SQLite specialist. You understand the concept better. Therefore, any method is suitable for me.

In the database scheme can still be optional tables. How could this be handled?

**Comment by fnc12** [comment]
It can be handled this way:
1) you create a storage (any storage, even empty like `make_storage("db.sqlite")`), then call `std::vector<table_info> tableInfo = storage.pragma.table_info("my_table");` and then `tableInfo.size()` equals a number of columns. Also every `table_info` struct contains column name and other useful info. So this is how you can define what schema it is. Next take another storage with the exact schema and work with it as is. It means you'll have to have a several storages for all possibilities of your columns combinations. This may not sound like a great idea but optional column isn't a great idea at all. These cases are handled with a maximum number of columns with nullable values. If you like it I'll add `storage.pragma.table_info("my_table");` function in `dev` branch.
2) BTW you can change your schema: just alter all columns with `NULL` values and all storages schema will be the same right after `sync_schema` call. If you are more interested in that way please tell me all your combinations of columns.
Thanks

**Comment by NikitaFeodonit** [comment]
> If you like it I'll add storage.pragma.table_info("my_table"); function in dev branch.

That would be good.

And it would be nice to be able to do this way:
```
  auto storage = make_storage("db.sqlite");
  std::vector<std::string> tableNames = storage.pragma.table_names();
  std::vector<table_info> tableInfo = storage.pragma.table_info("table_a");

  auto table_a = make_table("table_a",
      make_column("number", &TableA::number),
      make_column("color", &TableA::color)
  );

  for(auto & info: tableInfo) {
    if(info.name == "title") {
      table_a.add_column("title", &TableA::title);
    }
  }

  auto storageNew = make_storage("db.sqlite", table_a);

  for(std::string name : tableNames) {
    if(name == "optional_table") {
      auto optional_table = make_table("optional_table", .....);
      storageNew.add_table(optional_table);
    }
  }
```

> BTW you can change your schema: just alter all columns with NULL values and all storages schema will be the same right after sync_schema call.

As I said before, all databases are read-only, so I can not apply sync_schema.

**Comment by fnc12** [comment]
sorry, I forgot that databases are read-only. Also what you want is ill formed for `sqlite_orm` - the lib is designed to use static defined schema not dynamic. It means schema must be known at compile time. It means that functions like `add_column` cannot exist cause if they exist it means we cannot use template magic that makes storage API so simple and handful. Tell me please what options of columns can be and I will think about the best way to solve your problem. If you'd like to talk via voip in russian you can call me at telegram at t.me/fnc12

**Comment by NikitaFeodonit** [comment]
> It means schema must be known at compile time.

Ok. I need a dynamic schema. Then I'll think what else I can do with the static scheme.

**Comment by fnc12** [comment]
@NikitaFeodonit anyway I think I gotta add `pragma.table_info` public API to close the issue

**Comment by NikitaFeodonit** [comment]
Due to the fact that there are a lot of combinations of optional parameters, and the format is developing further, I should use another solution.

But I am grateful to you for so much detailed advice. Thank you.

**Comment by fnc12** [comment]
is the issue still actual?

**Comment by NikitaFeodonit** [comment]
It is no longer relevant to me. Thank you.
