### ISSUE TITLE
How to add and retrieve a vector from the DB 

### ISSUE THREAD

**Issue by quicksilver345** [fnc12/sqlite_orm#186]
Hi,

Basically i want to add and extract a class object in the DB which has one of the member variable as a vector of another class.
eg.
I have something like ->

class XYZ {
public:
	int         id;
	std::string name;
};
class ABC
{
public:
	int id;
	std::string name;
	std::vector<XYZ>  Vec_xyz;
};

Now i want to add and retrieve the object/s of class ABC from the DB.

I did like -> (but not getting the XYZ object from the database)
ABC obj { 1, "ABC1"};
XYZ xyz_obj1 {11, "xyz1" };
XYZ xyz_obj2 {12, "xyz2" };

obj.Vec_xyz.push_back(xyz_obj1);
obj.Vec_xyz.push_back(xyz_obj2);

then i stored the object of class ABC ( that is obj)using the "insert" method.
(while make_storage also i am not able to make the table of type ABC having a column of type XYZ )

But when i am trying to retrieving the data from DB i am not getting the data of class XYZ, i am getting a crash (that is i am retrieving with the get_all method)

Can you please help me regarding my problem.

**Comment by quicksilver345** [comment]
Ya sure i will provide you, but can you help with ->
while make_storage also i am not able to make the table of type ABC having a column of type XYZ, that i.e how to make schema which has one of the member variable as a vector of another class. (like in my example )

**Comment by fnc12** [comment]
ok, but how would you like to store it in a raw sqlite?

**Comment by quicksilver345** [comment]
like, if only a column entry says that how many number of XYZ objects are stored in the Vec_xyz ,that will also work for me.
I have mailed you my code for the reference

**Comment by quicksilver345** [comment]
yes this will work for showing that there is something in the vector, but how shall i add and retrive the data,
Iam getting a crash there.
Have you tried running my code? I think you will also get a crash

**Comment by fnc12** [comment]
I did not try to run your c ode but I do believe that you receive a crash. So if you want to store subentities you have to decide how would you store it in pure raw SQLite. You can add ABCid to XYZ and put it in the table as a column or serialize vector to a string (json or whatever) on insert and deserialize it on select. Both ways work well with `sqlite_orm`. First way is implemented in [subentities example](https://github.com/fnc12/sqlite_orm/blob/master/examples/subentities.cpp)

**Comment by quicksilver345** [comment]
yes, i think this will work for me, thank you so much for the quick help.

If anything else, i will get back

**Comment by fnc12** [comment]
@quicksilver345 you're welcome. Please feel free to post an issue or contact me via e-mail at any time.

**Comment by quicksilver345** [comment]
Hi,
The entities example worked for me but i have a concern here , i have sent you the source code via mail

While  fetching the data from DB, i want to have only those entities which are related to a particular object only.
Like for example -> If you can refer my code, while getting the container class object i want only those Symbol objects which i have pushed back into that particular object of Container not all symbol objects,
Like one to many relation and then fetching them back.

See my attached source code for reference.
I would appreciate if you can help
