### ISSUE TITLE
What if a data member is a std::shared_ptr<T>?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#189]
Is it possible to store/retrieve structs where at least one data member is a smart pointer?

Any example?

Thanks!!

**Comment by fnc12** [comment]
There is an example already located in readme. `std::shared_ptr` and `std::unique_ptr` map to a storage as a nullable types by default as is. Also you can bind your custom type as a nullable. For example [nullable enum](https://github.com/fnc12/sqlite_orm/blob/master/examples/nullable_enum_binding.cpp)

**Comment by juandent** [comment]
Ok, but the general case where std::shared_ptr holds a class does not work, right? Need to implement the relationship between entities with foreign keys, correct? That is, the following will not compile ever:
```
	class Category
	{
	public:
		std::string					m_name;
		bool						m_real_expense_or_income;
	};
	class StatementLine
	{
	public:
		std::shared_ptr<Category>	m_category;
       }
```

Thanks!

**Comment by fnc12** [comment]
yes, `stdLLshared_ptr` works out of the box only if you use basic types like `int`, `float`, `std::string` and other that can map to a column. The thing you want is the same thing you were asking in https://github.com/fnc12/sqlite_orm/issues/184

**Comment by juandent** [comment]
I apologize if I repeated the question.. Thanks for answering though.

**Comment by fnc12** [comment]
@juandent was it clear for you or do I need to answer it somehow another way?

**Comment by juandent** [comment]
I think I get it: basically connect entities with foreign/primary keys.
