### ISSUE TITLE
[feature request] unique constraint

### ISSUE THREAD

**Issue by ahxxm** [fnc12/sqlite_orm#19]
I'd like a column with UNIQUE constraint, this is supported by [sqlite](https://sqlite.org/syntax/column-constraint.html), but I didn't find related usage in sqlite_orm docs..

**Comment by fnc12** [comment]
added in 420b4d35027604a73224bf4969b7e4f037c58703
Please check `examples/unique.cpp` and close the issue if this is what you want. I've added simple constraint (that is specified right after column type not separately). Separated constraints are going bo added later after `FOREIGN KEY`

**Comment by ahxxm** [comment]
yes it's exactly what i want! btw this is quite a fast response........
