### ISSUE TITLE
What is the type returned by get_storage()?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#191]
Hi,
I have a method called get_storage() which initializes the schema and returns an auto& variable. However if I want to use this method elsewhere it complains that "ORM::ORM_DataTier::get_storage': a function that returns 'auto' cannot be used before it is defined"... yet I do not want to include all the schema everywhere I need to use the database and for that I would need a type instead of auto&. Is this type possible to write or not?
Maybe I should refrain from trying to access the storage from cpp files that are not part of the DataTier and the problem is gone. What are your thoughts on this?
Thanks!!

Juan

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/blob/master/examples/update.cpp

**Comment by juandent** [comment]
Yes that was clever but... the whole program still depends on the definition of init_storage()... There is no way to access the storage from another translation unit. We cannot do in another cpp something like so:

```
extern std::shared_ptr<Storage> stor;
```
It will complain that initStorage() returns auto and it needs to see the definition of the function to be able to deduce the type Storage.
So all cpps that want access to initStorage() must include the function's definition...

See the problem?

**Comment by fnc12** [comment]
Yeah. Move `initStorage` to a single `.h` file and include it everywhere you need it. There is not other way cause you need to know all types and members of types mapped to a storage. So it is ok that every translation unit who knows storage would know every mapped class

**Comment by juandent** [comment]
Thanks!!
