### ISSUE TITLE
Any architectural pattern you might suggest in order to keep data access separate from model?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#192]
Hi,
It's me again, haha. I was wondering if you have a small sample where you keep the data access stuff (all that require initStorage()) separate from the model and view of the application. Or if you don't have a sample, maybe you can explain the architecture you use?

Best regards for a lovely library!!

**Comment by juandent** [comment]
I understand. Would it be accurate to state:

1.  that the View does not see the model?
2.  that the Model does not see the View?
3.  that the Controller sees both the model and the view?
4.  but who sees the controller?  The View receives user input (like a mouse click or an edit to some text), thus it should be able to tell the Controller an interpretation of what that user input means. It seems to me that the View should therefore see the controller, to interpret user actions, but what about the Model? If the controller transfers user actions into model actions, the View will likely require updating. This can be done from the Controller sending a Refresh action to the View (accompanied by all the relevant data), so it seems the Model should not need to see the controller.

Is this correct?

You have no idea how much you are helping here!!

Regards

**Comment by fnc12** [comment]
view must not see the whole controller interface at least. To move implementation of user input from view to controller use either callbacks like `std::function` or an abstract class (an interface) like `ViewDelegate` which is inherited by controller and view must store a pointer/reference to it.
If model is active (it means has some kind of logic implemented) so it may be unseen for controller. But if model is just a struct with several fields and that's all so controller must operate with model and next ask view to refresh. You can view this architecture implemented in my [mitsoko-template repo](https://github.com/fnc12/mitsoko-template) in Core dir

**Comment by juandent** [comment]
it is for now
