### ISSUE TITLE
What is the proper way to create a table at runtime

### ISSUE THREAD

**Issue by rohmer** [fnc12/sqlite_orm#209]
I do not necessarily know what the table will be ahead of time, so I need to be able to create it during runtime.  What is the proper way to do this?

**Comment by fnc12** [comment]
Do you know your columns set?

**Comment by rohmer** [comment]
It is a plugin architecture, so I would know the columns at runtime.

**Comment by rohmer** [comment]
I could do something similar to make_storage/make_table, but I do not know how (Or at least it isn't obvious), how to call make_table/sync_schema AFTER the storage is created.

**Comment by fnc12** [comment]
please looks through examples. Storage is created like this:
```c++
struct User {
    int id;
    std::string name;
};

auto storage = make_storage("file.sqlite",
                                  make_table("users",
                                            make_column("id", &User::id, primary_key(),
                                            make_column("name", &User::name)));
```
So you need to know member pointer of your data model class (`&User::id` and `&User::name` in this case). Member pointers is a way to specify columns. So if you don't know member pointers it means you are unable to make/use a storage

**Comment by rohmer** [comment]
Ok, yes.  I am doing the above for the base program.  The issue is at some point in the future there will be plugins added.  So, essentially what I need to do is add a table to the storage after it is created.

Something along the lines of:
storage->add_table(make_table("foo", make_column("bar")

**Comment by rohmer** [comment]
Also, in the above, assume I have the ability to know everything I would at the time of the original make_storage, I just need to ADD to said storage.

**Comment by fnc12** [comment]
there is no difference if you put `make_table` in `make_storage` or in `add_table` call cause in both cases you do know the schema of your table at compile time (or you don't?). So just put it `make_storage` and add objects later when you need it

**Comment by fnc12** [comment]
@rohmer  is the issue actual? If it is let's assume that I've created `add_table` function. What arguments you'd pass in this function?
```c++
storage->add_table(make_table("foo", make_column("bar", &WhatClass::whichMember)));
```

**Comment by rohmer** [comment]
In the case of the above, simply put I would add the class and member.  I would know that.

WHat would be nice is to have the ability to simply add a table, after said storage is complete as opposed to calling make storage/update again.

**Comment by fnc12** [comment]
So you know the class and the member of a table/column which you are going to add after storage is created?

**Comment by rohmer** [comment]
Yes, sorry missed this.  I can push that on to the modules to use that methodology.

**Comment by fnc12** [comment]
Can you please provide a concrete example of code you wish to write if runtime table creation would exist? I need to see how do you see it to understand how to implement it correctly. Thanks

**Comment by rohmer** [comment]
storage->add_table

Then include the table definition exactly like storage->create

**Comment by fnc12** [comment]
So instead of writing
```c++
struct User {
    int id;
    std::string name;
};
auto storage = make_storage("storage.sqlite", make_table("users", make_column("id", &User::id, primary_key()), make_column("name", &User::name)));
```
you want to write
```c++
auto storage = make_storage("storage.sqlite");
storage.create_table("users", make_column("id", &User::id, primary_key()), make_column("name", &User::name));
```
?

**Comment by fnc12** [comment]
closing due to silence

**Comment by rohmer** [comment]
Apologies, yes, that is what I would like.  I would like to extend a previously created storage during run time.

**Comment by fnc12** [comment]
@rohmer describe please your case more detailed. In fact in most cases you really don't need to create table at runtime - you can create it at your program start and describe at compile time

**Comment by rohmer** [comment]
Ok, this case is this:
Server with a plugin architecture.  The plugins can and will be loaded at runtime, and many have yet to be written.  Each plugin will describe their tables and add them to the main database at runtime.

I do not know what they will be ahead of time, and the storage is already created when they are loaded.

**Comment by fnc12** [comment]
The main advantage of `sqlite_orm` is a bulk of cute templated API which lets you create short and descriptive queries with C++. They work because of templates. Templates work at compile time only. That is why storage class is different in different cases. Just like C++ lambda type. So if you want to use runtime loaded plugins with `sqlite_orm` it would be better to have different storages for a different plugins.

**Comment by rohmer** [comment]
Ok, can I have different storages all pointing to the same SQL file?

**Comment by fnc12** [comment]
yes but only if you access to the database within a single storage simultaneously. It means guard storage with a mutex and never call `open_forever` in storage
