### ISSUE TITLE
How to use sqlite_orm from different threads ?

### ISSUE THREAD

**Issue by FabienCarmagnac** [fnc12/sqlite_orm#210]
I tryied to create storage from different threads in parallel on same db file.
I tryied to create a single storage , then give a copy of it to each thread.
Each thread do the "User insertion" example of the wiki page.

No success, exception thrown each time.

Is there a way?

**Comment by fnc12** [comment]
Use a single storage, call `open_forever` after creation and don't copy storage

**Comment by FabienCarmagnac** [comment]
Thanks.

More details here (saw later this thread...) : [https://github.com/fnc12/sqlite_orm/issues/207
](https://github.com/fnc12/sqlite_orm/issues/207
)
