### ISSUE TITLE
How to parametrize the where condition?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#215]
Hi,

I have a wrapper called Repository with a member called Find and I want to pass to Find a predicate to be used in where(), like so:

```
std::vector<T> Find(std::function<bool()> predicate) override
{
	return storage.get_all<T>(sqlite_orm::where(predicate));
}
```

but this does not compile....

How can I get this to work? I want to pass the where clause to the Find method...

Regards,
Juan

**Comment by fnc12** [comment]
Hi. Thanks for using the lib. Your idea is good but can you please provide an example for predicate?

**Comment by juandent** [comment]
Well that's precisely my question ... how can I write a where clause as a predicate to pass it to a function such as this... for example:

`c(&Student::id) == student.id`

Regards,
Juan

**Comment by juandent** [comment]
ok great!!
one doubt: why the std::move(predicate)?

**Comment by fnc12** [comment]
you can omit `move` but in that case predicate will be copied cause `where` function takes argument as a value

**Comment by juandent** [comment]
I am trying to emulate Microsoft's Entity Framework basing on your library. That framework has the following architecture:
there is a DbContext to which objects are added or removed and when one desires to persist them a call to SaveChanges() takes place in which added objects are inserted and removed objects are deleted.
How do you suggest I accomplish this with your library?

**Comment by juandent** [comment]
One idea is to define a DbContext class but it would have to keep track of the status of each object inserted into it to see if it has to insert or upate it when SaveChanges() is called. Is it possible to have a super type for all persistable classes to inherit from? Is inheritance compatible with your library?

**Comment by fnc12** [comment]
Make it easily: 
1) make a storage
2) call sync schema
3) call `storage.begin_transaction()`
4) make `insert`, `remove`, `update`, `set`, `select` etc
5) in `SaveChanges` call `storage.commit()` and `storage.begin_transaction()` again
6) don't forget to call `commit` in the end of app work

**Comment by juandent** [comment]
That is brilliant and simple!!
Will try this way ....
best regards,
Juan

**Comment by juandent** [comment]
How can I expose the iterate method? That is, what is the signature of iterate if I want to make it part of my Repository class:

```
         repository.iterate<T>
```

Also, what is the type returned by make_storage()?  I want to place a reference to it in a class...

**Comment by fnc12** [comment]
1) parametrize iterate just as it declared in `sqlite_orm.h`.
2) return type of `make_storage` can be retrieved with `decltype` just like it is done in [update example](https://github.com/fnc12/sqlite_orm/blob/master/examples/update.cpp)

**Comment by fnc12** [comment]
is the issue actual?
