### ISSUE TITLE
syntax error: missing ';' before identifier 'value_type'

### ISSUE THREAD

**Issue by taclev01** [fnc12/sqlite_orm#216]
Hi,

I'm running through your example with a build of my own and I am getting the following errors linked to sqlite_orm.h in VS2015:

C2146 - syntax error: missing ';' before identifier 'value_type', line 5786
C4430 - missing type specifier - int assumed.  Note: C++ does not support default-int, line 5786

The trouble line is the following:
using collating_function_pair = typename decltype(collatingFunctions)::value_type;

My code is:

**#include "stdafx.h"
#include "sqlite_orm.h"
#include "sqlite3.h"
#include <string>
#include <iostream>
#include <conio.h>

struct user
{
	int id;
	std::string firstName;
	std::string lastName;
	int age;
	int typeId;
};

struct userType {
	int id;
	std::string name;
};

int main()
{
	using namespace sqlite_orm;

	auto storage = make_storage("emp.db", 
			make_table("users",
				make_column("ID", &user::id, primary_key(), autoincrement()),
				make_column("FIRST_NAME", &user::firstName),
				make_column("LAST_NAME", &user::lastName),
				make_column("AGE", &user::age),
				make_column("TYPE_ID",&user::typeId)),
		make_table("USER_TYPES",
			make_column("ID",&userType::id,autoincrement(),primary_key()),
			make_column("NAME",&userType::name,default_value("name_placeholder"))));

    return 0;
}**

Any help is appreciated!

**Comment by fnc12** [comment]
is the issue actual?

**Comment by taclev01** [comment]
Hi,

Yes, and switching to the dev branch fixed it.  Thank you.
