### ISSUE TITLE
Nested query

### ISSUE THREAD

**Issue by scott--** [fnc12/sqlite_orm#219]
Is it possible to create a nested query in sqlite_orm in the style:

select * from Table1
where Table1.id not in (
  select table1_id_ref from Table2 where
   (conditions))

I have not been able to achieve this with sqlite_orm.

Thanks.

**Comment by scott--** [comment]
Thanks, I was looking through the master branch, not the dev branch.

**Comment by fnc12** [comment]
yeah, it is in development state and will be merged to master within next release. But you can use it - subqueries API will not be changed I guess
