### ISSUE TITLE
Foreign key update/delete rules

### ISSUE THREAD

**Issue by DoozyX** [fnc12/sqlite_orm#230]
Is it possible to add rules on the foreign key constraints as cascade, set null etc when a record is deleted/updated?

**Comment by fnc12** [comment]
It depends on whether or not it is possible in SQLite. Do you use it in SQLite?

**Comment by DoozyX** [comment]
Yes it is possible in SQLite.

**Comment by fnc12** [comment]
@DoozyX could you please provide some kind of reference of example of this feature in SQLite? I don't understand you quite right. Thanks

**Comment by DoozyX** [comment]
Sorry, I meant is it possible to add the "on update cascade on delete cascade" to the table definition using the ORM. With raw sql it would look like this:
`
create table test
(
	col1 int
		constraint test_Group_ID_fk
			references "Group"
				on update cascade on delete cascade
);
`
Those are working when setting pragma to enable foreign keys witch is already implemented in the ORM.

**Comment by fnc12** [comment]
Hm, it is first time I face such a feature. Right now it is not supported in `sqlite_orm` but if it has such a simple syntax as you mentioned then it will be easy to add this

**Comment by fnc12** [comment]
I found info [here](https://www.sqlite.org/foreignkeys.html). I'll add this feature in a few days in `dev` branch and merge it in `master` within next release. Is it ok for you?

**Comment by fnc12** [comment]
@DoozyX done in https://github.com/fnc12/sqlite_orm/pull/232 . Please check out `dev` branch and tell whether everything is ok or not

**Comment by DoozyX** [comment]
Everything is working ok. Thank you.
