### ISSUE TITLE
Can visual studio 2015 compile it?

### ISSUE THREAD

**Issue by 36577543** [fnc12/sqlite_orm#235]
Can visual studio 2015 compile it?
If not, how about visual studio 2017?

**Comment by fnc12** [comment]
IDK, depends on C++ standard. Did you try to compile it with VS2015 with C++14?

**Comment by DoozyX** [comment]
I did manage to compile it on the dev branch, but there is an issue with the "journal_mode" enum class.
`enum class journal_mode : char {
  DELETE_MODE = 0,
  TRUNCATE = 1,
  PERSIST = 2,
  MEMORY = 3,
  WAL = 4,
  OFF = 5,
};`
 The first value DELETE is some msvc macro and you need to rename the value to some other name. and its usage in 
`  static std::array<journal_mode, 6> all = {
      journal_mode::DELETE_MODE, journal_mode::TRUNCATE, journal_mode::PERSIST,
      journal_mode::MEMORY,      journal_mode::WAL,      journal_mode::OFF,
  };
`

**Comment by DoozyX** [comment]
@fnc12 It used to give me a link to that macro on Visual Studio, but I currently don't have it installed. By searching on google now I think it's in winnt.h.
`#define DELETE                     0x00010000`

**Comment by fnc12** [comment]
@DoozyX thanks. I'll think how to fix it.

**Comment by fnc12** [comment]
`enum journal_mode` is a public API so changing it leads to a major version change. It is not correct. I guess there must be a better way to avoid this compilation error

**Comment by DoozyX** [comment]
Maybe undefining the macro could help but can't test it right now (not on Windows pc). I will let you know later today when I will be on a Windows pc.

**Comment by DoozyX** [comment]
#undef DELETE solved the issue for me also. I made pull request with it also.

**Comment by fnc12** [comment]
closing due to author silence

**Comment by trueqbit** [comment]
Note: related PR #1009.
