### ISSUE TITLE
Database/Query abstraction

### ISSUE THREAD

**Issue by swex** [fnc12/sqlite_orm#239]
Hello!
First of all great work! I'm not using your library but pretty impressed by its functionality. I think to use it but I have couple questions:

1. Have you ever thought about support other databases?
I'm asking because I'm planning to use Qt's sql(http://doc.qt.io/qt-5/sql-programming.html#database-classes)  and It already has support for several drivers including SQLite.
2. What SQLite specific functionality does library support that difficult to make abstract for other databases?
3. Seems like all I need are: 
3.1 Database connection abstraction(QSqlDatabase in Qt case) 
3.2 Statement execution abstraction(QSqlQuery in Qt case)
3.3 Rows output abstraction(still QSqlQuery)
4. Btw why there are no dev headers in CMakeLists.txt? Seems like you edit it separately and then just call
```bash
cat dev/*.h > sqlite_orm.h
```

What do you think of it in general and maybe some advice what's the best way to implement it.

**Comment by fnc12** [comment]
Hello. Thanks.
1. SQLite was the only db required for me once I've started. Other databases lead to more difficulties: different library dependencies for connectors. Also different databases require socket based connection but SQLite do not. So choosing SQLite was just an easy option for that moment
2. SQLite has several specific points: `total` and `sum` functions work a little bit differently, `REPLACE FROM` doesn't exist in SQL standard at all
3. Idea is great. Probably I'll add different databases but I need to think how to make it better without breaking public API of this lib
4. dev headers are stuck together by [amalgamate.py](https://github.com/fnc12/sqlite_orm/tree/master/third_party/amalgamate) script

The best way to implement another databases it to make abstract `database_connection` in storage class and specify database type in `make_storage`.

**Comment by swex** [comment]
Hello again
I've spent couple evenings and now I've got this:
https://github.com/swex/sqlite_orm/tree/db_abstraction_dev
it's in alpha state, but still. What do you think?

**Comment by fnc12** [comment]
Hello Alexey. It is a very good improvement.
But there are some issues:
1) how do you expect connecting other databases? I think that we cannot just include all connectors in a single lib cause other databases like MySQL require socket connection code which is platform specific. Probably you expect that other developers will create different connectors as a dedicated library and use it with `sqlite_orm`. Answer please how do you see it.
2) too many `virtual` functions. `virtual` can be omitted everywhere in your code cause in most cases developer knows at development time which database he/she wants to use. Do I suggest to replace virtuality with templates
3) unfortunately I cannot merge this code in the lib cause it make the whole lib reformatted and function names code style differs from `sqlite_orm`'s code style (C++ standard like)

But you gave me a good example. I see connecting to different databases like this:
```c++
auto sqliteStorage = make_storage<sqlite>("db.sqlite", make_table(...));
///
auto mysqlStorage = make_storage<mysql>("db.sqlite", make_table(...));
```
where `sqlite` and `mysql` are classes from `adapters` namespace or something like that. These classes have special functions implemented like ones you provided in `database` class (but not virtual). What do you think?

**Comment by swex** [comment]
1. I see it by compile time options like this:
```
option(Sqlite3Support OFF)

if(Sqlite3Support)
    add_definitions(-DSQLITE_ORM_SQLITE3_SUPPORT)
endif()
```
and then use URI strings in make_storage
I've done it already, but for now it uses "default" sqlite connector if string doesnt look like URI, see:
```c++
        static database* make_database(std::string uri)
        {
            auto driverPos = uri.find("://");

            auto driver = driverPos != std::string::npos ? uri.substr(0, driverPos) : std::string { "sqlite" };
            auto args = driverPos != std::string::npos ? uri.substr(driverPos)
                                                       : uri;
            auto ldb = db_driver_factory::create(driver, args);
            auto pdb = ldb.release();
            return pdb;
        }
//and later
auto sqliteStorage = make_storage("sqlite://db.sqlite", make_table(...));
auto mysqlStorage = make_storage("mysql://db.example.com?user=root&password=blabla", make_table(...));
```
2. I'm not sure if template based solution would be better/more performant etc... Also I disagree with  
```
developer knows at development time which database he/she wants to use.
```
What if I want my app to work with several databases? Database management app for example...
Even mobile app may store something locally OR work with remote server. And I think changing connection URI string is the best option that's one more point for `why virtual?`

3. That's totally understandable, I used clang-format's webkit profile for whole project. And I can improve function naming(at first I tried to follow but then lost style :smile:) If you can reformat your current state with some tool we can play next together someway)
4. Real problem in abstraction is how to handle features that not supported by connector?
5. I think that `query::statement_ptr` pretty ugly too, but I couldn't think of anything better quickly
6. Btw some test currently fails for your dev branch is it ok?

**Comment by fnc12** [comment]
2. You can easily work with several databases in a simple app with template based solution as you work with several different `std::vector` containers within a single app. The only case when `virtual` is required is when we don't know at compile time which database must be used but app knows it but getting info form file or network. And virtual functions work a little bit slower than non-virtual
6. Everything works well in both `master` and `dev` branches https://travis-ci.org/fnc12/sqlite_orm

**Comment by swex** [comment]
2. Of course, we can. But again imagine database management app.
3. It works with clang, but not with gcc `g++ (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)`

**Comment by fnc12** [comment]
2. It must work fine just like `std::vector` management app with different types in vectors: `switch` or `if`. I know that it is not the best solution for this case but case is very rare and it is not the reason to create so many virtual functions for all other cases
3. Which test file fails?

**Comment by swex** [comment]
3. My bad. Was failed by because of my changes. Everything is fine now.

**Comment by fnc12** [comment]
Now it is not planned to I am closing the issue. If you got some fresh ideas please feel free to reopen the issue
