### ISSUE TITLE
Saving and retrieving image(blob) in DB

### ISSUE THREAD

**Issue by Ninja-007** [fnc12/sqlite_orm#24]
Good morning,
Do you have any example for saving and retrieving image(blob) in DB? I do not know corresponding data type of blob in C++. 

It will be great if you provide some information.

**Comment by fnc12** [comment]
blob isn't supported right now - it has low priority in development plan cause blobs like images are rarely stored in sqlite. Anyway I planned to add blob support with `std::vector<char>` c++ blob type. I mean if you wanna bind blob to statement you have to use `std::vector<char>`.
Ok if it's required I'll add blob support in next commits: `std::vector<char>` mapping in `make_column`, inserting and selecting `std::vector<char>`.

**Comment by Ninja-007** [comment]
It will be great. Thanks.

**Comment by fnc12** [comment]
Please check it out [here](https://github.com/fnc12/sqlite_orm/blob/master/examples/blob.cpp)

**Comment by Ninja-007** [comment]
Thanks
