### ISSUE TITLE
add common code format specs

### ISSUE THREAD

**Issue by swex** [fnc12/sqlite_orm#240]
Hey there remember #239?
I've started to implement it, so I wonder if there are any contribution guidelines? 
First thing I've done: added dev headers to cmake
```cmake
add_custom_target(dev_headers "${CMAKE_CURRENT_SOURCE_DIR}/dev/*.h")
```
Second would be setup common code formatter. I prefer [clang-format](https://clang.llvm.org/docs/ClangFormat.html). It has nice profile called `File` in that mode clang-format searching upper directories for `.clang-format` file, so right way would be to add that file to repo root.

1. What do you think about format?
2. Can you please write some contribution guidelines?
3. Can you please provide some format specs?

**Comment by swex** [comment]
1. What do you mean by "don't use dev headers"? If I want to make PR I must contribute to final sqlite_orm.h? I though all development happened in dev/*.h, no?(`question for contribution guidelines`)

**Comment by soroshsabz** [comment]
@fnc12 I read [Code style](https://github.com/fnc12/sqlite_orm/wiki/%5BDraft%5D-Code-style) and have some suggestion

1. I think for non template and non pointer function typedef is easer ( one = lesser than using ) and not decreasing readability.
2. camelCase is worry in C++ (Stroustrup and google code style does not doing like this), I think it is good make all variable private like enterprise projects in C++ and provide some getter and setter and meaningful functions for access these in public section.
3. I think if curly braces is begin in another line the code is more cleaner and readable, specially in this project that have complex code.
4. I suggest add more suggest from google code style ( only that support by clang formatter )
5. I suggest add one rule to enforce separate implementation from API in -inl.h files ( I think it is great increasing readability)
6. I suggest add one rule to prohibit long function

thanks

**Comment by fnc12** [comment]
@swex Don't use dev headers in include path. Write code in dev headers, then call amalgamate python script, then commit/build

**Comment by fnc12** [comment]
1. `typedef` decreasing readability cause it has reverse arguments order. See how type aliases are written in different popular languages:
Kotlin: `typealias NodeSet = Set<Network.Node>`
Swift: `typealias Name = String`
C#: `using Cat = System.Text.StringBuilder;`
Typescript: `type MyNumber = number;`
All these examples have the same notation: `operator new = existing` just like assignment operator works: `auto b = 5;` -> `new = existing`. People who write with C++ have different experience in different languages. So the best option for us is using something that is more relevant for the most of people. `typedef` has reverse arguments order: `operator existing new` which is very unusual and actually is a legacy from pure C. So `typedef` will be deprecated totally in the lib once code style is published.
2. camelCase is ok cause it is also very popular in different languages. If I need to choose between comfortable + usual way and C++ special way I will choose the first one cause it makes easier to write features without switching context in your head when you switch to different programming language. Also one of main goals of the lib is API with stdlib style. So public functions/classes are named in stdlib's style. I don't like it but it makes code look like stdlib's one and it is cool (I was inspired by [nlohmann/json](https://github.com/nlohmann/json). But cameCase is more comfortable for writing cause it requires less amount of characters to write same things and underscode is located too far on a keyboard. So inside classes camelCase can be used for sure. Also I do work on the enterprise project where a lot of code is written with C++ with camelCase. About making all vars private: sorry my french but it is a bull*hit cause the best way of developing software or anything at all is KISS - keep it simple stupid. If you don't have to write one lined setter and getter so don't do it - lesser code does the same think. While someone is writing getters and setters I have already wrote a public var and thinking about next feature.
3. It is a matter of a habit. I started learning programming with QBasic where `IF` is written like:
```qbasic
IF myBoolVar THEN
    a = 4
ELSE
    b = 6
ENDIF
```
So similar C++ construction is:
```c++
if(myBoolVar){
    a = 4;
}else{
    b = 6;
}
```
It is easy to read cause everyone can see tab shift on the next line.
Probably you started with pascal which has a dedicated lines for `begin` and `end`.
4. Sorry but why google? Why not apple or microsoft or oracle? I understand that google is the most advanced company in web scope but it is not advanced in C++. Moreover a lot of C++ developers wait for google to add an adequate C++ support in Android Studio. I developer games with C++ for android, ios, windows and mac. And do you know what is the worst development platform? It is google's Android. Why you are talking about google is hard to understand for me. If I would choose whose code style take between google and apple I choose apple cause apple invested a lot in LLVM and clang development which made C++ so great today. But `sqlite_orm`'s code style will not copy code style from any enterprise company - only stdlib's.
5. No. In place implementation is a very popular feature. Look at C#, Java, Swift, Kotlin, JS, Python etc. It is easy to read when you see a declaration and implementation in one place cause you don't have to jump from declaration to implementation. Context jumps are decreasing readability.
6. Long in terms of columns or rows?

Thanks to you

**Comment by swex** [comment]
1. Hi there, any updates on providing prepared .clang-format?
2. Probably it would better to add something like
```c++
void check_result_code(int error, sqlite3* db, std::initializer_list<int> expected_errors = { SQLITE_OK })
{
    if (std::find(std::begin(expected_errors), std::end(valid_errors), error) != std::end(expected_errors)) {
        // sqlite_orm_exception - is some basic exception, based on std::runtime_error
        throw std::system_error(std::error_code(sqlite3_errcode(db), get_sqlite_error_category()));

        //                throw sqlite_orm_exception(error, sqlite3_errmsg(db));
    }
}


//current variant
sqlite3_stmt *stmt;
auto prepareResult = sqlite3_prepare_v2(db, query.c_str(), -1, &stmt, nullptr);
if (prepareResult == SQLITE_OK) {
    statement_finalizer finalizer{stmt};
    if (sqlite3_step(stmt) == SQLITE_DONE) {
        //..
    }else{
        throw std::system_error(std::error_code(sqlite3_errcode(db), get_sqlite_error_category()));
    }
}else{
    throw std::system_error(std::error_code(sqlite3_errcode(db), get_sqlite_error_category()));
}
//proposed variant
sqlite3_stmt* stmt;
check_result_code(sqlite3_prepare_v2(db, query.c_str(), -1, &stmt, nullptr), db);
statement_finalizer finalizer { stmt };
check_result_code(sqlite3_step(stmt), db, { SQLITE_DONE });


```
instead of long branching sheets as of now/

**Comment by fnc12** [comment]
1. clang-format is paused right now cause I'm working of bind bug fixes.
2. It is a good idea. I need to look how it can be used everywhere to deduce the amount of lines

**Comment by fnc12** [comment]
clang format config is added into `dev` branch. I think this issue can be closed
