### ISSUE TITLE
Add CMake config module

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#249]
ITNOA

Hi,

Thanks for great library, I suggest to add [CMake config module](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html) to found this library easily in projects that uses CMake build system with [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html#id3) command.

if you agree with me, I can provide PR for this.

**Comment by fnc12** [comment]
Hi. Thanks for using the lib. Of course I agree.

**Comment by soroshsabz** [comment]
@fnc12 I added PR #254 to resolved this issue, please review it :)

thanks a lot

**Comment by soroshsabz** [comment]
@fnc12 Sorry, I missing install header file, so I resolved this problem in new PR #259 

thanks

**Comment by fnc12** [comment]
merged. Closing the issue. Thanks again
