### ISSUE TITLE
Using include directive instead of copy all headr files to one manually

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#252]
ITNOA

I think it is more readable for library user to see many header files, instead of one large header file. so I think it is better to change sqllite_orm.h to header file that include all another header file, like many other header only projects, for example boost.

for this work you need install all header files alongside of sqlite_orm.h.

I think it is more readable and maintainable approach

if you agree with me, I can provide PR for this. :)

thanks

**Comment by fnc12** [comment]
Yeah, you're right. Single header is made initially to simplify the lib. But once the code became bigger I began to think that it is better to deny it. Also there are different headers in `dev` folder. Single header is glued with all of them together with python script amalgamate located here in `third_party` folder. I think I split code in 1.4. Thanks

**Comment by fnc12** [comment]
It doesn't work manually, it works by python script and this is the way the library works. IDK when this way will be changed cause now it is not the most important thing. Closing it cause it is no required
