### ISSUE TITLE
Change travis to using cmake instead of naked script

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#256]
ITNOA

I think it is good idea to using cmake in travis instead of naked script for building library and then run all tests.

I think if travis uses cmake, CMake files himself is also tested. and some problem like #255 is clear.

**Comment by fnc12** [comment]
There was a cmake script in travis one day submitted by one guy. The reason I changed it back to raw script is that I'm not the best cmake user. You can restore from git history `.travis` config with cmake and make a PR - it is easy. 
Thanks

**Comment by soroshsabz** [comment]
@fnc12 thanks to you we can close this issue now :)
