### ISSUE TITLE
Add appveyor configuration file

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#258]
ITNOA

I think windows is important, so I think appveyor is helpful to provide CI for windows, I suggest using [SQLiteCpp](https://github.com/SRombauts/SQLiteCpp/blob/master/appveyor.yml) configuration for this.

if you agree with me, I can provide PR for this.

**Comment by fnc12** [comment]
Yes. It would be great, thanks you

**Comment by soroshsabz** [comment]
@fnc12 I add PR #260 for add this enhancement.
