### ISSUE TITLE
Using gtest instead of naked main for unit testing

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#261]
ITNOA

I think it is good idea to using mature framework like gtest for unit test and add each unit test separately instead of using main function and add all unit tests to one.

it is very better for debugging and readability

thanks

**Comment by fnc12** [comment]
Yeah you're right. THe reason why I did not use gtest yet is that I did not need to mock anything. But the idea is great. Let's leave the issue opened until it is done. Thanks

**Comment by fnc12** [comment]
[This lib](https://github.com/catchorg/Catch2) I like more

**Comment by fnc12** [comment]
catch2 is added and available in `dev` branch instead of gtest
