### ISSUE TITLE
Official mechanism to declare instance of main types

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#267]
ITNOA

Hi,

I think keep type as variable in large project with many headers is important, so I think it is good to provide official mechanism with meta programming technique that can store main types in classes without using auto.

This issue does not need approach like [FAQ](https://github.com/fnc12/sqlite_orm/wiki/FAQ#1-storage-is-created-with-auto-type-in-all-the-examples-how-can-i-get-its-type-to-keep-a-storage-as-a-variable) , because it is not sufficient readable.

main types such as

```
storage
column
```

thanks

**Comment by soroshsabz** [comment]
related to #89 #128

**Comment by fnc12** [comment]
The answer is here https://github.com/fnc12/sqlite_orm/wiki/FAQ#1-storage-is-created-with-auto-type-in-all-the-examples-how-can-i-get-its-type-to-keep-a-storage-as-a-variable . There is no way to make it better except creating some kind of public types. But it is just a syntax sugar.
