### ISSUE TITLE
[Feature] Add remove overload for accept whole object

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#268]
ITNOA

Why remove does not accept whole object and we have to remove object by id?

I think it is good idea to have whole object overload, because general repository need it.

thanks

**Comment by fnc12** [comment]
cause SQL query doesn't require the whole row in `DELETE` statement - just primary key columns` values.

What ITNOA means?

You're welcome

**Comment by soroshsabz** [comment]
@fnc12 but I think it is not good for generic CRUD, because in large project with general repository pattern  we don't know which member variable or member function is primary key, but sqlite_orm know it and can use this knowledge to make easier using in large project.

**Comment by fnc12** [comment]
We can add one more `remove` function overload which takes `const T &` as an argument but I think it is not necessary. When someone wants to remove a row he or she provides a `WHERE` condition. The simples `WHERE` condition for a CRUD is `WHERE id = ?`. `sqlite_orm` has no goal to look like most CRUDs but it has goal to be a clear frontend for SQLite. That's why API is built with a rule where single function call is a single SQL query with a similar syntax.

**Comment by soroshsabz** [comment]
@fnc12 I think it is good API, please add it. I provide PR #270 for this.

It is necessary when we want to create general repository pattern in large project with many entity and we do not know which member variable is primary key in repository layer.

thanks :)

**Comment by fnc12** [comment]
Can you please provide an example when we use data with database but do not know which field is id? It is a very strange case

**Comment by soroshsabz** [comment]
@fnc12 I add one example in another language

https://github.com/BSVN/Commons/blob/9e71812c985132047aaf818ca68328e626a7e1fc/Source/BSN.Commons/Infrastructure/RepositoryBase.cs#L120

but it is same for C++

**Comment by fnc12** [comment]
Yeah, I used to work with ORMs on objc, swift and C# and I know that most of them have remove by value function. But it is steel is not an answer for question about how can developer use ORM without knowledge about primary keys columns

**Comment by soroshsabz** [comment]
@fnc12 I try to show one example of scenario for you in above example, as you can see in RepositoryBase class use generic object and this class dose not know primary keys columns for generic object, so it has to use remove by object not remove by id

:)

**Comment by soroshsabz** [comment]
@fnc12 Did you can change label to enhancement?

thanks

**Comment by fnc12** [comment]
No, I did not change the label cause I still do not think that this feature is required in the lib. I saw your example in `RepositoryBase.cs`. `RepositoryBase` doesn't know id cause `dbSet` has API which allows removing it without specifying its' id. This type of API is not bad. First of all it is comfortable for new coders and reduces the threshold of entry. Moreover languages with class traits has ORM libraries which add functions in a mapped class itself. E.g. swift https://github.com/IBM-Swift/Swift-Kuery-ORM  
```swift
let myObject = MyObject(id: 5, name: "Bebe")
myObject.insert()
myObject.remove()
```
Yes it is very comfortable and easy to write but `sqlite_orm`'s first goal is to have API that looks like raw SQL cause developer must understand what he writes and what query will be sent to database when any function is being called. 
When you want to delete a user by id in raw SQL you write:
```sql
DELETE FROM users
WHERE id = 5
```
When you need to delete a post by id you write:
```sql
DELETE FROM posts
WHERE id = 10;
```
So you have two args: table and id. So API like `storage.remove<User>(5);` and `storage.remove<Post>(10);` looks the best.
When I was asking you to *provide an example when we use data with database but do not know which field is id* I meant when we (developers) do not which member is id, not `RepositoyBase` or other proxy class. Proxy class doesn't care at all: if `dbSet` would have removal API just like `sqlite_orm` has: `dbSet.Remove<T>(id);` then it would know the id. Developer knows the id always cause he/she works with database very closely. So the question about case when a developer doesn't know which member is id is still opened.

**Comment by soroshsabz** [comment]
@fnc12 I don't say remove current exist API for `remove` I suggest and need to add another API for `remove` that can remove by object, instead of remove by id, so I think it is similar than `object.remove()`

if you add this API we can care Proxy class and increase usability this library for framework developer and make some users happy.

**Comment by fnc12** [comment]
This feature is not required. Closing the issue
