### ISSUE TITLE
Is there support for conditional logic in a select statement?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#281]
Hi,

Can this be programmed in sqlite_orm:

```
select ename, sal,
    case when sql <= 2000 then 'UNDERPAID'
    case when sql>= 4000 then 'OVERPAID'
    else "OK" 
    end as status
from emp
```

with some appropriate syntax?

Regards,
Juan Dent

**Comment by juandent** [comment]
sorry - meant sal not sql

**Comment by juandent** [comment]
or something similar...

**Comment by fnc12** [comment]
Hi. `CASE` is in [TODO list](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md) right now

**Comment by fnc12** [comment]
hey, it is almost done. Check it out [here](https://github.com/fnc12/sqlite_orm/pull/330)

**Comment by fnc12** [comment]
Just merged in `dev` branch. Please check it out
