### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by AlexandrePTJ** [fnc12/sqlite_orm#282]
Hello,

It's looks like there is an issue with how project is tagged.

From github view, release 1.3 exists since the April 9th 2019, but the git tag 1.3 is on September 15th 2018.

**Comment by fnc12** [comment]
Hello. Thanks for using the lib.
Why is this a problem?

**Comment by fnc12** [comment]
IDK why github does this. Probably tag was created once I created a release draft for 1.3 version

**Comment by AlexandrePTJ** [comment]
It is a problem for package creation because we rely on tag.

**Comment by fnc12** [comment]
How can we fix it?

**Comment by AlexandrePTJ** [comment]
I looks like I confused the v1.3 tag and the date of the release annoucement. 1.3 was ready on september but It have been annouced 3 weeks ago, so this what leads me to this confusion.
However v1.3 is not working for package creation, we will wait for the next release and stick to v1.2.

**Comment by fnc12** [comment]
Maybe the reason is that I created a draft release many weeks before I published it. I think it is a genuine practice. This must not confuse package manager or someone else.
`git tag` shows

**Comment by DoozyX** [comment]
Also when exploring github tags it doesn't show the new commits.
![image](https://user-images.githubusercontent.com/8559009/56972253-f4d7ce80-6b6a-11e9-9e28-7d41d20a9350.png)
It is the same with gitkaken.
![image](https://user-images.githubusercontent.com/8559009/56972492-5e57dd00-6b6b-11e9-9037-dae2baeb97d2.png)

**Comment by fnc12** [comment]
@DoozyX I don't understand what exactly you expect when you exploring github tags. Where do you expect new commits to show? You can view new commits by pressing `commits` button to the left from `branches`. Every tag keeps commit list immutable

**Comment by DoozyX** [comment]
I think the v1.3 tag should be where you merged the pull request from dev to master, so when people download the source at the 1.3 tag they can get the new changes, atm they download the source from 6 months ago

**Comment by fnc12** [comment]
I recreated `v1.3` tag and synced it with current `master` branch state. Not tag `v1.3` is up to date with true 1.3 version. Do I need to fix older tags? Also IDK why this happened but I will pay more attention during future releases

**Comment by soroshsabz** [comment]
@fnc12 Why two tag v1.3 exist in GitHub? as you can see in https://github.com/fnc12/sqlite_orm/tags

Did you can remove older v1.3 ?

thanks

**Comment by fnc12** [comment]
I removed `1.3` tag

**Comment by soroshsabz** [comment]
@fnc12 thanks for it, so I think this issue can close :)

**Comment by AlexandrePTJ** [comment]
Thanks, for works well.
