### ISSUE TITLE
SegFault on ArmV7

### ISSUE THREAD

**Issue by justinlottes** [fnc12/sqlite_orm#286]
I am cross compiling for a Raspberry Pi 3 and am experiencing a SegFault when I call synch_schema.

I followed the the stack trace to this line...

(line 7744)
`
if(this->pragma._journal_mode != -1) {
    this->pragma.set_pragma("journal_mode", static_cast<journal_mode> 
        (this->pragma._journal_mode), db);
}
`

It appears the library expects _journal_mode to be signed.  It is unsigned in my environment, causing the if statement to evaluate to true (_journal_mode has a value of 255).

I updated enum class journal_mode to extend signed char and updated the _journal_mode type in pramga_t to be a signed char and everything seemed happy.

**Comment by fnc12** [comment]
Looks like a bug. I'll fix it in a few days. Thank you

**Comment by saumilsdk** [comment]
We are also having the same issues on arm. Please merge the PR created.

**Comment by fnc12** [comment]
@saumilsdk I understand your pain but PR creator has to make fixes before merging

**Comment by fnc12** [comment]
I'm gonna fix it here https://github.com/fnc12/sqlite_orm/pull/288 in an hour

**Comment by fnc12** [comment]
Done. Please confirm whether everything is ok and close the issue if it is. Thanks

**Comment by justinlottes** [comment]
Sorry for the delay.  I have verified that the fix works for me.  Thanks.
