### ISSUE TITLE
Updating a single column value in a row

### ISSUE THREAD

**Issue by godrays** [fnc12/sqlite_orm#289]
Hi,

I'm just wondering if it's possible to update a single column value in a row. Lets say we have a table with 25 columns.

Example:

struct Data
{
    int id;
    string value1;
    string value2;
    ...
    string value24;
};

auto datas = storage.get_all<Data>();
storage.update(datas[5]);

If we need to update single column value, does sqlite_orm has to update (re-write) all columns? 

Please note: I have to use storage.get_all<> first to pull all data and do some calculation then update a column at the end.

My concern here is performance.

Thanks

**Comment by fnc12** [comment]
Yes, you can use `update_all` function which implements a raw update. E.g.:
```c++
auto datas = storage.get_all<Data>();
storage.update_all(set(c(&Data::value4) = 5), where(c(&Data::id) == 4));
```
Which means
```sql
UPDATE data
SET value4 = 5
WHERE id = 4
```
