### ISSUE TITLE
Can't create a method that would specify the sort order of a collection

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#290]
Hi,

I am trying to send the sort order as a parameter to a repository so as to "hide" sqlite_orm a bit and make the code of a higher abstraction level but I get a linker error like so:

> unresolved external symbol "public: class std::vector<struct Model::Category,class std::allocator<struct Model::Category> > __cdecl CategoryRepository::allCategoriesSortedBy<struct sqlite_orm::conditions::order_by_t<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > Model::Category::*>,class std::vector<struct Model::Category,class std::allocator<struct Model::Category> > >(struct sqlite_orm::conditions::order_by_t<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > Model::Category::*>)" (??$allCategoriesSortedBy@U?$order_by_t@PEQCategory@Model@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@conditions@sqlite_orm@@V?$vector@UCategory@Model@@V?$allocator@UCategory@Model@@@std@@@std@@@CategoryRepository@@QEAA?AV?$vector@UCategory@Model@@V?$allocator@UCategory@Model@@@std@@@std@@U?$order_by_t@PEQCategory@Model@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@conditions@sqlite_orm@@@Z) referenced in function "protected: void __cdecl Controller::CTesterForMFCUtilitiesDLLApp::OnFileExercise(void)" (?OnFileExercise@CTesterForMFCUtilitiesDLLApp@Controller@@IEAAXXZ)

The code I want to work with has the following "shape" but I don't know if it is viable. The parameter sortedBy is going to take an order_by.  The two code snippets that show the intent and perhaps the source of my linker error follow:
 
```
template<typename SortedBy, typename C>
C CategoryRepository::allCategoriesSortedBy(SortedBy sortedBy)
{
	using namespace sqlite_orm;

	auto collection = storage.get_all<Model::Category>(sortedBy);
	return collection;
}
```

and then:

```
using namespace sqlite_orm;
CategoryRepository repo;
auto cats = repo.allCategoriesSortedBy(order_by(&Model::Category::m_name_id));
```

Is this possible? Why does it compile fine but does not link? (unresolved external symbol)

Thanks in advance.

Juan Dent

**Comment by juandent** [comment]
What am I doing wrong here?

**Comment by fnc12** [comment]
@juandent I'm looking through it Thank you

**Comment by juandent** [comment]
great! much appreciated!

**Comment by fnc12** [comment]
Looks like you have your template function `allCategoriesSortedBy` implemented inside `.cpp` file not `.h` file

**Comment by juandent** [comment]
yes, indeed!! 
Will move to .h and test. Will let you know.
Thank you so much!!!

**Comment by fnc12** [comment]
Use clang instead of VC++ - it prints more readable error text for templates

**Comment by juandent** [comment]
Tested and success!
