### ISSUE TITLE
how to specify a not null column while creating table?

### ISSUE THREAD

**Issue by saumilsdk** [fnc12/sqlite_orm#291]

**Comment by fnc12** [comment]
Every column with any type is not null by default except `std::unique_ptr`, `std::shared_ptr` and types you explicitly marked as nullable with `type_is_nullable` template  class specialization

**Comment by saumilsdk** [comment]
But interesting thing is that i am able to insert rows without specifying values of few columns which are defined datatype like int and string.

**Comment by fnc12** [comment]
Please give me your code example for more clear context. Thanks

**Comment by fnc12** [comment]
Is the issue actual?

**Comment by saumilsdk** [comment]
I am travelling so i'll have to get back to you on this issue in 3 days.

**Comment by fnc12** [comment]
Is the issue actual?

**Comment by saumilsdk** [comment]
Closing the issue as couldn't get chance to test it.
