### ISSUE TITLE
Composite key documentation/example

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#292]
ITNOA

I think it is good to provide examples that covers all CRUD concepts for composite key and it is better to add specific page for composite key and describe CRUD functionalities for this

thanks a lot

**Comment by soroshsabz** [comment]
I created this issue to focus on documentation and enhance examples around it.

related to #18 #179

**Comment by soroshsabz** [comment]
I think it is good to add label wiki :)

**Comment by fnc12** [comment]
Not required

**Comment by soroshsabz** [comment]
@fnc12 Ok as you wish, but I think wiki is very better than example code to document and guide to how to using this library :)

**Comment by fnc12** [comment]
@soroshsabz Yeah, but right now wiki is used to write docs which have no place in code. This has a major priority. Examples exist in the examples folder and they are supported by CI services. Examples in wiki are hard to support. So there are more important things to write in wiki: e.g. connection lifecycle.
