### ISSUE TITLE
Add example of getter and setter in wiki

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#295]
ITNOA

I suggest add getter and setter documentation and example in wiki in relevant pages, such as `make_column` or `make_storage` or `primary_key` or ...

thanks

**Comment by soroshsabz** [comment]
non-relevant question: is there any way to help and contribute wiki in GitHub?

**Comment by fnc12** [comment]
IDK about contributing on wiki. But I think you can write pages in your fork and then copy and paste it to this project somehow. 
About issue: yes, it is important. Thanks. Now you can use example as a reference https://github.com/fnc12/sqlite_orm/blob/master/examples/private_class_members.cpp

**Comment by soroshsabz** [comment]
> IDK about contributing on wiki. But I think you can write pages in your fork and then copy and paste it to this project somehow.
> About issue: yes, it is important. Thanks. Now you can use example as a reference https://github.com/fnc12/sqlite_orm/blob/master/examples/private_class_members.cpp

My non-relevant question is about `somehow` how? ;)

**Comment by fnc12** [comment]
The simplest is copy and paste. If we need to use a more clever way then I need to google it first

**Comment by fnc12** [comment]
https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by fnc12** [comment]
Also [the example](https://github.com/fnc12/sqlite_orm/blob/master/examples/private_class_members.cpp) explains everything

**Comment by soroshsabz** [comment]
@fnc12 Ok as you wish, but I think wiki is very better than example code to document and guide to how to using this library :)
