### ISSUE TITLE
[Bug] replace does not compile for private class members

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#296]
ITNOA

If I add some little code in private_class_members.cpp in example like below

```cpp
	Player p = storage.get<Player>(soloId);
	soloId.setName("kadan");
	storage.replace(p)
```

I got compile error like below

```
sqlite_orm.h:9126:37: error: lvalue required as unary ‘&’ operand
                             value = &(((o).*(c.getter))());
```

**Comment by soroshsabz** [comment]
related to #4 #40

**Comment by soroshsabz** [comment]
As you can see `get_object_field_pointer` function it is logical and grammatical error, because we cannot point to r-value and return value of non-reference function is r-value so it is not correct to write something like below

```cpp
res = &((obj).*(col.getter))();
```

**Comment by soroshsabz** [comment]
@fnc12 I try to provide PR for this bug

**Comment by fnc12** [comment]
Thank you. There is a way to fix this. There is a class `internal::field_value_holder` which can help. I can fix it if you don't mind

**Comment by soroshsabz** [comment]
@fnc12 Ok but another problem rising with non-copyable member variable like unique_ptr in for example foriegn key example

:D

**Comment by fnc12** [comment]
@soroshsabz what problem?

**Comment by soroshsabz** [comment]
@fnc12 please review PR #298 

Problem: for non-copyable member variable we cannot copy return value of accessor or member variable to result variable and then return it.

**Comment by fnc12** [comment]
fixed in https://github.com/fnc12/sqlite_orm/pull/300

**Comment by soroshsabz** [comment]
@fnc12 How to resolve get_object_field_pointer bug?

**Comment by fnc12** [comment]
@soroshsabz how to reproduce it?

**Comment by fnc12** [comment]
@soroshsabz is the issue actual?

**Comment by soroshsabz** [comment]
@fnc12 yes if you see logic behind this bug, you can found it in some where of code base like get_object_field and …

but as you want I create another issue

**Comment by fnc12** [comment]
Yeah, it is better to have different issues for different bugs. It helps in keeping thing under control. Thank you
