### ISSUE TITLE
Send a raw sqlite query

### ISSUE THREAD

**Issue by unclevlad** [fnc12/sqlite_orm#302]
We are transitioning a large chunk of code from using sqlite3 directly to using this ORM. While most of the transition has been easy-ish, we keep hitting a wall with dynamic multi-column sorts.

In the past, we dynamically generate the sqlite3 query string by evaluating N pairs of column name and sort order. multi_order_by does not work for us in this case, as we have dozens of combinations possible per table.

Is there a way to gain access to the underlying sqlite3 connection so we can invoke sqlite3_exec directly?

**Comment by fnc12** [comment]
There are two points: one is bad and one is good.
The bad is that there is no way to send raw sqlite query with current storage API and storage is not designed for it.
The good is that there is one cute way of getting `sqlite3 *` pointer. Once other developers asked me to add encoding extension. It works easy: after every open you must call a special function and pass `sqlite3 *` pointer to it. So I made `std::function<void(sqlite3 *)> on_open` public member in `storage_t` which is called after every open. So you can write:
```c++
storage.on_open = [](sqlite3 *db){
    // code
};
```
One question is when it is called. If you do not call any query explicitly it will not fire. But if you call `storage.open_forever` then `on_open` will be called at once and database will stay opened until storage's dtor is called.

Please tell whether this fix is ok for you.

Also please paste here example if your dynamic queries. I shall think about it's implementation with current API.

Thanks

**Comment by moebetoblame** [comment]
Ok, on_open is called on every transaction/query. But if we were only concerned with certain transactions/queries we need to save context so that we can interrogate it to determine if we do or don't need to do something? Example:

    void foo::on_open( sqlite3* db ) {
        if ( !this->amConcerned( ) ) return;
        .
        .
        .
    }

**Comment by fnc12** [comment]
You can use `std::bind` to bind more context variables. E.g.
```c++
storage.on_open = std::bind([](sqlite3 *db, const MyContext &context){
    if(!context.anConcerned) return;
}, std::ref(context));
```
Or did I understand you not correctly?

**Comment by moebetoblame** [comment]
I see. But I understood the on_open to be global in nature? Or should we do (pseudocode):

    storage.on_open = ...;
    our_code_here_for_specific_sql_query;
    storage.on_open = nullptr;

    other sql query that is of no concern here // on_open not called

**Comment by fnc12** [comment]
`on_open` is not global. `on_open` is a member for every storage you have. Once storage opens SQLite3 database it runs code
```c++
auto db = sqlite3_open(...);
if(this->on_open){
    this->on_open(db);
}
```

**Comment by moebetoblame** [comment]
Not understanding. Then on_open is only called once, when the db is opened. I thought you said it's called per transaction/query?

**Comment by fnc12** [comment]
No. If you don't call `storage.open_forever` then `on_open` is called on every query which is not within a transaction and on every start of transaction.

**Comment by moebetoblame** [comment]
Ok, thanks :) Enough here to play around and see what works best for us.

**Comment by fnc12** [comment]
@moebetoblame I think it would be better if you write your desired queries options for me then I can think about how to add these features cause `on_open` is not designed for your case

**Comment by unclevlad** [comment]
`
/**
 * Sample class we display as a collection on our web pages
 */
struct Alarm {
    int id{ -1 };
    uint32_t sourceType{ 0 };
    uint32_t sourceId{ 0 };
    uint32_t eventKey{ 0 };
    std::string description{ "" };
    std::string tableRef{ "" };
    std::string tableRow{ "" };
    time_t occurredTimestamp{ 0 };
    uint64_t systemUptime{ 0 };
    time_t clearedTimestamp{ 0 };
    bool cleared { false };
    std::string detail{ "" };
    uint32_t severity{ 0 };
    bool acknowledged{ false };
    time_t acknowledgedTimestamp { 0 };
};

/**
 * Create the storage
 */
inline auto initAlarmStorage( const std::string& path ) {
    return sqlite_orm::make_storage(
        path,
        sqlite_orm::make_table<Alarm>
        (
            "alarms",
            sqlite_orm::make_column( "id", &Alarm::id, sqlite_orm::autoincrement(), sqlite_orm::primary_key( ) ),
            sqlite_orm::make_column( "sourceType", &Alarm::sourceType ),
            sqlite_orm::make_column( "sourceId", &Alarm::sourceId ),
            sqlite_orm::make_column( "key", &Alarm::eventKey ),
            sqlite_orm::make_column( "description", &Alarm::description ),
            sqlite_orm::make_column( "tableRef", &Alarm::tableRef ),
            sqlite_orm::make_column( "tableRow", &Alarm::tableRow ),
            sqlite_orm::make_column( "occurredTimestamp", &Alarm::occurredTimestamp ),
            sqlite_orm::make_column( "systemUptime", &Alarm::systemUptime ),
            sqlite_orm::make_column( "clearedTimestamp", &Alarm::clearedTimestamp ),
            sqlite_orm::make_column( "cleared", &Alarm::cleared ),
            sqlite_orm::make_column( "detail", &Alarm::detail ),
            sqlite_orm::make_column( "severity", &Alarm::severity ),
            sqlite_orm::make_column( "acknowledged", &Alarm::acknowledged ),
            sqlite_orm::make_column( "acknowledgedTimestamp", &Alarm::acknowledgedTimestamp )
        )
    );
}

/**
 * Get the declaration type of the return value of the initialization method
 */
using AlarmStorage = decltype( initAlarmStorage("") );

/**
 * Parameters passed into getAlarms for order-by clause
 */
using OrderByParameters = std::vector< std::pair< std::string, bool > >;

/**
 * Get all Alarms sorted by multiple columns
 */
std::vector< Alarm > getAlarms( const OrderByParameters& params ) {

    /**
     * The vector of parameters could be empty or could contain each non-boolean column name from the Alarm table. The order the pairs are in the
     * vector is based on information we received from an unstream request from the UI.
     *
     * What we do in legacy is build the order_by clause of the query string
     */
    std::string orderBy{ "ORDER BY" };
    std::stringstream out;
    for ( const auto& p : params ) {
        out << p.first << ' ' << ( ( p.second ) ? "ASC" : "DESC" ) << ',';
    }
}
`

**Comment by fnc12** [comment]
What underline type `OrderByParameters` has?

**Comment by unclevlad** [comment]
`using OrderByParameters = std::vector< std::pair< std::string, bool > >;`

It is a container of column names and and an ascending/descending flag in the order requested by the consumer.

**Comment by fnc12** [comment]
Hm, your issue is kind of problem cause `sqlite_orm` is designed for static queries not dynamic. I will think about creating a dynamic multi order by API but it is a challenge cause `sqlite_orm` is built with C++ templates which do not make a friendship with dynamic stuff. Probably I think about something like this:
```c++
auto orderBy = dynamic_order_by();
orderBy.emplace_back(&User::id, true);   // true is asc
orderBy.emplace_back(&User::name, false);    // false is desc
auto rows = storage.get_all<User>(orderBy);
```
IDK yet how to implement it but I think it is a good idea cause you are not the one who needs dynamic order by. Of course this feature will not fix other dynamic stuff but it is a good start.

**Comment by unclevlad** [comment]
While base static queries for select and update usually work, it is the where clauses, including order by, where things often get complicated.

**Comment by fnc12** [comment]
Hey, I have an idea that can be implemented and help you.
```c++
auto orderBy = dynamic_order_by(storage);
orderBy.emplace_back(&User::name, false);
orderBy.emplace_back(&User::id, true);
auto rows = storage.get_all<User>(where(...), orderBy);
```
It is a concept. What do you think?

**Comment by moebetoblame** [comment]
Looks pretty good. The boolean is hard to understand by just looking at code. That is, it's not self documenting. For us, it's great because it maps to what @unclevlad showed you. I'd suggest an enum or similar for the ascending vs descending. Then it becomes clear. We could translate our bool to the appropriate enum accordingly.

**Comment by fnc12** [comment]
enum for two values is over-engineering cause `bool` is an ultimate enum for two values. `true` means `ASC`, it will be specified in comment. Also `bool` arg may be optional so code `orderBy.emplace_back(&User::name);` must look good for people who doesn't specify asc/desc option

**Comment by moebetoblame** [comment]
I disagree. Code should be human readable as much as possible. Enum can be optional too and would look good for people who don't specify. Does true mean ASC or DSC? I have to look at comments somewhere :(

**Comment by fnc12** [comment]
`true` means `ASC` - everything is positive by default. I agree that it is no so readable but it is a common practice: if you need to specify two options use bool. If you need to know what it means just look at its name: `dynamic_order_by::emplace_back(F T::*m, bool isAsc)`

**Comment by moebetoblame** [comment]
I still disagree because you're making assumptions. And you validated my point. If I need to figure out what it means I have to jump to the header. In any case, we can disagree and you can still have a solution. In the end, it's your lib, your call.

**Comment by fnc12** [comment]
Ok, how would you do it?

**Comment by moebetoblame** [comment]
Enum

**Comment by moebetoblame** [comment]
BTW, I enjoy the debate. All in an effort to make good code. :)

**Comment by fnc12** [comment]
No, please show me the whole implementation of this snippet
```c++
auto orderBy = dynamic_order_by(storage);
orderBy.emplace_back(&User::name, false);
orderBy.emplace_back(&User::id, true);
auto rows = storage.get_all<User>(where(...), orderBy);
```

**Comment by moebetoblame** [comment]
orderBy.emplace_back(&User::name, scope_however_desired::DSC);
    orderBy.emplace_back(&User::id, scope_however_desired::ASC);

**Comment by fnc12** [comment]
1. Your version is longer
2. You don't have to jump to header to know what this bool means cause most IDEs show argument names
<img width="293" alt="Снимок экрана 2019-06-04 в 14 10 27" src="https://user-images.githubusercontent.com/6009640/58874821-7a9eea80-86d2-11e9-8027-48359fd4e24b.png">
3. If user uses notepad.exe and feels uncomfortable about this argument he/she can assume positive logic by default: `true` is `ASC`, `false` is `DESC`. This is how most people think

**Comment by moebetoblame** [comment]
1. Yes, but follows typical c++ std scoping approach
2. Agreed. But again you say **most** IDEs. I cover all cases.
3. Again, you say he/she can **assume**. I don't assume.

Look, while I agree most of time people can think true for ASC and IDEs show names, etc. I just don't like to make a presumption about my user when building a lib. That's my point. While this may be deemed trivial, it's a practice I follow regardless.

Like I said, really, it's up to you/community. Your lib is impressive. We just needed a method to do dynamic statements which I imagine others would need as well. It appears you have a potential solution for that which I appreciate.

Cheers

**Comment by fnc12** [comment]
3. do you use notepad.exe for coding? If no then you'll never face such an issue
Finally I decided to use a usual way of creating order_by:
```c++
auto orderBy = dynamic_order_by(storage);
orderBy.push_back(order_by(&User::id));
orderBy.push_back(order_by(&User::name).asc());
orderBy.push_back(order_by(&User::name).collate("myCollation"));
auto rows = storage.get_all<User>(where(...), orderBy);
```

**Comment by fnc12** [comment]
Merged in https://github.com/fnc12/sqlite_orm/pull/361 . Please check out the `dev` branch. If everything is cool please close the issue. Thanks
