### ISSUE TITLE
Reduce code duplication in storage.h

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#303]
ITNOA

I think storage.h is like god class and many code duplication exist in this class, so I suggest to heavy refactor this class and reduce code duplications and make implementation detach from interface, and maybe can define some other classes to distribute responsibility of this class and reduce similarity of this class to god class.

**Comment by fnc12** [comment]
Yeah, the idea exists (but in my head only)

**Comment by fnc12** [comment]
I think this issue cannot be solved in one PR cause the title is very generic. The process is going on every version. Target is: `storage_t` is a public API class, `storage_impl` is a class used for storing schema info. Functions like `storage_t::string_from_expression` will be moved into `statement_serializator` class. Functions `storage_t::parse_table_name` are already moved to a dedicated class called `table_names_collector`. I am closing the issue cause it is too generic.
