### ISSUE TITLE
can DATE and DATETIME type map to sqlite_type::TEXT？

### ISSUE THREAD

**Issue by prettybxp** [fnc12/sqlite_orm#304]
I adopt this library to improve my sqlite operate. 
I Found the DATA comlun data type is mapped to  sqlite_type::REAL;
but in my project, DATE colume is  parse to string.
so I just want to map DATE and DATETIME type  to sqlite_type::TEXT？
I change this in "to_sqlite_type" function,changd the typeMap;
Is there any risk if I do this? thanks in advance.

**Comment by fnc12** [comment]
Type is deduced from C++ type of member. What is C++ type?

**Comment by prettybxp** [comment]
my c++ type is string.
emm, there is a precondition in my question. In my project, the table in db  had created by this:
sql = "CREATE TABLE person ("
          "id VARCHAR(120) NOT NULL PRIMARY KEY,"
          "name VARCHAR(60) NOT NULL,"
          "sex INT NOT NULL DEFAULT(0),"
          "birthday DATE"
          ")";
and there were some date in the table. row : { id : '10091', name : 'jack', sex : '1', birthday : '2019-06-10' }
we don't want to lose the data.

now i create i person struct like this:
struct person
{
   int id;
   std::string name;
   int sex;
   std::string birthday;
}
after i call sync_schema, the result is "old table dropped and recreated"
I lost the data. I found the reason is the c++ type of  birthday should be float or double.
but the data "birthday : '2019-06-10'" can't be parsed to double.

so I want to map DATE and DATETIME type to sqlite_type::TEXT, is it OK?

**Comment by fnc12** [comment]
Hm, I see. Yeah, this is a problem. Looks like that fix is required. I think I can add a member field to a storage like:
```c++
storage.treat_date_as_string = true;
```
or a class specialization for your storage type. What do you think?

**Comment by prettybxp** [comment]
I have no idea which is better. But I appreciate it very much that you think this a problem.
for now, I just change the code like this, it seems work well.
  static std::map<sqlite_type, std::vector<std::regex>> typeMap = {
            { sqlite_type::INTEGER, {
                std::regex("INT"),
                std::regex("INT.*"),
                std::regex("TINYINT"),
                std::regex("SMALLINT"),
                std::regex("MEDIUMINT"),
                std::regex("BIGINT"),
                std::regex("UNSIGNED BIG INT"),
                std::regex("INT2"),
                std::regex("INT8"),
            } }, { sqlite_type::TEXT, {
                std::regex("CHARACTER\\([[:digit:]]+\\)"),
                std::regex("VARCHAR\\([[:digit:]]+\\)"),
                std::regex("VARYING CHARACTER\\([[:digit:]]+\\)"),
                std::regex("NCHAR\\([[:digit:]]+\\)"),
                std::regex("NATIVE CHARACTER\\([[:digit:]]+\\)"),
                std::regex("NVARCHAR\\([[:digit:]]+\\)"),
                std::regex("CLOB"),
                std::regex("TEXT"),
             +   std::regex("DATE"),
             +  std::regex("DATETIME"),
            } }, { sqlite_type::BLOB, {
                std::regex("BLOB"),
            } }, { sqlite_type::REAL, {
                std::regex("REAL"),
                std::regex("DOUBLE"),
                std::regex("DOUBLE PRECISION"),
                std::regex("FLOAT"),
                std::regex("NUMERIC"),
                std::regex("DECIMAL\\([[:digit:]]+,[[:digit:]]+\\)"),
                std::regex("BOOLEAN"),
            -   std::regex("DATE"),
            -   std::regex("DATETIME"),
            } },
        };

**Comment by fnc12** [comment]
I understand what you did. It works for you well but if I merge your fix in the lib I can break code for people who uses DATE as int

**Comment by fnc12** [comment]
Looks like this issue will be solved soon due to this issue https://github.com/fnc12/sqlite_orm/issues/557 cause type comparing is not required at all in SQLite.

**Comment by fnc12** [comment]
@prettybxp please check out `dev` branch again - probably it is solved after https://github.com/fnc12/sqlite_orm/pull/570
