### ISSUE TITLE
How to combine where condition flexibly 

### ISSUE THREAD

**Issue by prettybxp** [fnc12/sqlite_orm#307]
I have a question about how to combine where condition flexibly 
look at the code:

struct person
{
int id;
std::string name;
int sex;
std::string birthday;
}

auto getPerson(Json::value const& condition)
{
bool search_namme = false;
std::string name;
if (condition.isMember("name"))
{
	name = condition["name"].asString();
	search_namme = true;
}

bool search_sex = false;
int sex;
if (condition.isMember("sex"))
{
	sex = condition["sex"].adInt();
	search_sex = true;
}

if (search_namme && search_sex)
{
	return storage->get_all<person>(where(c(&person::name) == name and c(&person::sex) == sex));
}

if (search_namme && !search_sex)
{
	return storage->get_all<person>(where(c(&person::name) == name));
}

if (!search_namme && search_sex)
{
	return storage->get_all<person>(where(c(&person::sex) == sex));
}

if (!search_namme && !search_sex)
{
	return storage->get_all<person>();
}

}

so stupid way, isn't is?

**Comment by prettybxp** [comment]
oh, i got it, it seems duplicate with
https://github.com/fnc12/sqlite_orm/issues/272

**Comment by fnc12** [comment]
Please close it if everything is clear

**Comment by prettybxp** [comment]
I Found still a problem:

I changed my code according to #272

auto getPerson(Json::value const& condition)
{
bool search_namme = false;
std::string name;
if (condition.isMember("name"))
{
name = condition["name"].asString();
search_namme = true;
}

bool search_sex = false;
int sex;
if (condition.isMember("sex"))
{
sex = condition["sex"].adInt();
search_sex = true;
}

auto filter_namme = search_name and c(&person::name) == name;
auto filter_sex = search_sex and c(&person::sex) == sex);
return storage->get_all(where(filter_namme && filter_sex);

then:the sql string will be 
query.c_str()=SELECT 'person'."id", 'person'."name", 'person'."sex", 'person'."birthday" FROM 'users' WHERE (  ( (? ) AND ('person'."name" = ? ) ) AND ( (? ) AND ('person'."sex" = ? ) ) )

I found either filter_namme or filter_sex  is false, then the where conditon will be false. no result will be found.
is't my question clear?

**Comment by fnc12** [comment]
```c++
auto filter_namme = not search_name or c(&person::name) == name;
auto filter_sex = not search_sex or c(&person::sex) == sex);
```

**Comment by prettybxp** [comment]
thanks for your patient answer. I will try it tomorrow.

**Comment by prettybxp** [comment]
yes，it work now. It's my mistake.
I have another concern whitch is the performance.
I don't kwow whether the two sql have the same performance:
1、select * from person where (false or name='jack')
2、select * from person where （name='jack）
or do you have more efficient way to prevent "name='jack'" combine into condition when  the condition is (true or name='jack')

**Comment by fnc12** [comment]
Performance is the same cause https://en.wikipedia.org/wiki/Lazy_evaluation

**Comment by fnc12** [comment]
It the issue actual?

**Comment by prettybxp** [comment]
In china.we can't visit the wikipedia.haha~

**Comment by fnc12** [comment]
Lol. Google lazy conditions evaluation

**Comment by prettybxp** [comment]
I meet a new problem.
we have solved the quesion in where condition. but Now same issue in "internal::set_t<Args...>" when I  use update method.
I think this sentence can't work.
storage.update_all(set(c(false or &User::name) = "jack"), where(c(&User::id) == 1));
best regards

**Comment by fnc12** [comment]
yes, this sentence can't work. If you want to set different field you have to make different queries

**Comment by prettybxp** [comment]
for now，I uset get before update：
    db::person p = storage->get<db::person>(std::string(code));
    if (person.isMember("Name"))
    {
        p.name = person["Name"].asString();
    }

    if (person.isMember("Sex"))
    {
        p.sex = person["Sex"].asString() == "male" ? MALE : FEMALE;
    }

    if (person.isMember("Birthday"))
    {
        p.birthday = std::make_unique<std::string>(person["Birthday"].asString());
    }

    storage->update(p);
