### ISSUE TITLE
why the copy construct of storage_t will NOT copy on_open

### ISSUE THREAD

**Issue by prettybxp** [fnc12/sqlite_orm#309]
storage_t(const storage_t &other):
filename(other.filename),
impl(other.impl),
currentTransaction(other.currentTransaction),
inMemory(other.inMemory),
collatingFunctions(other.collatingFunctions),
pragma(*this),
limit(*this),
+on_open(other.on_open)
{}

**Comment by prettybxp** [comment]
storage_t(const storage_t &other):
            filename(other.filename),
            impl(other.impl),
            currentTransaction(other.currentTransaction),
            inMemory(other.inMemory),
            collatingFunctions(other.collatingFunctions),
            pragma(*this),
            limit(*this),
            +on_open(other.on_open)
            {}

**Comment by fnc12** [comment]
looks like a bug

**Comment by fnc12** [comment]
fixed in https://github.com/fnc12/sqlite_orm/pull/313 and merged in `dev` branch
