### ISSUE TITLE
better error reporting

### ISSUE THREAD

**Issue by swex** [fnc12/sqlite_orm#318]
@fnc12 two questions
1. What do you think about adding own exception based on `std::runtime_error`, with proper error string from `sqlite3_errmsg`?
2. I think it would be cool to show query if its preparation failed, and get expanded SQL query on error with `sqlite3_expanded_sql`

**Comment by fnc12** [comment]
1. On fail you receive `std::system_error` which contains `sqlite3_errmsg` already in `what()` function call. Check out [unique.cpp](https://github.com/fnc12/sqlite_orm/blob/master/examples/unique.cpp) example.
2. This is a good idea. I need to think about it. Do you have any idea about how to perform it?

**Comment by swex** [comment]
1. That is not true :cry: , currently you making `what()` output with `sqlite3_errstr(code)`, which returns result code explanation, there is no way to get exact reason of error with that, I understand thatk you using `errstr` because it works without `sqlite3*` object... So you'd better to throw out custom error category and replace it with custom exception...
2. Sure! wrap all `sqlite3_prepare_v2` calls in something like this:
```c++
void sqlite_orm_prepare(
        sqlite3 *db,            /* Database handle */
        const char *zSql,       /* SQL statement, UTF-8 encoded */
        int nByte,              /* Maximum length of zSql in bytes. */
        sqlite3_stmt **ppStmt,  /* OUT: Statement handle */
        const char **pzTail     /* OUT: Pointer to unused portion of zSql */
) {
    auto prepareResult = sqlite3_prepare_v2(db, zSql, nByte, ppStmt, pzTail);
    if (prepareResult) {
        std::string error_string;
        auto query = sqlite3_expanded_sql(*ppStmt);
        if (query) {
            error_string.assign(query);
            sqlite3_free(query);
        } else {//sqlite3_expanded_sql may return null @see https://www.sqlite.org/c3ref/expanded_sql.html
            error_string.assign(sqlite3_errstr(
                    prepareResult));//if expanded_sql unavaliable just retur error code explanation as before
        }
        throw sqlite_orm_exception(prepareResult, error_string);
    }
}
```

**Comment by fnc12** [comment]
1. Ok, I see. You're right. We need to figure out how to add custom string to `std::system_error`
2. It is a good idea but there is no reason to hurry up with it cause I am thinking about refactoring the whole code to separate template code with non-template. I shall keep your idea in mind

**Comment by fnc12** [comment]
the improvement is here https://github.com/fnc12/sqlite_orm/pull/355

**Comment by fnc12** [comment]
done
