### ISSUE TITLE
string primary key broken

### ISSUE THREAD

**Issue by swex** [fnc12/sqlite_orm#319]
check example below it failed on insert, because of prepared statement skips id column
```c++

static std::string get_random_string(int len = 5) {

    std::random_device random_device;
    std::mt19937 engine{random_device()};
    std::uniform_int_distribution<char> dist('a', 'z');
    std::string result;
    for (auto i = 0; i < len; ++i) {
        result.push_back(dist(engine));
    }
    return result;
}


struct StringPkEntry {
    std::string id = get_random_string();
    std::string value;
};


void check_string_pk() {
    using namespace sqlite_orm;
    auto storage = make_storage("",
                                make_table("string_pk_test",
                                           make_column("id", &StringPkEntry::id, primary_key()),
                                           make_column("value", &StringPkEntry::value)));
    storage.sync_schema();
    for (int i = 0; i < 5; ++i) {
        StringPkEntry entry;
        entry.value = "value #" + std::to_string(i);
        storage.insert(entry);
    }
    auto all_entries=storage.get_all<StringPkEntry>();
    for (const auto&entry:all_entries){
        std::cout <<storage.dump(entry) << std::endl;
    }
}
```
currently it throws on insert with query:
```sql
INSERT INTO 'string_pk_test' ( "value", "nullable_text") VALUES ( ?, ?)
```

**Comment by fnc12** [comment]
It is not a bug cause `insert` skips inserting pk column. Try it in raw SQLite:
```sql
sqlite> create table test(id text not null, value text not null);
sqlite> .schema
CREATE TABLE test(id text not null, value text not null);
sqlite> insert into test(value) values('ototo');
Error: NOT NULL constraint failed: test.id
sqlite> 
```

**Comment by fnc12** [comment]
If you need to insert an object with pk use `replace` instead

**Comment by swex** [comment]
I still think it **can/must?** be treated as bug because replace will `replace` row with the same pk, but insert will add one more row...

I thought in above insert ORM must generate below code
```SQL
sqlite> insert into test(id,value) values('megaId','ototo');
```

**Comment by fnc12** [comment]
if the row exists with the same pk `insert` will fail anyway. That is why `replace` must be used for inserting rows with pks

**Comment by swex** [comment]
ah you right, I messed up because of copy-pasting your example, but you didn't add `PRIMARY KEY` to id column. So my stupid test passed.(Yeah I was surprised when I could add second row with the same pk :)

**Comment by WXIN** [comment]
I understand that _replace_ must be used for inserting rows with pks.  But I am confused - if _insert_ will skip pks, then what is the utility of insert?  It seems _insert_ is useless?  

Any heads up would be appreciated. Thank you.

**Comment by fnc12** [comment]
@WXIN how would you perform this
```sql
create table users(id integer primary key autoincrement, name text not null, surname text not null);
insert into users (name, surname) values('Ava', 'Max');
insert into users (name, surname) values('Post', 'Malone');
select * from users;
1|Ava|Max
2|Post|Malone
```
with `sqlite_orm` without useless _insert_?
Sometimes you need sqlite to make an id for you. It works cause of `autoincrement` constraint with integer primary key

**Comment by WXIN** [comment]
Thank you for the heads up. I saw that insert works i.e., incrementing an
integer primary key, even when “autoincrement()” is not explicitly
specified using sqlite_orm.

So is it designed like that, “autoincrement” is always implicitly applied
to an integer primary key using sqlite_orm?

Or, in other words, we would need to use replace() if we don’t want an
integer primary key to be auto-incremented?

I am still learning this wonderful library. Your help is
greatly appreciated.

**Comment by fnc12** [comment]
`autoincrement` is not implicitly applied
to an integer primary key using `sqlite_orm` - `sqlite_orm` is about clarity. When you are describing a schema you describe it the same way you do it in raw SQL:
```c++
struct User {
    int id = 0;
    std::string name;
};

struct Visit {
    int id = 0;
    decltype(User::id) userId;
    long time = 0;
};
auto storage = make_storage("prepared.sqlite",
                                make_table("users",
                                           make_column("id", &User::id, primary_key(), autoincrement()),
                                           make_column("name", &User::name)),
                                make_table("visits",
                                           make_column("id", &Visit::id, primary_key()),
                                           make_column("user_id", &Visit::userId),
                                           make_column("time", &Visit::time),
                                           foreign_key(&Visit::userId).references(&User::id)));
```
means
```SQL
create table 'users' (
    'id' integer not null primary key autoincrement, 
    'name' text not null);
create table 'visits' (
    'id' integer not null primary key, 
    'user_id' integer not null, 
    'time' integer not null, 
    foreign key ('user_id') references 'users'('id'));
```
We have to use `replace` when we need to insert a pk by ourselves and we have to use `insert` when we need not to insert pk. More details can be found in the [project wiki](https://github.com/fnc12/sqlite_orm/wiki/storage_t%3A%3Ainsert)

**Comment by WXIN** [comment]
I was still quite confused with your explanation.  But after I looked into sqlite_orm source code, everything suddenly becomes clear: 
sqlite_orm::insert internally calls [sqlite3_last_insert_rowid()](https://www.sqlite.org/c3ref/last_insert_rowid.html), which according to sqlite document says "**_If the table has a column of type INTEGER PRIMARY KEY then that column is another alias for the rowid_**."

So the confusion really comes from the lack of explanation in sqlite_orm documentation that:  for a C++ struct memeber, if that member is of integer type AND is the designated primary key, AND the table is WITHOUT_ROWID, then,  that integer column is just an ALIAS of rowid which will be managed and autoincremented by sqlite.   Therefore,  in SUCH case,  sqlite_orm will just ignore that PK.  

Probably the documentation of sqlite_orm::insert could be improved, so a new user like me won't get lost why PK should be ignored.  Particularly, I would suggest that the wiki should explicitly point out that the integer primary key will be treated as ALIAS of ROWID.

Anyway - sqlorm is still the BEST C++ ORM for sqlite I've ever seen.  Thank you again for this great work and super neat design in modern C++.

**Comment by fnc12** [comment]
This feature is implemented in SQLite. `sqlite_orm` is just a frontend for it. If you know SQLite then you understand it automatically.
Also I glad to know that you like the lib.
