### ISSUE TITLE
Subentities (related subqueries) by storage

### ISSUE THREAD

**Issue by swex** [fnc12/sqlite_orm#326]
Hi there again!
You have an example with subentities, It works for sure, but I think it would be cool to have a way to fill automatically. As in most of ORMs, for example pythons sqlalchemy or django. see https://docs.djangoproject.com/en/2.2/ref/models/relations/ for example.

```c++
class Mark {
public:
    int value;
    int student_id;
};

class Student{
public:
    int id;
    std::string name;
    int roll_number;
    std::vector<decltype(Mark::value)> marks;
};

using namespace sqlite_orm;
auto storage = make_storage("subentities.sqlite",
                            make_table("students",
                                       make_column("id",
                                                   &Student::id,
                                                   primary_key()),
                                       make_column("name",
                                                   &Student::name),
                                       make_column("roll_no",
                                                   &Student::roll_number),
                                       related_set(&Student::marks,&Mark::student_id)), //something like that maybe
                            make_table("marks",
                                       make_column("mark",
                                                   &Mark::value),
                                       make_column("student_id",
                                                   &Mark::student_id)));
```
I'm not sure if its better to add overload like: `get_with_related, get_all_with_related`, or just add another variable template argument to list related fields user wants to load, or even storage_t member function to fill object with list of related fields.
```c++
//rs<&Student::marks> here and later some tag to indicate related set 
    auto res = storage.get_and_related<Student,rs<&Student::marks>>(studentId);
//or
    auto res = storage.get<Student>(studentId ,rs<&Student::marks>);
//or
    auto res = storage.get<Student, rs<&Student::marks>>(studentId );
//or
    auto res = storage.get<Student>(studentId);
    storage.fillRelated(res,rs<&Student::marks>);


```

**Comment by fnc12** [comment]
Oh you are not the first who is asking for this. Subentities is a huge milestone cause it has a lot of options that must be satisfied. First of all there are three relations options:
* one to one
* many to one
* many to many
Next there are different types of managing every case. Let me explain:
one to one can be performed in several ways:
1) `struct Book` holds a value/raw-pointer/reference/unique-pointer/shared-pointer to an instance of `struct Category`. Also it creates issues about how categories must be obtained right after any book with a given category was obtained before? E.g. I have a schema like this:
```
book
====
id: int
name: text
category_id: int

category
===
id: int
name: text
```

I have date inserted like this:
```sql
INSERT INTO categories(id, name)
VALUES (1, "Fiction");
INSERT INTO categories(id, name)
VALUES (2, "Poetry");

INSERT INTO books(id, name, category_id)
VALUES (1, "1984", 1);
INSERT INTO books(id, name, category_id)
VALUES (2, "Dune", 1);
INSERT INTO books(id, name, category_id)
VALUES (3, "Milk and Honey", 2);
```
So how C++classes must be declared?
```c++
struct Book {
    int id = 0;
    std::string name;
    int categoryId = 0;
};
```
or
```c++
struct Book {
    int id = 0;
    std::string name;
    Category *category = nullptr;
};
```
or
```c++
struct Book {
    int id = 0;
    std::string name;
    Category &category;
};
```
or even 
```c++
struct Book {
    int id = 0;
    std::string name;
};
```
with another service table with pairs
```c++
struct CategoryToBook{
    int bookId = 0;
    int categoryId = 0;
};
```
Also there is still an issue about how to store one to many relationship: as a foreign key in a `books` table or as a dedicated table with pairs of foreign keys to book and to category. I think we need to support both ways cause different people use different ways of implementations.

Also these issue can also be applied to one to one. The least issues has many to many relations cause it must be implemented with a dedicated table of id pairs. But we still are not sure how to store a reference to a related entity in C++ class: just a vector of subentities? If so do subentities need an `student_id` field? All marks of the same students have the same `student_id` to is looks like there is no reason of storing it. How must we make a reference to a related object in one to one relations? How to specify all these options in `make_storage` call?

You can use a different way: create a subclass of storage and add `get<T>` member function to it with two implementations: generic with `return this->super::get<T>();` call and specialized for `Student` which will get all marks and assign them to `Student::marks`

**Comment by fnc12** [comment]
if there are no suggestions I shall close the issue just like other subentities related issues
