### ISSUE TITLE
storage get with composite key seems to not work anymore

### ISSUE THREAD

**Issue by Moranos23** [fnc12/sqlite_orm#348]
Hi all, storage get functionality seems to not work correctly when a composite key is inserted.
Thanks.

**Comment by fnc12** [comment]
Hi. Could you please provide code to reproduce it? Are you talking about `dev` branch?

**Comment by Moranos23** [comment]
Yes, i'm talking of the dev branch. Simply calling the get with the std::tuple throw an exception. The same code worked for master branch.

**Comment by fnc12** [comment]
Looks like you are calling `auto object = storage.get<Object>(std::make_tuple(...));`. It is incorrect

**Comment by Moranos23** [comment]
I'm calling it like storage.get<Object>(tuple.get<0>,tuple.get<1>). So with two id fields

**Comment by fnc12** [comment]
How do you specify the storage schema?

**Comment by Moranos23** [comment]
classX tempRule = mSqliteDB.get<classX>(classY.mPrimaryKey, i);
class X definition in schema:

make_table("classXname",
            make_column("line", &classX::mLine),
            make_column("rule", &classX::mRule),
            make_column("fkclassZ", &classX::mFKclassZ),
            primary_key(&classX::fkclassZ, &classxX::mLine),
            foreign_key(&classX::fkclassZ).references(&classZ::mPrimaryKey).on_delete.cascade()),
I had no no problem with master branch

**Comment by fnc12** [comment]
Yeah, the problem exists in `dev` branch. The reason is tuple iteration refactoring. The bug can be reproduced in `get` and `get_pointer` call. Actual reason of incorrect behavior is that when you call `storage.get<Object>(1, 2);` it doesn't bind `1`, `2` but `2`, `1`. The fix is coming https://github.com/fnc12/sqlite_orm/pull/349 . Thanks you

**Comment by Moranos23** [comment]
Thanks you for the library.

**Comment by fnc12** [comment]
fixed
