### ISSUE TITLE
Separation of DB and ORM functionality request

### ISSUE THREAD

**Issue by Ninja-007** [fnc12/sqlite_orm#35]
There is some functionality which does not need table(s), for example drop_table, user_version. These operate above ORM functionality. Creating ORM storage object to use this functionality is not always possible and logical. For example, checking existence of table, checking version of database.
I see there are two alternatives. 
1. Creation of separate class which deals with database functionality and adding make_db equivalent to make_storage without tables. (preferred)
2. extending make_storage to make tables optional.

**Comment by Ninja-007** [comment]
DB
-int user_version()
-void user_version(int value)
-bool table_exists(const std::string &tableName)
-std::string libversion()
-void drop_table(const std::string &tableName)
-int changes()???
-int total_changes()???
-int64 last_insert_rowid()???

Possible candidates with modification
-void backup_table(sqlite3 *db)
-void create_table(sqlite3 *db, const std::string &tableName)
-void copy_table(sqlite3 *db, const std::string &name)
-void rename_table(sqlite3 *db, const std::string &oldName, const std::string &newName)

**Comment by fnc12** [comment]
This is excess over-engineering. Separation will make interface complicated.
If you do not need columns you can create a storage with no columns with `auto emptyStorage = make_storage("empty.sqlite");`

**Comment by Ninja-007** [comment]
Thanks, let me try it.

**Comment by Ninja-007** [comment]
What will happen when I call select on this make_storage("empty.sqlite"); instance?

**Comment by fnc12** [comment]
You'll get compile time error with `static_assert` that tells you that type isn't mapped to the storage

**Comment by Ninja-007** [comment]
auto DB = make_storage(GetDBPath());
    DB.table_exists("TableNames");

sqlite_orm/sqlite_orm.h:5049: error: ‘sqlite_orm::storage_t<>::impl_type {aka struct sqlite_orm::storage_impl<>}’ has no member named ‘table_exists’
             return this->impl.table_exists(tableName, db);
                    ~~~~~~~~~~~^~~~~~~~~~~~

**Comment by fnc12** [comment]
Ok. I'll fix it now

**Comment by Ninja-007** [comment]
Thanks, closed.

**Comment by Ninja-007** [comment]
Did you move again table_exists to impl?

**Comment by fnc12** [comment]
That's correct. You get empty map cause there are no mapped types in a storage.

**Comment by Ninja-007** [comment]
OK,  Can you put assert there?

**Comment by fnc12** [comment]
No. It works correctly. `sync_schema` syncs tables. If there is no tables you get empty map and 0 tables are synced. There is nothing incorrect here.

**Comment by Ninja-007** [comment]
OK
