### ISSUE TITLE
Fatal Error C1128: number of sections exceeded object file format limit : compile with /bigobj

### ISSUE THREAD

**Issue by Moranos23** [fnc12/sqlite_orm#351]
Hi all,
I'm having  this error in Visual Studio 2017, adding more code in make storage function.
I suppose my obj generated file is too big, cause I'm creating a db with 14 tables right now. There is a way to avoid this? Splitting the creation in more cpp files? I creating the storage in an inline function, I don't know if this can contribute.

**Comment by fnc12** [comment]
Hi. Please provide your `make_storage` call

**Comment by fnc12** [comment]
closing due to silence
