### ISSUE TITLE
[bug] char -1 is 255 on arm gccV5.4.0

### ISSUE THREAD

**Issue by chenzhengxi** [fnc12/sqlite_orm#363]
L7748: if(this->pragma._journal_mode != -1) {
this->pragma._journal_mode is -1, but when it compare with int, it become 255.
so L7748 is true. all char compare with -1 have the same bug.
change: if(this->pragma._journal_mode != **(char)**-1) will be OK.
platform: arm gcc 5.4.0

**Comment by fnc12** [comment]
Hi. Do you use the latest 1.4 release?

**Comment by chenzhengxi** [comment]
I use master branch, I know why, Thanks

**Comment by fnc12** [comment]
I am just asking. `dev` branch was merged a few days ago into `master` branch so the issue can still exist. Please check out whether it exists one more and tell me. If it does I shall fix the issue. Thanks
