### ISSUE TITLE
Can I make sqlite_orm friend with a class ?

### ISSUE THREAD

**Issue by meghasemim1999** [fnc12/sqlite_orm#365]
i need my classes to be encapsulated and i dont want it's fields to be accessed from outside of the class even with getters and setters 
for example i may have an "id" field in every class that is going to be stored in DB
but i dont want that id to be accessed by anyone else than sqlite_orm
is there a way to give sqlite_orm access to private fields without getters and setters?

**Comment by fnc12** [comment]
Ok, you can do it the same way you do it in other cases: you need to have friend classes/functions that access your members. In this case you need to have 2 friends: your storage class and a function/class that has `make_storage` call
