### ISSUE TITLE
Is it Possible To Provide a factory for sqlite_orm?

### ISSUE THREAD

**Issue by meghasemim1999** [fnc12/sqlite_orm#368]
Hi
I need to create the actual object in a factory with some pre Configurations then hand it over to sqlite_orm to feed it from database.
is it possible to do such thing?

**Comment by fnc12** [comment]
you have created a duplicate issue https://github.com/fnc12/sqlite_orm/issues/367 . Please close one of them

**Comment by meghasemim1999** [comment]
> you have created a duplicate issue #367 . Please close one of them

Sorry ... my bad ... I closed the other one

**Comment by fnc12** [comment]
I don't understand the issue. Could you provide more details please?

**Comment by meghasemim1999** [comment]
> I don't understand the issue. Could you provide more details please?

i have some field in my entity that are not being stored in data base and it is safe for me to set those fields before ORM sets other fields for me

**Comment by fnc12** [comment]
add default value to those fields

**Comment by meghasemim1999** [comment]
> add default value to those fields

They Are Other Objects them selves
I have them available at runtime

**Comment by fnc12** [comment]
Can you provide an example? I still cannot understand clearly what you are talking about.

**Comment by meghasemim1999** [comment]
![image](https://user-images.githubusercontent.com/30366887/63768261-034db100-c8e5-11e9-9661-59b3c71831ab.png)

**Comment by meghasemim1999** [comment]
![image](https://user-images.githubusercontent.com/30366887/63768641-ff6e5e80-c8e5-11e9-9f94-407464f53e6c.png)

**Comment by fnc12** [comment]
Ok, now I understand. These functionality is missing right now. I thought about this thing. The easiest solution is a `sqlite_orm::factory<T>` class which can be specialized:
```c++
namespace sqlite_orm {

    template<class T>
    struct factory {
        T make() const {
            return {};
        }
    };

}
```

And you specialize it like this:

```c++
namespace sqlite_orm {

    template<>
    struct factory<Entity> {
        Entity make() const {
            return {a, b}; // the question is where will you get those `a` and `b`
        }
    };

}
```
Is it ok for you?

**Comment by meghasemim1999** [comment]
it looks good but there will be some problems:

- my code will be dependent on the specific version of your library and my project is a big one and if some day you change it my project could be corrupted

- i need to store some fileds like "a" , "b" in my factory class to feed created entities, can i add fields to factory<Entitiy> class in my specialization?

in fact i think it would be good if i could tell ORM to use one of my custom classes to create Entity

**Comment by fnc12** [comment]
1) your code depends on the lib anyway. If some code is merged in a release it means that it will be supported by further versions until major version is not changed. Code can be changed in dev branch between releases it is true. But this is the way development is performed.

2) how do you create `a` and `b`? What dependencies do they have?

> in fact i think it would be good if i could tell ORM to use one of my custom classes to create Entity

this is exactly what I suggested before: specialization is a custom class which is done by you in your code not sqlite_orm code. Just like it is done in enum_binding example https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp

**Comment by fnc12** [comment]
is the issue actual?
