### ISSUE TITLE
Question  on using in memory db for examples/update.cpp 

### ISSUE THREAD

**Issue by leonyu1010** [fnc12/sqlite_orm#369]
Hi there, I am trying out the examples/update.cpp.  It works fine as-is. However, if I change to in memory db as follows

stor = std::make_unique<Storage>(initStorage(":memory:"));

then it would throw exception on the first call of  stor->replace().

In comparison, examples/in_memory.cpp  works fine for me.   

What is the difference in terms of using in-memory DB  between the two examples? 

thank you for your time and help.

**Comment by fnc12** [comment]
Yeah, I can reproduce it too. This is strange cause different example (`iteration.cpp`) works well with same steps. I need to investigate it more. Thank you

**Comment by fnc12** [comment]
I shall look through it in a few days. I am busy right now with reviewing the PR with code formatting and prepared statements feature. Sorry for waiting

**Comment by unclevlad** [comment]
I have gone through all of the examples in the dev branch, and I cannot get a single one to work when using the "initStorage" technique with an in memory database. They all work fine with a file. The call to sync_schema passes, but any CRUD method causes an exception with **no such table: <table name>: SQL logic error.**

**Comment by fnc12** [comment]
fix is on its way https://github.com/fnc12/sqlite_orm/pull/402

**Comment by fnc12** [comment]
bug is fixed. Please check out `dev` branch

**Comment by helmesjo** [comment]
Any release inc with this fix? @fnc12

**Comment by fnc12** [comment]
@helmesjo yes, in a month
