### ISSUE TITLE
How to store storage?

### ISSUE THREAD

**Issue by SecondReality** [fnc12/sqlite_orm#370]
The return _type_ of make_storage is usually a very long template type, such as:

sqlite_orm::internal::storage_t<sqlite_orm::internal::table_t< {stuff }, sqlite_orm::internal::column_t< {more stuff } }

If I want to make the storage a member of one of my classes is there a way to accomplish this without having to type out the full definition of the class (and without making a typedef somewhere?).

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/wiki/FAQ

**Comment by SecondReality** [comment]
Thank you and apologies! @fnc12
