### ISSUE TITLE
Recommendation for backup and restrore of underlying database

### ISSUE THREAD

**Issue by unclevlad** [fnc12/sqlite_orm#381]
We have a new requirement to perform run-time backup and restore of our SQLite database without stopping our service. We did this is previous versions using the native sqlite3 inteface.

What is the best way to do this using this ORM?

**Comment by fnc12** [comment]
Can you provide and example of how you do a backup of your database please? Backup API entry exists in [TODO list](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md). I just want to know how do you use it practically. Thanks

**Comment by unclevlad** [comment]
We literally implement the [SQLite 3 Backup API](https://www.sqlite.org/backup.html)

Upon return, we move the new database file to a specific location. For restore, we just reverse the process.

**Comment by naviialto** [comment]
I tried to get the sqlite3 * pointer and implement it myself for the same reason as above.
But I didn't find a way to get sqlite3 * handlers from storage.
Is there any way?

**Comment by fnc12** [comment]
@naviialto `sqlite_orm` is not designed for obtaining `sqlite3 *` at any time. It is designed for using its own API instead. The only way to get `sqltie3 *` is to use `storage.on_open` lambda which is called once every time database is opened. It was created for using encryption extensions

**Comment by fnc12** [comment]
According to API reference you provided the idea of backup API in `sqlite_orm` is:
```c++
storage.backup_to("filename.sqlite");
storage.backup_to(otherStorageInstance);
storage.backup_from("filename.sqlite");
storage.backup_from(otherStorageInstance);
```
First line performs a backup write operation to "filename.sqlite" file.
Second performs a backup write operation to `otherStorageInstance` which is `storage_t<...>`.
Third line performs a backup read operation from file named "filename.sqlite".
Fourth line performs a backup read operation from `otherStorageInstance` which is `storage_t<...>`.

Also you may need to make a step by step backup in some cases and report a progress outside. For this case a `backup_t` object can be handy:
```c++
auto backupObj = storage.make_backup_to("filename.sqlite");    //    backupObj is `sqlite_orm::internal::backup_t`
auto backupIsDone = false;
do {
    backupIsDone = backupObj.step(5);    //    this will call `sqlite3_backup_step`
    int remaining = backupObj.remaining();    //    remaining is int
    int pagesCount = backupObj.pagecount()    //    pagesCount is int
    //    report progress
} while (backupIsDone);
```
`backupObj` calls `sqlite3_backup_finish` in its dtor. What do you think?

**Comment by unclevlad** [comment]
This is exactly what I was looking for.

**Comment by fnc12** [comment]
Ok. I shall make this in a few days and merge it into `dev` branch

**Comment by unclevlad** [comment]
Thank you. I look forward to receiving it.

**Comment by fnc12** [comment]
Just merged https://github.com/fnc12/sqlite_orm/pull/383 . Please check out `dev` branch

**Comment by unclevlad** [comment]
Looks good. Thank you.
