### ISSUE TITLE
Linking Error: undefined reference to `typeinfo for std::_V2::error_category'

### ISSUE THREAD

**Issue by jason7sc** [fnc12/sqlite_orm#390]
I'm attempting to integrate this library into my project. I'm able to compile this with sqlite3, however I get this linker error:
```
[typeinfo for sqlite_orm::sqlite_error_category]+0x8): undefined reference to `typeinfo for std::_V2::error_category'
```

Any ideas on how to resolve this?

#### Environment
Compiler: GCC 5.2.0
SQLite Version: 3.29.0
C++ Version: c++14

**Comment by fnc12** [comment]
I am not sure whether it compiles with gcc 5. Please try gcc 6 or higher. CI supports gcc 6 +

**Comment by jason7sc** [comment]
Thanks for responding. It turns out it was an issue with RTTI. Compiling with the `-frtti` flag caused this linking error. Once I removed the flag, it worked. This will be compiler specific, depending on how the c++ std library is packaged.
