### ISSUE TITLE
Single query distinct get_all?

### ISSUE THREAD

**Issue by SecondReality** [fnc12/sqlite_orm#394]
I'd like to get a vector of my objects, but have them be unique on a particular column (let's call this column height).
I'm trying to achieve something like this:

    std::vector<BasketballPlayer> result = storage.get_all<BasketballPlayer>(
        distinct(&BasketballPlayer::Height))

In the case where there are several players with the same height, I don't care which one is selected. How can I achieve this?

Thank you!

**Comment by fnc12** [comment]
Hello. How would you write this query in raw SQL?

**Comment by SecondReality** [comment]
@fnc12 

apparently something like this:

`
SELECT * 
FROM armor_unsealed
WHERE id IN 
(
   SELECT min(id) 
   FROM armor_unsealed
   WHERE piece=:piece 
   GROUP BY image 
)'
`
(came from https://stackoverflow.com/questions/19010459/how-to-get-all-columns-from-a-select-distinct-query)

In that case it looks like it's using min to select between cases where there are multiple matches on the same image.

BasketballPlayer "Bob" 90cm 100kgs
BasketballPlayer "Tony" 80cm  78kgs
BasketballPlayer "Harry" 80cm  77kgs

So in this case I want to end up with:

BasketballPlayer "Bob" 90cm 100kgs
BasketballPlayer "Harry" 80cm  77kgs

(Harry and Tony are the same height, and I don't care which is selected, but going with the min weight is fine).

**Comment by fnc12** [comment]
```c++
std::vector<BasketballPlayer> result = storage.get_all<BasketballPlayer>(where(in(&BasketballPlayer::id, 
    select(min(&BasketballPlayer::id), where(is_equal(&BasketballPlayer::piece, myPieceInstance)), group_by(&BasketballPlayer::image)))));
```

**Comment by fnc12** [comment]
is the issue actual?

**Comment by SecondReality** [comment]
Thank you @fnc12 that helps a lot.
