### ISSUE TITLE
Private field in class?

### ISSUE THREAD

**Issue by LionZXY** [fnc12/sqlite_orm#40]
Maybe add support getter and setter for object class? Like this:
```
storage = make_storage("db.sqlite",
                               make_table("players",
                                          make_column("id",
                                                      &Player::getId,
                                                      &Player::setId,
                                                      autoincrement(),
                                                      primary_key())));
```

**Comment by fnc12** [comment]
Hi. Thanks for using the lib. Please show me your `Player` class code with `setId` and `getId` body. It helps me to define what form of setters and getters I should add. Thanks

**Comment by LionZXY** [comment]
Like this:
```
int getId();
void setId();
```

**Comment by fnc12** [comment]
Maybe you want to say `int getId() const {return id;}` instead? If setters and getters are so simple I can add what you want easily I guess.

**Comment by LionZXY** [comment]
I want method for custom processing data.
Russian version:
Я прошу добавить возможность кастомных геттеров/сеттеров. Чтобы можно было как-то обрабатывать удобно данные без классов-прослоек.

**Comment by fnc12** [comment]
Ok. You mean you need to do some extra actions in `setId`?

**Comment by LionZXY** [comment]
Yes

**Comment by fnc12** [comment]
@LionZXY ok. I'll do it tomorrow

**Comment by fnc12** [comment]
added in fb9ebdbc91e48d5720d2e566c695ecc8b273ddfc. Please check it out and if everything is ok close the issue. Thanks

**Comment by LionZXY** [comment]
Yes, big thanks!
