### ISSUE TITLE
When I create a table, how to set the default value of the column is the current time？

### ISSUE THREAD

**Issue by daitouguan** [fnc12/sqlite_orm#408]
My code is written like this, but it doesn't work.
make_column("timestamp", &induction::date, default_value((string)datetime("now", "localtime")))

**Comment by daitouguan** [comment]
This is the statement I want to create the table：

Create Table If Not Exists signal (
id INTEGER PRIMARY KEY AUTOINCREMENT,
datetime timestamp default (datetime('now','localtime')),
）；

**Comment by fnc12** [comment]
this is a good case and `default_value` function is planned exactly for something similar but right now functions in `default_value` are not supported cause you're the first one who asked for this. Fortunately it is very easy to fix to I shall merge a fix soon. Syntax will be like `make_column("timestamp", &induction::date, default_value(datetime("now", "localtime")))` (no conversion to string)

**Comment by fnc12** [comment]
@daitouguan please check out `dev` branch.

**Comment by daitouguan** [comment]
THANKS！
