### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Ninja-007** [fnc12/sqlite_orm#41]
Thanks for providing the great libraries.
I really appreciate your work and consultation. 

As recognition to your work, I would like to donate some money. Do you accept donations?`

**Comment by fnc12** [comment]
Hi. Thanks for using the lib. I'm glad it is useful for you. Of course you can donate $ to https://www.paypal.me/fnc12 . Thanks

**Comment by Ninja-007** [comment]
Welcome.
I need to find out some financial details like tax deductions etc. Once I get these details, I shall set connection with you.

**Comment by Ninja-007** [comment]
I need some paper signed by you. Please write your email address. Then I can send you draft of the document.

**Comment by fnc12** [comment]
fnc12@me.com

**Comment by Ninja-007** [comment]
I sent one email to you.

**Comment by Ninja-007** [comment]
I sent you donation as commited before.
Looking forward for your co-operation.

**Comment by fnc12** [comment]
Thanks you very much. It really makes me work harder

**Comment by fnc12** [comment]
@Ninja-007  is the issue still active?

**Comment by Ninja-007** [comment]
I made my donation. If you want, you can keep it active for other prospective doners else close it. MfG

**Comment by fnc12** [comment]
@Ninja-007 thanks for your donation. I'd like to close the issue cause opened issue means I have to work on it but there is no work to solve. Also all comments will still be accessible to this is not a problem if I close the issue I guess
