### ISSUE TITLE
Escaping string values

### ISSUE THREAD

**Issue by bkfox** [fnc12/sqlite_orm#42]
String quotes are not escaped and generate wrong sql queries. Taking the employee examples, making a query like:

`storage.get_all<Employee>(where(is_equal(&Employee::name, "Paul'l")));`

Generates query:
`SELECT COMPANY."ID", COMPANY."NAME", COMPANY."AGE", COMPANY."ADDRESS", COMPANY."SALARY" FROM 'COMPANY' WHERE (  'COMPANY'."NAME" = 'Paul'l') `

Throwing an error:

`
terminate called after throwing an instance of 'std::runtime_error'
  what():  near "l": syntax error
zsh: abort (core dumped)  ./a.out
`

**Comment by fnc12** [comment]
Thanks for posting the issue. There are two ways to solve it in the lib:
1) not serialize arguments but bind them
2) serialize but replace single quotes with double quotes.
I'll think about it and fix it.

**Comment by fnc12** [comment]
Closed in 38722eea32852c2da169f53c25b4eba6c9a31218 . Also added this case in `tests.cpp`. Solved by 2 way cause `iterate` function returns an object that uses pure string query.
