### ISSUE TITLE
CSV import to populate database

### ISSUE THREAD

**Issue by Ninja-007** [fnc12/sqlite_orm#43]
I am considering to use CSV file to populate database. 

There are two choices to do that 
1. Use build-in facility of sqlite to import CSV format. I tried to find some examples to deal with it, but could not find any useful.
2. Parsing and doing insert/replace on database: This option will have to read and parse CSV. It is kind of error-prone.

What do you think about option 1? Do you know how to implement it?

**Comment by fnc12** [comment]
`sqlite_orm` is an sqlite frontend not CSV parsing lib. To solve your issue you need to get CSV parser, next parse it line by line in a loop. In every iteration create a data model object and insert it. To improve it insert values within a transaction. If you doubt about this method assume you don't have `sqlite_orm` but have only libsqlite3. You'd parse CSV with CSV parser and next created queries with SQLite C interface and run it. So I repeat `sqlite_orm` isn't a CSV parser. But you can stick together CSV parser with `sqlite_orm` to solve your issue.

**Comment by Ninja-007** [comment]
Thanks.
I was asking you about 8. CSV Import from https://sqlite.org/cli.html 
If you know any easier way to do it.

**Comment by fnc12** [comment]
Ok I see. The point is that `.import` and `.mode csv` are implemented only in `sqlite3` command shell not in C API. More info [here](https://stackoverflow.com/questions/1626604/how-do-i-use-the-sqlite3-import-command-using-the-c-api)

**Comment by Ninja-007** [comment]
Thanks.
Then I close this topic as out of scope.
