### ISSUE TITLE
questions regarding threading and crashes

### ISSUE THREAD

**Issue by midjji** [fnc12/sqlite_orm#430]
I guess you would make the defaults something like serialized(in the sqlite multithreaded sense) statements, disk sync after each change, journaling? and leave it to the user to select otherwise if they want to trade guarantees for speed. I just want to make sure? 

More specifically: I cant see what the default threading option is? 
What happens if the program crashes while doing an op? 
What happens if the program terminates ? will it synch?
Can I instruct the storage to synch to disk in a blocking fashion? Do I need to ?

cheers
//mikael

**Comment by fnc12** [comment]
Hello. I don't understand the first paragraph.
About `More specifically`: one can obtain value of threading option by calling `sqlite_orm::threadsafe()` function which calls `sqlite3_threadsafe()` and returns its returned  value. If the program crashes then the whole process is crashed and IDK what can be done at all. If the program terminates then it will terminate. What do you mean asking `will it synch?`? Whether the storage will resync during next time the program run? No it will not. All that `sqlite_orm` does is provides a comfortable API for using SQLite3. If you want to know how it works in a multithreaded app then you need to know how SQLite3 works in a multithreaded app. If you change the threading compilation option of SQLite3 then `sqlite_orm::threadsafe()` will return a different value. 
Is it clear or I did not understand you quite right?

**Comment by midjji** [comment]
sqlite_orm is great btw :) I've been looking for something like this for ages. 

If im not mistaken, sqlite3 defaults to multithreading enabled in serialized mode, meaning it can be changed in software to async multithreaded access, does sqlite_orm do so?

Assuming a storage.insert(...) is in process. Will it finish and write the result to disk if the program crashes or terminates?

Assuming a storage.insert() has finished and then the program crashes, will the insert always have been written to disk or is it buffered internally first?

**Comment by midjji** [comment]
Another question, gcc7.4 and clang 6.0 give internal compiler error on storage.sych_storage() is that something you recognize, like too big tables or something?

**Comment by midjji** [comment]
nvm I removed a bunch of autos and it started working, probably just template recursion depth

**Comment by fnc12** [comment]
according to the [doc](https://www.sqlite.org/threadsafe.html) serialized mode is enabled by default and allows multithreaded usage. So it your SQLite3 lib is compiled with this flag then it is also works with `sqlite_orm` cause `sqlite_orm` is just a front-end for SQLite3.


> Assuming a storage.insert(...) is in process. Will it finish and write the result to disk if the program crashes or terminates?

It will work the same way it works without `sqlite_orm` but with pure C `libsqlite3`.

`storage_t` doesn't buffer data from tables cause `sqlite_orm` is just a front end. What is buffered is limits and some pragmas which need to be enabled on every storage open. But it doesn't affect data.

Thanks for using=)

**Comment by fnc12** [comment]
@midjji is the issue actual?

**Comment by midjji** [comment]
The question is answered, thank you
