### ISSUE TITLE
Compilation fails on latest VS2019

### ISSUE THREAD

**Issue by bftjoe** [fnc12/sqlite_orm#433]
VS 2019 Version 16.4.0

Error	C2039	'bind': is not a member of 'sqlite_orm::statement_binder<field_type,void>'	ExampleAIModule	C:\vcpkg\installed\x86-windows\include\sqlite_orm\sqlite_orm.h	9385	

Error	C2039	'__this': is not a member of 'sqlite_orm::statement_binder<field_type,void>'	ExampleAIModule	C:\vcpkg\installed\x86-windows\include\sqlite_orm\sqlite_orm.h	9385	

Looks like this line: https://github.com/fnc12/sqlite_orm/blob/master/include/sqlite_orm/sqlite_orm.h#L8486

**Comment by fnc12** [comment]
Hello. Please paste the code with `storage.update` and `make_storage` calls

**Comment by bftjoe** [comment]
struct UnitInfo {
	int id;
	UnitType type;
	int p;
};

struct commands {
	int id;
	int cmdType;
	int target;
};



auto storage = make_storage("bwapi.sqlite",
	make_table("units",
		make_column("id", &UnitInfo::id, primary_key()),
		make_column("player", &UnitInfo::p),
		make_column("type", &UnitInfo::type)));

auto commands = make_storage("commands.sqlite",
	make_table("commands",
		make_column("id", &commands::id, autoincrement(), primary_key()),
		make_column("target", &commands::target)));

**Comment by fnc12** [comment]
How `UnitType` is mapped to the storage? Did you add custom bindings? Looks like you did not. `sqlite_orm` doesn't know how to store field with type `UnitType` in the database. You have to either change the type of `UnitInfo::type` or add custom types bindings just like it is done [here](https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp)

**Comment by bftjoe** [comment]
Thanks, working now, changed to int.
