### ISSUE TITLE
[Visual Studio 2017] warning because of std::toupper usage

### ISSUE THREAD

**Issue by andrei-datcu** [fnc12/sqlite_orm#442]
```
sqlite_orm\include\sqlite_orm/sqlite_orm.h(159): note: see reference to function template instantiation '_OutIt std::transform<std::_String_iterator<std::_String_val<std::_Simple_types<_Ty>>>,std::_String_iterator<std::_String_val<std::_Simple_types<_Ty>>>,sqlite_orm::to_sqlite_type::<lambda_3e8adb8c15d56ddc802a0f74f8b3518d>::()::<lambda_6a21209d312548d70dd3489595fed6b9>>(const _InIt,const _InIt,_OutIt,_Fn)' being compiled
1>        with
1>        [
1>            _OutIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,
1>            _Ty=char,
1>            _InIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,
1>            _Fn=sqlite_orm::to_sqlite_type::<lambda_3e8adb8c15d56ddc802a0f74f8b3518d>::()::<lambda_6a21209d312548d70dd3489595fed6b9>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\algorithm(1443): warning C4244: '=': conversion from 'int' to 'char', possible loss of data
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\algorithm(1443): warning C4244: 'argument': conversion from 'int' to 'char', possible loss of data
```

**warning C4244: '=': conversion from 'int' to 'char', possible loss of data**
That's because `std::toupper` actually returns an int. Furthermore, according to the standard, `std::to_upper` is UB if the argument is a char:
https://en.cppreference.com/w/cpp/string/byte/toupper

So most likely you should just switch to `static_cast<char>(std::toupper(static_cast<unsigned char>(c))`.

**Comment by fnc12** [comment]
Thanks. I shall fix it soon

**Comment by andrei-datcu** [comment]
Got two more, same setup:
```sqlite_orm.h(11687): warning C4458: declaration of 'impl' hides class member```

```sqlite_orm.h(11687): warning C4456: declaration of 'index' hides previous local declaration```

**Comment by fnc12** [comment]
the fix is on its way https://github.com/fnc12/sqlite_orm/pull/473

**Comment by fnc12** [comment]
fixed. Is the issue actual?

**Comment by fnc12** [comment]
warning is fixed in `dev` branch. Closing the issue. Thank you for reporting. Please feel free to post about every warning you face inside my code - the lib must have zero warnings.
