### ISSUE TITLE
Support sqlcipher / PRAGMA key

### ISSUE THREAD

**Issue by arolson101** [fnc12/sqlite_orm#449]
I request that you add support for sqlcipher by adding a ```pragma key <string>``` that runs after a db  is opened/created but before any tables are created.

Reference: https://www.zetetic.net/sqlcipher/sqlcipher-api/#PRAGMA_key

**Comment by intxparts** [comment]
This functionality should already be available from the enhancement provided in https://github.com/fnc12/sqlite_orm/issues/22.

I believe SqlCipher implements its own sqlite3_key() function that just needs to be called on_open.

```Cpp
void on_open(sqlite3* db)
{
	const char* key = "password";
	sqlite3_key(db, key, strlen(key));
}

void create_empty_db()
{
	const char* filePath = "data.db";
	auto storage = DAL::create_storage(filePath);
	storage.on_open = on_open;
	storage.sync_schema(true);
}
```

**Comment by fnc12** [comment]
@arolson101 is the issue actual?
