### ISSUE TITLE
Dynamically Build Queries

### ISSUE THREAD

**Issue by gluaxspeed** [fnc12/sqlite_orm#459]
Was wondering if it is possible to dynamically build queries? I couldn't find any examples of a such a thing.

For example,
```C++
auto query = storage.prepare(get_all<Item>(
    where()
  ));

  if (attributes) {
// would build (like(...) and like(...))
    for (const auto &attr : attributes.value()) {
	auto stmt = like(&Item::attributes, "%" + attr + "%");
	some_vector.push_back(stmt);	
    }
  }

get<0>(query) = some_vector.start();
get<1>(query) = some_vector.end();
```
Is this possible in anyway?

**Comment by fnc12** [comment]
Dynamic queries are not supported cause templates must know everything at compile time otherwise there is no way to make such a brilliant API. But you can make static queries with dynamic arguments. Example here https://github.com/fnc12/sqlite_orm/issues/272 (also this is duplicate). Also `ORDER BY`  clause has dynamic version: `dynamic_order_by` in case you want to add dynamic amount of columns. Queries with static SQL text are more effective cause you can reuse them as statements without recompilation

**Comment by gluaxspeed** [comment]
Hmmm okay I think I will need to drop down to raw SQL for my purposes since I have an unknown amount of like statements to put in a where statment.

Thanks for the help!

**Comment by fnc12** [comment]
please show me your SQL query and I shall help you

**Comment by gluaxspeed** [comment]
Here's the query I am trying to perform.
```c++
auto like_attr(const std::string &attr) {
	return like(&models::Item::attributes, "%" + attr + "%");
}
using attr_like_type = decltype(like_attr(""));

std::vector<attr_like_type> attr_likes;
  if (attributes) {
    for (const auto &attr : attributes.value()) {
      std::cout << attr << std::endl;
      attr_like_type attr_like = like_attr(attr);
			attr_likes.push_back(attr_like);
    }
  }

return storage.get_all<models::Item>(where(
	attr_likes
));
```

**Comment by fnc12** [comment]
How do you want to chain these likes together? With `AND` or `OR` binary operator? What is the biggest amount of likes within a single query?

**Comment by gluaxspeed** [comment]
In this situation I would like to chain them together with and. As for how many it would be passed from user input but I could always cap that to a max number of like 5 let's say.

**Comment by fnc12** [comment]
you can construct a query in a different way. IMHO the best way is not to chain SQL string together but use a second table with your conditions. The best way of designing queries is keeping SQL queries static and making all dynamic stuff in data. Keeping SQL queries static allows you reusing same statements as prepared statements. Avoiding string concatenating allows you to avoid dynamic syntax errors. So my decision is creating a second table `patterns`:
```sql
CREATE TABLE patterns (pattern TEXT NOT NULL)
```
Next obtain list of patterns in your C++ code:
```c++
    struct Pattern {
        std::string value;
    };
    struct Item {
        std::string attributes;
    };
    auto storage = make_storage("db.sqlite",
                                make_table("patterns",
                                           make_column("pattern", &Pattern::value)),
                                make_table("items",
                                           make_column("attributes", &Item::attributes)));
    storage.sync_schema();
    
    storage.replace(Item{"one"});
    storage.replace(Item{"two"});
    storage.replace(Item{"three"});
    
    std::vector<Pattern> patterns;
    patterns.push_back({"n"});
    patterns.push_back({"w"});
    storage.insert_range(patterns.begin(), patterns.end());
    
    auto items = storage.select(columns(&Item::attributes, &Pattern::value), where(like(&Item::attributes, conc(conc("%", &Pattern::value), "%"))));
    cout << "items size = " << items.size() << endl;
    for(auto &item : items) {
        cout << "item = " << get<0>(item) << endl;
    }
```

**Comment by gluaxspeed** [comment]
Hm I'm trying to imagine how that would work. The attributes field for our use case is a csv list like "red,fruit,edible". 

So I would like users to be able to query them by "red" and "fruit."

In this schema it seems I am storing what the user gives me as a query in the pattern table and the doing a like operator on the string on that? I'm having a bit of a hard time visualizing how that would work for the case we would want.

**Comment by fnc12** [comment]
It will work well. You can make it within a transaction and rollback it every time to keep `patterns` table empty forever. What question exactly you are facing?

**Comment by gluaxspeed** [comment]
I'm just having trouble visualizing how that works in terms of sql. But also trying to run that I get a no such column exists error patterns.patern.

**Comment by fnc12** [comment]
Assume user did input  "red" and "fruit"
```sql
BEGIN TRANSACTION;
INSERT INTO patterns (pattern) VALUES ('red');
INSERT INTO patterns (pattern) VALUES ('fruit');
SELECT *
FROM items
WHERE id IN (
    SELECT id
    FROM items, patterns
    WHERE attributes LIKE '%' || pattern '%'
);
```
So the query is constant and this makes using it easier than dynamic query.
One problem with this: query like 
```sql
SELECT id
FROM items, patterns
WHERE attributes LIKE '%' || pattern '%'
```
is not supported right now cause `FROM` table set is parsed only from columns not from `WHERE` conditions. I can fix it quickly if you need it.

**Comment by gluaxspeed** [comment]
Ahhh I see thanks for explaining that to me!

Yea that would be great if you could add it since we need it for our use case. Especially with a select(columns(asterisk<Item>(),  &Pattern::value), where(...) or a get_all with something similar :).

**Comment by fnc12** [comment]
This is how it must work in C++. But is throws a runtime error right now. The same error you faced earlier: `no such column: patterns.pattern: SQL logic error`. This happens cause `FROM` tables are parsed only from columns not from `WHERE` expression. I shall fix it soon and write about it here.
```c++
struct Pattern {
    std::string value;
};
struct Item {
    int id = 0;
    std::string attributes;
};
auto storage = make_storage("/Users/johnzakharov/Desktop/db.sqlite",
                            make_table("patterns",
                                       make_column("pattern", &Pattern::value)),
                            make_table("items",
                                       make_column("id", &Item::id, primary_key()),
                                       make_column("attributes", &Item::attributes)));
storage.sync_schema();

storage.replace(Item{1, "one"});
storage.replace(Item{2, "two"});
storage.replace(Item{3, "three"});

std::vector<Pattern> patterns;
patterns.push_back({"n"});
patterns.push_back({"w"});

storage.begin_transaction();
storage.insert_range(patterns.begin(), patterns.end());
auto items = storage.get_all<Item>(where(in(&Item::id, select(&Item::id, where(like(&Item::attributes, &Pattern::value))))));
storage.rollback();
```

**Comment by fnc12** [comment]
fix is on its way

**Comment by fnc12** [comment]
@gluaxspeed fix is merged. Please check out `dev` branch. I've also added unit tests for your case [here](https://github.com/fnc12/sqlite_orm/blob/dev/tests/unique_cases/get_all_with_two_tables.cpp)

**Comment by fnc12** [comment]
is the issue still actual?

**Comment by gluaxspeed** [comment]
Hey sorry didn't get to test till today.

It works for one of our cases now! Right now the problem is that the way it works is passing multiple patterns queries all things with "n" or "w". The current way would return item 1 and 2. Which is also a good use case to have :).

However, what if we wanted items with "n" and "w" only?
For example 
```C++
storage.sync_schema();

storage.replace(Item{1, "one"});
storage.replace(Item{2, "two"});
storage.replace(Item{3, "three"});
storage.replace(Item{4, "nw"});

storage.begin_transaction();
std::vector<Pattern> patterns;
patterns.push_back({"n"});
patterns.push_back({"w"});

storage.insert_range(patterns.begin(), patterns.end());
auto items = storage.get_all<Item>(...); // items would only query item 4.
storage.rollback();
```

**Comment by fnc12** [comment]
Do you want to get all items with attributes equal to "nw"? If so:
```sql
SELECT *
FROM items
WHERE attributes = 'nw'
```
and
```c++
auto items = storage.get_all<Item>(where(is_equal(&Item::attributes, "nw")));
```

**Comment by gluaxspeed** [comment]
No, the n and w are not next to each other. 

I’m talking about something like 

```SQL
SELECT *
FROM items
WHERE attributes LIKE “%n%” AND LIKE “%W”
```

Such that items with an attribute like “a,b,n,t,w” and “f,g,w,y,n” would be queried, but items with attributes like “a,b,n” or “w” would not be queried.

**Comment by fnc12** [comment]
Oh, I see. You want to chain query with `AND` not `OR`?

**Comment by gluaxspeed** [comment]
Would there be some way we could specify which we could chain a query with? I think both are useful to have.

**Comment by fnc12** [comment]
this is your query:
```sql
SELECT id
FROM items, patterns 
WHERE attributes LIKE '%' || pattern || '%'
GROUP BY id
HAVING COUNT(pattern) = (
	SELECT COUNT(*)
	FROM patterns
)
```
and C++
```c++
auto items = storage.get_all<Item>(
             where(in(&Item::id, select(&Item::id,
                 where(like(&Item::attributes, conc(conc("%", &Pattern::value), "%"))),
                 group_by(&Item::id),
                 having(is_equal(count(&Pattern::value), 
                                 select(count<Pattern>())))))));
```

**Comment by gluaxspeed** [comment]
Awesome! That works.

Thanks for both these examples and the work to make everything possible!

**Comment by fnc12** [comment]
You're welcome. Please feel free to post any issue you have related to `sqlite_orm`. Is this issue actual?
