### ISSUE TITLE
noway to get error code ? Consider using std::system_error instead of std::runtime_error 

### ISSUE THREAD

**Issue by lethe555** [fnc12/sqlite_orm#46]

**Comment by fnc12** [comment]
good idea. Thanks. I'll read about `std::system_error` today and give you an answer

**Comment by lethe555** [comment]
a good blog about std::error_code:) [https://akrzemi1.wordpress.com/2017/07/12/your-own-error-code/]

**Comment by fnc12** [comment]
Ok I see. One question: what kind of error category do you expect? I cannot understand it quite right

**Comment by lethe555** [comment]
maybe `sqlite_category`, for errors reported by sqlite, like `std::system_category` for errors reported by the operating system, `std::iostream_category` for  iostream errors

**Comment by fnc12** [comment]
You need sqlite error code originally, don't you?

**Comment by lethe555** [comment]
yes, without sqlite error code ,it's hard to handle different errors

**Comment by fnc12** [comment]
@lethe555 please check it out here https://github.com/fnc12/sqlite_orm/pull/109

**Comment by lethe555** [comment]
good job!
except should throw std::system_error instead of std::error_code

**Comment by fnc12** [comment]
@lethe555  https://github.com/fnc12/sqlite_orm/pull/110 fixed

**Comment by fnc12** [comment]
please review and close the issue if everything is ok. Thanks
