### ISSUE TITLE
Avoid references names and/or foreign keys names to be considered as SQLite command in final query

### ISSUE THREAD

**Issue by indoubtchoose12** [fnc12/sqlite_orm#462]
When a column name is a  namesake of SQLite command (for example 'Index') it is impossible to make storage with foreign keys and references because the name is understand as valid SQLite command.

It can be easily fixed by adding quotes arround columnNames and referencesNames in method serialize_column_schema for foreign keys and references query building.

**Comment by fnc12** [comment]
is the issue actual?
