### ISSUE TITLE
Custom Container binding won't compile and missing prepare function.

### ISSUE THREAD

**Issue by k03rdt6** [fnc12/sqlite_orm#465]
For Some reason std::deque won't work as custom container bindings when using get_all.
I am using master branch  zip downloaded from github repo,
when I tried downloading from vcpkg custom bindings work but prepare statment wont.
may be I am downloading wrong repo with wrong branch or i am not installing lib properly.

Just pretext getStorageHandler is like make_storage
**### When using githubrepo master branch:**
These are the following erros from visual studio.
### Code:
`auto data = Databasestorage::GetHandler().getStorageHandler().get_all<UserProfile,std::deque<UserProfile>>();`
### Error:
'return': cannot convert from 'std::vector<O,std::allocator<_Ty>>' to std::deque<UserProfile,std::allocator<_Ty>>	TemplateStyle	

**### When using vcpkg 	sqlite-orm (Package Name)**
### Code:
`auto stmt = Databasestorage::GetHandler().getStorageHandler().prepare(select(&UserProfile::id));`
### Error:
'prepare': is not a member of 'sqlite_orm::internal::storage_t<sqlite_orm::internal::table_t<UserProfile,sqlite_orm::internal::column_t<UserProfile,int,const int &(__thiscall UserProfile::* )(void) const,void (__thiscall UserProfile::* )(int),sqlite_orm::constraints::autoincrement_t,sqlite_orm::constraints::primary_key_t<>,sqlite_orm::constraints::unique_t>,sqlite_orm::internal::column_t<UserProfile,std::string,const std::string &(__thiscall UserProfile::* )(void) const,void (__thiscall UserProfile::* )(std::string)>,sqlite_orm::internal::column_t<UserProfile,std::string,const std::string &(__thiscall UserProfile::* )(void) const,void (__thiscall UserProfile::* )(std::string)>,sqlite_orm::internal::column_t<UserProfile,std::string,const std::string &(__thiscall UserProfile::* )(void) const,void (__thiscall UserProfile::* )(std::string)>,sqlite_orm::internal::column_t<UserProfile,int,const int &(__thiscall UserProfile::* )(void) const,void (__thiscall UserProfile::* )(int)>>>'	TemplateStyle

**Comment by fnc12** [comment]
Hi. Looks like you use different versions of the lib. You can compare SHA hash in releases section here on github. Also I shall check both cases in `dev` branch. Looks like that at least one of them must be reproducible there. Thanks

**Comment by fnc12** [comment]
Yeah, looks like that i broke custom containers support in `get_all` during prepared statements feature development. I shall fix it soon and add unit tests for it. Thank you for posting this issue

**Comment by fnc12** [comment]
The fix is on its way https://github.com/fnc12/sqlite_orm/pull/472

**Comment by k03rdt6** [comment]
Thanks mate  for the follow through 
it was very essential that we could use custom containers since majority of Code we use is deque dependent.I ran the fix with test code. I will check with my production code tomorrow will close the 
issue than.

**Comment by k03rdt6** [comment]
Fix works as expected.
In my production code I had clang tidy tools complianing about unused variable context,ts,ti. it was merely a warning I fixed it on my end . I am not sure whether it will be relatively important on your end so just a heads up.
line in question is  6560 ,9029,9253,8994,9204

**Comment by fnc12** [comment]
@k03rdt6 thank you, I shall fix these warnings very soon
