### ISSUE TITLE
Cannot find the package installed by vcpkg

### ISSUE THREAD

**Issue by algobot76** [fnc12/sqlite_orm#466]
See https://github.com/microsoft/vcpkg/issues/10141

**Comment by fnc12** [comment]
Hi. Probably you need to write `./vcpkg install sqlite_orm` instead.

**Comment by algobot76** [comment]
I run `./vcpkg install sqlite_orm`  on my laptop but I got this error:

```
Error: <unknown>:1:7: invalid character in package name (must be lowercase, digits, '-')
   on expression: "sqlite_orm"
                         ^
Example:
  vcpkg install zlib zlib:x64-windows curl boost
```

**Comment by fnc12** [comment]
Is your issue related to https://github.com/fnc12/sqlite_orm/issues/443 and duplicates it or not?

**Comment by algobot76** [comment]
I've read both https://github.com/fnc12/sqlite_orm/issues/443 and https://github.com/microsoft/vcpkg/issues/9482. It seams like vcpkg team won't bother to rename sqlite-orm as sqlite_orm. My issue isn't about the naming of the package though. It's about not being able to find the package installed by vcpkg.

**Comment by k03rdt6** [comment]
vcpkg integrate install            Make installed packages available user-wide. Requires admin 
                                               privileges on first use
vcpkg integrate project          generate individual nuget package for vs project you have to install from nuget pkg manager afterwards.

try vcpkg integrate install
vcpkg install sqlite-orm

on the further note installation directiory for user-wide installation will be
            path-to-installed/vcpkg/install/ platfrom-type[x86/x64]/include/sqlite-orm
this will only show when installation is  user-wide.

**Comment by fnc12** [comment]
is it ok if we rename `sqlite_orm` to `sqlite-orm` in 'README' file in this lib?

**Comment by fnc12** [comment]
Fixed in readme. Everyone please excuse me for long waiting.
