### ISSUE TITLE
Using Case API In Possibly where Statement

### ISSUE THREAD

**Issue by k03rdt6** [fnc12/sqlite_orm#467]
e'llo mate great Lib btw 
I have come across this little issue when dealing with **Case API**
 Now I could be completly wrong since I am not fully familier with LIB specific syntax.

So I want to achive this 

**SQL Statment in sqlite_orm**
`select * from UserProfile where firstName = case WHEN (length(?) > 0 ) then (?) else firstName end;`

I have tried this in **sqlitestudio** I can get desired result so, I tried to implement this with **sqlite_orm** lib's Case api with something like this [ I could be completly wrong about this with my unfamiliarity with synatx in this lib specific regard so ]

**In C++ Code**

```
auto stmt = Databasestorage::GetHandler()
		.getStorageHandler()
		.prepare(get_all<UserProfile>(
				where(c(&UserProfile::firstName)=case_<std::string>(name)
					.when((length(name) > 0),then(name))
					.else_(&UserProfile::firstName)
					.end())
			
			));
```

it yields the following error:

**'std::tuple<std::pair<sqlite_orm::conditions::greater_than_t<sqlite_orm::internal::core_function_t<int,sqlite_orm::internal::length_string,std::string>,int>,std::string>>::tuple': no appropriate default constructor available**

I understand this is a bit of dynamic behaviour but I am just testing Lib so I can port my qt sql code to sqlite_orm.

**Comment by fnc12** [comment]
Hi. You need to replace assignment operator `=` with comparison operator `==` inside `where` function cause operators are written in C++ in `sqlite_orm`:
```c++
auto stmt = Databasestorage::GetHandler()
		.getStorageHandler()
		.prepare(get_all<UserProfile>(
				where(c(&UserProfile::firstName)==case_<std::string>(name)
					.when((length(name) > 0),then(name))
					.else_(&UserProfile::firstName)
					.end())
			
			));
```

**Comment by k03rdt6** [comment]
thanks for quick reply but 
I made a mistake when writing the questions. actually I did used == opeartor in actual code 
I must have pasted wrong code cause i was experimenting withother variants anyway it is still same error with '==' and 'is_equal' code.

```
auto stmt = Databasestorage::GetHandler()
		.getStorageHandler()
		.prepare(get_all<UserProfile>(
				where(is_equal(&UserProfile::firstName, case_<std::string>(name)
					.when((length(name) > 0), then(name))
					.else_(&UserProfile::firstName)
					.end()
			))));
```

**std::tuple<std::pair<sqlite_orm::conditions::greater_than_t<sqlite_orm::internal::core_function_t<int,sqlite_orm::internal::length_string,std::string>,int>,std::string>>::tuple': no appropriate default constructor available**
I know name.length() is c++ specific but it compiles the code but it will not properly evaluate on
sql for some reason. it is always false.
```
auto stmt = Databasestorage::GetHandler()
		.getStorageHandler()
		.prepare(get_all<UserProfile>(
			where(c(&UserProfile::firstName) == case_<std::string>(name)
				.when((name.length() > 0), then(name))
				.else_(&UserProfile::firstName)
				.end())

			));


```

**Comment by fnc12** [comment]
You're right, it doesn't compile for me too. I shall fix it soon

**Comment by fnc12** [comment]
The fix is [here](https://github.com/fnc12/sqlite_orm/pull/468). It will be merged after several hours into `dev` branch. This fix also will be available in `master` after next release

**Comment by k03rdt6** [comment]
hi thanks for quick resolution 
it works great but when i tried to use with std::ref it gave same error. 
I could be wrong in the use.

**Code:**
```
auto stmt = Databasestorage::GetHandler()
		.getStorageHandler()
		.prepare(get_all<UserProfile>(
			where(c(&UserProfile::firstName) == case_<std::string>()
				.when((length(std::ref(name)) > 0), then(std::ref(name)))
				.else_(&UserProfile::firstName)
				.end())

			));
	name = "";
	
```
**Error:**
'std::tuple<std::pair<sqlite_orm::conditions::greater_than_t<sqlite_orm::internal::core_function_t<int,sqlite_orm::internal::length_string,std::reference_wrapper<std::string>>,int>,std::reference_wrapper<std::string>>>::tuple': no appropriate default constructor available.

cheers.

**Comment by fnc12** [comment]
Yeah you are right. The reason why this happens cause I need to have a ctor for `std::tuple<N>` which accepts two arguments: `std::tuple<N - 1>` and one extra element. I need to think about general fix not only for core function as I performed in PR linked to this issue. I shall respond soon. Thanks

**Comment by k03rdt6** [comment]
thank you kindly for quick reply
 but I found another weird thing
when tried to use it in (where) clause  case_ as a first argument it gave same error.  I Thought with out using std::ref  it would work  but its still giving me same error.so, it is safe to assume its
throwing error for same reason you mentioned in previous comment.

**Comment by fnc12** [comment]
Please give me a line of code to reproduce it. Thanks. BTW I've just merged a PR with fix

**Comment by k03rdt6** [comment]
**SQL Code:**
`select * from user_profile where case when length(@param)>0 then ( firstName like @param ) else (true) end;`
Tested sql code in  sql studio achived desired result.

**C++ Code:**
```
auto stmt = Databasestorage::GetHandler()
		.getStorageHandler()
		.prepare(get_all<UserProfile>(where(
			case_<std::string>()
			.when(length(name)>0,then(like(&UserProfile::firstName,name)))
			.else_(true)
			.end())));
```
**Error:**
'std::tuple<std::pair<sqlite_orm::conditions::greater_than_t<sqlite_orm::internal::core_function_t<int,sqlite_orm::internal::length_string,std::string>,int>,sqlite_orm::conditions::like_t<std::string UserProfile::* ,std::string,void>>>::tuple': no appropriate default constructor available

**Comment by fnc12** [comment]
Ok I see. The reason it fails in `like` operator. I can also add a default ctor into `like` class but it will help only for this case not for all. To fix a generic case I need to create a way to make a tuple from a subtuple like this:
```c++
T fifthArgument;
std::tuple<4 arguments> t1;
std::tuple<5 argument> t2{std::move(t1), std::move(fifthArgument)};
```
Looks like I need to post it to stackoverflow cause this task doesn't look trivial.

**Comment by fnc12** [comment]
Good news! It turned out not so difficult as it seemed at first. The fix is here https://github.com/fnc12/sqlite_orm/pull/471

**Comment by fnc12** [comment]
Fixed. Please check out `dev` branch

**Comment by fnc12** [comment]
Is the issue actual?

**Comment by k03rdt6** [comment]
much obliged there.
It works for the test code I will run it in my Production code and will confirm this afternoon.

**Comment by k03rdt6** [comment]
Thanks for quick resolution of matter kudos mate
Done it works on the module I am working. I am closing the issue.
