### ISSUE TITLE
how to inherit the struct?

### ISSUE THREAD

**Issue by dotkt** [fnc12/sqlite_orm#469]
//your sample code:
    User secondUser{ -1, "Alice", "Inwonder", 831168000, {} , 2 };
    insertedId = storage.insert(secondUser);
    secondUser.id = insertedId;
    cout << secondUser.id << endl;

    // if i want to inherit from User and add some function to it
    **//how to do this in the right way?**
    class super_user_class :public User
    {
    public:
        int super_level = 10;
    };
    super_user_class* someone = new super_user_class();
    someone->super_level = 100;
    auto ret=storage.insert((User)*someone);
    cout << ret << endl;

**Comment by fnc12** [comment]
Yes, you do it right way. Or you can specify type explicitly in template brackets:
```c++
storage->insert<User>(*someone);
```
