### ISSUE TITLE
 sqlite_orm compiled with errors !

### ISSUE THREAD

**Issue by 2020karaulov2020** [fnc12/sqlite_orm#485]
```
bool SearchCrc32(unsigned int crc32, std::string & mapname, std::string & mapfilename)
{
	auto pMapStruct = storage.get_pointer<MapStruct>(where(c(&MapStruct::crc32) == crc32));
	if (pMapStruct != nullptr)
	{
		mapname = pMapStruct->Name;
		mapfilename = pMapStruct->Path;
		return true;
	}
	return false;
}
```

Error : 
**sqlite_orm.h(11484,1): error C2039: '__this': is not a member of 'sqlite_orm::statement_binder<field_type,void>'**
 and 
**error C2039: 'bind': is not a member of 'sqlite_orm::statement_binder<field_type,void>'**

**Comment by fnc12** [comment]
what is `MapStruct::crc32` type?

**Comment by 2020karaulov2020** [comment]
**unsigned int**

**Comment by 2020karaulov2020** [comment]
```

struct MapStruct
{
	int id;
	bool IsMemHack;
	bool ContainPatches;
	int Downloads;
	int Rating;
	unsigned int crc32;
	std::string Path;
	std::string Name;
	std::string Category;
	std::string Author;
	std::string Description;
	std::string Players;
	std::string UpdateCode;
};

```

**Comment by fnc12** [comment]
This error is correct. You are using `get_pointer` incorrectly. `get_pointer` expects primary key column value as an argument not `where` clause. If you need to query filtered entities by some `where` condition you need to use `storage.get_all` function.
I shall add `static_assert` for these cases to make compilation error more helpful.

**Comment by 2020karaulov2020** [comment]
> This error is correct. You are using `get_pointer` incorrectly. `get_pointer` expects primary key column value as an argument not `where` clause. If you need to query filtered entities by some `where` condition you need to use `storage.get_all` function.
> I shall add `static_assert` for these cases to make compilation error more helpful.

but i need only first struct, no all

**Comment by fnc12** [comment]
use `limit`. Anyway in raw SQL you would write:
```sql
SELECT *
FROM mapStruct
WHERE crc32 = ?
```
This query can return more than one row so you need to handle it by yourself. `get_pointer` and `get` return one row cause there can be only one row with specified primary key but `crc32` is not a primary key so more than one row can have the same `crc32`  value. So in raw SQL you must write:
```sql
SELECT *
FROM mapStruct
WHERE crc32 = ?
LIMIT 1
```
Same query in `sqlite_orm`:
```c++
auto rows = storage.get_all<MapStruct>(where(c(&MapStruct::crc32) == crc32), limit(1));
if(!rows.empty()){
    auto &row = rows.front();  // decltype(row) is MapStruct &
    // do something with row
}
```
Also if your table has more than one rows with same `crc32` it is a good practice to specify `ORDER BY` clause cause SQLite's `SELECT` does not guarantee the order of its result. But if `crc32` is unique don't mind.
