### ISSUE TITLE
Idea: change testing framework to [Boost].UT

### ISSUE THREAD

**Issue by data-man** [fnc12/sqlite_orm#489]
[Boost UT](https://github.com/boost-experimental/ut)
- modern
- fast compiling
- no macros
- flexible
- and much more :)

**Comment by fnc12** [comment]
thanks for the advice. Let me read about this framework. I've never heard about it

**Comment by fnc12** [comment]
hey the idea is good but right now there is no much requirement in improving unit test pramework used in this lib cause catch2 does what it must. The only thing is macros cause I don't like them but it is only about beauty and there are other issue that are more important that this. Anyway thanks
