### ISSUE TITLE
Foreign keys documentation/example

### ISSUE THREAD

**Issue by jeresch** [fnc12/sqlite_orm#49]
It looks like in #10 some support for foreign keys has been added, and the readme seems to suggest so as well in the features.  Is there any chance that someone could write a short example or two for the readme or wiki?

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/blob/master/examples/foreign_key.cpp

**Comment by jeresch** [comment]
Thanks, sorry I missed that!  Great work on the library
