### ISSUE TITLE
README vcpkg command is wrong

### ISSUE THREAD

**Issue by Git-Curve** [fnc12/sqlite_orm#490]
When trying to install this library with the provided vcpkg command I noticed that the given name is wrong, its not "sqlite_orm" its "sqlite-orm"

**Comment by fnc12** [comment]
Hi. Looks like a [duplicate](https://github.com/fnc12/sqlite_orm/issues/466). I shall fix the readme soon. Thanks

**Comment by Git-Curve** [comment]
Oh I didnt check for duplicates, I'm sorry!

**Comment by fnc12** [comment]
@Git-Curve  I shall fix the readme file soon
