### ISSUE TITLE
Question: UUID as primary key

### ISSUE THREAD

**Issue by jakemumu** [fnc12/sqlite_orm#492]
Hello, 

I'm coming from primary experience with Postgresql & Rails, but trying this in a cpp app since yesterday. 

I'm curious if there is support for primary key as UUID type? 

If not is there any suggestions on how I may help add this? the templates and depth of c++ usage in the library is a bit beyond me still but I'm happy to try and help! 

Best,

J

**Comment by fnc12** [comment]
Hello. What is UUID? Is this is just a unique string than you can make your primary key as a string and generate UUID by yourself with some UUID generator. E.g. https://gist.github.com/fernandomv3/46a6d7656f50ee8d39dc or https://www.boost.org/doc/libs/1_65_0/libs/uuid/uuid.html.

**Comment by jakemumu** [comment]
UUID is an alternative for incremental indexes on databases which synchronize across many different instances. It's handy in the case of databases across multiple clients sharing IDs for the same objects: 

https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439

Perhaps I haven't looked into the documentation enough, it's hard for me to get an overview of the library as a single header. Perhaps it's as simple as passing the the type of int64 into the first column you mark at primary key? 

I guess the issue is then yeah, you'll need to create the UUID for new records. In postgresql you can declare the type on the primary key UUID and it will generate new UUIDs when the new records are added, similar to how you have the auto incremented primary key column currently. 

I'm using this library currently to create UUIDs and store them in a separate std::string column, but it looks like it'd be possible to use a int64 which may be faster for queries & lookups: 

https://docs.juce.com/master/classUuid.html

Keeping the primary key an int and storing the UUID of the record in a secondary column, but the primary key is over little importance to be so was wondering if this was something that was available out of the box. 

After reading this thread: 

https://stackoverflow.com/questions/17277735/using-uuids-in-sqlite

It seems like this might just be a limitation of sqlite not having any sort of UUID mechanism built in. 

In any case thanks for the quick response!

**Comment by fnc12** [comment]
I understand your wish and it is very useful. You understand everything correctly: the issue is related to SQLite cause SQLite does not have any UUID data type. `sqlite_orm` is just a frontend for SQLite and if there would be UUID data type in SQLite it also would be accessible in `sqlite_orm`. You can use any type as a primary key using `sqlite_orm` (int, string, blob, double) just generate UUID on your own and everything will be good. 
Thank you for using the lib.

**Comment by fnc12** [comment]
is the issue actual?

**Comment by jakemumu** [comment]
I think there's no resolution as it's an SQLite issue and not an issue with the ORM, apologies -- closing
