### ISSUE TITLE
Fix travis latest clang unit tests run configuration

### ISSUE THREAD

**Issue by fnc12** [fnc12/sqlite_orm#493]
This is it https://travis-ci.org/github/fnc12/sqlite_orm/jobs/672144876 . IDK what happened. Looks like some kind of problem with homebrew or whatever. I beg someone who knows how to fix it to fix it. Thanks in advance

**Comment by Leon0402** [comment]
Is this still happening?

**Comment by fnc12** [comment]
Yes. I commented out confirmations in Travis config file. Uncomment it and create a PR to see failed builds. It would be very good if you fix it. Thanks

**Comment by fnc12** [comment]
all comments here https://github.com/fnc12/sqlite_orm/blob/dev/.travis.yml

**Comment by Leon0402** [comment]
Okay thanks, I will have a look!

**Comment by fnc12** [comment]
@Leon0402 I've created a PR with it https://github.com/fnc12/sqlite_orm/pull/576

**Comment by fnc12** [comment]
@Leon0402 5 failed builds here https://travis-ci.org/github/fnc12/sqlite_orm/builds/714931351

**Comment by Leon0402** [comment]
Hi, 

the current problem seems to be introduced with my recent commit. I didn't see that the before_script section is executed for every environment including mac os. Obviously the code I added to get a recent cmake version, is Ubuntu specific.
Presumably, the easiest fix would be to move that code in the else block instead (so it's only executed if you are actually on ubuntu).
In general though it seems kinda strange to me to run basically the same code on ubuntu as well as on mac os (and handle everything with if else statements) Maybe this could be splitted up? I'm not a travis expert though, I would have to read about how this all works.

I suppose though that this isn't the real issue, but a new one. Once this is fixed, I need to take a look at the old one as well.

**Comment by fnc12** [comment]
@Leon0402 travis is fixed. You were right - enabling beta fixes the problem. Example: https://github.com/fnc12/sqlite_orm/pull/580

**Comment by Leon0402** [comment]
Great! That makes it a little bit easier

**Comment by fnc12** [comment]
@Leon0402 do you have any progress on this issue? If you stopped working on it I can close it.

**Comment by Leon0402** [comment]
I had no time lately for it and probably won't have some in the near future.

**Comment by fnc12** [comment]
it was fixed before. Thanks
