### ISSUE TITLE
update statement

### ISSUE THREAD

**Issue by SaeedAqamiri** [fnc12/sqlite_orm#498]
Hello

Thanks for your attention to previous issue.

Now I want to dynamically change a statement.
For example, I want to do something like this:

auto statement = storage.prepare(get_all<Student>(where(in(&Classifier::id, {1, 2, 3}))));
//Statement is: select * from storage where id IN {1, 2, 3}

if (age_range in queries)  //queries is a json like object that store user's query
    statement.add(where(in(&Classifier::age, age_range))));
    //Statement is: select * from storage where id IN {1, 2, 3} and age IN age_range
else
   don't something 
   //Statement is: select * from storage where id IN {1, 2, 3}

**Comment by fnc12** [comment]
Hello. Use bool flags like they are used in this issue https://github.com/fnc12/sqlite_orm/issues/459

**Comment by SaeedAqamiri** [comment]
Thank you very much.

It's solved via this feature.
