### ISSUE TITLE
why compile slowly ?

### ISSUE THREAD

**Issue by ahahahahalo** [fnc12/sqlite_orm#499]
hello,i used it in my project,it can run successfully,but it compile slowly,why?
my english is poor,looking forward to your reply,thanks

**Comment by ahahahahalo** [comment]
my code is here,tables have fifty columns,three tables or much.
![image](https://user-images.githubusercontent.com/46733082/80165006-05e7de00-860d-11ea-8d20-e1584433aba7.png)

**Comment by fnc12** [comment]
cause of big amount of templates. You can reduce compilation time using [technique from faq](https://github.com/fnc12/sqlite_orm/wiki/FAQ#slow--size-effective)

**Comment by ahahahahalo** [comment]
OK，now i have another question,
 for (auto &item : storage.iterate<NodeB>())
    {  for (auto &item2 : storage.iterate<Sector>(where(c(&Sector::nodebId) == item.userNodebId)))
        {   for (auto &item3 : storage.iterate<Cell>(where(c(&Cell::sectorId) == item2.id)))
            {}}}
it  has  three  for，about 30K record，it run slowly ，how to optimize

**Comment by fnc12** [comment]
This question is not about `sqlite_orm`. This question is about optimizing sqlite3 calls. `storage::iterate` is optimized already. The reason your code runs slowly is big amount of iterations/records. Probably your code can be simplified and transformed into on query if you have simple logic inside your `for` body. Please show the whole loop.

**Comment by ahahahahalo** [comment]
this is whole loop,maybe i need simply my Business Logic，thank for your reply. Emmmm

for (auto &item : storage.iterate<NodeB>())
    {
        // cout << storage.dump(item) << endl;
        // cout << item.id << endl;
        // cout << item.nodebName << endl;
        BaseStationInfo bs_temp;
        bs_temp.BSID = item.id;
        bs_temp.Type = item.nodebType;
        bs_temp.LocationX = item.coordinateX;
        bs_temp.LocationY = item.coordinateY;
        cout<<"bs "<<bsxxx<<endl;
        int index = 0;
        for (auto &item2 : storage.iterate<Sector>(where(c(&Sector::nodebId) == item.userNodebId)))
        {
            bs_temp.Sector[index].BSID = item.id;
            bs_temp.Sector[index].SectorID = item2.id;
            bs_temp.Sector[index].IsActive = item2.isActive == "1";
            bs_temp.Sector[index].ACLR1 = item2.aclr1;
            bs_temp.Sector[index].ACLR2 = item2.aclr2;
            bs_temp.Sector[index].ACS1 = item2.acs1;
            bs_temp.Sector[index].ACS2 = item2.acs2;
            bs_temp.Sector[index].ClutterID = item.id;
            bs_temp.Sector[index].wirelessID = item.id;
            bs_temp.Sector[index].RelayAntHeight = item.id;
            bs_temp.Sector[index].SectorFrequencyPoint = item.id;
            bs_temp.Sector[index].Height = item.id;
            bs_temp.Sector[index].NoiseFigure = item.id;
            int index2 = 0;
            for (auto &item3 : storage.iterate<Cell>(where(c(&Cell::sectorId) == item2.id)))
            {
                bs_temp.Sector[index].Cell[index2].TechnologyType = item.id;
                bs_temp.Sector[index].Cell[index2].CellType = item.id;
                bs_temp.Sector[index].Cell[index2].BroadcastChannelCount = item.id;
                bs_temp.Sector[index].Cell[index2].DownlinkLoad = item.id;
                bs_temp.Sector[index].Cell[index2].Radius = item.id;
                bs_temp.Sector[index].Cell[index2].FreStart = item.id;
                bs_temp.Sector[index].Cell[index2].FreEnd = item.id;
                bs_temp.Sector[index].Cell[index2].CarrierPerCell = item.id;
                bs_temp.Sector[index].Cell[index2].Pc = item.id;
                bs_temp.Sector[index].Cell[index2].EPRE = item.id;
                bs_temp.Sector[index].Cell[index2].MaxTxPower = item.id;
                bs_temp.Sector[index].Cell[index2].AntennaHeight = item.id;
                bs_temp.Sector[index].Cell[index2].AntennaDirection = item.id;
                bs_temp.Sector[index].Cell[index2].AntennaMechanicalDownTilt = item.id;
                strcpy(bs_temp.Sector[index].Cell[index2].PropagationModelName, "hello1");
                strcpy(bs_temp.Sector[index].Cell[index2].AntennaName, "hello2");
                bs_temp.Sector[index].Cell[index2].FiberLoss = item2.fiberLoss;
                bs_temp.Sector[index].Cell[index2].CellID = item.id;
                bs_temp.Sector[index].Cell[index2].PSSID = item.id;
                bs_temp.Sector[index].Cell[index2].SSSID = item.id;
                bs_temp.Sector[index].Cell[index2].RBNum = item.id;
                bs_temp.Sector[index].Cell[index2].CarrierNo = item.id;
                bs_temp.Sector[index].Cell[index2].FrequencyBand = item.id;
                index2++;
            }
            bs_temp.Sector[index].CellNumber = index2;
            index++;
        }
        bs_temp.SectorNumber = index;
        vec_bsdata.push_back(bs_temp);
        bsxxx++;
    }

**Comment by fnc12** [comment]
why do you need `vec_bsdata`?

**Comment by ahahahahalo** [comment]
![image](https://user-images.githubusercontent.com/46733082/80198066-25edc080-8652-11ea-90ee-4fbf031b5ffe.png)
i need output file,for another software.

**Comment by fnc12** [comment]
looks like you are trying to extract a lot of entries at once and write them into file. This is a very heavy operation. You can increase speed by changing HDD to SSD but there is no way to fix it algorithmically.

**Comment by ahahahahalo** [comment]
my workmate has helped me to solve this problem，it can run completely  in 10 seconds.
thanks for your relay again,haha

**Comment by fnc12** [comment]
is the issue actual?

**Comment by ahahahahalo** [comment]
ok i close it.
