### ISSUE TITLE
Qt compatibility

### ISSUE THREAD

**Issue by majidkamali1370** [fnc12/sqlite_orm#5]
Hi.
How can someone change the library to work with Qt's Sqlite driver and Qt Data types (QList, QString etc) ?
Is it possible?

**Comment by fnc12** [comment]
Yes, it is possible to update the lib for it. Please provide your data type for me to be clear about what you want. Thanks

**Comment by fnc12** [comment]
@majidkamali1370 Did I understand you quite right? You need:
1) using Qt Sqlite driver with `sqlite_orm`
2) using QList as a result type of `get_all` and `select` storage member functions
2) using QString as a member in your mapped data type class

**Comment by majidkamali1370** [comment]
Hi.
Yes. All you said :-)
1. Using Qt Sqlite driver with `sqlite_orm`
2. Using QList as return type of `get_all` and `select`
3. Using QString (or QDateTime, if possible), and using QSharedPointer in Model classes:
```c++
struct User{
    int id;
    QString firstName;
    QString lastName;
    QDateTime birthDate;
    QSharedPointer<QString> imageUrl;      
    int typeId;
};
```

**Comment by fnc12** [comment]
ok. 
1) I read about Qt Sqlite driver and it turned out that you can use either it or `sqlite_orm` (or any other sqlite binder). Why do you need to use Qt Sqlite driver with `sqlite_orm` and how do you expect it to works? Can you just use either?

2) This is a very interesting idea. It is a topic of update. This is how I see it:

`auto usersVector = storage.get_all<User>(); // decltype(usersVector) = std::vector<User>`

`auto usersQList = storage.get_all<User, QList>(); // decltype(usersQList) = QList<User>`

Right now this code will not work. But I'm gonna to add different STL containers support for this. Main requirement for container - it must be STL compatible (and QList is). Please stay subscribed to know about updates (or accept a pull request with desired feature if you wish so).

3) This is an another topic of update. Custom types gonna be accepted with template specializations. I will close the issue once this update will be released. A short question: how do you want to store `QDateTime` into sqlite database?

**Comment by majidkamali1370** [comment]
@fnc12 
> how do you want to store QDateTime into sqlite database?
Usually as milliseconds since unix epoch (or a text with specific format). But what I actually mean is, automatic convert of that integer to QDateTime.

**Comment by fnc12** [comment]
Hey @majidkamali1370 . I've just pushed an update with new feature: now you can specify return container type explicitly:

```
auto allUsers = storage.get_all<User, std::list<User>>();
```

or in your case 

```
auto allUsers = storage.get_all<User, QList<User>>();
```

Could you please review and test it. If everything is cool I will add same thing to `select` member function. Thanks

**Comment by majidkamali1370** [comment]
Great :-)
I don't khow templates very well. Main implementation of `get_all` is at line 2163. Am I right?
Can't its usage become a little simpler? Because type of container (std::vector, QList, etc) is same as first template parameter.
```c++
auto allUsers = storage.get_all<User, QList>();
```

**Comment by fnc12** [comment]
It would be great if you write some code with this function.

Also it is better to specify full container type explicitly in case if developer wants to return container with different contained type. For example one can use [nlohmann::json](https://github.com/nlohmann/json) library with it like this:

`auto allUsers = storage.get_all<User, json>();` and it will return json array with json representation of users if `to_json` and `from_json` functions implemented in user's namespace

**Comment by majidkamali1370** [comment]
I tested `get_all` with QList, but it gives an error.
in line `2187` : error: 'class QList<RapArtist>' has no member named 'emplace_back'; did you mean 'pop_back'?
I modified code of `in_memory` example:
```c++
int main(/*int argc, char *argv[]*/)
{
//    QCoreApplication a(argc, argv);

    auto storage = make_storage(":memory:",
                                make_table("rap_artists",
                                           make_column("id",
                                                       &RapArtist::id,
                                                       primary_key()),
                                           make_column("name",
                                                       &RapArtist::name)));

    storage.sync_schema();

    storage.insert(RapArtist{ -1, "The Weeknd"});
    storage.transaction([&]{
            storage.insert(RapArtist{ -1, "Drake" });
            return true;
        });

    QList<RapArtist> artists = storage.get_all<RapArtist, QList<RapArtist>>();

    for(const auto& a : artists)
    {
        qDebug() << a.id << a.name.c_str();
    }

    return 0;
//    return a.exec();
}
```

**Comment by fnc12** [comment]
@majidkamali1370 this happens because `QList` doesn't have `emplace_back` function. This function acts like `push_back` but takes type constructor arguments. There is no need to use `emplace_back` in my case actually so I'll change code with `push_back` instead soon.

**Comment by fnc12** [comment]
@majidkamali1370 please pull changes and try it again

**Comment by majidkamali1370** [comment]
Works like a charm :-)
But there are two issues.
1. there are 21 warnings while compiling the program. it may not be important for now.
2. I use QtCreator and autocompletion does not work at all. typing dot after storage does not show me a list. it may not be important either.

**Comment by fnc12** [comment]
@majidkamali1370 
1. Please show me lines with warnings - it is very good to know where other developers meet warnings in my code. I'll fix it

2. For autocompletion you can do a trick that worked for me at Xcode:

```
auto initStorage(){
    auto storage = make_storage(":memory:",
                                    make_table("rap_artists",
                                               make_column("id",
                                                           &RapArtist::id,
                                                           primary_key()),
                                               make_column("name",
                                                           &RapArtist::name)));
}
typedef decltype(initStorage()) Storage;
Storage storage = initStorage();
storage.sync_schema();
```

**Comment by majidkamali1370** [comment]
1. `sqlite_orm.h:715: warning: 'sqlite_orm::table_impl<sqlite_orm::column_t<RapArtist, int, sqlite_orm::primary_key>, sqlite_orm::column_t<RapArtist, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::col' will be initialized after [-Wreorder]
         column_type col;
                     ^~~`
2. `sqlite_orm.h:1367: warning: 'sqlite_orm::storage_impl<sqlite_orm::table_t<sqlite_orm::column_t<RapArtist, int, sqlite_orm::primary_key>, sqlite_orm::column_t<RapArtist, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::table' will be initialized after [-Wreorder]
         table_type table;
                    ^~~~~`
3. `sqlite_orm.h:2468: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(auto storageColumnInfoIndex = 0; storageColumnInfoIndex < storageTableInfo.size(); ++storageColumnInfoIndex) {`
4. Four similar warnings as 3 in lines 1431, 1433, 1440, 1442
5. `sqlite_orm.h:2175: warning: unused parameter 'azColName' [-Wunused-parameter]
                                    [](void *data, int argc, char **argv,char **azColName) -> int {
                                                                                ^~~~~~~~~`
6. `sqlite_orm.h:715: warning: 'sqlite_orm::table_impl<sqlite_orm::column_t<RapArtist, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::col' will be initialized after [-Wreorder]
         column_type col;
                     ^~~`
7. `sqlite_orm.h:2377: warning: unused parameter 'azColName' [-Wunused-parameter]
                                    [](void *data, int argc, char **argv,char **azColName) -> int {
                                                                                ^~~~~~~~~`
8. same as 3 in lines 2431 and 2433
9. `sqlite_orm.h:1253: warning: unused parameter 'db' [-Wunused-parameter]
         void sync_schema(sqlite3 *db, bool preserve) {
                                   ^~`
10. `sqlite_orm.h:2148: warning: unused parameter 'ss' [-Wunused-parameter]
         void process_conditions(std::stringstream &ss, Args ...args) {
                                                    ^~`
11. `sqlite_orm.h:691: warning: unused parameter 'l' [-Wunused-parameter]
         void for_each_column(L l) {}
                                ^`

**Comment by fnc12** [comment]
I see. I fix warnings in a few days. Thanks for response

**Comment by fnc12** [comment]
@majidkamali1370 I've fixed all the warnings you specified here. Please check it out

**Comment by fnc12** [comment]
@majidkamali1370 I've added custom field type binding. Now you are able to map a class with `QString` and `QDateTime` to a storage. Please see `enum_binding.cpp` in examples folder

**Comment by majidkamali1370** [comment]
There is another warning:
`sqlite_orm.h:2386:80: warning: unused parameter 'azColName' [-Wunused-parameter]`

@fnc12 Thanks, I'll check that example :-)

**Comment by fnc12** [comment]
@majidkamali1370 ok I removed this warning and several other unused warnings (with `sqlite3 *db` argument at the `storage_impl` class). Tell me if you meet warnings anywhere else

**Comment by fnc12** [comment]
So now one can use `QList` to retrieve data and bind QTypes. There is nothing to do with Qt's Sqlite driver so I offer to close the issue.

**Comment by fnc12** [comment]
@majidkamali1370 hey what's up? Let's close the issue
