### ISSUE TITLE
Possible to use pointer types throughout?

### ISSUE THREAD

**Issue by acidtonic** [fnc12/sqlite_orm#500]
I have been struggling with bad_alloc and stack problems with this library providing back class instances without using pointers.

I noticed the get_pointer() method but many of the examples and optimized use cases such as .iterate() instead of get_all() seem to not provide pointers.

I was trying to use shared_ptr and just dereference when calling insert but it seems the memory behind my object is trashed after doing that.

I really like the library but I don't see how to easily use pointer types for my mapped data. Prefer shared_ptr everywhere instead of raw class instances.

I "tried" and after trying to move around a few 5MB blob classes I'm running into stack problems already.

Am I missing something? This just seems to strange to use for anything besides small examples. I'm trying to keep selected data saved to a session class for saving things as the user works. It's proving difficult....

**Comment by acidtonic** [comment]
After fighting around more with get_pointer() and unique_ptr I do indeed need shared_ptr, it's just too difficult to wrestle unique_ptr in this use case.

Is this supported? Do I need to hack up the code and flip unique_ptr back to shared_ptr in the library? This is what I need.

Thanks

**Comment by fnc12** [comment]
You can construct `std::shared_ptr` from `std::unique_ptr`:
```c++
std::shared_ptr<User> user = storage.get_pointer<User>(userId);
```
To insert you can just deref your pointer:
```c++
std::shared_ptr<User> user = ...;
storage.insert(*user);
```

**Comment by acidtonic** [comment]
Odd but in for-each loops with get_all_pointer() I tried that and was getting compile errors.... Perhaps something to do with overload not matching in the iterator context maybe?

What about iterate support for large tables when get_all won't fit in ram? I didn't see iterate_pointer or anything similar.

**Comment by fnc12** [comment]
```c++
auto uniquePointerVector = storage.get_all_pointer<User>();
std::vector<std::shared_ptr<User>> sharedPointerVector;
sharedPointerVector.reserve(uniquePointerVector);
for(auto &uniquePointer : uniquePointerVector) {
    sharedPointerVector.push_pack(std::shared_ptr<User>(move(uniquePointer)));
}
uniquePointerVector.clear();
//    now sharedPointerVector contains shared pointers to all users
```

**Comment by acidtonic** [comment]
Right that is basically what I am doing now, I thought maybe there was a cleaner way.

This still doesn't use iterate though and would run out of memory if the table was large....

**Comment by acidtonic** [comment]
I am storing blobs of video frames for an application to edit them realtime and absolutely cannot store the entire table in a vector, with sqlite3 I iterate and only store one row in memory at a time.

This is the only way to not run out of memory when working with a table like that, your example with get_all_pointer doesn't address this as it will return a vector. 

Unless they are lazy loaded one at a time, I don't see how that would work.

**Comment by fnc12** [comment]
```c++
for(auto &user : storage.iterate<User>()){
    auto sharedPointerToUser = std::make_shared<User>(std::move(user));
    // do whatever you want with sharedPointerToUser
}
```

**Comment by acidtonic** [comment]
That works, thanks :)

**Comment by acidtonic** [comment]
Could you toss this example onto the front readme page....

**Comment by fnc12** [comment]
@acidtonic this solution is very easy to recreate and it holds zero value cause most people will not understand why can't we just work with objects as is not `std::shared_ptr` so I think I shall not post it on readme page. If you tell why you need `std::shared_ptr` instead of strict object probably I shall think about it. Thanks
