### ISSUE TITLE
many tables and columns，how to code

### ISSUE THREAD

**Issue by ahahahahalo** [fnc12/sqlite_orm#503]
return make_storage(path, lite_nodeb, lite_sector, lite_cell,
                              lite_antenna, lite_beam,
                              lite_beamhgain, lite_beamhvgain, lite_beamvgain, lite_beamvhgain,
                              lite_terminaltype, lite_wireclutter, lite_wireset);

many tables，it didnt work well，compile failed，
this is error message，
string table overflow at offset 10000014
 can't close CMakeFiles/main.dir/main.cpp.obj: File too big

**Comment by ahahahahalo** [comment]
even i separate these tables into more storages，its still wrong，
just “string table overflow at offset 10001515”、“Fatal error: can't close CMakeFiles/main.dir/main.cpp.obj: File too big”
maybe i use it correctly，so sad

**Comment by fnc12** [comment]
Hi. This is a regular template problem. Too many template instantiations within one object file. You need to perform two steps to solve this issue:
1) get rid of `inline` in function which contains `make_storage` call and move its implementation into different `.cpp` file. Example https://github.com/fnc12/sqlite_orm/wiki/FAQ#slow--size-effective .This is not so comfortable and makes code very long but it is the most effective way to avoid templates overflow in modern C++. This is not a lib failure but this is a C++ compilers' failure (or C++ itself) cause people also meet this issue using boost.
2) split your storage into several dedicated storages and move every storage into dedicated `.cpp` file. It will reduce amount of template functions been compiled within the same object file in the same time.
If you still have question please feel free to post here. Same issue have already been met by another user of this lib and we fixed it together.

**Comment by ahahahahalo** [comment]
i separate my storages into 3 .h  files,but its still overflow,
how many tables are Suitable in  one file？

**Comment by ahahahahalo** [comment]
about 100 tables,if the tables not be compiled inside one file，how to do，
can u show me some examples？
i am a newcomer to c++，a little difficult for me. thanks.

**Comment by fnc12** [comment]
100 tables is a lot. I have an experience with user with 40 tables (every table has about 10-15 columns) facing the same issue. There is no exact amount of tables supported in a single storage. It depends on amount of columns in every table and your compiler. This is just like `how many empty bottles can be carried in a single bag`. It depends on several things and there is no exact value. Try to experiment: reduce the number of tables in your storage in two times then try to compile. The repeat until you find your amount of tables.

**Comment by ahahahahalo** [comment]
i split my storages to 3 .cpp files,and do not included in one cpp,it  run successfully.
![image](https://user-images.githubusercontent.com/46733082/80442054-c1c34900-893e-11ea-87fb-27d03aedebb1.png)

 and another question,when i click compile ,it spend 10 seconds,
but when i click debug,it spend about 2-3minutes,i dont know why,so confusing

**Comment by fnc12** [comment]
Nice to hear that everything compiles finally. What compiler, OS and IDE do you use?

**Comment by ahahahahalo** [comment]
thanks for your help，you are very patient and kind.
i use windows 、 vscode、Mingw-w64 compiler、cmake tools...

**Comment by fnc12** [comment]
You are welcome. IDK why mingw compiles debug binary slower. Debug executable always has overhead cause it has debug symbols but release executable don't. But 10 seconds vs 2-3 minutes is too much. I used to compile C++ with Xcode clang, with GCC on Linux and with VC++ on Windows and timings dod not differ much. I sed mingw about 8 years ago so I cannot tell anything helpful about it :(. Try to google it. Probably switching LTO can help https://gcc.gnu.org/wiki/LinkTimeOptimization
