### ISSUE TITLE
Invalid conversion from a constant pointer to pointer error

### ISSUE THREAD

**Issue by mikiTesf** [fnc12/sqlite_orm#505]
sqlite_orm is a really cool library and I've been using it lately. I really appreciate your work fnc12. But this week I was trying to map one of the classes I wrote using `sqlite_orm` and I get the following build error: `error: invalid conversion from ‘const pts::Program*’ to ‘pts::Program*’`. The `Program` class looks like this:
```c++
class Program
{
private:
    int id;
    std::string date;
    int congregation_id;
    int elder_id;
    bool is_free;
public:
    Program();

    void setId(int);
    void setDate(std::string);
    void setCongregationId(int);
    void setElderId(int);
    void setFree(bool);

    int getId();
    std::string getDate();
    int getCongregationId();
    int getElderId();
    bool getFree();
};
```
I have written data mappings in a dedicated file `database.h` and the build error disappears and the code compiles fine when I remove the following function from the file:
```c++
public: static Program save (Program program) {
        program.setId(storage.insert(program));
        return program;
}
```
Nowhere in the code I am using the function to insert a `const Program` object to the database. The error points to a part of `sqlite_orm.h` that I find extremely baffling:
```c++
else {
    using getter_type = typename column_type::getter_type;
    field_value_holder<getter_type> valueHolder{((o).*(c.getter))()};
    if(SQLITE_OK != statement_binder<field_type>().bind(stmt, index++, valueHolder.value)) {
        throw std::system_error(
            std::error_code(sqlite3_errcode(db), get_sqlite_error_category()),
            sqlite3_errmsg(db));
    }
}
```
I would like to understand what is going on here. Again, sqlite_orm is an amazing library. Keep up the good work!

**Comment by fnc12** [comment]
Hi. Thanks for using `sqlite_orm`. To fix this issue try to change your getters you map to your storage to right `const` functions: `int getId() const;` instead of `int getId();` and so on.

**Comment by mikiTesf** [comment]
Thank you very much. It builds fine now. What exactly is going on here? Why aren't other classes I mapped asking for the same change?

**Comment by fnc12** [comment]
`storage.insert` takes `const Program &` as an argument, then storage asks this argument for all fields to insert into database using getters you provided. Your getters can be called only if your object is not `const`. It is better to make them right `const` - this is the way you guarantee that these getters will not ever alter your object and that is why one can call these getters with `const Program &`. This is how C++ works. More details [here](https://www.geeksforgeeks.org/const-member-functions-c/).
Also you don't have to copy your object here:
```c++
public: static Program save (Program program) {
        program.setId(storage.insert(program));
        return program;
}
```
Better change it to
```c++
public: static void save (Program &program) {
        program.setId(storage.insert(program));
}
```
But this is IMHO

**Comment by mikiTesf** [comment]
Thanks. You may close this "issue" now.

**Comment by fnc12** [comment]
@mikiTesf you are welcome. Please feel free to post any issue you meet here at any time

**Comment by mikiTesf** [comment]
Sure will. And by the way, I just noticed that the `getter` functions in the other classes already had the `const` modifier in them. Anyways, thanks again man.
