### ISSUE TITLE
I meet a problem :"database is locked"

### ISSUE THREAD

**Issue by yuanlida** [fnc12/sqlite_orm#506]
When run in multithread, Meet a write db error, It said "database is locked".
I have define "#define SQLITE_THREADSAFE 1" in sqlite3.

**Comment by yuanlida** [comment]
using namespace sqlite_orm;
namespace a8 {
    inline auto InitDB(const string &dbpath) {
        auto storage = make_storage(dbpath,
                                    make_table("organization_info",
                                               make_column("id", &OrganizationInfo::id, autoincrement(), primary_key()),
                                               make_column("name", &OrganizationInfo::name),
                                               make_column("domain", &OrganizationInfo::domain, unique()),
                                               make_column("homepage", &OrganizationInfo::homepage),
                                               make_column("description", &OrganizationInfo::description),
                                               make_column("profileImag", &OrganizationInfo::profileImag),
                                               make_column("facebook", &OrganizationInfo::facebook),
                                               make_column("linkedin", &OrganizationInfo::linkedin),
                                               make_column("twitter", &OrganizationInfo::twitter),
                                               make_column("updateTime", &OrganizationInfo::updateTime)));
//        storage.sync_schema();
        storage.sync_schema(true);
        return storage;
    }
    class DBhelper {
        using A8Storage = decltype(InitDB(""));
    public:
        DBhelper();

        DBhelper(const string &dbpath);

        void Save(OrganizationInfo &info);
        void Save(vector<OrganizationInfo> &infos);

        vector<OrganizationInfo> QueryOrganizationInfos(const vector<string> &domains, bool fullmode=false);

        ~DBhelper();
    private:
        string dbpath;
        std::shared_ptr<A8Storage> db;
    };
}

**Comment by yuanlida** [comment]
DBhelper::DBhelper(const string &dbpath) {
    if (dbpath == "") {
        this->dbpath = "./a8.db";
    } else {
        this->dbpath = dbpath + "/a8.db";
    }
    this->db = std::make_shared<A8Storage>(InitDB(this->dbpath));
    this->db->open_forever();
}


void DBhelper::Save(OrganizationInfo &info) {
    if (!info.updateTime) {
        info.updateTime = time(0);
    }
    auto app = RXApplication::Instance();
    auto storage{*db};
    storage.begin_transaction();
    try {
        auto items = storage.get_all<OrganizationInfo>(where(c(&OrganizationInfo::domain) == info.domain));
        if (items.size() == 0) {
            storage.insert(info);
            app->Log(spdlog::level::info, "Insert Org:" + info.domain);
        } else if (info.description != "") {
            storage.replace(info);
            app->Log(spdlog::level::info, "Update Org:" + info.domain);
        } else if (items[0].description == "") {
            storage.replace(info);
            app->Log(spdlog::level::info, "Update Org:" + info.domain);
        } else {
            app->Log(spdlog::level::warn, "Ignore Saving Org:" + info.domain);
        }
        storage.commit();
    } catch (std::exception &e) {
        storage.rollback();
        app->Log(spdlog::level::err, "WRITE DB ERROR:" + string(e.what()));
    }
}

**Comment by yuanlida** [comment]
static void t() {
    DBhelper dBhelper("./data/db");
    OrganizationInfo info;
    info.domain = "domain3.com";
    info.updateTime = time(0);
    dBhelper.Save(info);
}

**Comment by yuanlida** [comment]
void TestORM() {

    std::thread t1(t);
    std::thread t2(t);
    std::thread t3(t);
    std::thread t4(t);
    std::thread t5(t);
    std::thread t6(t);

    t1.join();
    t2.join();
    t3.join();
    t4.join();
    t5.join();
    t6.join();
}

**Comment by yuanlida** [comment]
int main() {
    TestORM();
return 0;
}

**Comment by yuanlida** [comment]
I delete the code: this->db->open_forever();
This error happened too.

**Comment by fnc12** [comment]
Hi. This is not `sqlite_orm` issue but `SQLite3` issue. The reason is that you try to write in a single file from different thread simultaneously. More details [here](https://www.sqlite.org/lockingv3.html) section `3.0 Locking` and type `EXCLUSIVE`. Even if you have compiled SQLite3 with `"#define SQLITE_THREADSAFE 1" ` you can meet this error cause SQLite stores data in a file and this file cannot be written in the same time from two or more threads - this is how files work. But it can be read from any number of threads simultaneously. Other people meet the same issue [here](https://beets.io/blog/sqlite-nightmare.html). Try to increase [busy timeout](https://sqlite.org/c3ref/busy_timeout.html) like this:
```c++
storage.busy_timeout(5000);    // once per storage, argument in ms
```
But this also can increase your threads work time. Probably you have to reorganize your multithread application to write from one thread only or to add a mutex for all write operations.

**Comment by yuanlida** [comment]
Thanks, I have resolved this problem and found a new problem.
I will open a new issue.

**Comment by spiritEcosse** [comment]
I don't meet this error if sqlite use in memory

**Comment by spiritEcosse** [comment]
by the way, for the sake of interest, is it possible to use sqlite like redis (run inn memory and save by time or count actions) ?

**Comment by fnc12** [comment]
@spiritEcosse yes. You can create in memory database and sometimes run backup API
```c++
storage.backup_to("filename.sqlite");
```

**Comment by fnc12** [comment]
@spiritEcosse by the way: what project do you develop with `sqlite_orm`?

**Comment by spiritEcosse** [comment]
my project is mobile app

**Comment by spiritEcosse** [comment]
there is project mybible and i write analog for mobile linux and in the future for multi platforms

**Comment by fnc12** [comment]
@spiritEcosse wow that is nice. Do you have a link to provide it inside readme?

**Comment by spiritEcosse** [comment]
sorry , I didn't write readme yet

**Comment by spiritEcosse** [comment]
but you want to see repo ?

**Comment by fnc12** [comment]
Writing `Do you have a link to provide it inside readme?` I meant to mention your project inside readme of this repo

**Comment by fnc12** [comment]
> but you want to see repo ?

I am not sure whether it is required

**Comment by spiritEcosse** [comment]
oh, sorry, yes, this is cool
https://github.com/spiritEcosse/bible
