### ISSUE TITLE
storate.busy_timeout(30000) doesn't work.

### ISSUE THREAD

**Issue by yuanlida** [fnc12/sqlite_orm#507]
static inline auto InitDB(const string &dbpath) {
        auto storage = make_storage(dbpath,
                                    make_table("organization_info",
                                               make_column("id", &OrganizationInfo::id, autoincrement(), primary_key()),
                                               make_column("name", &OrganizationInfo::name),
                                               make_column("domain", &OrganizationInfo::domain, unique()),
                                               make_column("homepage", &OrganizationInfo::homepage),
                                               make_column("description", &OrganizationInfo::description),
                                               make_column("profileImag", &OrganizationInfo::profileImag),
                                               make_column("facebook", &OrganizationInfo::facebook),
                                               make_column("linkedin", &OrganizationInfo::linkedin),
                                               make_column("twitter", &OrganizationInfo::twitter),
                                               make_column("updateTime", &OrganizationInfo::updateTime)));
//        storage.sync_schema();
//        storage.sync_schema(true);
        storage.busy_timeout(30000);
        return storage;
    }

**Comment by fnc12** [comment]
what result do you get and what you expect?
