### ISSUE TITLE
Improve get_all to be able parse FROM block also in WHERE conditions just like SELECT does

### ISSUE THREAD

**Issue by fnc12** [fnc12/sqlite_orm#511]
Appeared after https://github.com/fnc12/sqlite_orm/issues/501 .
If you want to call a select query which returns all columns of one table but has more than 1 table in `FROM` block
```sql
SELECT b.*
FROM tagmap bt, bookmark b, tag t
WHERE bt.tag_id = t.tag_id
AND (t.name IN ('bookmark', 'webservice', 'semweb'))
AND b.id = bt.bookmark_id
GROUP BY b.id
HAVING COUNT( b.id )=3
```
you have to write
```c++
auto rows = storage.select(asterisk<Bookmark>(),
    where(is_equal(&Tagmap::tagId, &Tag::tagId) 
        and in(&Tag::name, {"bookmark", "webservice", "semweb"}) 
        and is_equal(&Bookmark::id, &Tagmap::bookmarkId)),
    group_by(&Bookmark::id),
    having(is_equal(count(&Bookmark::id), 3))
);
```
This query works fine but user also must be able to fetch result not only as `std::vector<std::tuple<...>>` but also as `std::vector<Object>`. When user calls:
```c++
auto rows = storage.get_all<Bookmark>(
    where(is_equal(&Tagmap::tagId, &Tag::tagId) 
        and in(&Tag::name, {"bookmark", "webservice", "semweb"}) 
        and is_equal(&Bookmark::id, &Tagmap::bookmarkId)),
    group_by(&Bookmark::id),
    having(is_equal(count(&Bookmark::id), 3))
);
```
it produces select query with one table on `FROM` block but 3 required. It must produce query with 3 tables instead. It will not affect current `get_all` users (I hope so) but will improve its usage scenarios.

**Comment by fnc12** [comment]
@jakemumu what if I shall add `asterisk_o<Bookmark>()` instead of `asterisk<Bookmark>()` in `select` function which will return objects instead of tuples? I don't want to affect `get_all` cause current behavior is a feature cause if I change it I shall break queries like
```sql
SELECT id, name
FROM users
WHERE id IN (
    SELECT user_id
    FROM posts
    WHERE ....some_coldition....
)
```
It will become 
```sql
SELECT id, name
FROM users, posts   /// bug is here
WHERE id IN (
    SELECT user_id
    FROM posts
    WHERE ....some_coldition....
)
```
and will be illformed

**Comment by jakemumu** [comment]
I think that sounds okay as long as it's documented

it might be clearer to do something like:

object<Bookmark> which would mean you'd like the object or
asterisk<Bookmark> which would mean you'd like the columns as a tuple?

**Comment by fnc12** [comment]
yeah `object` is a good function name. I shall do it within this issue soon and document it as required. Thank you

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/pull/520

**Comment by fnc12** [comment]
@jakemumu done and merged into `dev` branch. Please check it out

**Comment by jakemumu** [comment]
Hey sorry I missed this for ages, coming back to the project will check it out! Awesome!
