### ISSUE TITLE
get for prepared statement doesn't work as it expected

### ISSUE THREAD

**Issue by fnc12** [fnc12/sqlite_orm#512]
Check out this example
```c++
auto selectStatement = db->getDatabase()->prepare(select(asterisk<MKUSampleMeta>(),
                                                         where(like(&MKUSampleMeta::name, "%"+mCurrentSearchString.toStdString()+"%")
                                                               and is_equal(&MKUTagging::tag_uuid, &MKUTagMeta::uuid)
                                                               and in(&MKUTagMeta::name, { tags_string })
                                                               and is_equal(&MKUSampleMeta::uuid, &MKUTagging::taggable_uuid)),
                                                         group_by(&MKUSampleMeta::row_id),
                                                         having(is_equal(count(&MKUSampleMeta::row_id), tag_count))));


std::cout << selectStatement.sql() << std::endl;
std::cout << get<0>(selectStatement) << std::endl;
std::cout << get<1>(selectStatement) << std::endl;
std::cout << get<2>(selectStatement) << std::endl;
```
Comment from @jakemumu:

_There are 3 variables passed into this prepare statement, however the resulting sql statement is failing to get<1>(statement) & get<2>(statement) after creation._

_This is from dev_

**Comment by fnc12** [comment]
@jakemumu I figured out what is the reason of this behavior. When you use `in` function with a vector it serializes in `columnName IN (?, ?, ... ?)`. Amount of question marks is equal to the size of your vector (it is 1 in your case). When you call `get` it firstly finds out what type you want to get and them what field you want to get. `get` has a compile time index but vector has runtime size. So are not able to use `get` for getting vector elements. What do you expect to get calling `get<1>` ? A whole vector reference?

**Comment by jakemumu** [comment]
Hmm yeah that sounds quite complex. 

As a pretty junior person with databases & SQL, I would expect each of the variable elements from the query to be each index in the tuple. 

My thinking of this was that this code was simply compiled down in a string query, but perhaps that's not the case. 

```
get<0> would return : mCurrentSearchString
get<1> would return : tags_string
get<2> would return : tag_count 
```

as those are the 3 variables which were passed into the query construction. 

Then in the future if I wanted to change parameters on the query, I could do: 

`get<0> = "my text search option"`

this might be defined by an enum where the query was created: 

`get<SearchOptions::TextSearchField> = "my text search option"`

Then I could just create the query code ones, and call & populate it where I'd like to use it in the code.

**Comment by fnc12** [comment]
Unfortunately it can't be done like this. Let me describe you why and then I'll try to offer some other options.
`get` function must know its return type at compile time. Consider a situation when you create a query with three arguments to bind:
1) `std::string` - "%" + mCurrentSearchString + "%"
2) `std::string` - tags_string
3) `int` tag_count
When use function `in` which it returns a struct with vector. Vector has size known only at runtime not  compile time. `get<N>` function must know size at compile time cause when you call `get<2>` in your case my code must know size of your vector but it can't cause `std::vector::size` function is not `constexpr`. All I can do it replace `std::vector` with `std::array` cause array's size can be known at compile time. But I cannot replace it cause then I shall break backward compatibility. So vector will stay there only if we are not able to create API which will stay the same but will generate structs with `std::array` instead of `std::vector`. If you're interested in it please review `struct in_t` in `sqlite_orm.h` and `in` functions below this struct. I need to think about it. If you have any ideas please feel free to tell it. Thanks

**Comment by fnc12** [comment]
Or I can deny using `in` with `get` using `static_assert` but it will work as it works now without using `get` and add another in function like this: `c(&MKUTagMeta::name).in(tags_string);` which will make `in_t` with `std::array` then `get` will work as you wish when you use new version of `in` function. What do you think?

**Comment by jakemumu** [comment]
I'm going to come back to the database pieces of my project this week and I'll get back to you! Thanks for the useful information.

**Comment by fnc12** [comment]
the fix is on its way https://github.com/fnc12/sqlite_orm/pull/695

**Comment by fnc12** [comment]
@jakemumu please check out `dev` branch. Now you can use static `in` like this:
```c++
auto selectStatement = db->getDatabase()->prepare(select(asterisk<MKUSampleMeta>(),
                                                         where(like(&MKUSampleMeta::name, "%"+mCurrentSearchString.toStdString()+"%")
                                                               and is_equal(&MKUTagging::tag_uuid, &MKUTagMeta::uuid)
                                                               and c(&MKUTagMeta::name).in(tags_string)
                                                               and is_equal(&MKUSampleMeta::uuid, &MKUTagging::taggable_uuid)),
                                                         group_by(&MKUSampleMeta::row_id),
                                                         having(is_equal(count(&MKUSampleMeta::row_id), tag_count))));
```
please note `c(&MKUTagMeta::name).in(tags_string)` instead of `in(&MKUTagMeta::name, {tags_string})`

**Comment by fnc12** [comment]
closing cause it is fixed. Please feel free to reopen this if something is wront
