### ISSUE TITLE
Add storage.dump(statement); feature

### ISSUE THREAD

**Issue by fnc12** [fnc12/sqlite_orm#516]
Sometimes developers may need to print a statement just like `statement.sql();` does but with real values instead of question marks. To achieve it we need a storage cause it holds all information about tables and columns:
```c++
auto statement = storage.prepare(select(add(1, 1)));
auto statementSql = statement.sql();  // SELECT ? + ?
auto statementRealSql = storage.dump(statement);  // SELECT 1 + 1
```

**Comment by fnc12** [comment]
@jakemumu the feature is almost ready https://github.com/fnc12/sqlite_orm/pull/560

**Comment by fnc12** [comment]
merged. @jakemumu please check it out

**Comment by jakemumu** [comment]
Thank you!
