### ISSUE TITLE
Autoincrement & composite keys

### ISSUE THREAD

**Issue by ninnyg** [fnc12/sqlite_orm#518]
Hello,
I would like to create a table with a composite key while having one field to be auto-incremented.
Is it possible?
I've always used the autoincrement declaration followed by the primary_key() declaration when having one single primary key, but this time the application crashes for a syntax error.

`make_table("trigger_event_sender",
                                   make_column("id", &trigger_event_sender::id, autoincrement()),
                                   make_column("mode_id", &trigger_event_sender::mode_id),
                                   make_column("sender_name", &trigger_event_sender::sender_name),
                                   make_column("event_id", &trigger_event_sender::event_id),
                                   primary_key(&trigger_event_sender::id,&trigger_event_sender::mode_id, &trigger_event_sender::sender_name)`

**Comment by fnc12** [comment]
Hello. How would you write this thing in raw SQLite? Looks like it is not an `sqlite_orm` issue but SQLite issue. https://stackoverflow.com/questions/6154730/sqlite-multi-primary-key-on-a-table-one-of-them-is-auto-increment

**Comment by ninnyg** [comment]
Oh ok sorry, 
I am a beginner on sqlite so I didn't know that!
Thanks anyway

**Comment by fnc12** [comment]
it is ok. Please feel free to post any issue you got. I (or someone else) shall try to help you anyway.

**Comment by ninnyg** [comment]
Actually in the link you sent there's someone suggesting to use IDENTITY:
`create table [dbo].[Person]
{
   ID int IDENTITY (1,1) not null,
   CompositeID1 int not null,
   CompositeID2 int not null,

   constraint [pk_person] primary key clustered (ID asc, CompositeID1 asc, CompositeID2 asc)
}`

Do you think is there any chance to use it with sqlite_orm?

**Comment by fnc12** [comment]
`IDENTITY` is a feature from [Microsoft SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15). Please read it again more precisely:

_Surprisingly, I was able to implement auto-increment for SqLite with composite keys with syntax exactly the same with **SQL Server**:_

**Comment by fnc12** [comment]
Oh looks like you're right - SQLite supports `IDENTITY`. Let me read about it and them I shall answer you

**Comment by fnc12** [comment]
Please try to run SQLite query with `IDENTITY` keyword and try to use it. Looks like it doesn't act like `AUTOINCREMENT` cause when I insert something skipping id I get an error saying that `not null constraint failed`. 
Also keyword `IDENTITY` doesn't exist in [SQLite's keywords list](https://www.sqlite.org/lang_keywords.html).
To answer your question I'd better use 'Mike Sherrill 'Cat Recall's' answer from provided SO page:
```
NIQUE INDEX alone doesn't have the same effect as PRIMARY KEY. A unique index will allow a NULL; a primary key constraint won't. You're better off declaring both those constraints.

CREATE TABLE ticket (
     id INTEGER PRIMARY KEY AUTOINCREMENT,
     seat TEXT NOT NULL, 
     payment INTEGER,
     UNIQUE (id, seat));
You should also think hard about whether you really need to accept NULL payments.
```

**Comment by ninnyg** [comment]
Maybe another solution that will work for me in the same way is to use the id  column with the autoincrement & primary_key declaration as usual. And add a unique contraints on multiple columns with the columns that are left.. which is actually possible in sqlite.
Do you think is it possible with sqlite_orm? 
I just found the unique() constraint that is not taking any parameter in input....

**Comment by fnc12** [comment]
`unique()` is designed for adding it right after member pointer. Actually `unique()` doesn't support two columns. I shall add it, I just didn't know about this feature. Thanks for providing information about it. If you want to make unique pair then use `CREATE UNIQUE INDEX` query which can be achieved in `sqlite_orm` like [this](https://github.com/fnc12/sqlite_orm/blob/master/examples/index.cpp)

**Comment by fnc12** [comment]
I reopen this issue until you find a way to fix your problems.

**Comment by fnc12** [comment]
I created an [issue](https://github.com/fnc12/sqlite_orm/issues/519) for adding several columns support for `unique`. I shall fix it within this week.

**Comment by fnc12** [comment]
@ninnyg hey good news. Now once can use `unique` function with several column. I've just merged it into `dev` branch. Please check it out

**Comment by fnc12** [comment]
@ninnyg is the issue actual?

**Comment by ninnyg** [comment]
Amazing, thank you very much! I will try it asap! I think you can close the issue now!
Thanks again
