### ISSUE TITLE
vs2015 update3 compile error

### ISSUE THREAD

**Issue by fool404** [fnc12/sqlite_orm#525]
```c++
#include "stdafx.h"
#include "sqlite_orm.h"


using namespace  sqlite_orm;
int main()
{
	struct User {
		int id;
		std::string firstName;
		std::string lastName;
		int birthDate;
		std::unique_ptr<std::string> imageUrl;
		int typeId;
	};

	struct UserType {
		int id;
		std::string name;
	};

	auto filename = "db.sqlite";
	auto storage = make_storage(filename,
		make_table("users",
			make_column("id", &User::id, autoincrement(), primary_key()),
			make_column("first_name", &User::firstName),
			make_column("last_name", &User::lastName),
			make_column("birth_date", &User::birthDate),
			make_column("image_url", &User::imageUrl),
			make_column("type_id", &User::typeId)),
		make_table("user_types",
			make_column("id", &UserType::id, autoincrement(), primary_key()),
			make_column("name", &UserType::name, default_value("name_placeholder"))));

	storage.sync_schema();
    return 0;
}
```

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2664	“sqlite_orm::internal::table_base::table_base(sqlite_orm::internal::table_base &&)”: 无法将参数 1 从“const std::basic_string<char,std::char_traits<char>,std::allocator<char>>”转换为“const sqlite_orm::internal::table_base &”	ConsoleApplication2	c:\users\wzx\desktop\consoleapplication2\consoleapplication2\sqlite_orm.h	5736

**Comment by fnc12** [comment]
Hi. I don't understand error text in chinese but I shall try this code on my machine and write back to you.

**Comment by fnc12** [comment]
Please provide error text in english.

**Comment by fnc12** [comment]
I've added your code into unit tests and everything passed on CI (including different visual studio builds) https://github.com/fnc12/sqlite_orm/pull/526. Please provide more info. Also please check whether you enabled C++17. And provide error text in english.

**Comment by fool404** [comment]
> I've added your code into unit tests and everything passed on CI (including different visual studio builds) #526. Please provide more info. Also please check whether you enabled C++17. And provide error text in english.

I I compiled this program in vs2017 without bugs

**Comment by fool404** [comment]
Error C2664 "sqlite_orm::internal::table_base::table_base(sqlite_orm::internal::table_base &&)": Cannot change parameter 1 from "const std::basic_string<char,std::char_traits,std::allocator>" Converted to "const sqlite_orm::internal::table_base &" ConsoleApplication2

**Comment by fnc12** [comment]
Looks like a bug in vs2015. Is the issue actual?

**Comment by fool404** [comment]
It's true, I compiled this program on two different computers

**Comment by rocaalc** [comment]
It is due to there is not implicit constructor in table_base. With this one line is fixed:

table_base(decltype(name) name_):name(std::move(name_)){}

Currently, it exists in last version in MSVC 2015 c++14 support, always is necessary a constructor.
