### ISSUE TITLE
Right way to work with multiple tables

### ISSUE THREAD

**Issue by godrays** [fnc12/sqlite_orm#528]
Hi,

sqlite_orm is a great library and thank for all contributors.

I have a use case and trying to figure out how I can handle this within sqlite_orm.

I want to create multiple tables with different names but all the tables will have the same columns. Literally identical columns but table names. I would like to group data in different tables for many reasons, especially for performance reason.

Here is a code example for the table. For example, more than 1000 tables will have the same columns:

```
 ....   make_storage("sqlite.db",
        make_table("tablename",
                   make_column("id", &UserInfo::id, autoincrement(), primary_key()),
                   make_column("timestamp", &UserInfo::timestamp),
                   make_column("data1", &UserInfo::data1),
                   make_column("data2", &UserInfo::data2),
                   make_column("data3", &UserInfo::data3)));

```

I know all columns and types at the beginning, and they will never change. One option is very obvious: creating a new storage for each different "tablename". But I think this is ugly because I want to keep storage open forever (for performance). If you have 1000 different tables, it's not a good idea to create 1000 storages. With low level sqlite3 lib, it's easy to handle this. For the consistency, I would like to keep using sqlite_orm.

What is the right way to achieve this use case with sqlite_orm? Any other approach to handle this?

If there is no option to handle this easily, I'm just wondering if it would be easier to add a method: 

```
storage->change_tablename(&UserInfo, "new_tablename");
or
storage->change_tablename(<table identifier>, "new_tablename");
```

Thanks

**Comment by fnc12** [comment]
Hi. Thanks for using the lib. I can make a member function `rename_table` in `storage_t` class. I think this will be enough to achieve your goals.

**Comment by godrays** [comment]
Thank you for the quick response. 

I agree. It should be enough.

I would just worry about the case where the table is not exist yet. Would it be possible to create the table as well if it's not exist? This could be an option to the rename_table(..., createTableIfNotExist = true) member function (flag would be default false) or maybe you can add separate method. (If it's not a big deal)

**Comment by fnc12** [comment]
use `storage.sync_schema()` to create tables that do not exist

**Comment by fnc12** [comment]
Almost done https://github.com/fnc12/sqlite_orm/pull/529

**Comment by godrays** [comment]
I looked at your change and It looks you are changing original table name in the database. I thought you would change table name in storage object but not in the database. With your change, I won't be able to create multiple tables in the data base and alternate by using the rename_table method.

**Comment by godrays** [comment]
Example use case:

```
storage = InitStorage(...)   // "tablename"  is associated with struct UserInfo.
storage->get_all<UserInfo>(...)    // All data is coming from table called "tablename" in database.
storage->change_table(UserInfo, "new_tablename") // Old table is still exist in database.
storage->get_all<UserInfo>(...)    // NOW all data is coming from table called "new_tablename" in database.
```
Hope this clarifies the confusion.

**Comment by fnc12** [comment]
Ok I see. I shall add it too:
```c++
storage.rename_table<UserInfo>("new_table_name");
```
this function will not affect database itself but change table name inside schema data inside storage object.

**Comment by fnc12** [comment]
It can be like this:
```c++
auto storage = make_storage("sqlite.db",
        make_table("tablename",
                   make_column("id", &UserInfo::id, autoincrement(), primary_key()),
                   make_column("timestamp", &UserInfo::timestamp),
                   make_column("data1", &UserInfo::data1),
                   make_column("data2", &UserInfo::data2),
                   make_column("data3", &UserInfo::data3)));
storage.sync_schema();  // create all tables specified in `make_storage`

storage.rename_table<UserInfo>("tablename1"); 
storage.sync_schema();  // create `tablename1` table, all other tables are not affected

storage.rename_table<UserInfo>("tablename2"); 
storage.sync_schema();  // create `tablename2` table, all other tables are not affected
```
etc.
`sync_schema` calls will not affect performance - they will only create your new table cause other tables are already created. Also it would be good to add a function like this:
```c++
storage.tablename<UserInfo>();  // returns `std::string` or `const std::string &` and raise a compile time error if `UserInfo` is not mapped to the storage
// or
tablename<UserInfo>(storage);
```

**Comment by godrays** [comment]
Sounds good!

**Comment by fnc12** [comment]
@godrays please check out `dev` branch - I've merged https://github.com/fnc12/sqlite_orm/pull/529 . Not one can use `storage.rename_table<User>("new_name");` and `storage.tablename<User>()` to get current name from storage schema (not database)

**Comment by godrays** [comment]
Thank you. This is a fantastic enhancement.

One last thing: I didn't see a functional test that really tests the feature other than checking existence of tables or table names. 

Do you think it's necessary to add a test that shows the library can read/write right data from/to a table after changing a table name?

**Comment by fnc12** [comment]
@godrays you're welcome.
I really added only the lightest test. It is easier to create an idea for a test of this feature for you not me cause you know the reason why this feature i required better than me. Please feel free to write what scenario is the best to test this feature and I shall add it or you can write it on your own and make a PR. Anyway thank you for your help - library is getting better with you!
