### ISSUE TITLE
Is There any way to Encrypted database？

### ISSUE THREAD

**Issue by MovRIP** [fnc12/sqlite_orm#533]
sqlite orm is really greate. but i am trying to Encrypt database...try to integrated with wxsqlite. but i dont know how to do that....is there any way to use sqlite orm and create an Encrypted database?

**Comment by fnc12** [comment]
storage class has public `on_open` field which is `std::function<void(sqlite3 *)>` and it is called right after every `sqlite3_open` call so you can call inside it any encryption routine.

**Comment by MovRIP** [comment]
Yes, Thank you....I got that...and i wanna share this demo code for example, maybe it will be helpful to other guys:
`using std::cout;
using std::endl;

// std::function<void(sqlite3 *)>
void data_base_key_callback(sqlite3* db_hanlde)
{
	DBGOUT("call sqlite3_rekey_v2");
	sqlite3_key_v2(db_hanlde, "blob.sqlite", "MyKey123", sizeof("MyKey123"));
	// sqlite3_rekey_v2(db_hanlde, "blob.sqlite", "MyKey123", sizeof("MyKey123"));
}

struct User {
	int id;
	std::string name;
	std::vector<char> hash;  //  binary format
};

int main(int, char**) {
	using namespace sqlite_orm;
	auto storage = make_storage("blob.sqlite",
		make_table("users",
			make_column("id", &User::id, primary_key()),
			make_column("name", &User::name),
			make_column("hash", &User::hash)));
	storage.on_open = data_base_key_callback;

	storage.sync_schema();		// this party will call on_open and create the datebase filed:)
	storage.remove_all<User>();

	User alex{
		0,
		"Alex",
		{0x10, 0x20, 0x30, 0x40},
	};
	alex.id = storage.insert(alex);

	cout << "users count = " << storage.count<User>() << endl;

	cout << "alex = " << storage.dump(storage.get<User>(alex.id)) << endl;

	auto hash = storage.get<User>(alex.id).hash;
 	assert(hash.size() == 4);
 	assert(hash[0] == 0x10);
	assert(hash[1] == 0x20);
        assert(hash[2] == 0x30);
 	assert(hash[3] == 0x40);
	system("pause");

	return 0;
}`
I use wxsqlite for encrption...the way we integrate  wxsqlite and sqlite orm together is very easy...we dont need to include all wxsqlite code, just Compile the code in directory:sqlite3secure. and include these files and you can open the datebase file in Binary. Then you will fund it has been encrpted successfully....

**Comment by fnc12** [comment]
@MovRIP is the issue actual?

**Comment by MovRIP** [comment]
yes...thanks, the solution you give me is actually works....on_open callback is the interface that we can encrpt

**Comment by shanekoss** [comment]
> Yes, Thank you....I got that...and i wanna share this demo code for example, maybe it will be helpful to other guys:
> 
> ```c++
> using std::cout;
> using std::endl;
> 
> // std::function<void(sqlite3 *)>
> void data_base_key_callback(sqlite3* db_hanlde)
> {
> 	DBGOUT("call sqlite3_rekey_v2");
> 	sqlite3_key_v2(db_hanlde, "blob.sqlite", "MyKey123", sizeof("MyKey123"));
> 	// sqlite3_rekey_v2(db_hanlde, "blob.sqlite", "MyKey123", sizeof("MyKey123"));
> }
> 
> struct User {
> 	int id;
> 	std::string name;
> 	std::vector<char> hash;  //  binary format
> };
> 
> int main(int, char**) {
> 	using namespace sqlite_orm;
> 	auto storage = make_storage("blob.sqlite",
> 		make_table("users",
> 			make_column("id", &User::id, primary_key()),
> 			make_column("name", &User::name),
> 			make_column("hash", &User::hash)));
> 	storage.on_open = data_base_key_callback;
> 
> 	storage.sync_schema();		// this party will call on_open and create the datebase filed:)
> 	storage.remove_all<User>();
> 
> 	User alex{
> 		0,
> 		"Alex",
> 		{0x10, 0x20, 0x30, 0x40},
> 	};
> 	alex.id = storage.insert(alex);
> 
> 	cout << "users count = " << storage.count<User>() << endl;
> 
> 	cout << "alex = " << storage.dump(storage.get<User>(alex.id)) << endl;
> 
> 	auto hash = storage.get<User>(alex.id).hash;
>  	assert(hash.size() == 4);
>  	assert(hash[0] == 0x10);
> 	assert(hash[1] == 0x20);
>         assert(hash[2] == 0x30);
>  	assert(hash[3] == 0x40);
> 	system("pause");
> 
> 	return 0;
> }
> ```
> 
> I use wxsqlite for encrption...the way we integrate wxsqlite and sqlite orm together is very easy...we dont need to include all wxsqlite code, just Compile the code in directory:sqlite3secure. and include these files and you can open the datebase file in Binary. Then you will fund it has been encrpted successfully....

Thanks for this example.  It seems we can easily use on_open to decrypt a file already stored, but how would we go about encrypting the data we are saving to the file?

**Comment by fnc12** [comment]
@shanekoss create a new db and encrypt it inside `on_open` call

**Comment by fnc12** [comment]
@shanekoss how would you do it without `sqite_orm` but with raw libsqlite3?

**Comment by shanekoss** [comment]
> @shanekoss how would you do it without `sqite_orm` but with raw libsqlite3?

@fnc12  - thanks for the quick reply!

Perhaps I was thinking about it wrong, but my plan was to encrypt and decrypt with blowfish like so:

`        storage.on_open = [this](sqlite3* handle)
        {
            blowfish.encrypt( handle, sizeof(handle), sizeof(handle) + 8 );
        };`

However, when I do that, I get a bad access error here in table_exists:

`                auto rc = sqlite3_exec(
                    db,
                    query.c_str(),
                    [](void *data, int argc, char **argv, char * * /*azColName*/) -> int {
                        auto &res = *(bool *)data;
                        if(argc) {
                            res = !!std::atoi(argv[0]);
                        }
                        return 0;
                    },
                    &result,
                    nullptr);`

which I would expect since it probably doesn't know how to handle the encrypted data.  Do I need to modify those classes to decrypt first or is there a better way?  

Cheers!

**Comment by fnc12** [comment]
@shanekoss please show me docs about using blowfish for sqlite encoding

**Comment by shanekoss** [comment]
> @shanekoss please show me docs about using blowfish for sqlite encoding

based on that answer, clearly I am thinking of this wrong.  I am not very familiar with sqlite- and perhaps naively I was thinking of encrypting and decrypting the file itself - but sounds like that is not the right way to go, so I will think of something else.  Thanks for the replies.

**Comment by fnc12** [comment]
unfortunately I cannot help you with some custom encrypting. All I can do it provide some API for this within `sqlite_orm`
