### ISSUE TITLE
How to cache the return value of make_storage

### ISSUE THREAD

**Issue by HyperionChen** [fnc12/sqlite_orm#536]
I want to save the return value of make_storage in a global variable, and then the SQL operation only needs to use this global variable, so that you don't need to call make_storage every time first. What type should I use to declare this global variable?

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/wiki/FAQ

**Comment by fnc12** [comment]
is the issue actual?

**Comment by HyperionChen** [comment]
> is the issue actual?
It's works. Thanks.
