### ISSUE TITLE
insert_range

### ISSUE THREAD

**Issue by zajzhuaijun** [fnc12/sqlite_orm#537]
std::vector<record_task> list;
storage.insert_range(list.begin(), list.end());
how can I get every record_task primary_key value

**Comment by fnc12** [comment]
```c++
std::vector<record_task> list;
std::vector<int> ids;
ids.reserve(list.size());
storage.transaction([&list, &storage, &ids]{
    for(auto &recordTask : list) {
        auto id = storage.insert(recordTask);
        ids.push_back(id);
    }
    return true;
});
```

**Comment by zajzhuaijun** [comment]
thankes very much

**Comment by azais-corentin** [comment]
Could `insert_range` return a `std::vector<int>` containing the primary keys?

**Comment by fnc12** [comment]
@azais-corentin the better way is to use `RETURNING` SQLite statement which is not implemented yet in `sqlite_orm`
