### ISSUE TITLE
How do I call the remove method

### ISSUE THREAD

**Issue by HyperionChen** [fnc12/sqlite_orm#538]
I saved the **storage** variable in the following way.

```
inline auto createStorage()
{
    return sqlite_orm::make_storage("libdatabase/sample/db/db.sqlite",
                                    sqlite_orm::make_table("users",
                                                           sqlite_orm::make_column("id", &User::id, sqlite_orm::autoincrement(), sqlite_orm::primary_key()),
                                                           sqlite_orm::make_column("first_name", &User::firstName),
                                                           sqlite_orm::make_column("last_name", &User::lastName, sqlite_orm::default_value("default"))));
}

using Storage = decltype(createStorage());
static Storage storage = createStorage();
```

It's ok to call the **remove** method directly.

```
storage.remove<User>(80);
```

But when I encapsulate a method, the compilation fails

```
template <typename Storage>
static void deleteByPrimaryKey(Storage &storage, int primaryKey)
{
    storage.remove<User>(primaryKey);
}

deleteByPrimaryKey<decltype(storage)>(storage, 80);
```

The error message is as follows:

```
error: expected primary-expression before ‘>’ token
[build]    52 |         storage.remove<User>(80);
```

How do I encapsulate the **remove** method?

**Comment by fnc12** [comment]
try
```c++
template <typename Storage>
static void deleteByPrimaryKey(Storage &storage, int primaryKey)
{
    storage.template remove<User>(primaryKey);
}
```

**Comment by HyperionChen** [comment]
> try
> 
> ```c++
> template <typename Storage>
> static void deleteByPrimaryKey(Storage &storage, int primaryKey)
> {
>     storage.template remove<User>(primaryKey);
> }
> ```

It's works. You're just amazing.

**Comment by acidtonic** [comment]
I don't mean to reopen, but I hit this issue and was rather perplexed by what exactly is going on with this.

Any chance you can explain what C++ rule requires this dance?

I spent some time tracking down the compile error after templating out my storage class in a similar but different way. The storage class was intact enough to complain if I call the wrong method with it's type, but not a primary expression if I call the correct method even though the struct type for the table was also in scope.... I am curious why or what rule causes this?

(And yes .template fixed it for me too but I want to know *why* if you don't mind a brief explanation)

**Comment by fnc12** [comment]
Quick explanation is: when you call template member function from template variable then you need to tell your compiler that these are two layers of templates. AFAIK this will be not necessary in C++20. More details here https://stackoverflow.com/questions/610245/where-and-why-do-i-have-to-put-the-template-and-typename-keywords
