### ISSUE TITLE
test fails in like.cpp TEST_CASE("Like_operator") line 67

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#539]
```
        auto rows = storage.select(like("ototo", "ototo%").escape("%"));
        REQUIRE(rows.size() == 1);
        REQUIRE(rows.front() == true);
```

rows.front() == false!!!
Syntax error for escape?

Regards,
Juan

**Comment by fnc12** [comment]
what branch? `master` or `dev`?

**Comment by juandent** [comment]
master

**Comment by fnc12** [comment]
Does it reproduce with `dev` branch?

**Comment by juandent** [comment]
just take a look at like.cpp line 67 - I have no way to test the dev branch

**Comment by fnc12** [comment]
Hm. yeah you're right. Looks like I didn't test this query within a different SQLite client. So for now query
```sql
SELECT 'ototo' LIKE 'ototo%' ESCAPE '%'
```
returns 0 within SQLite client but query `storage.select(like("ototo", "ototo%").escape("%"))` returns `true`. This is a bug and I shall fix it soon. Thank you

**Comment by fnc12** [comment]
```c++
    sqlite3 *db;
    sqlite3_open("", &db);
    {
        sqlite3_exec(db, "SELECT 'ototo' LIKE 'ototo%' ESCAPE '%'", [](void */*data*/, int /*argc*/, char **argv, char * * /*azColName*/) -> int {
            cout << "[!]" << argv[0] << endl;
            return 0;
        }, nullptr, nullptr);
    }
    sqlite3_close(db);
```
this code also prints `[!]1`. Looks like we (or I) don't understand something. What do you think?

**Comment by juandent** [comment]
sorry I am not proficient in sqlite, I am afraid I can't help you right now :-(

**Comment by fnc12** [comment]
Also when I run `SELECT 'ototo' LIKE 'ototo%' ESCAPE '%'` inside `sqlite3` CLI utility I get `1`. Looks like it is not a bug - it is a correct behavior. Please check information about `LIKE` operator https://www.sqlitetutorial.net/sqlite-like/

**Comment by fnc12** [comment]
is the issue actual?

**Comment by juandent** [comment]
the issue persists in dev branch

**Comment by juandent** [comment]
we get front() = false
