### ISSUE TITLE
Storing a null (value 0x0) in Blob

### ISSUE THREAD

**Issue by Rishi321** [fnc12/sqlite_orm#54]
Hi,
  I'm storing a vector (matrix dump) into a BLOB in SQLite.
  This works fine until a 0 value is encountered. While reading, it stops at the 0 and the rest is garbage.
  The data in the database also stops printing after the first 0 value, although the `select length(data) from blob;` returns the correct length (100 in this case).
  After reading the data back it gives me the length 9 (where the first 0 is forced), always.
  Not sure if it's me, here's the code to reproduce

    #include <bits/stdc++.h>
    #include "sqlite_orm.h"

    using namespace std;
    using namespace sqlite_orm;

    typedef char byte;

    struct BlobData {
        vector<char> data;
    };

    byte* generateData(int size) {
        byte *data = (byte*)malloc(size*sizeof(byte));

        for (int i = 0; i < size; ++i) {
            if ((i+1) % 10 == 0) {
                data[i] = 0;
            } else {
                data[i] = (rand() % 100) + 1;
            }
        }

        return data;
    }

    auto getStorage(string dbpath) {
        auto table = make_table("blob",
                                            make_column("data", &BlobData::data)
                                        );
        auto storage = make_storage(dbpath, 
                                        table
                                    );
        return storage;
    }

    void newDB(string dbname) {
        auto storage = getStorage(dbname);
        storage.sync_schema();
        storage.remove_all<BlobData>();
    }

    void writeBlob(string dbname, byte* data, int size) {
        auto storage = getStorage(dbname);

        BlobData d;
        // d.data = string( reinterpret_cast<char const*>(data), size );
        std::vector<char> v(data, data+size);
        d.data = v;
        cout << "Write Size: " << d.data.size() << endl;
        storage.insert(d);
    }

    void readBlob(string dbname) {
        auto storage = getStorage(dbname);

        vector<BlobData> vd = storage.get_all<BlobData>();
        for (int i = 0; i < vd.size(); ++i)
        {   
            cout << "Read Size " << vd[i].data.size() << endl;
            for (int j = 0; j < vd[i].data.size(); ++j)
            {
                printf ("%d ", vd[i].data[j]);
            }
            cout << endl;
        }
    }

    int main(int argc, char const *argv[])
    {
        int size = 100;
        string dbname = "blob.db";
        byte* data = generateData(size);

        newDB(dbname);
        writeBlob(dbname, data, size);
        readBlob(dbname);

        return 0;
    }

**Comment by Rishi321** [comment]
I see the issue
Line 2449 `auto len = ::strlen(row_value);`
`strlen` will stop at a null.
Still scratching my head on how to get around this.

**Comment by fnc12** [comment]
Hi. The only way I see is to give up using `sqlite3_exec` in `get_all` but use prepared statement. But let me think a little bit more - probably there is a way to solve it with a easier way

**Comment by fnc12** [comment]
http://sqlite.1065341.n5.nabble.com/Blob-in-the-callback-of-sqlite3-exec-td8604.html

**Comment by fnc12** [comment]
Please use `select` now for a few days - I'll change `get_all` implementation so it will use prepared statement. I think this is a best solution cause prepared statement gives more functionality

**Comment by Rishi321** [comment]
Aah, thanks
`select` is also using the `sql_exec callback` method, so I'm using the `iterate` and manually checking the for the conditions for now

**Comment by fnc12** [comment]
@Rishi321 thanks for your patience

**Comment by Rishi321** [comment]
Thank you for your quick redressal :)

**Comment by fnc12** [comment]
@Rishi321 please check latest commits. I've refactored `get_all` with statements and added tests based on your case. I'm gonna refactored `select` and close the issue. Is it ok for you?

**Comment by Rishi321** [comment]
Works. Perfect. :+1:

**Comment by fnc12** [comment]
I didn't finish refactoring within `select` function so I leave the issue opened until it is done
