### ISSUE TITLE
raw sql

### ISSUE THREAD

**Issue by zajzhuaijun** [fnc12/sqlite_orm#545]
how to execut raw sql ,like 'select * from table_name where .....'

**Comment by fnc12** [comment]
three ways:
```c++
auro rows = storage.get_all<User>(where(is_equal(&User::name, "ototo"))); // decltype(rows) is std::vector<User>
```
or
```c++
auto rows = storage.select(asterisk<User>(), where(...));  // decltype(rows) is std::vector<std::tuple<...>>
```
or 
```c+++
auto rows = storage.select(columns(&User::id, &User::name), where(...));
```

**Comment by zajzhuaijun** [comment]
I mean use sql gramma like 
auto res = db.execut("select * from table where xxxx");

**Comment by zajzhuaijun** [comment]
auto selectStatement = storage.prepare(select(&record_task::record_id, where(like(&record_task::content, "我%"))));
	cout << "selectStatement = " << selectStatement.sql() << endl;


selectStatement = SELECT 'record_task'."record_id" FROM 'record_task'  WHERE ( 'record_task'."content" LIKE ?)
why like content is ?

**Comment by fnc12** [comment]
> I mean use sql gramma like
auto res = db.execut("select * from table where xxxx");

`sqlite_orm` is not designed for raw sql cause most of raw queries can be performed using `sqlite_orm` API and their amount is heading to 100%

> selectStatement = SELECT 'record_task'."record_id" FROM 'record_task' WHERE ( 'record_task'."content" LIKE ?)
why like content is ?

Cause this is what `sqlite3_sql` returns (https://www.sqlite.org/c3ref/sql.html). Question mark means that this value is bound and may be rebound using `sqlite_orm::get` API:
```c++
auto selectStatement = storage.prepare(select(&record_task::record_id, where(like(&record_task::content, "我%"))));
auto data1 = storage.execute(selectStatement);
get<0>(selectStatement) = "brother%"; // change "我%" whatever it means to "brother%"
auto data2 = storage.execute(selectStatement);
```
Hope it helps.

**Comment by zajzhuaijun** [comment]
thanke you，I have solved it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yevgeniy Zakharov"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 晚上7:24
收件人:&nbsp;"fnc12/sqlite_orm"<sqlite_orm@noreply.github.com&gt;;
抄送:&nbsp;"天马行空"<978206970@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fnc12/sqlite_orm] raw sql (#545)





  
I mean use sql gramma like
 auto res = db.execut("select * from table where xxxx");
  
sqlite_orm is not designed for raw sql cause most of raw queries can be performed using sqlite_orm API and their amount is heading to 100%
  
selectStatement = SELECT 'record_task'."record_id" FROM 'record_task' WHERE ( 'record_task'."content" LIKE ?)
 why like content is ?
  
Cause this is what sqlite3_sql returns (https://www.sqlite.org/c3ref/sql.html). Question mark means that this value is bound and may be rebound using sqlite_orm::get API:
 auto selectStatement = storage.prepare(select(&amp;record_task::record_id, where(like(&amp;record_task::content, "我%")))); auto data1 = storage.execute(selectStatement); get<0&gt;(selectStatement) = "brother%"; // change "我%" whatever it means to "brother%" auto data2 = storage.execute(selectStatement);
 
Hope it helps.
