### ISSUE TITLE
How do I download the dev branch?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#547]
I need a little push with git commands, like so:

I have this:

>git clone https://github.com/fnc12/sqlite_orm.git

does it get me the master branch by default? if so, how can I get the dev branch?

Regards,
Juan Dent

**Comment by fnc12** [comment]
what OS do you use?

**Comment by fnc12** [comment]
```
git clone https://github.com/fnc12/sqlite_orm.git
cd sqlite_orm
git checkout dev
```

**Comment by juandent** [comment]
I get an error:

> C:\Components\sqlite_orm>git checkout dev
fatal: 'dev' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate

??
I get the following also:

> C:\Components\sqlite_orm>git branch
* master


so I don't have a dev branch locally -- is git checkout dev referring to the remote branch dev?

**Comment by juandent** [comment]
I believe I am not being successful checking out dev because here is the response to git branch -r:

> git branch -r
  origin/HEAD -> origin/master
  origin/bitwise-binary-operators
  origin/dev
  origin/feature/custom-functions
  origin/feature/on-conflict
  origin/master
  origin/remove-clang-latest

How can I access the remote branches so I can checkout dev from the remote repository?

**Comment by fnc12** [comment]
try `git checkout origin/dev`

**Comment by juandent** [comment]
won't work
I need to reference the remote branch

**Comment by fnc12** [comment]
did you try? What is output?

**Comment by juandent** [comment]
C:\Components\sqlite_orm>git checkout origin/dev
HEAD is now at 2dbdcad Merge pull request #542 from fnc12/bugfix/backup

**Comment by juandent** [comment]
should I do a pull request? with what syntax?

**Comment by juandent** [comment]
is this the remote dev?

**Comment by fnc12** [comment]
you did right. You're now at `dev` branch

**Comment by juandent** [comment]
yet the source code hasn't changed!
what file was changed so I can check it?

**Comment by fnc12** [comment]
`sqlite_orm.h`

**Comment by fnc12** [comment]
Did it work?

**Comment by juandent** [comment]
Yes!!!
Great work

**Comment by Leon0402** [comment]
Just wanted to say that the issue here is that one folder is named dev as well, so git isn't sure what to do. 
A `git checkout dev --" will do the trick and setup a local remote tracking branch

@fnc12 Consider renaming the dev folder perhaps, I think this can be rather confusing. I got the same error message before.

**Comment by fnc12** [comment]
after creating a local branch from `origin/dev` it must not lead to error. So It happens only once. Or it happens after setting up local tracking branch?

**Comment by Leon0402** [comment]
@fnc12 Yeah it just happens once. But I think once is already enough, make it as easy as possible for new developers.
