### ISSUE TITLE
statement for alter table with string default value has double single quotes

### ISSUE THREAD

**Issue by Hartigan** [fnc12/sqlite_orm#55]
I found bug with default value and sync schema.
First revision of schema:
```
make_storage("test_db.sqlite",
    make_table("User",
        make_column("Id",
            &User::userId,
            primary_key()),
        make_column("Name",
            &User::name),
        make_column("Age",
            &User::age)));
```

Second revision(with std::string field 'email'):

```
make_storage("test_db.sqlite",
    make_table("User",
        make_column("Id",
            &User::userId,
            primary_key()),
        make_column("Name",
            &User::name),
        make_column("Age",
            &User::age),
        make_column("Email",
            &User::email,
            default_value("example@email.com"))));
```

Single qoutes was added in default_value_extractor and get_table_info.
Generated statement: `ALTER TABLE User ADD COLUMN Email TEXT NOT NULL DEFAULT ''example@email.com'' `

**Comment by fnc12** [comment]
so expected statement is `ALTER TABLE User ADD COLUMN Email TEXT NOT NULL DEFAULT 'example@email.com'` ?

**Comment by Hartigan** [comment]
yes

**Comment by fnc12** [comment]
thanks for a bug report. Default value is least tested feature from all library features. So it is time to fix it and cover with tests. I'm gonna fix this in a few days.

**Comment by Hartigan** [comment]
Thanks

**Comment by Ninja-007** [comment]
To take care of use case involving table and column names as numbers(e.g. 1) .

It should be 
ALTER TABLE 'User' ADD COLUMN 'Email' TEXT NOT NULL DEFAULT 'example@email.com' ?

**Comment by Ninja-007** [comment]
https://blog.christosoft.de/2012/10/sqlite-escaping-table-acolumn-names/

**Comment by fnc12** [comment]
@Hartigan does storage work after modifying schema with `email` column?

**Comment by Ninja-007** [comment]
https://www.sqlite.org/lang_keywords.html

**Comment by Hartigan** [comment]
@fnc12 storage not worked because statement `ALTER TABLE User ADD COLUMN Email TEXT NOT NULL DEFAULT ''example@email.com''` cannot be prepared

**Comment by fnc12** [comment]
@Hartigan ok. I'll fix it and cover with unit tests
