### ISSUE TITLE
Why the result of insert is int?

### ISSUE THREAD

**Issue by HyperionChen** [fnc12/sqlite_orm#551]
In `insert` method, converts the return value to `int` coercively. Now I have a very big table, the primary key must be uInt64, how can I do it?

The second question, can I user std::string for primary key?

**Comment by fnc12** [comment]
> In insert method, converts the return value to int coercively. Now I have a very big table, the primary key must be uInt64, how can I do it?

especially for this situation you can find `storage.last_insert_rowid()` function. It returns `int64`. If it returns 0 then you need to call it right after `insert` call within a transaction.

> The second question, can I user std::string for primary key?
Yes. Just try it

**Comment by HyperionChen** [comment]
It's works, thank you!
