### ISSUE TITLE
My VC++ 2019 compiler issues this warning when compiling release (not present when compiling debug)

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#552]
> C:\Components\sqlite_orm\include\sqlite_orm\sqlite_orm.h(252): warning C4172: returning address of local variable or temporary

which corresponds to this code:

```
template<bool B, typename T>
        decltype(auto) static_if(const T &t) {
            return static_if(std::integral_constant<bool, B>{}, t, [](auto &&...) {});
        }
```
This could be very dangerous. Please take a look at it.

Again I am using VStudio 2019 in Windows 10 Pro

Regards,
Juan

**Comment by fnc12** [comment]
Oh really. Looks like you're right. The last argument `[](auto &&...) {}` is a temporary object but it's reference is passed outside. I shall fix it soon. Thank you

**Comment by fnc12** [comment]
fix is here https://github.com/fnc12/sqlite_orm/pull/553

**Comment by fnc12** [comment]
merged. Please check it out

**Comment by juandent** [comment]
I checked it out but got this:

> C:\Components\sqlite_orm>git checkout origin/dev
HEAD is now at 2dbdcad Merge pull request #542 from fnc12/bugfix/backup

C:\Components\sqlite_orm>git branch
* (HEAD detached at origin/dev)
  dev
  help
  master

and I don't see any difference in the salite_orm.h file so something is wrong with the checkout
please help so I can confirm your corrections

Regards,
Juan Dent

**Comment by fnc12** [comment]
run `git pull`. If it will not change the commit then run
`git pull origin dev`

**Comment by juandent** [comment]
yes it works!! congrats

BTW, why do I keep getting this message:

> C:\Components\sqlite_orm>git status
HEAD detached from 2dbdcad

what does HEAD detached mean?

**Comment by fnc12** [comment]
HEAD detached means that you are off a branch right now (locally). To attach the HEAD run
```
git checkout origin/dev
git checkout -b dev
git branch --track origin dev
```
Now the HEAD is up attached to `dev`. To pull `dev` run `git pull`, to push: `git push`

**Comment by juandent** [comment]
I got this:

> C:\Components\sqlite_orm>git checkout origin/dev

HEAD is now at 3efc98c Merge pull request #553 from fnc12/vs-warning-remove

> C:\Components\sqlite_orm>git checkout -b dev

fatal: A branch named 'dev' already exists.

> C:\Components\sqlite_orm>git branch --track origin dev

Branch 'origin' set up to track local branch 'dev'.


what does this mean?
