### ISSUE TITLE
Custom Blob Type

### ISSUE THREAD

**Issue by mzatkhahi** [fnc12/sqlite_orm#557]
I created a custom blob type named POINT. (This type is common in GIS applications like QGIS)
But there is a problem in sync_schema which always recreate table. This is because to_sqlite_type does not handle the Custom type name, After adding the Type name in function to_sqlite_type the following manner the bug fixed:
```

          {sqlite_type::BLOB,
             {
                 std::regex("BLOB"),
                 std::regex("POINT")
             }}, 

```
Of course this bug should be solved in general code that supports any Type name.

Code for creating custom Blob type:

```

struct Point
{
    std::vector<char> geometry;
};
namespace sqlite_orm {
    
   
    template<>
    struct type_printer<Point> {
        inline const std::string& print() {
            static const std::string res = "POINT";
            return res;
        }
    };

    template<>
    struct statement_binder<Point> {

        int bind(sqlite3_stmt* stmt, int index, const Point& value) {
            return statement_binder<std::vector<char>>().bind(stmt, index, value.geometry);            
        }
    };

   
    template<>
    struct field_printer<Point> {
        std::string operator()(const Point& t) const {
            std::stringstream ss;
            ss << std::hex;
            for (auto c : t.geometry) {
                ss << c;
            }
            return ss.str();
        }
    };

    
    template<>
    struct row_extractor<Point> {
        Point extract(const char* row_value) {
            Point p;
            p.geometry = row_extractor<std::vector<char>>().extract(row_value);
            return p;
        }

        Point extract(sqlite3_stmt* stmt, int columnIndex) {
            auto str = row_extractor<std::vector<char>>().extract(stmt, columnIndex);
            Point p;
            p.geometry = str;
            return p;
        }
    };
}
```

**Comment by fnc12** [comment]
SQLite stores data in dynamic types so one can use any type in any column. But C++ is strong typed language. `sqlite_orm` is designed to store columns with strong types. It means if you first create a storage with a table with a column of type `std::string`, call `sync_schema`, than you change `std::string` to `int` and call `sync_schema` again storage will drop and recreate this column. So SQLite's type is called affinity. It is not a type. And that is why SQLite allows you to provide any word for type when you write `CREATE TABLE` query. 
Type comparison is very important way to check whether columns are equal or not. Assume you decided to treat `POINT` as `BLOB` and some another person wants to treat `POINT` as `TEXT`. How can storage understand which `POINT` is correct and which isn't? Ok you can create a specialization but how storage type parser can find all specializations?
So it is better to use `BLOB` instead of `POINT` cause this is the way to make it right.

**Comment by fnc12** [comment]
Ok I thought about it in a different way. One can add custom type if storage somehow knows about custom types. Example:
```c++
auto storage = make_storage("",
    make_table(...),
    make_table(...),
    make_custom_types<Point, ...>(),
    );
```
Then in `to_sqlite_type` function storage will iterate all types, call `type_printer<Point>{}.print()` and compare it somehow. What do you think?

**Comment by mzatkhahi** [comment]
> Ok I thought about it in a different way. One can add custom type if storage somehow knows about custom types. Example:
> 
> ```c++
> auto storage = make_storage("",
>     make_table(...),
>     make_table(...),
>     make_custom_types<Point, ...>(),
>     );
> ```
> 
> Then in `to_sqlite_type` function storage will iterate all types, call `type_printer<Point>{}.print()` and compare it somehow. What do you think?

Yes that's a very good idea and will fulfill the requirements. 

Also it's good to mention that , the main target for the custom type name is syncing with sqlite DB that is generated by other apps like QGIS. Some applications may use the Custom Type Name as additional information to deserialize the BLOB or TEXT, ... 

Thank you in advance.

**Comment by fnc12** [comment]
I've checked out sqlite's source and I figured out that it doesn't contain any type parsing. It means that type name means nothing for 100%. So i think I need to remove `to_sqlite_type` function and its' related enum with its' comparison. I means that `sync_schema` will be altered this way: changing member field's type will not alter schema at all.

**Comment by fnc12** [comment]
fix on its way https://github.com/fnc12/sqlite_orm/pull/570

**Comment by fnc12** [comment]
@mzatkhahi please check out `dev` branch whether you have such a problem. Thanks

**Comment by fnc12** [comment]
@mzatkhahi are you there?

**Comment by fnc12** [comment]
closing cause everything is fixed. If you have any additional issues please feel free to post it here and reopen this issue or create a new one. Thanks
