### ISSUE TITLE
which is best to use: unique_ptr or shared_ptr in the definition of an optional field?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#559]
For instance:

```
struct Transaccion
{
	int id_transaccion;
	double amount_colones;
	double amount_dolares;
	int fkey_account_origin;				// Account
	std::unique_ptr<int> fkey_account_destination;			// Account optional
	int fkey_statementline;					// StatementLine
};
```

or

```
struct Transaccion
{
	int id_transaccion;
	double amount_colones;
	double amount_dolares;
	int fkey_account_origin;				// Account
	std::shared_ptr<int> fkey_account_destination;			// Account optional
	int fkey_statementline;					// StatementLine
};
```

?

Regards,
Juan

**Comment by fnc12** [comment]
This is question can be simplified: what is better to use: `std::shared_ptr` or `std::unique_ptr`. Both of them are treated as optional. The best way is to use C++17 and `std::optional`. If you need C++14 then use `std::unique_ptr` cause it has less runtime overhead than `std::shared_ptr`

**Comment by juandent** [comment]
but using optional leaves the ownership undefined... as far as I understand??

**Comment by fnc12** [comment]
I don't understand. If you think that `std::shared_ptr` as foreign key points to the same int that is stored in database then you are wrong. `std::shared_ptr` is just another nullable type just like `std::unique_ptr` and `std::optional`. `std::optional` is just like `std::unique_ptr` but it stores data in stack not in heap

**Comment by juandent** [comment]
Ok, then using optional eliminates the ownership problem and is much faster... I get it, thanks :-)

Regards,
Juan
