### ISSUE TITLE
Error compling in Vs2015 update 3

### ISSUE THREAD

**Issue by Andrey-N** [fnc12/sqlite_orm#56]
Hi
Awesome library. Got this error when compile sample in Visual Studio 2015, is it possible to fix? Or it's vs2015 unsupport some c++14 feature? I don't fugurate for do to that. Also 2017 compile pretty well.

Thank you.

Error	C2440	'return': cannot convert from 'initializer list' to 'sqlite_orm::constraints::primary_key_t<>'	

    template<class ...Cs>
    inline constraints::primary_key_t<Cs...> primary_key(Cs ...cs) {
		return{ std::make_tuple(cs...) }; // << Error
    }

**Comment by fnc12** [comment]
Thanks for using the lib. Yes VS2015 is sensitive to initializing from initializer_list. I've added constructor to `constraints::primary_key_t` and now it must compile with VS2015.

**Comment by fnc12** [comment]
It would be good if we could run CI tests with VS compiler on windows

**Comment by Andrey-N** [comment]
Now my code is  compile. 
But tests is not.
I made project in vc 2015 with tests from this source sqlite_orm\tests\tests.cpp and got errors

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'return': cannot convert from 'initializer list' to 'sqlite_orm::constraints::foreign_key_intermediate_t<std::shared_ptr<int> testForeignKey::Visit::* >'	sqlite_orm_tests	d:\vc++\sqlite_orm_tests\sqlite_orm_tests\sqlite_orm.h	288	
Error	C2440	'return': cannot convert from 'initializer list' to 'sqlite_orm::constraints::foreign_key_t<C,int testForeignKey::Location::* >'	sqlite_orm_tests	d:\vc++\sqlite_orm_tests\sqlite_orm_tests\sqlite_orm.h	268	
```

Also i made some changes in sqlite_orm.h after namespace sqlite_orm { insert macro and undefine min max windows.h macro
```
namespace sqlite_orm {

#ifdef _MSC_VER
#undef min
#undef max
#define and &&
#define or ||
#endif
```

**Comment by fnc12** [comment]
fixed. And why do you use `#undef min` and `#define and &&`?It looks like VC++ doesn't know about `and` and `or` keywords.
