### ISSUE TITLE
Column sort-order in an Index

### ISSUE THREAD

**Issue by azurepine** [fnc12/sqlite_orm#567]
I have a `CREATE INDEX` statement like below.
```sql
CREATE INDEX fooIndex ON fooTable
(
    bar1 ASC, 
    bar2 DESC, 
    bar3 ASC
);
```

Is there a way to specify the sort-order of each column?
```c++
make_index("fooIndex", 
    &fooTable::bar1 /*ASC*/, 
    &fooTable::bar2 /*DESC*/, 
    &fooTable::bar3 /*ASC*/
);
```

**Comment by fnc12** [comment]
Looks like a feature that `sqlite_orm` is missing. So I (we) need to create API for it. I see some options:
1)
```c++
make_index("fooIndex",
     asc(&fooTable::bar1),
     desc(&fooTable::bar2),
     asc(&fooTable::bar3)
);
```
2)
make_index("fooIndex",
     indexed_column(&fooTable::bar1).collate("my_collate).asc(),
     indexed_column(&fooTable::bar2).collate_binary().desc(),
     indexed_column(&fooTable::bar3).asc()
);
```
The first is short and does not allow to specify collation type (https://www.sqlite.org/lang_createindex.html). The second is not so short but allows to specify collation type. Which one do you prefer?

**Comment by azurepine** [comment]
In terms of compliance with the specification, I think the second one would be better. :thumbsup:

**Comment by fnc12** [comment]
PR is on its way https://github.com/fnc12/sqlite_orm/pull/577

**Comment by fnc12** [comment]
@azurepine merged into `dev` branch. Please check out in

**Comment by azurepine** [comment]
Looks good. 👍
Thanks.
