### ISSUE TITLE
Foreign Key usage unable to complete build

### ISSUE THREAD

**Issue by Zarrey** [fnc12/sqlite_orm#57]
Attached is a rough example where I cannot build using the makefile.  There is nothing special about these tables, one merely points to another with a foreign key.  The 2 tables both have primary keys, and the second points to the first with a foreign key.  The ORM allows it to generate the schema fine, but when you call update on the db object with the second table with the foreign key, it breaks.  Commenting out the update call will build.

[sqlite_orm_bug.tar.gz](https://github.com/fnc12/sqlite_orm/files/1431796/sqlite_orm_bug.tar.gz)

Here is the error output:

`In file included from main.cpp:4:0:
sqlite_orm.h: In instantiation of ‘std::vector<std::__cxx11::basic_string<char> > sqlite_orm::table_impl<H, T ...>::column_names_with() [with Op = {sqlite_orm::constraints::primary_key_t<>}; H = sqlite_orm::constraints::foreign_key_t<int testnamespace::test2::*, int testnamespace::test1::*>; T = {}]’:
sqlite_orm.h:1809:64:   recursively required from ‘std::vector<std::__cxx11::basic_string<char> > sqlite_orm::table_impl<H, T ...>::column_names_with() [with Op = {sqlite_orm::constraints::primary_key_t<>}; H = sqlite_orm::internal::column_t<testnamespace::test2, int>; T = {sqlite_orm::internal::column_t<testnamespace::test2, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, sqlite_orm::internal::column_t<testnamespace::test2, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, sqlite_orm::constraints::foreign_key_t<int testnamespace::test2::*, int testnamespace::test1::*>}]’
sqlite_orm.h:1809:64:   required from ‘std::vector<std::__cxx11::basic_string<char> > sqlite_orm::table_impl<H, T ...>::column_names_with() [with Op = {sqlite_orm::constraints::primary_key_t<>}; H = sqlite_orm::internal::column_t<testnamespace::test2, int, sqlite_orm::constraints::primary_key_t<> >; T = {sqlite_orm::internal::column_t<testnamespace::test2, int>, sqlite_orm::internal::column_t<testnamespace::test2, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, sqlite_orm::internal::column_t<testnamespace::test2, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, sqlite_orm::constraints::foreign_key_t<int testnamespace::test2::*, int testnamespace::test1::*>}]’
sqlite_orm.h:1994:69:   required from ‘std::vector<std::__cxx11::basic_string<char> > sqlite_orm::table_t<Cs>::column_names_with() [with Op = {sqlite_orm::constraints::primary_key_t<>}; Cs = {sqlite_orm::internal::column_t<testnamespace::test2, int, sqlite_orm::constraints::primary_key_t<> >, sqlite_orm::internal::column_t<testnamespace::test2, int>, sqlite_orm::internal::column_t<testnamespace::test2, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, sqlite_orm::internal::column_t<testnamespace::test2, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, sqlite_orm::constraints::foreign_key_t<int testnamespace::test2::*, int testnamespace::test1::*>}]’
sqlite_orm.h:4230:110:   required from ‘void sqlite_orm::storage_t<Ts>::update(const O&) [with O = testnamespace::test2; Ts = {sqlite_orm::table_t<sqlite_orm::internal::column_t<testnamespace::test1, int, sqlite_orm::constraints::primary_key_t<> >, sqlite_orm::internal::column_t<testnamespace::test1, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, sqlite_orm::internal::column_t<testnamespace::test1, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, sqlite_orm::table_t<sqlite_orm::internal::column_t<testnamespace::test2, int, sqlite_orm::constraints::primary_key_t<> >, sqlite_orm::internal::column_t<testnamespace::test2, int>, sqlite_orm::internal::column_t<testnamespace::test2, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, sqlite_orm::internal::column_t<testnamespace::test2, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, sqlite_orm::constraints::foreign_key_t<int testnamespace::test2::*, int testnamespace::test1::*> >}]’
main.cpp:78:22:   required from here
sqlite_orm.h:1810:13: error: ‘sqlite_orm::table_impl<sqlite_orm::constraints::foreign_key_t<int testnamespace::test2::*, int testnamespace::test1::*> >::column_type {aka struct sqlite_orm::constraints::foreign_key_t<int testnamespace::test2::*, int testnamespace::test1::*>}’ has no member named ‘has_every’
             if(this->col.template has_every<Op...>()) {
             ^
sqlite_orm.h:1811:17: error: ‘sqlite_orm::table_impl<sqlite_orm::constraints::foreign_key_t<int testnamespace::test2::*, int testnamespace::test1::*> >::column_type {aka struct sqlite_orm::constraints::foreign_key_t<int testnamespace::test2::*, int testnamespace::test1::*>}’ has no member named ‘name’
                 res.emplace_back(this->col.name);
                 ^
makefile:4: recipe for target 'cpp' failed
make: *** [cpp] Error 1`

**Comment by fnc12** [comment]
Hey. Thanks for using the lib. I'll look through tour issue today and write a feedback

**Comment by fnc12** [comment]
fixed in the latest commit and added a test case with your code in `tests.cpp` in `testForeignKey2` function. Thanks

**Comment by Zarrey** [comment]
Thank you for the quick fix.
