### ISSUE TITLE
Destruction of storage object does not close database connection

### ISSUE THREAD

**Issue by Wosser1sProductions** [fnc12/sqlite_orm#582]
I wanted to try this library out and it looks promising. But after a quick test, it seems that after a storage object goes out of scope, it retains one reference to its connection (in `sqlite_orm::internal::connection_holder`), and so `sqlite3_close(this->db)` is never called.

After looking a bit further, this is the flow that happens:

1. Call `make_storage` 
2. Call `sync_scheme`: this creates a scoped ref with get_connection that gets released after returning (Ok)
3. Call `transaction(f)` with a lambda that inserts some values:
    1. `begin_transaction()`: retains one connection --> _retain_count == 1_
    2. `con = get_connection()`: creates and returns a new `connection_ref` --> _retain_count == 2_
    3. `db = con.get()` gets used for either `commit(db)` or `rollback(db)`
    4. Scope exit: destroys `con`, releasing the reference --> _retain_count == 1_ (Ok)

So the retained connection from `begin_transaction()` persists. A solution could be to either (in `transaction(f)` in [single header](https://github.com/fnc12/sqlite_orm/blob/f51a73431a97c2f8774187644938b8ec71b460ff/include/sqlite_orm/sqlite_orm.h#L8280) or here in [dev](https://github.com/fnc12/sqlite_orm/blob/f51a73431a97c2f8774187644938b8ec71b460ff/dev/storage_base.h#L124)):
* Call `con = get_connection()` first and use that result to begin the transaction
* Never use `get_connection()` and instead call the `commit()` and `rollback` functions without a parameter
* Or adding `this->connection->release()` at the end.

Note that I could be missing some other designed behaviour of course. The reason I ran into this is that I wrote a unit test that creates a simple database, uses transaction to insert some data, verify that it is there and then delete the file from disk afterwards. But std::filesystem throws a `broken pipe` error, indication that the file is still in use (because `sqlite_orm` did not close it).

**Comment by fnc12** [comment]
Hi. Looks interesting. Let me investigate it. Thanks

**Comment by fnc12** [comment]
the fix is here https://github.com/fnc12/sqlite_orm/pull/596

**Comment by fnc12** [comment]
I've merged it a minute ago. Thank you
