### ISSUE TITLE
How can I ignore case queries?

### ISSUE THREAD

**Issue by HyperionChen** [fnc12/sqlite_orm#584]
I have a word named `weather` in database, and now I want to query it by "WEATHER", "Weather", what do I need to do?I did not find something from the documentation.

**Comment by fnc12** [comment]
use `COLLATE NOCASE`

**Comment by HyperionChen** [comment]
> COLLATE NOCASE

I have a name with data:

```
HELLO
Hello
HEllo
```

I can get all data when I user sqlite3 instruct with:

```
SELECT * FROM users WHERE first_name == 'hello' COLLATE NOCASE;
``` 

But when I use sqlite_orm, I can't get any data.

```
std::vector<User> userList = storage.get_all<User>(
        sqlite_orm::where(
            sqlite_orm::is_equal(&User::firstName, "hello").collate_nocase()
    ));
```

Is there any problem with the way I use it?

**Comment by HyperionChen** [comment]
I found something. 

In `get_all` method, the `query` variate is 

`"SELECT 'users'.\"id\", 'users'.\"first_name\", 'users'.\"last_name\" FROM 'users' WHERE ( 'users'.\"first_name\" = ? COLLATE NOCASE) "`

It's cannot query anything. But if I modify `query` variate to:

```
"SELECT 'users'.\"id\", 'users'.\"first_name\", 'users'.\"last_name\" FROM 'users' WHERE ( 'users'.\"first_name\" = 'hello' COLLATE NOCASE) "
```

It's can query all datas.

**Comment by fnc12** [comment]
let me check it out

**Comment by fnc12** [comment]
It is a bug. I shall fix it today

**Comment by fnc12** [comment]
fix is on its way https://github.com/fnc12/sqlite_orm/pull/589

**Comment by fnc12** [comment]
merged in `dev` branch. Please check it out

**Comment by fnc12** [comment]
@HyperionChen are you there?

**Comment by HyperionChen** [comment]
> @HyperionChen are you there?

I verified it, and it worked!
