### ISSUE TITLE
make_column definitions cause a "recipe for target failed" error for MinGW64 make

### ISSUE THREAD

**Issue by FinnHornhoover** [fnc12/sqlite_orm#588]
**Platform**: Windows 10, MinGW64
**Compiler Version**: `x86_64-w64-mingw32-g++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0`
**Compiler Args**: `-Wall -std=c++17 -O2`
**Make Executable**: `mingw32-make.exe`

**SQLite3 Linking**: Through compiling from source and linking the object file, `sqlite3.c` and `sqlite3.h` being in the same directory as `sqlite_orm.h`.

**Branch**: `dev`
**Modifications**: The `#include <sqlite3.h>` lines in `sqlite_orm.h` were changed to `#include "sqlite3.h"`.

**Issue**: Trying to create tables similar to the code below:
```c++
// a.hpp
#pragma once

namespace a {
    struct bb {
        int ccc0;
        std::string ccc1;
        std::string ccc2;
        int ccc4;
    };
    struct dd {
        int eee0;
    };
    struct ff {
        int ggg0;
        int ggg1;
        short int ggg2;
        std::string ggg3;
        std::string ggg4;
        short int ggg5;
        short int ggg6;
        short int ggg7;
        short int ggg8;
        short int ggg9;
        short int ggg10;
        short int ggg11;
        short int ggg12;
        short int ggg13;
        short int ggg14;
        short int ggg15;
        int ggg16;
        short int ggg17;
        short int ggg18;
        short int ggg19;
        short int ggg20;
        short int ggg21;
        short int ggg22;
        short int ggg23;
        bool ggg24;
        bool ggg25;
        int ggg25;
        int ggg27;
        int ggg28;
        int ggg29;
        int ggg30;
    };
};
```
```c++
// a.cpp
#include "a.hpp"
#include "x/y/sqlite_orm.h" //same folder where I keep sqlite.h as well, compiled and linked from source

using namespace sqlite_orm;

auto storage = make_storage("storage.db",
    make_table("bb",
        make_column("ccc0", &a::bb::ccc0, autoincrement(), primary_key()),
        make_column("ccc1", &a::bb::ccc1),
        make_column("ccc2", &a::bb::ccc2),
        make_column("ccc3", &a::bb::ccc3)
    ),
    make_table("dd",
        make_column("eee0", &a::dd::eee0, primary_key())
    )
    make_table("ff",
        make_column("ggg0", &a::ff::ggg0, autoincrement(), primary_key()),
        make_column("ggg1", &a::ff::ggg1),
        make_column("ggg2", &a::ff::ggg2),
        make_column("ggg3", &a::ff::ggg3),
        make_column("ggg4", &a::ff::ggg4),
        make_column("ggg5", &a::ff::ggg5),
        make_column("ggg6", &a::ff::ggg6),
        make_column("ggg7", &a::ff::ggg7),
        make_column("ggg8", &a::ff::ggg8),
        make_column("ggg9", &a::ff::ggg9),
        make_column("ggg10", &a::ff::ggg10),
        make_column("ggg11", &a::ff::ggg11),        
        make_column("ggg12", &a::ff::ggg12),
        make_column("ggg13", &a::ff::ggg13),
        make_column("ggg14", &a::ff::ggg14),
        make_column("ggg15", &a::ff::ggg15),
        make_column("ggg16", &a::ff::ggg16),
        make_column("ggg17", &a::ff::ggg17),
        make_column("ggg18", &a::ff::ggg18),
        make_column("ggg19", &a::ff::ggg19),
        make_column("ggg20", &a::ff::ggg20),
        make_column("ggg21", &a::ff::ggg21),
        make_column("ggg22", &a::ff::ggg22),
        make_column("ggg23", &a::ff::ggg23),
        make_column("ggg24", &a::ff::ggg24),        
        make_column("ggg25", &a::ff::ggg25),        
        make_column("ggg26", &a::ff::ggg26),        
        make_column("ggg27", &a::ff::ggg27),
        make_column("ggg28", &a::ff::ggg28),
        make_column("ggg29", &a::ff::ggg29),
        make_column("ggg30", &a::ff::ggg30)
    )
);
```
I get the following error after waiting for a while:
```
x86_64-w64-mingw32-g++ -c -Wall -std=c++17 -O2  -o src/a.o src/a.cpp

Makefile:108: recipe for target 'src/a.o' failed
mingw32-make: *** [src/a.o] Error 1
```
On my system, erasing all columns after `ggg12` in the `ff` table makes this error disappear and make runs successfully. Introducing `ggg13`'s column or more columns after that causes the error.

I have confirmed that make runs successfully in Debian with all the columns and the same compile arguments but with the `clang++` compiler instead.

Is this a template issue? How can I fix this for my environment?

**Comment by fnc12** [comment]
try to increase template recursion. It is a compile option. More details [here](https://stackoverflow.com/questions/12277732/template-metaprogramming-recursion-up-limits)

**Comment by FinnHornhoover** [comment]
@fnc12 I've tried with `-ftemplate-depth=1024` and `-ftemplate-depth=4096`, the results didn't change. I was able to compile it with `-O0` instead of `-O2` however. But that's not very desirable for me.

**Comment by fnc12** [comment]
Looks like a template issue. There are two ways of fixing it:
1) reducing the amount of template calls within the lib
2) fixing gcc cause clang compiles the same code very well
I don't have a quick fix right now. Either remove optimization from compiler options or use clang instead

**Comment by FinnHornhoover** [comment]
Updating this so that others may find it useful, I've found that disabling a few optimizations lets me restore the rest of the optimizations in `O3`:
```
-fno-tree-dce (this is enough to fix if your optimization level is O1)
-fno-inline-small-functions (for O2 and O3, you need this as well)
```
Compiling with `x86_64-w64-mingw32-g++ -c -Wall -std=c++17 -O3 -fno-tree-dce -fno-inline-small-functions` yields no errors, even without altering the template recursion parameter.
