### ISSUE TITLE
no longer support:  template<class O, class C = std::vector<O>, class... Args>

### ISSUE THREAD

**Issue by ChineseBoyLY** [fnc12/sqlite_orm#595]
`/**
             *  Select * with no conditions routine.
             *  O is an object type to be extracted. Must be specified explicitly.
             *  @return All objects of type O stored in database at the moment.
             */
            template<class O, class C = std::vector<O>, class... Args>
            C get_all(Args &&... args) {
                this->assert_mapped_type<O>();
                auto statement = this->prepare(sqlite_orm::get_all<O>(std::forward<Args>(args)...));
                return this->execute(statement);
            }`

release v1.5 : no support  template C ???

**Comment by fnc12** [comment]
does it reproduce in `dev` branch? There was a bug and it must be fixed already

**Comment by fnc12** [comment]
please consider this test in `dev` branch https://github.com/fnc12/sqlite_orm/blob/dev/tests/get_all_custom_containers.cpp . It is fixed already and will be release in v1.6

**Comment by fnc12** [comment]
@ChineseBoyLY are you there?

**Comment by ChineseBoyLY** [comment]
understand. Thank you!
