### ISSUE TITLE
I need the REF, HEAD_REF and SHA512 for the develop branch so I can download it using vcpckg like so:

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#599]
> vcpkg_from_github(

    OUT_SOURCE_PATH SOURCE_PATH
    REPO fnc12/sqlite_orm
    REF b30ddc6a50dc582c93cd49d8d0cf8f5025ba1d2b # 1.5
    SHA512 faeeef88aef11e89e9565850c23087925fb4d75ef48a16434055f18831db8e230d044c81574d840dacca406d7095cb83a113afc326996e289ab11a02d8caa2f4
    HEAD_REF master   ///// change master to develop or whatever branch I desire to download
    PATCHES 
        fix-includes-not-found.patch
        disable-examples.patch
)

How can I get the values for REF, HEAD_REF and SHA512 for a particular branch?  vcpckg comes with support for master branch but I need to download another branch!

Regards,
Juan

**Comment by fnc12** [comment]
@juandent did you try to ask the same thing in vcpckg repo? Looks like it cam be simplified to `how one can specify a branch not tag`? This question also bothers me cause all vcpckg users I saw unable to do it.

**Comment by fnc12** [comment]
@juandent are you there?

**Comment by Leon0402** [comment]
Just use HEAD_REF only I suppose? 

I've never tried it, but according to https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_from_github/ you can specify REF (which is a commit id or tag) or HEAD_REF (which is a branch name). Ideally you would specify both, but it doesn't seem to be a requirement. 

If you want to specify a REF, you can find them here: https://github.com/fnc12/sqlite_orm/commits/dev ... the docs tell you how to get SHA512.

Taking a look at https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_from_github.cmake it seems like HEAD_REF will be the default and REF the fallback solution.

**Comment by fnc12** [comment]
@juandent is the issue actual?

**Comment by juandent** [comment]
to be perfectly honest I stopped trying to download a specific branch of your library using vcpckg and downloaded it frorm github instead so I never got the solution,,,, Are you close to a solution using vcpckg?

**Comment by fnc12** [comment]
I don't use vcpkg actually. I never use it. That is why I placed 'help wanted' label here =/

**Comment by juandent** [comment]
I have just placed the question in vcpckg github. Will let you know if I get a solution!! Happy to help!

**Comment by fnc12** [comment]
thank you @juandent !

**Comment by fnc12** [comment]
@juandent is the issue actual?

**Comment by fnc12** [comment]
@juandent is the issue actual?

**Comment by juandent** [comment]
No, you may close the issue!

 

Juan

**Comment by juandent** [comment]
This issue if incomplete and it needs to be reopened to answer the question of the issue. I got a response in the vcpkg repo that clearly explains what we need to do when desiring to download a different version of a repository. It all has to do with the port file corresponding to sqlite_orm which lies in vcpkg\ports\sqlite-orm\portfile.cmake. This contains a function that needs tweeking (vcpkg_from_github)

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO fnc12/sqlite_orm
    REF e8a9e9416f421303f4b8970caab26dadf8bae98b # v1.5
    SHA512 9774345e0209482a137e5f3058e2f27db55ea72fd08c44e67c0989df8927fee896cb789dcb2cd21167689c2f2be1c126bd730a6ea1083a48e6dd58fb048c6f5e
    HEAD_REF master
)
```
We need to change HEAD_REF to desired branch, the value of REF needs to be updated with the commit id in the dev branch. Then you install the port, which will fail; vcpkg will give you the correct SHA512 which then you must modify in the function and install again, succeding. It will use the correct source in dev branch.

At the end, the function in the portfile will look something like:

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO fnc12/sqlite_orm
    REF 6df8ebeedcede68d59a2f3820566e6be233f240c
    SHA512 2014b7247e8466b57ec7937e23381fd93b16f207550f9881c4fd2d1f6971bb93016cd465806ab71bc66388c5bdedd5f7dae43adbd67708bc2ba5b670b551b3ef
    HEAD_REF dev
)
```

That's it!!

Please reopen this issue and mark it "solved" ...

Regards,
Juan Dent

**Comment by juandent** [comment]
Hi John,

 

I found a complete answer to the issue #599 that clearly explains how to use vcpkg to install any version of a github repository… it’s rather simple actually!!

 

Please mark it as answered so people using Windows and vcpkg can benefit from this explanation and can download whatever version of sqlite_orm they please.

 

Regards,

Juan Dent

**Comment by fnc12** [comment]
@juandent thanks
