### ISSUE TITLE
C++11 Support

### ISSUE THREAD

**Issue by lucasshrew** [fnc12/sqlite_orm#6]
Hi,

How difficult you think it is to re-implement the parts that are done in C++14 for sqlite_orm to be C++11 compatible?

Thanks.

**Comment by fnc12** [comment]
@lucasshrew not too difficult. Why? What's your compiler and target platform?

**Comment by fnc12** [comment]
bump. Is the issue still actual?

**Comment by fnc12** [comment]
Ok. The answer is no. Right now code requires C++14. Main reason is templated lambdas. If course one can avoid it and replace with template classes but it would make code less readable. One more point about C++14 availability. C++14 is available on most popular compilers: iOS clang, Android NDK (or CrystaX NDK), MSVC++15.
