### ISSUE TITLE
Memory leak exists for sqlite3

### ISSUE THREAD

**Issue by HyperionChen** [fnc12/sqlite_orm#604]
When I used `Valgrind` to check for memory problems, The report showed a memory leak in `sqlite3`

```
==4463== 56,560 bytes in 21 blocks are indirectly lost in loss record 259 of 260
==4463==    at 0x4841054: malloc (vg_replace_malloc.c:309)
==4463==    by 0x548E277: sqlite3MemMalloc (in ********/libsqlite3.so)
```

Is there a way to break sqlite3's connection like `release` and so on?

**Comment by undisputed-seraphim** [comment]
That's an issue with sqlite3 🤣 It says there, in `libsqlite3.so`
Maybe if you post a code sample we can try to determine if the problem can be remediated on this side.

**Comment by fnc12** [comment]
yes as @undisputed-seraphim said `sqlite3MemMalloc` is sqlite3's function. Try to write sqlite3 team about it. Here is useful link https://www.sqlite.org/src/wiki?name=Bug+Reports

**Comment by HyperionChen** [comment]
> That's an issue with sqlite3 🤣 It says there, in `libsqlite3.so`
> Maybe if you post a code sample we can try to determine if the problem can be remediated on this side.
