### ISSUE TITLE
is it possible to use unordered_map to save the collection?

### ISSUE THREAD

**Issue by spiritEcosse** [fnc12/sqlite_orm#606]
good time of day, is it possible to use unordered_map to save the collection?

Like this

     std :: unordered_map <const char *, User> users;
     users.insert ({"key", User {-1, "Jonh", "Doe", 664416000, std :: make_unique <std :: string> ("url_to_heaven"), 3}});
     storage.insert_range (users.begin (), users.end ());

error: static assertion failed: type is not mapped to a storage

**Comment by fnc12** [comment]
You pass a pair into `insert`. What do you need key for?

**Comment by spiritEcosse** [comment]
I need a key to group objects by fields. just before writing to the database the key is no longer needed.

**Comment by fnc12** [comment]
what kind of API do you expect?

**Comment by spiritEcosse** [comment]
Thanks for the answers. Speaking of the adapter, could you provide an example please?
