### ISSUE TITLE
transaction memory leak

### ISSUE THREAD

**Issue by HyperionChen** [fnc12/sqlite_orm#607]
in struct `connection_holder`, the `retain` method increase `_retain_count`, the `release` reduce `_retain_count`, and when _retain_count equal 0, the `sqlite3_close` will be called.

then, in `begin_transaction` method call `connection->retain()`, in `commit()` method and `rollback()` method call `connection->release()`, but `commit(sqlite3 *db)` and `rollback(sqlite3 *db)` don't call `connection->release()`

so, When I use `transaction(const std::function<bool()> &f)`, the method's definition like this:

```
            bool transaction(const std::function<bool()> &f) {
                this->begin_transaction();
                auto con = this->get_connection();
                auto db = con.get();
                auto shouldCommit = f();
                if(shouldCommit) {
                    this->commit(db);
                } else {
                    this->rollback(db);
                }
                return shouldCommit;
            }
```

in `begin_transaction` increase `_retain_count`, but `commit(db)` and `rollback(db)` don't reduce `_retain_count`. so `sqlite3_close` will never be called, the memory leak here.

I can use `begin_transaction()`, `commit()` and `rollback()` to call transaction explicitly, no memory leaks.

**Comment by undisputed-seraphim** [comment]
Ah, I see the problem.
The code should be calling `this->commit()` instead of `this->commit(db)`, and so on.

@fnc12 I have avoided the problem by simplifying the code around that area ([See this commit in my fork](https://github.com/undisputed-seraphim/sqlite_orm/commit/765caee81fdffe34869cd9dfb6c1cf2464540f44))

**Comment by fnc12** [comment]
@HyperionChen does it exist in `dev`? I remember that I fixed the same thing a few weeks ago and this fix was merged two days ago into `master`.

**Comment by fnc12** [comment]
@HyperionChen are you there?

**Comment by fnc12** [comment]
@HyperionChen are you there?

**Comment by HyperionChen** [comment]
> @HyperionChen are you there?

It's worked.
