### ISSUE TITLE
How do I create storage from other class and return it to storage? Because the type is too complex

### ISSUE THREAD

**Issue by lingme** [fnc12/sqlite_orm#610]
I see that all the examples are created from the current class. How do I create from another class and return this storage

It looks something like this：
``` C
auto storage = RepositoryFactory.CrateStorage();

do something
```

**Comment by fnc12** [comment]
what's the problem? Do it. If you need a type of your storage please check out [FAQ](https://github.com/fnc12/sqlite_orm/wiki/FAQ)

**Comment by lingme** [comment]
@fnc12, thanks very much, let me try
