### ISSUE TITLE
SELECT MAX(_ROWID_) FROM Table

### ISSUE THREAD

**Issue by gitmodimo** [fnc12/sqlite_orm#613]
I tried to perform such query using:
```
 select(max(oid<Table>()));
```
However error is thrown due to the fact that serialized query does not contain FROM clause.
I tracked down the issue to method "parse_table_name" not parsing internal::table_oid_t<T> (and similar types)
I fixed it in version 1.5 by implementing overload for internal::table_oid_t:
```
template<class O>
std::set<std::pair<std::string, std::string>> parse_table_name(const internal::table_oid_t <O>&) const {
   std::string alias = {};
   return { std::make_pair(this->impl.template find_table_name<O>(), std::move(alias)) };
}
```
I can see that development version is changed vastly in that matter, but still does not allow query in the title.
This seems like minor change. Can you consider implementing such functionality?
Or is there another(correct) way to perform such query?

**Comment by fnc12** [comment]
Hi. Thanks for reporting this issue. It is hard to track all types of errors. Looks like a bug. There are two ways of fixing it in a quick way:
1) you create a branch from `dev`, fix it and make a PR to `dev`
2) I create a branch from `dev`, fix it and make a PR to `dev`

Either option is good for me. Please tell me what do you like the most? Thanks

**Comment by gitmodimo** [comment]
Option 2 is fine form me. I just needed quick fix for version 1.5 (which I am using at the moment). I don't have much time on my hand at the moment to figure it out in master branch.

**Comment by fnc12** [comment]
Actually the stable version is 1.6 and PR will be merged into `dev`. Is it ok for you?

**Comment by gitmodimo** [comment]
Yes it is. I did not find 1.6 version earlier, but it seems it already is vastly different in terms of "parse_table_name"

**Comment by fnc12** [comment]
yes. Serializing was refactored totally to make it more scalable.

**Comment by fnc12** [comment]
the fix is ready https://github.com/fnc12/sqlite_orm/pull/614 . We are waiting for CI builds and them I shall merge it

**Comment by fnc12** [comment]
merged. Please check it out in `dev` branch

**Comment by gitmodimo** [comment]
Wow that was fast! Works great now.
Thanks

śr., 14 paź 2020 o 16:44 Yevgeniy Zakharov <notifications@github.com>
napisał(a):
