### ISSUE TITLE
C++17 Support

### ISSUE THREAD

**Issue by meghasemim1999** [fnc12/sqlite_orm#616]
hi
should i do any thing for this library to be buildable in c++17?
i changed my c++ version to c++17 and it lead to a lot of compile errors
is there any HEADER to define or smth else?

my erros look like this:

'sqlite_orm::internal::table_t<T,Cs...> sqlite_orm::make_table(const std::string &,Cs...)': could not deduce template argument for 'T' 

'sqlite_orm::internal::column_t<O,T,const T&(__cdecl O::* )(void) const,void(__cdecl O::* )(T),Op...> sqlite_orm::make_column(const std::string &,T O::* ,Op...)': could not deduce template argument for '<unnamed-symbol>'

**Comment by fnc12** [comment]
everything must work as is. C++17 configurations are being built every time once a new PR appears just like C++14 ones. What is your compiler? Paste a piece of your code which results to this error. Thanks

**Comment by meghasemim1999** [comment]
it's ok now. thanks.
