### ISSUE TITLE
How do I create a prepared statement that is bound later?

### ISSUE THREAD

**Issue by undisputed-seraphim** [fnc12/sqlite_orm#628]
I would like to create a prepared statement that is not bound to anything at first.
`SELECT EXISTS (SELECT 1 FROM users WHERE name == ?)`

So I suppose the syntax is
```
auto pstmt = storage.prepare(select(
  exists(
    select(1, where(
      is_equal(&User.name, std::string())
    )
  )
);
```

How do I bind `?` to different strings later?
I can see from the examples that `get<0>(pstmt) = some_string;`, but I get a very long compile error.
Sorry, but it is very difficult to try to see what is wrong during compilation, too many errors involving very long type-names.
It is also somewhat hard to see what tuple offset maps to which variables.
Some clearer examples or documentation on this will be helpful.

**Comment by fnc12** [comment]
you can bind any dummy data at first and them rebind it. One thing you need to preserve: types of bound arguments. If you still have issues please paste you code here.

**Comment by undisputed-seraphim** [comment]
I'm getting a `error: no matching function call to <long type name>` no matter what value I put for `get<N>(pstmt)`.
I have trouble identifying the right `N` to use, or if the problem exists elsewhere in the code.

Here is a simplified version of what I want to do
```
struct Entry {
  int id;
  std::string prefix;
  std::string name;
};

auto create_table() { return make_storage( /* Table with Entries */ ); }
using table_t = decltype(create_table());

// SELECT EXISTS (SELECT 1 FROM entries WHERE prefix = ?
auto prepare_check_exists(table_t& table) {
  return table.prepare(
    select(
      exists(
        select(1, where(
          is_equal(&Entry::prefix, std::string())
        )
      )
    )
  );
}

// Assign the prepared statement to a member variable
// Use it somewhere in the code
bool prefix_exists(const std::string& prefix) }
  std::get<N>(m_pstmt_check_exists) = prefix;
  return table.execute(m_pstmt_check_exists);
}
```
(There's actually a bit more to the code, this is a simplified version)

So I get a compile error at `std::get<N>` where no numbers work. I can't tell what I'm supposed to put there lol

**Comment by undisputed-seraphim** [comment]
Oh ok, I see... I should not be using `std::get<>` , there is a sqlite_orm specific overload for `get<>`

**Comment by fnc12** [comment]
nice. Is the issue actual?

**Comment by fnc12** [comment]
Please show me your code.

**Comment by fnc12** [comment]
@undisputed-seraphim is the issue actual?

**Comment by undisputed-seraphim** [comment]
Sorry for the lack of response. I'm testing some code now to see if it works.
