### ISSUE TITLE
can I include as a column of a select an is_null() function?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#629]
Something like (though it does not compile):

auto rows = Storage::getStorage().select(is_null(&Transaccion::fkey_account_other), &Transaccion::fkey_account_other);

Is there a way to get true or false depending on the nullness of a column?

Regards,
Juan Dent

**Comment by fnc12** [comment]
how would you write it with raw SQL?

**Comment by juandent** [comment]
maybe something like this:

SELECT  ifnull(Transaccion.fkey_account_other, -1) from Transaccion

**Comment by juandent** [comment]
but I can't find the scalar function ifnull in sqlite_orm...

**Comment by juandent** [comment]
How about this::

```c++
auto rows = Storage::getStorage().select(columns( coalesce<int>(&Transaccion::fkey_account_other, -1), (&Transaccion::fkey_concepto)));
```
it works!

**Comment by juandent** [comment]
It works like a charm with coalesce!
Thanks for forcing me to look into the raw SQL!!

**Comment by juandent** [comment]
what if we have this:

```c++
	auto otherlines = Storage::getStorage().select(columns(
		alias_column<als_t>(&Transaccion::fkey_account_other),
		alias_column<als_t>(&Transaccion::fkey_account_own),
		alias_column<als_a>(&Account::id_account),
		alias_column<als_b>(&Account::id_account)),
		left_join<als_a>(on(c(alias_column<als_t>(&Transaccion::fkey_account_other)) == alias_column<als_a>(&Account::id_account))),
		inner_join< als_b>(on(c(alias_column<als_t>(&Transaccion::fkey_account_own)) == alias_column<als_b>(&Account::id_account))));

```

and a row contains a NULL value in Transaccion::fkey_account_other?? the alias_column<als_a>(&Account::id_account) displays a 0 but it should contain a NULL! The left_join did not find a corresponding Account row for the Transaccion::fkey_account_other is NULL!

Can't use coalesce because Account::id_account is not null - it displays a value (0)...

**Comment by juandent** [comment]
Sorry it does work!!! -- excuse me I tried it and it works ... coalesce does the job with this code:

```c++
	auto otherlines = Storage::getStorage().select(columns(
		alias_column<als_t>(&Transaccion::fkey_account_other),
		coalesce<int>(alias_column<als_t>(&Transaccion::fkey_account_other), -1),
		alias_column<als_t>(&Transaccion::fkey_account_own),
		coalesce<int>(alias_column<als_a>(&Account::id_account), -1),
		alias_column<als_b>(&Account::id_account)),
		left_join<als_a>(on(c(alias_column<als_t>(&Transaccion::fkey_account_other)) == alias_column<als_a>(&Account::id_account))),
		inner_join< als_b>(on(c(alias_column<als_t>(&Transaccion::fkey_account_own)) == alias_column<als_b>(&Account::id_account))));
```

marvelous library

**Comment by fnc12** [comment]
`ifnull` isn't implemented right now. Core functions implementation status can be observed in [wiki](https://github.com/fnc12/sqlite_orm/wiki/Core%2C-aggregate-and-date-functions). I shall add its' support soon.
`coalesce` returns 0 cause you specify `<int>` as returned value and `int` isn't nullable. Specify `std::optional<int>` then it will return `std::nullopt` in case nothing found.
