### ISSUE TITLE
VS2017 x86 build failed

### ISSUE THREAD

**Issue by alexly** [fnc12/sqlite_orm#63]
hello,

I have the following errors when building sqlite_orm
https://i.gyazo.com/95587fceec7f7af8269a1b3d6f8bc1e2.png

SQLITE_VERSION        "3.21.0"

**Comment by fnc12** [comment]
Please show me `make_storage` function call

**Comment by alexly** [comment]
struct KeyValue {
	std::string key;
	std::string value;
};

auto& getStorage() {
	using namespace sqlite_orm;
	static auto storage = make_storage("key_value_example.sqlite",
		make_table("key_value",
			make_column("key",
				&KeyValue::key,
				primary_key()),
			make_column("value",
				&KeyValue::value)));
	return storage;
}

**Comment by fnc12** [comment]
This is weird. Could show me please contents of `main_context_impl.cc` file?

**Comment by alexly** [comment]
main_context_impl.cc like this:
..
#include "orm_model.h"
..
these errors disappear when I remove this line

**Comment by fnc12** [comment]
I still don't understand. Please show `orm_model.h` file contents and `main_context_impl.cc`

**Comment by alexly** [comment]
orm_model.h

#pragma once

#include <sqlite_orm/sqlite_orm.h>
#include <iostream>

using std::cout;
using std::cerr;
using std::endl;

/**
*  This is just a mapped type. User doesn't have to interact with it directly.
*/
struct KeyValue {
	std::string key;
	std::string value;
};

auto& getStorage() {
	using namespace sqlite_orm;
	static auto storage = make_storage("key_value_example.sqlite",
		make_table("key_value",
			make_column("key",
				&KeyValue::key,
				primary_key()),
			make_column("value",
				&KeyValue::value)));
	return storage;
}

in the file main_context_impl.cc a lot of code. but this code does not use anything from header orm_model.h.

I get this error just by plugging the header orm_model.h

**Comment by fnc12** [comment]
What line number error points? Your initial screenshot describes almost nothing. Sorry but I cannot understand your code yet.

**Comment by alexly** [comment]
Morning Yevgeniy, 

It is very strange. Today I prepared a test project, but it was built without problems.Then I recompiled my source project and there is also the problem disappeared. 

Thank you for your work and sorry for the trouble.

**Comment by fnc12** [comment]
Morning. That's cool. Good luck using Visual Studio
