### ISSUE TITLE
compile failed when struct inherit

### ISSUE THREAD

**Issue by ozil-cao** [fnc12/sqlite_orm#632]
sometimes we have some same columns in different tables,and we can put them in a base struct.    and others can derive from it.
for example
```
struct TbBase {
    int id;
    bool deleted;
};

struct XUser : TbBase {
    std::string firstName;
    std::string lastName;
};

 auto storage = sqlite_orm::make_storage("local.db",
                                            make_table("tb_xuser",
                                                    make_column("id", &XUser::id, autoincrement(), primary_key()),
                                                    make_column("deleted", &XUser::deleted),
                                                    make_column("first_name", &XUser::firstName),
                                                    make_column("last_name", &XUser::lastName)
                                                      ));
    storage.sync_schema();
    XUser user;
    user.id = 2;
    user.firstName = "Mark";
    user.lastName = "Jason";
    user.deleted = false;
    auto insertedId = storage.insert(user);
```
but it did't work, some error happened when I try to compile,here is the error message:
```
sqlite_orm.h:11653: error: static_assert failed due to requirement 'tuple_helper::has_type<XUser, std::__1::tuple<TbBase> >::value' "type is not mapped to a storage"
        static_assert(tuple_helper::has_type<O, mapped_types_tuples>::value,
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/sqlite_orm.h:6641: error: no member named 'get_impl' in 'sqlite_orm::internal::storage_impl<>'
        return this->super::template get_impl<O>();
               ~~~~                  ^
```
I run on mac os 10.15.3  with  clang-1103.0.32.62   
what can I do to make it correct ?

**Comment by fnc12** [comment]
this happens cause storage thinks that you want to store `TbBase` not `XUser`. The way it defines the type it very simple: type of struct of a member pointer passed into the first `make_column` call. Specify type explicitly to avoid this misunderstanding:
```c++
 auto storage = sqlite_orm::make_storage("local.db",
                                            make_table<XUser>("tb_xuser",
                                                    make_column("id", &XUser::id, autoincrement(), primary_key()),
                                                    make_column("deleted", &XUser::deleted),
                                                    make_column("first_name", &XUser::firstName),
                                                    make_column("last_name", &XUser::lastName)
                                                      ));
```

**Comment by ozil-cao** [comment]
Thanks, It works fine for me!
but I still have some troubles here

```
struct TbBase {
    int id;
    bool deleted;
};

struct XUser: public TbBase {
    std::string firstName;
    std::string lastName;
   
   //declare a getter here
    int getId() const {
        return  id;
    }
};

auto storage = sqlite_orm::make_storage("local.db",
                                            make_table<XUser>("tb_xuser",
                                                    make_column("id", &XUser::id, autoincrement(), primary_key()),
                                                    make_column("deleted", &XUser::deleted),
                                                    make_column("first_name", &XUser::firstName),
                                                    make_column("last_name", &XUser::lastName)
                                                      ));

//did't work
auto lessThan5 = storage.get_all<XUser>(where(c(&XUser::id) < 5));

```
some error happened as follows,because of ```id```  is declared in ```TbBase```
sqlite_orm.h:6616:29: error: no member named 'column_name' in 'sqlite_orm::internal::storage_impl<>'
        return this->super::column_name(m);
               ~~~~         ^
I'd solved this problem  as follows, replace id with getId which delclared in XUser .
```
//It's fine ,because of getId is delclared in XUser
auto lessThan6 = storage.get_all<XUser>(where(c(&XUser::getId) < 6));
```
any other good idea here ?

**Comment by fnc12** [comment]
Use this.
```c++
auto lessThan5 = storage.get_all<XUser>(where(column<XUser>(&XUser::id) < 5));
```
Cause C++ compiler thinks that `&XUser::id` is actually `&TbBase::id`.

**Comment by ozil-cao** [comment]
It works fine, No problems anymore .
Your help was very much appreciated !

**Comment by DarkArkantos** [comment]
Hi!
Is this solution still working?
```cpp
auto lessThan5 = storage.get_all<XUser>(where(column<XUser>(&XUser::id) < 5));
```
I tried to use that one, but there's an error when I place `==`.
### My code:
`BinEntry` -> DerivedClass;
`&BinEntry::value` -> Defined in base class

```cpp
this->storage_->get_all<BinEntry>(where<BinEntry>(column<BinEntry>(&BinEntry::value) == bin), limit(1));
```

The error is the following

`No operator matches these operands  operand types are: sqlite_orm::internal::column_pointer<db::models::lists::BinEntry, std::string db::models::lists::BaseValueEntry::*> == std::string`

no known conversion for argument 1 from `‘sqlite_orm::internal::column_pointer<db::models::lists::BinEntry, std::__cxx11::basic_string<char> db::models::lists::BaseValueEntry::*>’`

Am I missing something else? 🤔

Tried also:

`this->storage_->get_all<BinEntry>(where<BinEntry>(column<BinEntry>(&BinEntry::value).field == bin), limit(1));``

Thank you so much!

**Comment by fnc12** [comment]
try adding `using namespace sqlite_orm;` inside the scope before line with `==`

**Comment by DarkArkantos** [comment]
It's already there, actually. 🤔
This is the whole method
```cpp
BinEntry BinRepository::find_entry(std::string bin) {
				using namespace sqlite_orm;
				auto result = this->storage_->get_all<BinEntry>(where<BinEntry>(column<BinEntry>(&BinEntry::value) == bin), limit(1));				
				if (result.size() == 0) {
					errors::print_error(__FILE__, "Entry not found", __func__);
					BinEntry entry_result;
					return entry_result;
				}
				auto data = result.at(0);
				
				return data;
			}
```

**Comment by fnc12** [comment]
try `dev` branch. I have already fix some operators usage. If it fails I'll fix it. Thanks

**Comment by DarkArkantos** [comment]
Alright sir. Thank you so much for your help. I'll give it a try.

**Comment by DarkArkantos** [comment]
Hi!
I tried using dev branch but it stills presenting the same error. I'll go for repeating code in child classes in the meantime while the fix comes out.
I'll be looking after any update, thank you so much. It's a really nice library! :D

**Comment by fnc12** [comment]
@DarkArkantos you are right. The problem exists. But it is not related to inheritance but using of explicit column `column<BinEntry>(&BinEntry::value)`. It does not work with comparison operators (my bad). Let me fix it today.

**Comment by fnc12** [comment]
@DarkArkantos fix is here https://github.com/fnc12/sqlite_orm/pull/742. Let's wait for unit tests builds and merge it (tomorrow).

**Comment by fnc12** [comment]
@DarkArkantos merged into `dev` branch. Please check it out
