### ISSUE TITLE
Inheritance is not supported

### ISSUE THREAD

**Issue by 305236917** [fnc12/sqlite_orm#634]
struct A
	{
		int Id;
		string Name;
	};

	struct B : A
	{
		string Extern;
	};

	auto ts = 
		make_storage("Storage.db",
			make_column("Id", &B::Id, primary_key()),
			make_column("Name", &B::Name),
			make_column("Extern", &B::Extern)
		);

//Compile failed

**Comment by fnc12** [comment]
`make_storage` does not accept `make_column` calls but accepts `make_table` instead. Please correct your `make_storage` call.

**Comment by 305236917** [comment]
thanks a lot, it works..
