### ISSUE TITLE
foreign key

### ISSUE THREAD

**Issue by 305236917** [fnc12/sqlite_orm#640]
I want to create a database with a foreign key like this:
	struct A
	{
		int a;
	};

	struct B : A
	{
		int b;
	};

	struct C
	{
		int c;
	};

	auto ts =
		make_storage("TS",
			make_table("C",
				make_column("c", &C::c, primary_key())
			),
			make_table("AB",
				make_column("b", &B::a, primary_key()),
				make_column("b", &B::b),
				foreign_key(&B::b).references(&C::c).on_delete.cascade()
			)
		);
	ts.sync_schema(true);

but it compiled failed.

**Comment by fnc12** [comment]
@305236917 is everything good?
