### ISSUE TITLE
stricter registration of fields in a table?

### ISSUE THREAD

**Issue by denzor200** [fnc12/sqlite_orm#645]
How about this?
```c++
#include <sqlite_orm/sqlite_orm.h>

using namespace sqlite_orm;

struct User {
  std::string username;
  std::string password;
  bool isActive;
};

struct User2 : User {};
struct User3 : User {};

int main() {
  auto storage = make_storage(
      "storage.sqlite", ///

      /// ALL RIGHT: all fields were registered
      make_table("users", ///
                 make_column("username", &User::username, primary_key()),
                 make_column("password", &User::password),
                 make_column("isActive", &User::isActive)),

      /// ALL RIGHT: 'isActive' field were ignored, other fields were registered
      make_table("users2", ///
                 make_column("username", &User2::username, primary_key()),
                 make_column("password", &User2::password),
                 ignored(&User2::isActive)),

      /// FAILED: 'isActive' field was skipped
      make_table("users3", ///
                 make_column("username", &User3::username, primary_key()),
                 make_column("password", &User3::password))

  );
  return 0;
}
```
compatibility with the previous version will be lost a little .. But I think it's worth it.

**Comment by fnc12** [comment]
Thanks for submitting this.
Two questions:
1) what profit we will get?
2) how to implement this?

**Comment by denzor200** [comment]
1. On a large number of tables, it is very easy to miss the "make_column" and suffer sitting in the debugger (
2. It is not easy, but it is possible. Let's take a look at the "pfr" library, implemented in pure C ++ 14, with no additional dependencies. I believe that we can repeat.
https://github.com/boostorg/pfr

**Comment by fnc12** [comment]
1. It will be fixed in this https://github.com/fnc12/sqlite_orm/issues/450 . Probably you'll like it more
2. prf looks like `magic_get` by Anton Polukhin from yandex company. This is a great library and Anton is a brilliant C++ coder but there is not need to add `magic_get`'s functionality in `sqlite_orm` if we can solve it using codegen.

**Comment by denzor200** [comment]
Ok. I have no answers
