### ISSUE TITLE
Several different sqlite3 dlls in one application?

### ISSUE THREAD

**Issue by denzor200** [fnc12/sqlite_orm#646]
```c++
#include <sqlite_orm/sqlite_orm.h>

using namespace sqlite_orm;

struct User {
    std::string username;
    std::string password;
    bool isActive;
};

static int my_sqlite3_open(
  const char *filename,
  sqlite3 **ppDb)
{
	// TODO: implement this
	return 0;
}

static int my_sqlite3_exec(
  sqlite3*,
  const char *sql,
  int (*callback)(void*,int,char**,char**),
  void *,
  char **errmsg)
{
	// TODO: implement this
	return 0;
}

static int my_sqlite3_close(sqlite3*)
{
	// TODO: implement this
	return 0;
}

int main()
{
	auto api = std::make_tuple( ///
		my_sqlite3_open,
		my_sqlite3_exec,
		my_sqlite3_close
		// TODO: more sqlite3 calls..
		);
		
	/// storage object with my api
    auto storage = make_storage("storage.sqlite", api, ///
        make_table("users", ///
            make_column("username", &User::username, primary_key()),
            make_column("password", &User::password),
            make_column("isActive", &User::isActive)));
			
	/// storage object with the default api
    auto storage_defapi = make_storage("storage_defapi.sqlite", ///
        make_table("users", ///
            make_column("username", &User::username, primary_key()),
            make_column("password", &User::password),
            make_column("isActive", &User::isActive)));
	
    return 0;
}
```

**Comment by fnc12** [comment]
why? Do you really have several different sqlite3 binaries linked to your main binary?

**Comment by denzor200** [comment]
For example, it would be useful to have several libraries with different values of the SQLITE_THREADSAFE macro. In some cases, reliability is important, and in others, performance is important.

**Comment by fnc12** [comment]
But you can have different libraries already now. And you can use different sqlite libraries with different `sqlite_orm` storages.
Also I am still interested do you really have a project with more than one sqlite3 lib linked to?

**Comment by fnc12** [comment]
@denzor200 is the issue actual?

**Comment by denzor200** [comment]
> And you can use different sqlite libraries with different sqlite_orm storages

I don't know how. Please, can you tell me?

> Also I am still interested do you really have a project with more than one sqlite3 lib linked to?

No, I want to experiment with that. There are suggestions that this will take root in my project

**Comment by fnc12** [comment]
> I don't know how. Please, can you tell me?

It is very weird practice and is not desired at all. Assume you have two different cpp files. They are compiled to two different translation units. Either of these units can be linked against different binaries even if these binaries have the same functions. You need to learn about static libraries compiling (it is not so complicated actually) and linking. But again: this technique is not desired so I don't understand practical usage of initial issue. 

> No, I want to experiment with that. There are suggestions that this will take root in my project

As I said these experiments will not help anyone. The only advantage is that you will get some XP. So there is no need to apply such changes in `sqlite_orm`. But you can perform these changes in your fork if you want of course.

**Comment by denzor200** [comment]
Ok. Thanks for your time.
