### ISSUE TITLE
Rollback error handler

### ISSUE THREAD

**Issue by denzor200** [fnc12/sqlite_orm#647]
Let's give as an example the code for executing a certain transaction using _**sqlite_orm**_.
```c++
using TStorage = std::decay_t<decltype(storage)>;
using TMethSign = int (TStorage::*)(const TObject&);

/// Doing the main logic..
auto guard = storage.transaction_guard();
storage.template remove_all<TObject>();
std::transform(objects.begin(),
			   objects.end(),
			   std::back_inserter(ids),
			   std::bind((TMethSign)&TStorage::insert, &storage, _1));
guard.commit();
```
This code is pretty cool, but let's imagine such a situation as "none of the application modules has the right to stop the application in the event of any external error without prior notification of other modules". This is a normal situation for background daemons that run 24/7.
It turns out that we cannot use `transaction_guard` in this context, because errors from the `rollback` lead to a rude `std::terminate`.. It's a shame.

Let's take a look at my solution implemented by means of the current _**sqlite_orm**_.
```c++
static void rollback_error_handler()
{
	// TODO: perform the steps to prepare the state of the application to stop
}

try
{
	try
	{
		/// Doing the main logic..
		storage.begin_transaction();
		storage.template remove_all<TObject>();
		std::transform(objects.begin(),
					   objects.end(),
					   std::back_inserter(ids),
					   std::bind((TMethSign)&TStorage::insert, &storage, _1));
		storage.commit();
	}
	catch (...) ///< something from the main logic went wrong..
	{
		storage.rollback();
	}
}
catch (...) ///< rollback went wrong..
{
	rollback_error_handler();
	/// just keep going.. The application will be stopped in the future
}
```
This code is scary but it works. 
### My suggestion is
What if the `transaction_guard` was extended a little so that a similar task could be solved with an elegant design?
```c++
static void rollback_error_handler()
{
	// TODO: perform the steps to prepare the state of the application to stop
}

try
{
	/// Doing the main logic..
	auto guard = storage.transaction_guard();
	guard.set_fire_handler(&rollback_error_handler);
	storage.template remove_all<TObject>();
	std::transform(objects.begin(),
				   objects.end(),
				   std::back_inserter(ids),
				   std::bind((TMethSign)&TStorage::insert, &storage, _1));
	guard.commit();
}
catch (...) ///< something from the main logic went wrong..
{
	/// just keep going.. The application will be stopped in the future
}
```
I can suggest an implementation if interested.
PS: we can go even further and make it look like `std::set_new_handler`

**Comment by fnc12** [comment]
The idea is nice. How you'd implement this?

**Comment by denzor200** [comment]
I will describe in more detail in the near future

**Comment by denzor200** [comment]
I would start with this destructor implementation. This is already enough for most cases.
```
~transaction_guard_t() {
  try {
    if (this->gotta_fire) {
      if (!this->commit_on_destroy) {
        this->rollback_func();
      } else {
        this->commit_func();
      }
    }
  } catch (...) {
    if (!this->fire_handler)
      throw; ///< no hanlder.. act by default - continue to spin up the stack to std::terminate

    this->fire_handler(); ///< perform the steps to prepare the state of the application to stop
    /// just keep going.. The application will be stopped in the future
  }
}
```
But, if we need the ability to retry, the implementation will have to be a little more complicated.
```
~transaction_guard_t() {
  while (true) {
    try {
      if (this->gotta_fire) {
        if (!this->commit_on_destroy) {
          this->rollback_func();
        } else {
          this->commit_func();
        }
      }
      break; ///< just keep going.. execution was successful
    } catch (...) {
      if (!this->fire_handler)
        throw; ///< no hanlder.. act by default - continue to spin up the stack to std::terminate

      if (this->fire_handler()) ///< perform the steps to prepare the state of the application to STOP or RETRY
        continue; ///< another try requested
      break; ///< just keep going.. The application will be stopped in the future
    }
  }
}
```
Here we see that the custom `fire_handler`, in addition to preparing to stop the application, can also prepare for another iteration. But do we really need this retry? While this question remains open

PS: it's a bad idea - like std::set_new_handle. Not our case

**Comment by fnc12** [comment]
The first implementation will call `fire_handler` if `rollback_func` or `commit_func` (i.e. user code) will throw an exception. This is weird cause you talk only about rollback case. I think that the best way of implementing it is finding out this feature in SQLite and then adapt it in `sqlite_orm`. Also adding `while (true)` is not what transaction guard is about. It guards a transaction and that is all. I know that adding `white (true)` in any program will make it loop infinitely one day for sure.
BTW libsqlite3 has commit and rollback hooks https://www.sqlite.org/c3ref/commit_hook.html.
So we can adapt these API to work like this:
```c++
auto storage = make_storage(...);
storage.commit_hook([]{
    // do anything..
    return 0;    //  return 0 to make commit or not zero to make a rollback operation
});
storage.rollback_hook([]{
    //  do anything, nothing to return here..
});
```
What do you think?

**Comment by denzor200** [comment]
I got acquainted with sqlite3_commit_hook and sqlite3_rollback_hook. Do they register error handlers? As i undestand, they are called before normal execution of rollback

**Comment by fnc12** [comment]
Yes `sqlite3_rollback_hook` is called on every rollback: both on explicit rollback called by you and implicit called by sqlite. You can set a hook right before executing a query that can fire implicit rollback and reset a hook right after this query. Or you can keep a bool flag to indicate that implicit rollback is expected.

**Comment by fnc12** [comment]
@denzor200 what do you think about idea I wrote about 9 days ago here? It is ok or you'd like it another way?

**Comment by fnc12** [comment]
@denzor200 is the issue actual?

**Comment by denzor200** [comment]
> @denzor200 is the issue actual?

We will return to discussing this issue as soon as https://github.com/fnc12/sqlite_orm/issues/676 is resolved.

**Comment by fnc12** [comment]
@denzor200 is the issue actual?

**Comment by fnc12** [comment]
Closing cause it is not required due to discussion
