### ISSUE TITLE
Without rowid

### ISSUE THREAD

**Issue by denzor200** [fnc12/sqlite_orm#654]
The `_without_rowid` parameter only affects the `insert` method. This parameter does not apply to `insert_range`. Is this expected?

**Comment by denzor200** [comment]
statement serializator for `insert`:
https://github.com/fnc12/sqlite_orm/blob/dev/include/sqlite_orm/sqlite_orm.h#L10710
statemente serializator for `insert_range`:
https://github.com/fnc12/sqlite_orm/blob/dev/include/sqlite_orm/sqlite_orm.h#L10832

**Comment by fnc12** [comment]
It looks like a bug

**Comment by denzor200** [comment]
Ok, i will fix it in separate PR

**Comment by denzor200** [comment]
Fixed.
https://github.com/fnc12/sqlite_orm/pull/655

**Comment by fnc12** [comment]
@denzor200  thanks. I've merged it a minute ago.
