### ISSUE TITLE
How to make select's result field optional?

### ISSUE THREAD

**Issue by Overlordff** [fnc12/sqlite_orm#656]
I have some data model:
```cpp
struct Bond {
    // ...
    double coupon;
};
```
And have scheme:
```cpp
make_table("bond", make_column("coupon", &Bond::coupon))
```
Now I write some query with `LEFT JOIN`:
```cpp
select(columns(&Bond::coupon, ... ),
       left_join<...>(...))
```

When I write `left_join`  I expect that some rows doesn't match the "on" predicate and column `coupon` will be `NULL` in the result table.
So, i want to see `std::optional<double>` in result tuple with `std::nullopt` values when `NULL`. But I got `double` type and `0.0` values instead.  How to tell sqlite_orm that type need to be optional when selecting from joined result table?

My current workaround is something like this:
```cpp
select(columns(coalesce<std::optional<double>>(&Bond::coupon, nullptr)), ... ),
       left_join<...>(...))
```
`coalesce` return type is `std::optional<double>` so result type in tuple is correct.

**Comment by Overlordff** [comment]
Also, I need to write `nullptr` in `coalesce` even I work with `std::optional`. I want to write `std::nullopt`. It looks like a bug.

**Comment by fnc12** [comment]
When you select `&Bond::coupon` you get `decltype(Bond::coupon)` e.i. `double`. If you change Bond's coupon type to optional then you'll get an optional as result. But it is not the best solution. Using `coalesce` is correct cause it is why it was created.
Please show me the example of writing `nullptr ` in `coalesce` cause I cannot understand what you are talking about. Thanks

**Comment by Overlordff** [comment]
> Please show me the example of writing `nullptr ` in `coalesce` cause I cannot understand what you are talking about. Thanks

I found test case that fails (1.6 release):
```cpp
struct Foo
{
	double field;
};

auto test_storage = make_storage("test_storage.sqlite",
                                 make_table("foo", make_column("field", &Foo::field)));
auto test_statement = test_storage.prepare(select(coalesce<std::optional<double>>(&Foo::field, nullptr))); // OK
auto test_statement2 = test_storage.prepare(select(coalesce<std::optional<double>>(&Foo::field, std::nullopt))); // FAILED
```

**Comment by Overlordff** [comment]
> When you select &Bond::coupon you get decltype(Bond::coupon) e.i. double

May be provide some way to explicit set result type? Something like this:
```cpp
auto st = storage.prepare(select(columns(&Asset::shortName,
                                         &Asset::currency,
                                         as_nullable(&Bond::coupon)), // doesn't change SQL query, just C++ type of result.
                                left_join<Bond>(on(c(&Asset::id) == &Bond::asset_id))));
auto result = storage.execute(st);

using row_type = decltype(result)::value_type;
using coupon_type_in_result_row = std::tuple_element_t<2, row_type>; // The third column in the result table
static_assert(std::is_same<coupon_type_in_result_row, std::optional<double>>::value);
```
`coalesce` seems like a crutch in this case.

**Comment by Overlordff** [comment]
Also, I think the best way is to deduce all columns that come from joined table (`Bond` in my case) as `std::optional<T>` because they really can be `NULL` in the result table. But I'm not sure that it can be implemented in general case.

**Comment by fnc12** [comment]
> > Please show me the example of writing `nullptr ` in `coalesce` cause I cannot understand what you are talking about. Thanks
> 
> I found test case that fails (1.6 release):
> 
> ```c++
> struct Foo
> {
> 	double field;
> };
> 
> auto test_storage = make_storage("test_storage.sqlite",
>                                  make_table("foo", make_column("field", &Foo::field)));
> auto test_statement = test_storage.prepare(select(coalesce<std::optional<double>>(&Foo::field, nullptr))); // OK
> auto test_statement2 = test_storage.prepare(select(coalesce<std::optional<double>>(&Foo::field, std::nullopt))); // FAILED
> ```

Oh man. You're right. Let me fix it. Thanks

> > When you select &Bond::coupon you get decltype(Bond::coupon) e.i. double
> 
> May be provide some way to explicit set result type? Something like this:
> 
> ```c++
> auto st = storage.prepare(select(columns(&Asset::shortName,
>                                          &Asset::currency,
>                                          as_nullable(&Bond::coupon)), // doesn't change SQL query, just C++ type of result.
>                                 left_join<Bond>(on(c(&Asset::id) == &Bond::asset_id))));
> auto result = storage.execute(st);
> 
> using row_type = decltype(result)::value_type;
> using coupon_type_in_result_row = std::tuple_element_t<2, row_type>; // The third column in the result table
> static_assert(std::is_same<coupon_type_in_result_row, std::optional<double>>::value);
> ```
> 
> `coalesce` seems like a crutch in this case (because it changes SQL query).

No. Let me explain it. First let's imagine how the same task can be solved in raw SQLite. SQLite has a schema like this:
```sql
CREATE TABLE foo (field NUMERIC NOT NULL)
```
Consider `NOT NULL` constraint. It is added always when member is not nullable (`double` in your case). Without this rule we will meet ambiguous behavior: in both cases when databases stores 0 and NULL we'd get `double(0)`. So when we run
```c++
auto rows = storage.select(columns(&Foo::field));
```
we actually run
```sql
SELECT field
FROM foo
```
and cannot have NULL in results on SQLite level. So adding ability to specify null expectation is weird.
So if you want to select or get null there are special SQL functions for it: `COALESCE` and `iFNULL`. So everything works right cause in raw SQL you'd right the same code.

**Comment by Overlordff** [comment]
When we use `LEFT JOIN` - `NOT NULL` constraint has no effect. You have considered case with one simple select, but I'm talking about select + left join!

For example, we have the DB:
```sql
CREATE TABLE IF NOT EXISTS "Author" (
	"id" INTEGER NOT NULL,
	"Name" TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Book" (
	"id" INTEGER NOT NULL,
	"Title" TEXT NOT NULL,
	"author_id" INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("author_id") REFERENCES "Author"("id")
);
INSERT INTO "Author" ("id","Name") VALUES
 (1,'Dostoevsky'),
 (2,'Tolstoy'),
 (3,'Chekhov'),
 (4,'Joanne Rowling');
INSERT INTO "Book" ("id","Title","author_id") VALUES
 (1,'War and Peace',2),
 (2,'Crime and Punishment',1),
 (3,'Harry Potter',4);
```

We make a query:
```sql
SELECT a.id, a.Name, b.id, b.Title, b.author_id FROM Author a
LEFT JOIN Book b ON a.id = b.author_id
```

And got the result:
![image](https://user-images.githubusercontent.com/17942815/106401545-bce37680-6435-11eb-981b-f14635ebb871.png)
All fields in my scheme are `NOT NULL`, but  i got `NULL` values in columns from joined table. That's what I'm talking about.

Now, if I want to make the same query via sqlite_orm i will write something like this:
```cpp
select(columns(&Author::id, &Author::name, &Book::id, &Book::Title, &Book::author_id)
       left_join<Book>(on(c(&Author::id) == &Book::author_id)));
```
And no type in result tuple is optional. There are just default constructible values instead of `NULL` in the third row.

**Comment by Overlordff** [comment]
I hope you understand me now :-)

**Comment by Overlordff** [comment]
The main problem is that when we use `sqlite_orm::left_join` we can't detect where it is really `NULL` value, and where it is "default constructed" values, for example empty string or 0 integer because the all will be "default constructed" in the result tuples. May be I use `left_join` incorrectly, but I can't find good way to set correct type in the result tuple.

Again, i think use `coalesce` to explicitly set correct type is a crutch because it changes SQL query.

**Comment by fnc12** [comment]
Oh man looks like you're right. I've never thought that SQLite can make such a trick with NULL. So it means that I understand you and it looks like that your initial suggestion about `select` function column nullability has its meaning.
Your idea about `as_nullable` is good but I'd like to name it `as_optional` cause `nullable` is very common word and there are more than one nullable classes (e.g. `std::unique_ptr`) in C++ but optional is only one. Calling `as_optional` inside `columns` functions or inside `select` without `columns` (in case we need only one column) will change result type from `T` to `std::optional<T>`. And it also will work on C++17 and higher cause `std::optional` is available in C++17 and higher. It will make people to migrate from C++14 to C++17 faster. What do you think?

**Comment by Overlordff** [comment]
> SQLite can make such a trick with NULL

It is common feature of `OUTER` joins in SQL (`LEFT JOIN` means `LEFT OUTER JOIN`). They write `NULL` if row from joined table doesn't match predicate in `ON` expression. If we used just `JOIN` which means `INNER JOIN`, we would not get `NULL` values (because not matched rows would not be included in result table).

I have already wrote how I see the best solution:
https://github.com/fnc12/sqlite_orm/issues/656#issuecomment-770381380
But it  is obviously a breaking change...

> What do you think?

The approach with explicitly setting optional columns in select suits me personally. I don't mind using `as_optional ` name and only `std::optional` type support.

Should I split this issue on 2 different for your convenience?
1) Bug with `coalesce` and `std::nullopt`
2) New `as_optional` function

**Comment by fnc12** [comment]
I think one issue is enough. I shall fix both cases soon. Thanks

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/pull/657 nullopt bindings https://github.com/fnc12/sqlite_orm/pull/657. Please add yourself as reviewer if you wish to.

**Comment by fnc12** [comment]
@Overlordff please review https://github.com/fnc12/sqlite_orm/pull/658

**Comment by Overlordff** [comment]
Cool, when is the release planned?

**Comment by fnc12** [comment]
IDK. In a month or two. I need to add enough features to make a release. If you can't wait probably you want to use `dev` branch in your project?

**Comment by Overlordff** [comment]
I can't use dev branch (cause I use your library via vcpkg), but I can wait. So, no problem.

I have finished review and have tested locally, so u can close this issue.

**Comment by fnc12** [comment]
Thank you. And thanks for your help.
