### ISSUE TITLE
Add support for sqlite triggers

### ISSUE THREAD

**Issue by fmichaut-dev** [fnc12/sqlite_orm#659]
Hello,

I wanted to use [SQlite triggers](https://sqlite.org/lang_createtrigger.html).
But I realised that there is no such feature in sqlite_orm, is it something that you plan to integrate in the library ?

**Comment by fnc12** [comment]
Hello. Triggers exist in the [todo list](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md). Triggers is a great feature. It was added to the todo list a long time ago but it was unable to complete before prepared statements existence. But now it is available to do it. I think it will be done in the nearest future. The plan for the nearest release is user defined functions and triggers. BTW if you would like to do it by yourself you are welcome.

**Comment by surajmitsel** [comment]
Hello, I am looking for the SQlite triggers so can you update if is it still under TODO list or under progress

**Comment by fnc12** [comment]
@surajmitsel hello. It is in todo list right now. When I start implementing it I'll add `in progress` label here and write a comment about it.

**Comment by fmichaut-dev** [comment]
Hello, I started to work on it yesterday, but I am wondering how the interface should look like from a user point of view @fnc12 ?

Should the create_trigger function return a trigger object to pass to the make_storage function as for make_table ?
Or should there be a function inside the storage base class to call like `storage.create_trigger(...)` ?
Or maybe a static function that has nothing to do with the storage at all ?

**Comment by fnc12** [comment]
Hello. Triggers are a part of schema so I see it like this:
```c++
auto storage = make_storage(path,
                            make_trigger(...)
                            make_table(...)...);
```
and they must be created inside `sync_schema` call as tables and indexes

**Comment by fmichaut-dev** [comment]
Hello, 
Sorry for the delay, I was busy a lot lately

I'm gonna make `make_trigger` work in the same way as the `make_table` as you suggested.
I was going with a signature like this :
```c++
make_trigger(name, 
             trigger_timing_ /* BEFORE|AFTER|INSTEAD_OF */, 
             trigger_type /* DELETE|INSERT|UPDATE */, 
             table, 
             statements...)
```
I am just wondering if you prefere `table` to be just a string or a `internal::table_t` (returned by `make_table`) ?
 
Also, how do I generate the `sqlite_orm/sqlite_orm.h` file from all the includes in the `dev/` folder ?
I looked everywhere for instructions and I only found mention of `/build/cmake/README.md` inside `CONTRIBUTING.md` but the mentioned README file doesn't exists anymore

**Comment by fnc12** [comment]
> Also, how do I generate the sqlite_orm/sqlite_orm.h file from all the includes in the dev/ folder ?
```
python third_party/amalgamate/amalgamate.py -c third_party/amalgamate/config.json -s .
```

> I am just wondering if you prefere table to be just a string or a internal::table_t (returned by make_table) ?

No strings if it is possible. If you need to specify table just pass it as a template argument `<User>`. If you need to pass a column just pass a member pointer `&User::id`.

If you can please make API look the same way as SQL. This is how `sqlite_orm` is built.

**Comment by fmichaut-dev** [comment]
Hello, I had some time yesterday so I did some progress
I'm still having trouble wrapping my head around the whole codebase (and trying not to reinvent the weel)

Could you take a look at the [draft pull request I just made](https://github.com/fnc12/sqlite_orm/pull/861) and give me some preliminary feedback on the API / implementation ?

There is only one part missing. If we take a look at the sqlite trigger syntax, what is missing is the red rectangle shown here (the trigger statements to be executed) : 
![image](https://user-images.githubusercontent.com/33881730/144934966-12d3c717-69bc-4bd8-885f-ec168bb33369.png)

I am wondering if I can reuse some of the existing code or if I need to implement 4 new insert/update/select/delete function just for the triggers ?
I saw the prepared_statement insert/update functions, and I tried to use them, but without success.

If you could give me some insight about wich structs / functions I should use, that would be very helpful.

**Comment by fnc12** [comment]
yes red rectangle can be implemented with ready `sqlite_orm::update`, `sqlite_orm::insert`, `sqlite_orm::remove` and `sqlite_orm::select` non member functions. Actually prepared statements were also designed to make dedicated code entities for triggers in future. How I see API:
```c++
make_trigger("my_trigger", before().delete_().on<User>().for_each_row().begin(update(/* update statement is here */)).end())
// or
make_trigger("my_trigger", after().insert().on<User>().when(is_equal(...)).begin(insert(/* insert statement is here */)).end())
// or
make_trigger("my_trigger", instead_of().update_of(&User::name, &User::id).on<User>().for_each_row().begin(remove(/* remove statement is here */)).end())
```
About your code: it is a very nice code. But please replace enums with enum classes. Enum usage is prohibited here cause enums cause name collisions.

**Comment by fmichaut-dev** [comment]
Okay, so how do I use the prepared statements ? 

I've tried to use it like that (I didn't change the API yet) : 
```cpp
// trigger.h
internal::trigger_t<St, S...>
make_trigger(const std::string &name, trigger::trigger_timing_t timing, St type, S... statements) {
    return {name, timing, type, true, nullptr, std::forward<S>(statements)...};
}

// trigger_test.cpp
Test a{"test_trigger", 1, 2};
make_trigger(
            "test_trigger", trigger::after(), trigger::on_update(table_test, &Test::y, &Test::x, &Test::text),
            sqlite_orm::update(a)
)
        
// somewhere in statement_serialisator.h
  C c{context.impl};

  c.replace_bindable_with_question = true;
  ss << "BEGIN ";
  iterate_tuple(statement.stmts, [&ss, &c](auto &v) {
    ss << serialize(v, c) << ";";
  });

  ss << " END";
  std::cout << ss.str() << std::endl;
```
Outputs: 
`CREATE TRIGGER IF NOT EXISTS 'test_trigger' AFTER UPDATE OF 'sql_y', 'sql_x', 'sql_text' ON 'test' FOR EACH ROW BEGIN INSERT INTO 'test' ("sql_text", "sql_x", "sql_y") VALUES (?, ?, ?); END`

**Comment by fnc12** [comment]
functions `update`, `insert`, `remove` and `select` return special objects `update_t`, `insert_t`, `remove_t` and `select_t` respectively.  And all these types can be serialized using `serialize` function. So let `begin` function accept template T object and store it

**Comment by fmichaut-dev** [comment]
In the example I showed you, I am using the `serialize` function on the return value of `insert` function (stored in `.stmts` in the example).
I call the `serialize` function with a context where I set `replace_bindable_with_question` to `true`. Also tried with `false`.

I always end up with `BEGIN INSERT INTO 'test' ("sql_text", "sql_x", "sql_y") VALUES (?, ?, ?); END`, how do I get the question marks replaced ?

**Comment by fnc12** [comment]
`replace_bindable_with_question` must be false. Also it looks like that `replace_bindable_with_question` support isn't implemented everywhere. It is got to be implemented also

**Comment by fnc12** [comment]
@fmichaut-dev if you like we can make a zoom call and I can help you with API making

**Comment by fmichaut-dev** [comment]
Sounds good
You can send me an email so we can schedule a time

**Comment by fnc12** [comment]
@fmichaut-dev please use raw insert: it supports serialization without question marks out of box. More info [here](https://github.com/fnc12/sqlite_orm/wiki/Raw-insert). So there is no need to change basic CRUD insert serialization cause binding must be added later to your feature cause BLOB will not work otherwise. If you have any questions please feel free to ask

**Comment by fmichaut-dev** [comment]
So it means that users will only be able to use triggers with `raw_insert` ?
Isn't that a bit contraining ?

**Comment by fnc12** [comment]
Just for now for you to make sure that you do everything right. Once it is done you'll refactor it with question marks and everything will work with all types of statement
