### ISSUE TITLE
Test for static assertions

### ISSUE THREAD

**Issue by denzor200** [fnc12/sqlite_orm#661]
Do we need tests that will confirm that static assertions will work at the right time? Many C ++ templating libraries have tests like this, why not.

**Comment by fnc12** [comment]
What exactly are you talking about? Static tests are being tested not straight but classes used inside static asserts are tested too. Or you are talking about catching build errors?

**Comment by denzor200** [comment]
Build error is always better than runtime error - it's a fact.
As yet _sqlite_orm_ is able to detect **not** so many invalid cases at compile time. And we can follow each `static_assert` manually and make sure that it really throws an build error. But in the future, when there will be a lot of static asserts, it will become impossible to follow them manually.

**Comment by fnc12** [comment]
Yes you are right. How would you like to improve it?

**Comment by denzor200** [comment]
The first thing that comes to mind. Write a utility that accepts the path to the directory in which the cpp files with invalid code are located. Call the compiler for each file and parse the compiler output.

**Comment by denzor200** [comment]
I will need to see how this is done in all sorts of well-known libraries, for example, boost

**Comment by fnc12** [comment]
This type of tests is called environmental tests. Of course it will make code safer. But there is easier way: encapsulate static assert inside a class and cover it with static tests. But of course if you write environmental tests it will be the best way.

**Comment by fnc12** [comment]
@denzor200 environmental tests are not going to be implemented so there is no reason to keep this issue open. Do you have other questions related to it?

**Comment by fnc12** [comment]
currently static tests perform the same logic: they test not static asserts firing but value of expressions written inside static assets. This is almost the same but is cheaper. If someone wants to implement real environmental tests you are welcome.
