### ISSUE TITLE
Add Support,Read Open Db

### ISSUE THREAD

**Issue by zhongguo1987** [fnc12/sqlite_orm#662]
At present, ORM can only create a new database and does not support operations on existing databases

**Comment by fnc12** [comment]
> At present, ORM can only create a new database and does not support operations on existing databases

No it work with existing databases as well from the very first commit.

**Comment by fnc12** [comment]
@zhongguo1987 is the issue actual?

**Comment by zhongguo1987** [comment]
> @zhongguo1987 is the issue actual?

Which open the database using **SQLite3_ open**，But this function, according to the official instructions, creates a new one when the database file does not exist, so it is not good to determine whether the specified database file exists at present. Or there is a way to know whether the specified database file exists or not.

**Comment by fnc12** [comment]
You can check whether file exists before accessing it with sqlite: https://stackoverflow.com/questions/12774207/fastest-way-to-check-if-a-file-exist-using-standard-c-c11-c

**Comment by fnc12** [comment]
@zhongguo1987 is the issue actual?

**Comment by zhongguo1987** [comment]
> @zhongguo1987 is the issue actual?

Then close it
