### ISSUE TITLE
insert VS insert_range

### ISSUE THREAD

**Issue by denzor200** [fnc12/sqlite_orm#663]
There have some differences between `insert` impl and `insert_range` impl.
1. `insert` checks that each column name isn't a composite column name, but `insert_range` don't.
2. if `columnNames` is empty, then the `DEFAULT` tag will be used instead of list of column names. (only `insert`)

Is it expected?

**Comment by fnc12** [comment]
No. Looks like a legacy bug and got to be fixed if it is available

**Comment by denzor200** [comment]
Too much copypasting.. Why we just can't collapse `insert` and `insert_range` into shared implementation?

**Comment by fnc12** [comment]
We can and we need to do it. It is a legacy code.

**Comment by denzor200** [comment]
Ok, i will make PR

**Comment by fnc12** [comment]
thank you
