### ISSUE TITLE
Default value for integer primary key

### ISSUE THREAD

**Issue by denzor200** [fnc12/sqlite_orm#664]
Is this a bug or is it incorrectly written code by the user? 
```c++
struct User {
  int id;
  std::string name;
};

auto storage = make_storage(
    "primary_key_def.sqlite",
    make_table("users", ///
               make_column("id", &User::id, default_value(100)),
               make_column("name", &User::name, default_value("dummy_name")),
               primary_key(&User::id, &User::name)));
storage.sync_schema();
storage.remove_all<User>();

const auto id = storage.insert<User>({-1, ""}); ///< id is always 1
const auto user = storage.get<User>(id);        ///< error: Not found
```
I can't imagine who might need this in real code. I reproduced this when I wrote the test.

**Comment by fnc12** [comment]
I tried to reproduce it in raw SQLite client:
```sql
CREATE TABLE users (
    id INTEGER NOT NULL DEFAULT 100,
    NAME TEXT NOT NULL DEFAULT 'dummy_name'
);
INSERT INTO users (name)
VALUES ('');
SELECT last_insert_rowid();
```
Two notes:
1) this is how `DEFAULT` works in SQLite
2) `storage_t::insert` returns `last_insert_rowid` no matter what happened before.

It does not look like a bug cause raw SQLite works the same way. If someone faces such an issue then he/she must know what is he/she doing.

**Comment by denzor200** [comment]
Ok. No answers.
