### ISSUE TITLE
Creating a multi condition where clause

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#668]
Hi,

I am stuck. I have 3 different optionales conditions to be included in a where clause, they are filter by doctor and/or filter by patient and/or filter by date depending which are currently selected values (i.e. if there is a doctor selected  in a combobox or a patient selected in a combobox...). A non compiling sample follows:

```C++
auto start = GetDate(m_start_date);
	auto end = GetDate(m_end_date);


	auto whereStatement = c(alias_column<als_c>(&Claim::start_date)) >= start
		&& c(alias_column<als_c>(&Claim::start_date)) <= end;

	auto doctor = m_doctoresCB.current();
	auto paciente = m_pacientesCB.current();


	// auto doctor_id = doctor ? doctor->id : -1;

	std::optional<int> doctor_id = std::nullopt;

	if(doctor)
	{
		doctor_id = doctor->id;
	}
	
	auto doctorWhere = c(alias_column<als_c>(&Claim::fkey_doctor)) == doctor_id.value_or(0);

	std::optional<int> patient_id = std::nullopt;

	if(paciente)
	{
		patient_id = paciente->id;
	}

	auto pacienteWhere = c(alias_column<als_c>(&Claim::fkey_patient)) == patient_id.value_or(0);

	auto compoundWhere = whereStatement && doctorWhere && pacienteWhere;
```

could using NULL help in this case? what is the result  condition of NULL && conditionA && conditionB?
or another approach all together ?

I am stuck plesase lend me a hand here...

Did I explained my intent correctly and clearly?

**Comment by fnc12** [comment]
> what is the result condition of NULL && conditionA && conditionB?

You can always know by opening any SQLite editor (`sqlite` shell in unix shell or GUI editor like https://sqliteman.dev). Adding `NULL` into condition will make it always false. Just try to call `SELECT 1` -> you will get `1`, try `SELECT 1 WHERE NULL` -> you will get 0 rows.

If you want to have optional conditions use bool flags. The same issue you have already created before amigo https://github.com/fnc12/sqlite_orm/issues/272. Please you the same technique here. If you still have questions please feel free to post it here.

**Comment by juandent** [comment]
Got it!!!! Of course!

Thanks...   how is the other issue coming along?

**Comment by fnc12** [comment]
I am sorry I did not write new code for foreign key issue. I shall do it in a week.
