### ISSUE TITLE
Avoid extra copies by specifying values per column at insertion time

### ISSUE THREAD

**Issue by andrei-datcu** [fnc12/sqlite_orm#670]
Given the following model 
```
struct BigFatModel {
    std::vector<char> blobCol;
};
```

how can I avoid an extra copy when I have the blob data stored as a `std::span` (or even as an `std::string`) and I don't want to create a `BigFatModel` instance just for the sake of db insertion? So, I know I can do this

```
void storeInDb(const std::string& bigData)
{
     storage.insert(BigFatModel{std::vector<char>(bigData.begin(), bigData.end())});
}
```

is there any possibility to do something like this

```
void storeInDb(const std::string& bigData)
{
     storage<BigFatModel>.insert(values(value_for<BigFatModel::blobCol>({bigData.data(), bigData.size()})...));
}
```
?

**Comment by fnc12** [comment]
You can replace `std::vector<char>` with other type and add bindings to tell `sqlite_orm` how to insert and select this type. E.g. `std::span` or whatever. [Enum binding example](https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp) shows exactly what I am talking about. The same way people use to allow `sqlite_orm` work with `QString` also

**Comment by andrei-datcu** [comment]
I ended up making my own special container, using it in `BigFatModel` and binding it per your suggestion. Having `std::span` directly in the model was not an option because somebody has to own the data.
