### ISSUE TITLE
Assemble prepared statement from parts?

### ISSUE THREAD

**Issue by ArpadBalika** [fnc12/sqlite_orm#671]
Is it possible to?...

I would like to mimic the following thing in sqlite_orm:
I have a "base" query string something like this:
    SELECT %s
    cols...
    FROM Table
    INNER JOIN Something AS Alias ON ... = ...
    %s %s
    ORDER BY time DESC

3 placeholders get changed dynamically:
1.: LIMIT somenumber or no limit at all based on user decision
2.: WHERE (if the user decides to query without it, it would be omitted)
3.: details of the WHERE part

- If I use default constraints like LIMIT unsigned long max, and in the where part from "beginning of time" to "end of the world" it could work, but it would slow down every query right?

- I can make prepared statements for each case, duplicating tons of lines of code, but it would be performant.

- Third approach would be mimicking the the sql command string assembling by sqlite_orm. This third would be the most elegant: DRY and performant, but I do not know if it is possible and how.
How I imagine it: making a prepared statement, saving it as auto preparedStatement then modifying this preparedStatement later when I already know the further details of the query.

**Comment by fnc12** [comment]
Actually prepared statement has only one constant string query value in raw SQLite. Just try it without `sqlite_orm` to see that it is true. Preparation of statement is a compilation process performed by SQLite engine and initial query value cannot be altered. All you can do is to make a cute query with maximum cases and bind bool flags to make some conditions on or off. Same thing was described here https://github.com/fnc12/sqlite_orm/issues/272 . About LIMIT: yes you need to bind 0 and a very large value. Also it will not affect query cause all comparisons are cheap.

**Comment by ArpadBalika** [comment]
First of all, I am grateful for your work!

I have 3 things that can change in the query.
1.: LIMIT: this is no longer an issue, because you said it is cheap.
2.: WHERE part1: table.colX BETWEEN datetimeTEXT1 AND datetimeTEXT2
3.: WHERE part2: table.colY IN {vector of int values}
relation between the two parts of the WHERE is constant AND.

Another question emerged while I have been fooling around:
It is not clear how can I implement a select with multiple inner joins and aliases like that, because the examples are much simpler (some complex examples would be really helpful):
SELECT
SiteSource.HostName AS SourceHostName,
DeviceSource.DeviceName AS SourceDeviceName,
SiteTarget.HostName AS TargetHostName,
DeviceTarget.DeviceName AS TargetDeviceName
FROM ...
INNER JOIN Site AS SiteSource ON Actions.SourceHostNo = SiteSource.HostNo "
INNER JOIN Device AS DeviceSource ON Actions.SourceHostDeviceNo = DeviceSource.DeviceNo "
INNER JOIN Site AS SiteTarget ON Actions.TargetHostNo = SiteTarget.HostNo "
INNER JOIN Device AS DeviceTarget ON Actions.TargetHostDeviceNo = DeviceTarget.DeviceNo "

One last thing: Is it possible to...
ORDER BY something1 DESC, something2 ASC

**Comment by fnc12** [comment]
> First of all, I am grateful for your work!

Thank you. I am glad this project fits you.

```c++
where( (not betweenFlag and between(&Actions::StopTime, "strStartTime", "strStopTime")) and (not inFlag and in(&Actions::FilterNo, {1,2,3,4,5})))
```
looks correctly. Just try it.

> It is not clear how can I implement a select with multiple inner joins and aliases like that, because the examples are much simpler (some complex examples would be really helpful):

Just write inner joins as is using `inner_join` function. API is built to be very clear: `inner_join` function accepts type as a table to join and `on` condition as argument. You can place several different joins one by one just like you do in SQL. All argument you pass in `select` and `get_all` functions are serialized in SQL in the same order to make everything clear during writing and reading your code. Also some old closed issues had examples with 3 joins and they worked well. Just try it. If you have any problem please feel free to write it here - we shall fix it easily.

> One last thing: Is it possible to...
> ORDER BY something1 DESC, something2 ASC
> I saw examples with single order by param, but no examples with multiple order by params.

This feature exists and called `multi_order_by`. There is no example for it (my bad) but you can find the usage in [unit tests](https://github.com/fnc12/sqlite_orm/blob/master/tests/tests3.cpp).

**Comment by ArpadBalika** [comment]
Many thanks!
Everything works like a charm, except the inner join supplemented with alias.
I cannot get my head around it, how to make this happen in sqlite_orm.
Example query containing only the questionable parts:
`SELECT
    SiteSource.HostName AS SourceHostName,
    SiteTarget.HostName AS TargetHostName,
FROM ...
INNER JOIN
	Site AS SiteSource ON Actions.SourceHostNo = SiteSource.HostNo
INNER JOIN
	Site AS SiteTarget ON Actions.TargetHostNo = SiteTarget.HostNo`

If you could provide me a snippet regarding this example, it would be more than welcome!

**Comment by fnc12** [comment]
@ArpadBalika please provide struct declaration and `make_storage` call to let me understand your schema. Thanks

**Comment by ArpadBalika** [comment]
Finally I managed to get it done by studying the self_join.cpp and the custom_aliases.cpp examples.
In case somebody else is in my shoes and wondering how to do it:

I made some custom alias structs:
`
struct SourceHostName : sqlite_orm::alias_tag
{
	static const std::string &get()
	{
		static const std::string res = "SourceHostName";
		return res;
	}
};

struct TargetHostName : sqlite_orm::alias_tag
{
	static const std::string &get()
	{
		static const std::string res = "TargetHostName";
		return res;
	}
};

template <class T>
struct SiteSourceAlias : sqlite_orm::alias_tag
{
	using type = T;

	static const std::string &get()
	{
		static const std::string res = "SiteSource";
		return res;
	}
};
using SiteSource = SiteSourceAlias<Site>;

template <class T>
struct SiteTargetAlias : sqlite_orm::alias_tag
{
	using type = T;

	static const std::string &get()
	{
		static const std::string res = "SiteTarget";
		return res;
	}
};
using SiteTarget = SiteTargetAlias<Site>;
`

After that, the actual prepared select statements looks like this (unneccessary things removed, only the interesting part remained):
`
auto queryStatement = storage->prepare(
		select(columns(
			as<SourceHostName>(alias_column<SiteSource>(&Site::HostName)),
			as<TargetHostName>(alias_column<SiteTarget>(&Site::HostName)),
		inner_join<SiteSource>(on(c(&Actions::SourceHostNo) == alias_column<SiteSource>(&Site::HostNo))),
		inner_join<SiteTarget>(on(c(&Actions::TargetHostNo) == alias_column<SiteTarget>(&Site::HostNo))),
...
`

**Comment by fnc12** [comment]
@ArpadBalika good work! Is the issue actual?

**Comment by ArpadBalika** [comment]
Thanks, everything is fine now, I am closing it. Have a nice day!
