### ISSUE TITLE
get<>(where(...)) is not compiling for me - probably a syntax isssue 

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#672]
Please help I am stuck!!

I have the following line which does not compile

```C++
auto resp_line = storage.get<INSResponseLine>(where(c(alias_column<als_k>(&INSResponseLine::fkey_factura)) == invoice->id));
```

compiler errors are:

error C2039: 'bind': is not a member of 'sqlite_orm::statement_binder<field_type,void>'
error C2039: '__this': is not a member of 'sqlite_orm::statement_binder<field_type,void>'

What am I doing wrong?

Regards
Juan

**Comment by fnc12** [comment]
You are using API incorrectly. `storage.get` function expects id(s) as arguments like:
```c++
auto object = storage.get<INSResponseLine>(5);  // 5 is pk column value
```
If you want to use `WHERE` condition please use `storage.get_all` function instead:
```c++
auto objects = storage.get_all<INSResponseLine>(where(c(alias_column<als_k>(&INSResponseLine::fkey_factura)) == invoice->id));
```

**Comment by juandent** [comment]
thanks!!
