### ISSUE TITLE
sum() forces me to get the value of the sum by reference making my text formatting unoperable

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#673]
I have

```C++
auto otherlines = Storage::getStorage().select(columns(
		alias_column<als_i>(&Invoice::id),
		sum(alias_column<als_i>(&Invoice::amount))),
		where(t));
```
To present the value in a grid I use this code:

```C++
const auto& value = std::get<Col>(z[row]);
Cstring cs = format(value);

// where format is this method:

	template<typename T>
	static CString format(T&& t)
	{
		return Util::to_cstring(std::forward<T>(t));   // t
	}

// and the Util::to_cstring is a function with 9 overloads
// but no overloads coud convert all the argument types!
// this only appears when I use sum() in the SQL query
``` 

where z is the vector of tuples...

Errors: 
'Util::to_cstring': none of the 9 overloads could convert all the argument types

what type is returned by std::get<Col>(z[row]);? where Col refers to the sum column of the query?

**Comment by juandent** [comment]
A simplified code:

```C++
auto otherlines = Storage::getStorage().select(columns(
		alias_column<als_i>(&Invoice::id),

		sum(alias_column<als_i>(&Invoice::amount))),
		where(true));

	long count = otherlines.size();
	if(count>0)
	{
		auto line = std::move(otherlines[0]);
		auto&& val = std::get<1>(line);
		using ValueType = decltype(val);
		static_assert(std::is_same_v<std::unique_ptr<double>&, ValueType>);  // returns false!!!
		auto x = Util::unique_ptr_to_cstring(std::move(val));
		
		CString cs = Util::to_cstring( val);
    } 
``` 

what overloads must I administer to Util::to_cstring?

**Comment by fnc12** [comment]
looks like you don't know the type returned. You always get print it out using `std::cout << typeid(ValueType).name() << std::endl;`. Spoiler: `sum` returns `std::unique_ptr<double>` instead of raw `double> cause `SUM` can return `NULL`

**Comment by fnc12** [comment]
@juandent is the issue actual?

**Comment by fnc12** [comment]
@juandent offtop: what project you use `sqlite_orm` for? I'd like to know if it is not a secret. I want to make a list of projects in library description who uses this lib. Gracias.

**Comment by juandent** [comment]
my project has to do with supplying a connecting layer between two incompatible systems but I am very much stuck!

Maybe you can throw some light, I would appreciate it immensely.

I have a grid displayer template class that works with joined selects really well and displays the rows in a grid. However, now that I want to use sum() its behavior has become useless. The compiler complains that  there is no match with the 10 overloaded functions that transform the fields of the persistent classes into a CString (which is Microsoft's version of a string). These overloaded functions receive parameters by value - I tried adding versions that receive parameters by left reference only to get 1000 errors ssaying that  the call to Util::to_cstring is ambiguous  to overloaded function. So how can I support fields of the type produced by sum() (and yes I know that it returns a unique_ptr<double>).


Let me share some code with you maybe you can shine some light on me (boy do I need it):


the display loop is as follows:

```C++
for (int i = 0; i < lines.size(); ++i)
{
	PrintDataInGrid<0, Container, NumCols>::Apply(i, lines, grid);
}
```

The actual "printing" is accomplished by this struct where the main problem occurs in line X because that gets the value of the tuple element number Col which is fine as long as the element is not a unique_ptr which we know it cannot copy itself  - yes doing a move would work but then I ineed to place many if constexpr() s. Once the value of the field is taken, some formatting is done depending on whether the value is numeric or string. This causes a call to Util::to_cstring which is called from lines B-D.

```C++
template<int Col, typename Container, unsigned NumCols>
	struct PrintDataInGrid
	{
		static void Apply(int row, const Container& z, CJDGridCtrl& grid)
		{
			// auto value = std::get<Col>(z[row]);                                                  ////    LINE X
			auto&& value = extractValue(std::get<Col>(z[row]));
			
			using ValueType = decltype(value);

			CString cs;

			if constexpr (std::is_integral_v<ValueType> || std::is_floating_point_v<ValueType>)
			{
				grid.m_sortingFunctions[Col + 1] = Util::Comparison::Money;

				if( ColonesCols::template found<Col+1>() )
				{
					Util::Colones c(value);
					cs = format(c);                                                                          //// Line A
				}
				else if ( DollarsCols::template found<Col+1>() )
				{
					Util::Dolares d(value);
					cs = format(d);                                                                       //// Line B
				}
				else
				{
					cs = format(value);                                                                //// line C
				}
			}
			else
			{
				grid.m_sortingFunctions[Col + 1] = Util::Comparison::Text;
				cs = format(value);                                                                         /// line D
			}
			grid.SetItemText(row + 1, Col + 1, cs);
			PrintDataInGrid<Col+1, Container, NumCols>::Apply(row, z, grid);
		}
	};
```

The format functions are as follows:

```C++
	template<typename T>
	static CString format(T&& t)
	{
		return Util::to_cstring( std::forward<T>( t) );                       ///// Line QQQQQQQQ
	}

	template<typename T>
	static CString format(const std::shared_ptr<T>& t)
	{
		if (t)
		{
			return Util::to_cstring(*t);
		}
		return L"";
	}
```

I tried to deal with this by inventing function extractValue which has overloads as in:


```C++
inline double& extractValue(std::unique_ptr<double>& val)
{
	static double null_value = 0.0;
	if (val)
	{
		return *val;
	}
	return null_value;
}
template<typename T> requires (!std::is_same_v<T, std::unique_ptr<double>&>)
inline static T& extractValue(T& t)
	{
		return t;
	}
template<typename T>
inline static T& extractValue(std::optional<T>& opt)
{
	return *opt;
}
```

This gives the error:

error C2665: 'Util::to_cstring': none of the 10 overloads could convert all the argument types

on line QQQQQQQQ

The overloads are:

```C++
'ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t>>> Util::to_cstring(Util::Dolares)'
'ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t>>> Util::to_cstring(Util::Colones)'
'ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t>>> Util::to_cstring(bool)'
'ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t>>> Util::to_cstring(int)'
'ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t>>> Util::to_cstring(std::chrono::time_point<std::chrono::system_clock,date::days>)'
'ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t>>> Util::to_cstring(double &&)'
'ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t>>> Util::to_cstring(double)'
'ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t>>> Util::to_cstring(std::basic_string<char,std::char_traits<char>,std::allocator<char>>)'
'CString Util::to_cstring(const std::optional<int> &)'
'CString Util::to_cstring<double>(std::unique_ptr<double,std::default_delete<double>> &&)'
```

Please help!!!

Regards,
Juan Dent

**Comment by juandent** [comment]
I solved it!!
Thanks anyway!!

**Comment by fnc12** [comment]
@juandent replace `sum` with `total`
