### ISSUE TITLE
The API with non-throwing overload

### ISSUE THREAD

**Issue by denzor200** [fnc12/sqlite_orm#676]
What if we extend **_sqlite_orm_** API, by simply adding "**The non-throwing overload**" for each public method? Just like `std::filesystem` API, for example:
```
template<class O>
int insert(const O& o); ///< may throw std::system_error. the overload exists in the current sqlite_orm

template<class O, class... Cols>
int insert(const O& o, columns_t<Cols...> cols); ///< may throw std::system_error. the overload exists in the current sqlite_orm

template<class O>
int insert(const O& o, std::error_code& ec); ///< may NOT throw std::system_error. Why we just can't add this overload?

template<class O, class... Cols>
int insert(const O& o, columns_t<Cols...> cols, std::error_code& ec); ///< may NOT throw std::system_error. Why we just can't add this overload?
```
Advantages:
1. It will help us to resolve the issue https://github.com/fnc12/sqlite_orm/issues/647
2. This will favorably affect the entry of new users. Not everyone uses exceptions, unfortunately. Not everyone needs an exception.

**Comment by fnc12** [comment]
Yes I understand. One human before wanted to use this lib but was unable to do this cause of exceptions: their project was compiled without exceptions at all. Your examples look nice but how would you improve `get` API and any other API that has variadic amount of arguments?
There are two reasons why non exceptions API is not implemented in this lib:

1. Making ORM's is a complex task. `insert` function you mentioned has 4 classes of interactions with users: tradition arguments, template arguments, return value and exception that can be thrown. And all of these things are required: we need to provide an object to insert, type of object to insert (it may differ in some cases), we need to get id cause sometimes sqlite can make it for us and we need to handle errors that can occur at any time during sqlite statement execution. All these objectives are made using different of classes of interaction to avoid intersection of them. Intersection of these things will lead to a mess in API and implementation of it. Of course we can add one more argument as out parameter for error code but it will affect all the API existing and future one.
2. There are two c++ languages actually just like python: with exceptions and without. Globally I don't like it. I want c++ to be one and solid. And that is why I must make a choice. So my choice is with exceptions cause exceptions is a regular feature in the most popular languages and people understand how it works easily. Yeah I know that Google has its own c++ code style with prohibited exceptions. But it has zero value cause google's c++ code style looks shitty for me at all.

**Comment by fnc12** [comment]
@denzor200 is the issue actual?
