### ISSUE TITLE
No apparent way to issue PRAGMA commands

### ISSUE THREAD

**Issue by ahupowerdns** [fnc12/sqlite_orm#68]
Thank you so much for sqlite_orm, it is a LOT of fun! Using it for some analysis now that I would otherwise never have been able to do safely.
So question, I need to insert millions of objects quickly, and I'd like to issue things like "PRAGMA synchronous = OFF". 
I have looked for ways to get_db() the handle out of sqlite_orm, but it is not obvious if you can do that from storage_t. I have also looked for something like ::raw_query() but can't find it.
I can also implement this feature, but would like your guidance on where this should 'live'. 

I added a simple pragma() above libversion():
```
        void pragma(const std::string& str) {
            std::shared_ptr<internal::database_connection> connection;
            sqlite3 *db;
            if(!this->currentTransaction){
                connection = std::make_shared<internal::database_connection>(this->filename);
                db = connection->get_db();
                this->on_open_internal(db);
            }else{
                db = this->currentTransaction->get_db();
            }
            int rc = sqlite3_exec(db, ("PRAGMA "+str).c_str(), nullptr, nullptr, nullptr);
            if(rc != SQLITE_OK) {
                auto msg = sqlite3_errmsg(db);
                throw std::runtime_error(msg);
            }
        }
```
Is this an idea?

**Comment by fnc12** [comment]
Hey. Thank you for using the lib. You're right about getting `sqlite*` object - you cannot get it at random time. You can obtain it only with database opening using `on_open` member. `on_open` member os designed for SQLite extensions that require `sqlite*` pointer - not for raw query. Also there is no raw query interface cause `sqlite_orm`'s goal is to make correct queries by using C++ features with no raw query.
The best way to achieve what you want is to add a public function for `synchronous` pragma just like `user_version` function. Something like this:
```c++
    void synchronous(int value) {
            std::shared_ptr<internal::database_connection> connection;
            sqlite3 *db;
            if(!this->currentTransaction){
                connection = std::make_shared<internal::database_connection>(this->filename);
                db = connection->get_db();
                this->on_open_internal(db);
            }else{
                db = this->currentTransaction->get_db();
            }
            std::stringstream ss;
            ss << "PRAGMA synchronous = " << value;
            auto query = ss.str();
            auto rc = sqlite3_exec(db, query.c_str(), nullptr, nullptr, nullptr);
            if(rc != SQLITE_OK) {
                auto msg = sqlite3_errmsg(db);
                throw std::runtime_error(msg);
            }
        }

    int synchronous() {
            std::shared_ptr<internal::database_connection> connection;
            sqlite3 *db;
            if(!this->currentTransaction){
                connection = std::make_shared<internal::database_connection>(this->filename);
                db = connection->get_db();
                this->on_open_internal(db);
            }else{
                db = this->currentTransaction->get_db();
            }
            std::string query = "PRAGMA synchronous";
            int res = -1;
            auto rc = sqlite3_exec(db,
                                   query.c_str(),
                                   [](void *data, int argc, char **argv,char **) -> int {
                                       auto &res = *(int*)data;
                                       if(argc){
                                           res = row_extrator<int>().extract(argv[0]);
                                       }
                                       return 0;
                                   }, &res, nullptr);
            if(rc != SQLITE_OK) {
                auto msg = sqlite3_errmsg(db);
                throw std::runtime_error(msg);
            }
            return res;
        }
```

and use it like this:
```c++
storage.synchronous(0);
```

Only one thing exists I don't know - do we need to call this function every time after database is opened or once per file?

**Comment by fnc12** [comment]
@ahupowerdns you there?

**Comment by fnc12** [comment]
I see that `PRAGMA synchronous` sets value only per connection. So it is gonna be like this: `you call `storage. synchronous(0);` (or any other value) and storage will remember this value and will set it every time connection is opened. Getter `storage. synchronous();` will return value from database. Is it ok?

**Comment by ahupowerdns** [comment]
yes, I think this is super! Perhaps some other pramas will come along that work like this btw, might be worth to generalise this somewhat internally. If I can help or test please let me know!

**Comment by fnc12** [comment]
Hey @ahupowerdns  I got an idea. I'll add `pragma` member to a `storage_t` class with `user_version` and `synchronous` functions. It can be accessed like this:
```c++
storage.pragma.user_version();    //  getter
storage.pragma.user_version(int);    //  setter
storage.pragma.synchronous();    //  getter
storage.pragma.synchronous(int);    //  setter
```

Also other pragmas will be added to `pragma` member's class later.

**Comment by fnc12** [comment]
@ahupowerdns please check out the latest commit. I need your confirmation that the issue is closed. Also take a look at the way pragmas implemented now. Adding new pragma is easy but please don't forget to pull request it to me. Thanks

**Comment by fnc12** [comment]
I just got an idea. I will be more comfortable for library users to user another syntax: 
```c++
storage.pragma.user_version = 1;   // same as storage.pragma.user_version(1); now
int version = storage.pragma.user_version;  // same as storage.pragma.user_version(); now
```
and same way with `synchronous`. The benefits are:
1) syntax looks like sqlite even more
2) ability for adding hint functions just like this:
```c++
storage.pragma.synchronous.off();   // same as storage.pragma.synchronous = 0;
storage.pragma.synchronous.normal();  // same as storage.pragma.synchronous = 1;
//etc..
```
What do you think?

**Comment by ahupowerdns** [comment]
I would definitely not do the assignment syntax. It hides the fact that "things are happening". Actual functions make that very clear, and that is more "the C++ way". I'll check your commit in production now!

**Comment by fnc12** [comment]
@ahupowerdns you're right. Let's leave it in current way

**Comment by ahupowerdns** [comment]
```
 <sqlite_orm.h>
struct Query
{
  std::string src_ip;
  uint16_t src_port;
  uint16_t txn_id;
  uint32_t tv_sec;
  uint32_t tv_usec;
  std::string name;
  uint16_t type;
};

int main(int argc, char** argv)
{
  using namespace sqlite_orm;

   auto storage = make_storage("index.sqlite",
                              make_table("queries",
                                         make_column("tv_sec", &Query::tv_sec),
                                         make_column("tv_usec", &Query::tv_usec),
                                         make_column("name", &Query::name),
                                         make_column("type", &Query::type),
                                         make_column("src_ip", &Query::src_ip),
                                         make_column("src_port", &Query::src_port),
                                         make_column("txn_id", &Query::txn_id))
                              );
  storage.sync_schema();

  storage.pragma.synchronous(0);
  storage.remove_all<Query>();
}

```

**Comment by fnc12** [comment]
@ahupowerdns nice example. I've copied this code to [synchronous](https://github.com/fnc12/sqlite_orm/blob/master/examples/synchronous.cpp) example if you don't mind. Also I've fixed recursive call. Please check it out

**Comment by fnc12** [comment]
@ahupowerdns if everything is ok please close the issue.

**Comment by ahupowerdns** [comment]
works as intended now, thanks!
