### ISSUE TITLE
how to add Null Set  in update_all ?

### ISSUE THREAD

**Issue by bitTalk1** [fnc12/sqlite_orm#682]
Is there NullUpdate type accpeted by  set ?

bool bSetsalary=false;
db.update_all(   set(
                     c(&Employee::address) = "Texas",
                    bSetsalary ? c(&Employee::salary) = 20000.00 : NullUpdate
                     ),
                     where(c(&Employee::age) < 30));

**Comment by fnc12** [comment]
you can pass `nullptr` or `std::nullopt` and it will serialized to query as `NULL`

**Comment by bitTalk1** [comment]
Is there any example in source code ?

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/blob/dev/tests/tests4.cpp#L163

**Comment by fnc12** [comment]
is it clear?

**Comment by bitTalk1** [comment]
thanks. 
done it.
