### ISSUE TITLE
Subquery within FROM clause

### ISSUE THREAD

**Issue by ArpadBalika** [fnc12/sqlite_orm#683]
Hi!
I would like to ask how to make a query where I nest a subquery within the FROM clause.
For example:
```
SELECT
   Sub.Column1, Sub.Column2
FROM
   (
      SELECT
         ...
   ) AS Sub
```
My goal is to create a subquery in the FROM clause of the "outer" query and give an alias name to this subquery to reference it's columns. I found example with WHERE clause only. Thanks!

**Comment by fnc12** [comment]
Hi. Unfortunately it is not implemented right now. It exists in [todo list](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md) as `explicit FROM for subqueries in FROM argument`

**Comment by ArpadBalika** [comment]
Understandable, thanks for reply.
Could you help me make an equivalent query that can be implemented in sqlite_orm?
Here is the original:

```
  SELECT
	  Clients.Client1,
	  Stuff.Stuff1,
	  Thing1, Thing2,
	  UserData.UserData1,
	  Setup.Setup1
	  Stuff.Stuff2,
	  ReportStampFirst, ReportStampLast
	  
  FROM
  (
	SELECT
	ClientID, StuffID, UserDataID, Thing2, Thing1,
	MIN(ReportStamp) AS ReportStampFirst,
	MAX(ReportStamp) AS ReportStampLast
	FROM
	Report
	GROUP BY ClientID, StuffID, UserDataID, Thing2, Thing1
  ) AS Sub
	
  INNER JOIN Clients ON Sub.ClientID = Clients.ClientID
  INNER JOIN Stuff ON Sub.StuffID = Stuff.StuffID
  INNER JOIN UserData ON Sub.UserDataID = UserData.UserDataID
  INNER JOIN Setup ON Stuff.SetupID = Setup.SetupID
```

**Comment by fnc12** [comment]
this query cannot be implemented right now cause of lacking explicit `FROM` feature. But all other features like `INNER JOIN` and aliases are available. FO if you simplify the query to avoid explicit `FROM` then you will be able to implement such a query.

**Comment by ArpadBalika** [comment]
Success, thanks!
