### ISSUE TITLE
sync_schema_simulate with indexed column compile time error

### ISSUE THREAD

**Issue by ArpadBalika** [fnc12/sqlite_orm#687]
I have a database schema that works just fine if I call sync_schema() on it, but if I try to call sync_schema_simulate() it gives compile time error.
I temporarily removed the indexes from the schema then it compiled, however I need my indexes so this is not a solution.
I have a couple of make_unique_index() and make_index() calls before the make_table() calls in my make_storage() statement.

Error	C2039
'get_table_info': is not a member of 'sqlite_orm::internal::index_t<sqlite_orm::internal::indexed_column_t<C>>'
sqlite_orm.h	6592

You can repro it with any simple make_storage call that involves at least one make_index or make_unique_index call.

**Comment by fnc12** [comment]
@ArpadBalika give me the simplest example please

**Comment by ArpadBalika** [comment]
```
	struct Cols
	{
		int Col1;
	};

	auto storage = make_storage("db",
		make_index("IX_Col1", &Cols::Col1),
		make_table("Table",
			make_column("Col1", &Cols::Col1)));

	auto syncSchemaResult = storage.sync_schema_simulate();
```

**Comment by fnc12** [comment]
@ArpadBalika thanks. Let me check it today a little bit later. Then I'll respond.

**Comment by fnc12** [comment]
fix is on its' way https://github.com/fnc12/sqlite_orm/pull/688 . Will be merged once unit tests execution is over

**Comment by fnc12** [comment]
@ArpadBalika merged. Please check out `dev` branch

**Comment by ArpadBalika** [comment]
I tested it like this:
```
	auto syncSchemaResult = storage->sync_schema_simulate();
	for (const auto&[name, status] : syncSchemaResult)
	{
		if (sqlite_orm::sync_schema_result::already_in_sync != status)
		{
			std::cout << name << " is NOT in sync.\n";
		}
		else
		{
			std::cout << name << " is in sync.\n";
		}
	}
```
It works now on my complex schema with many indexes and tables, thanks!
