### ISSUE TITLE
"no member named 'get_impl' in 'sqlite_orm::storage_impl<>'"

### ISSUE THREAD

**Issue by jvhoven** [fnc12/sqlite_orm#69]
Hey, thank you for creating this library first of all. I'm running into a slight problem initializing and storing the Storage object. In another issue it was recommended to use the trick used in [this example](https://github.com/fnc12/sqlite_orm/blob/master/examples/update.cpp#L44:22).

However I run into the error `no member named 'get_impl' in 'sqlite_orm::storage_impl<>'` with the following implementation:

```#ifndef PERSONALWIKI_STORAGE_H
#define PERSONALWIKI_STORAGE_H

#include "sqlite_orm/sqlite_orm.h"
#include "../entry.hpp"

using namespace sqlite_orm;

const std::string DATABASE = "/Users/jeffrey/Documents/test.db";

auto initStorage(const std::string &path) {
    return make_storage(path,
        make_table("entry",
                   make_column("id", &Entry::id, autoincrement(), primary_key()),
                   make_column("name", &Entry::name),
                   make_column("content", &Entry::content)
        )
    );
}

typedef decltype(initStorage("")) Storage;

static std::shared_ptr<Storage> storage;

class StorageService {
public:
    static std::shared_ptr<Storage> getStorage() {
        return std::make_shared<Storage>(initStorage(DATABASE));
    }
};


#endif //PERSONALWIKI_STORAGE_H
```

Where `entry.hpp` contains:

```
#ifndef PERSONALWIKI_ENTRY_H
#define PERSONALWIKI_ENTRY_H

struct Entry {
    int id;
    std::string name;
    std::string content;
};

enum EntryType {
    Web,
    Text
};

#endif
```

---

I'm not the most experienced C++ programmer so I might be doing something silly. Thanks in advance.

**Comment by fnc12** [comment]
Hey. Thanks for using the lib. I've tried to compile your code and it compiled well. I used Xcode 9.1 with clang++. Which compiler and IDE do you use?

**Comment by jvhoven** [comment]
The IDE I'm using is CLion, the compiler I'm compiling it with is `Toolchains/XcodeDefault.xctoolchain/usr/bin/c++`, `Apple LLVM version 9.0.0 (clang-900.0.38)`.

**Comment by jvhoven** [comment]
It had to do with the way I was passing `Entry` for insertion. I was wrapping it in a `std::shared_ptr` but it could (probably) not identify the structure of Entry through that, even when passing it `std::shared_ptr::get()` to unwrap the pointer.

Once again thank you for this terrific library, it makes interfacing with SQLite so much easier :).

**Comment by fnc12** [comment]
@jvhoven you're welcome. Please feel free to post any issue once you got one or ask for any new feature.
