### ISSUE TITLE
insert_range save std::vector<std::unique_ptr<T>>

### ISSUE THREAD

**Issue by spiritEcosse** [fnc12/sqlite_orm#694]
Good day, i have data such type 
```
std::vector<std::unique_ptr<T>>
```

i guess that i cannot use function storage->insert_range ? I thought about writing overloaded operator which returns * std :: unique_ptr it is make sense ?

**Comment by fnc12** [comment]
Good day. One can make an overload for `insert_range` no problem. Will you make a PR or I need to make it?

**Comment by spiritEcosse** [comment]
I would be only glad, however in my project cmake max 3.11, and in master sqlite_orm min 3.16

**Comment by fnc12** [comment]
I think it would be better to add a universal overload which will accept two iterators and transformer object just like std::transform does. This will allow to call insert_range with any container type: std::optional or whatever

**Comment by spiritEcosse** [comment]
yes, it sounds good

**Comment by fnc12** [comment]
API will be like this:
```c++
std::vector<std::unique_ptr<User>> users;
storage.insert_range<User>(users.begin(), user.end(), [](const std::unique_ptr<User> &userPointer) {
    return *userPointer;
});
```
and prepared statement:
```c++
auto statement = storage.prepare(insert_range<User>(users.begin(), user.end(), [](const std::unique_ptr<User> &userPointer) {
    return *userPointer;
}));
```
is it ok?

**Comment by spiritEcosse** [comment]
yes, it sounds good

**Comment by fnc12** [comment]
@spiritEcosse Pr is on its' way https://github.com/fnc12/sqlite_orm/pull/700

**Comment by fnc12** [comment]
@spiritEcosse please check out `dev` branch for new API for `insert_range` and `replace_range`

**Comment by fnc12** [comment]
@spiritEcosse is it actual?

**Comment by spiritEcosse** [comment]
yes, give me time please

**Comment by fnc12** [comment]
damn. Looks like that I forgot to add API to storage class. I've added new API only to prepared statement functions.

**Comment by fnc12** [comment]
@spiritEcosse I've updated `dev`. I have added more unit tests, found and fixed a bug and added `storage.insert_range<T>` and `storage.replace_range<T>` functions. Please check it out

**Comment by spiritEcosse** [comment]
i got error : 
![image](https://user-images.githubusercontent.com/13799508/116724091-e38b5c00-a9e8-11eb-9c1c-f4f0ee0d4bcd.png)

my code
```
std::vector<std::unique_ptr<Host>> container;
m_db->storage->insert_range<Host>(container.begin(), container.end(), [](const std::unique_ptr<Host> &pointer) {
    return *pointer;
});
```

**Comment by fnc12** [comment]
yes. I had it too. It happens cause C++ return value type of your lambda
```c++
[](const std::unique_ptr<Host> &pointer) {
    return *pointer;
}
```
as T not `const T &`. I don't know how to make it work correctly by default. Please add explicit return type:
```c++
[](const std::unique_ptr<Host> &pointer) -> const Host & {
    return *pointer;
}
```

**Comment by spiritEcosse** [comment]
yes, its work ,and i checked 
```
auto statement = storage->prepare(insert_range<T>(begin, end, [](const std::unique_ptr<T> &userPointer) -> const T & {
    return *userPointer;
}));

```

**Comment by spiritEcosse** [comment]
very cool, thanks

**Comment by fnc12** [comment]
@spiritEcosse you are welcome. Thanks for this idea
