### ISSUE TITLE
sqlite_orm::statement_binder<T>::extract(const char*) should be internal only

### ISSUE THREAD

**Issue by andrei-datcu** [fnc12/sqlite_orm#697]
If I'm reading the code correctly, these functions are only used to extract values from `sqlite3_exec` calls (which internally calls sqlite3_column_text). Currently, these are only used to retrieve values in pragma calls and all values are either `int` or `bool`.

Writing an `extract(const char*)` overload should not be mandatory for other types and **is not even possible** for some. Take for instance `std::vector<char>` which is mapped as `BLOB`. The overload that ships with `sqlite_orm` is currently both unused and incorrect: One could have a blob with a 0 in the middle and `sqlite3_column_text` will only add a 0 at the end. Therefore, one cannot retrieve the original full length of the blob by just calling `strlen` as the current implementation does.

My recommendations therefore are:
1) Remove the overload from documentation and from the enum binding examples
2) don't use that overload in the pragma calls
3) static_assert and warn users that 1) has happened and they should remove their unused code.

**Comment by fnc12** [comment]
great idea. I have added this initially cause it was used widely. Not it is redundant and incorrect in blob's case - you are right. Thanks for advice. I'll fix it. Or you can do it by yourself

**Comment by fnc12** [comment]
@andrei-datcu the reason why `sqlite_orm::statement_binder<T>::extract(const char*)` is still public cause it can become required to override in custom specializations if pragma has any values with custom types. Now it does not exist and you can skip this function. But later it can change. Anyway it must not make any problems skipping this function implementation in your specializations so nothing needs to be done.
