### ISSUE TITLE
Inserting a `std::string` with embedded null terminators results in data loss

### ISSUE THREAD

**Issue by SuperV1234** [fnc12/sqlite_orm#703]
Consider a storage like this one:

```cpp
auto storage = make_storage("ohdb.sqlite",
    make_table("users",
        make_column("id", &User::id, autoincrement(), primary_key()),
        make_column("passwordHash", &User::passwordHash)
    )
);
```

If I have a user like this:

```cpp
std::string hash = getHash(somePassword);
User user{-1, hash};
```

Where `hash` is a `std::string` containing an embedded byte with value `0` (e.g. `8 21 -5 -36 -120 10 -99 53 74 -105 0 -68 108 127 -84 -122 8`)

And then insert it:

```cpp
storage.insert(user);
```

Then the data in the string after the embedded null terminator will be lost. Only the `8 21 -5 -36 -120 10 -99 53 74 -105` bytes will be placed into the database.

**Comment by fnc12** [comment]
`std::string` is not designed for this. Actually you can store a null terminator in the middle of `std::string` due to bug in `std::string`. Replace `std::string` with correct blob class, bind it to `sqlite_orm` just like in `enum` examples and everything will work fine

**Comment by fnc12** [comment]
@SuperV1234 is the issue actual?

**Comment by fnc12** [comment]
@SuperV1234 is the issue actual?

**Comment by SuperV1234** [comment]
I've replaced `std::string` with `std::vector<char>`, and it works. I'm not sure what the correct behavior for `sqlite_orm` should be but that's up to your to decide. Thanks!

**Comment by fnc12** [comment]
@SuperV1234 you are welcome. Thanks
