### ISSUE TITLE
How to write  a simple select in sqlite_orm?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#705]
The SQL version is SO SIMPLE:

```SQL
select fkey_INSResponse = 1, number from Invoices
```

I tried this:
```C++
		is_equal(c(alias_column<als_i>(&Invoice::fkey_INSResponse)),1)),
```

as part of a `storage.select(columns( ....` but it does not compile!!

Please help!!!

**Comment by fnc12** [comment]
looks like we need to add support for this. This is very old and not popular case which is not supported. I'll add it in a few days. Thanks

**Comment by juandent** [comment]
great news!!

**Comment by fnc12** [comment]
@juandent please check out `dev` branch

**Comment by juandent** [comment]
Please help as to downloading dev branch.
So far I do 

```
git clone https://github.com/fnc12/sqlite_orm.git dev_sqlite_orm
cd dev_sqlite_orm
git checkout dev
```

but I get 

C:\Components\dev_sqlite_orm>git checkout dev
fatal: 'dev' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate

**Comment by juandent** [comment]
Downloaded dev branch
Where is the sample code?

**Comment by fnc12** [comment]
code is the same you wrote. Case is that this code `storage.select(is_equal(&Invoice::fkey_INSResponse, 1));` led to compile error before. Now it compiles well. Just try it

**Comment by juandent** [comment]
Works like a charm, thank you!!

**Comment by fnc12** [comment]
you are welcome
