### ISSUE TITLE
How to use in multi-threaded mode?

### ISSUE THREAD

**Issue by NewYaroslav** [fnc12/sqlite_orm#707]
Hey! I am unable to use the library in multi-threaded mode

After creating the database, I do the following methods
```
storage.open_forever();
storage.pragma.journal_mode(journal_mode::WAL);
storage.busy_timeout(10);
storage.sync_schema();
```
A separate stream periodically records:
```
storage.transaction([&]() mutable {
    for (const Tick& t : transaction_buffer) {
        storage.replace(t);
    }
    return true;
});
```

The main thread is trying to read data
```
first_tick = storage.get_all<Tick>(
                            where(c(&Tick::timestamp) <= timestamp_ms),
                            order_by(&Tick::timestamp).desc(),
                            limit(1));
```

This causes the program to crash.

If you add a mutex to the code to eliminate the possibility of simultaneous reading and writing, then it will be impossible to read after writing. Reading will hang.

Plus, if a library can't read while writing, what's the point of WAL?

**Comment by NewYaroslav** [comment]
I tried with all the options SQLITE_THREADSAFE (0,1,2)

**Comment by fnc12** [comment]
`sqlite_orm` does nothing about multithreading. If you have multithreaded issues using `sqlite_orm` then you'd have the same issues if you use raw libsqlite3 library. To eliminate this issue just google how to use libsqlite3 in multithreaded environment and use `sqlite_orm` as is. `sqlite_orm` is just a frontend for SQLite3: it does not manage threads or data for you. It just takes AST you provided, serializes it to a raw string SQL and sends it to SQLite3 engine.

**Comment by NewYaroslav** [comment]
I don't know how your library works internally. Here is what I found while looking for why reads are blocked while writing in WAL mode:
https://web-answers.ru/c/bd-sqlite-s-wal-zablokirovana-pri-podgotovke-quot.html
https://stackoverflow.com/questions/1680249/how-to-use-sqlite-in-a-multi-threaded-application

> check if you have sqlite3_reset after every sqlite3_step because this is one of the cases that leads to a database lock error.
> after preparing a statement with sqlite3_prepare and executing it with sqlite3_step, you must always reset it with sqlite3_reset.
> 
> Sqlite3_reset (S) interface resets prepared statement S back to
> the beginning of his program.
> 
> hope this solves your problem ... !!!

> Your sqlite3_step, sqlite3_prepare and some other calls may return SQLITE_BUSY or SQLITE_LOCKED. SQLITE_BUSY usually means that sqlite needs to acquire the lock. The biggest difference between the two return values:
> SQLITE_LOCKED: if you get this from a sqlite3_step statement, you MUST call sqlite3_reset on the statement handle. You should only get this on the first call to sqlite3_step, so once reset is called you can actually "retry" your sqlite3_step call. On other operations, it's the same as SQLITE_BUSY
> SQLITE_BUSY : There is no need to call sqlite3_reset, just retry your operation after waiting a bit for the lock to be released

**Comment by fnc12** [comment]
`sqlite3_reset` is called always when you call any query. What is the reason of your crash?

**Comment by fnc12** [comment]
@NewYaroslav how do you do? I got one new question: does your SQLite build has `-DTHREADSAFE=1` flag?

**Comment by NewYaroslav** [comment]
> @NewYaroslav, как поживаете ? У меня есть один новый вопрос: есть ли у вашей сборки SQLite `-DTHREADSAFE=1`флаг?

This flag is. I switched to using pure sqlite. It seems to me that your code has an error handling the SQLITE_BUSY event, which sometimes occurs while reading. I haven't gone into the details of your code, but I'm guessing it just throws an exception when an error occurs. For this reason, it is not possible to process SQLITE_BUSY correctly. 

For example, how do you implement this in an exception handler?
```
//......
err = sqlite3_step(stmt.get());
if(err == SQLITE_BUSY) {
    sqlite3_reset(stmt.get());
    sqlite3_clear_bindings(stmt.get());
    std::this_thread::sleep_for(std::chrono::milliseconds(1));
    continue;
}
// ....
```

**Comment by NewYaroslav** [comment]
This example does not cause freezes or crashes while reading in multi-threaded mode. How to implement similar logic for working with sqlite in your library?

```
inline Proxy get_proxy_from_db(utility::SqliteStmt &stmt, const std::string &key) {
          Proxy proxy;
          int err = 0;
          while (true) {
              if ((err = sqlite3_reset(stmt.get())) != SQLITE_OK) {
                  std::cout << "error in [file " << __FILE__ << ", line " << __LINE__ << ", func " << __FUNCTION__ << "], message: sqlite3_reset return code " << err << std::endl;
                  return Proxy();
              }
              if (sqlite3_bind_text(stmt.get(), 1, key.c_str(), -1, SQLITE_TRANSIENT) != SQLITE_OK) {
                  std::cout << "error in [file " << __FILE__ << ", line " << __LINE__ << ", func " << __FUNCTION__ << "], message: sqlite3_reset return code " << err << std::endl;
                  return Proxy();
              }
              err = sqlite3_step(stmt.get());
              if(err == SQLITE_BUSY) {
                  sqlite3_reset(stmt.get());
                  sqlite3_clear_bindings(stmt.get());
                  std::this_thread::sleep_for(std::chrono::milliseconds(1));
                  continue;
              } else
              if (err != SQLITE_ROW) {
                  sqlite3_reset(stmt.get());
                  sqlite3_clear_bindings(stmt.get());
                  return Proxy();
              }

              proxy.ip = (const char *)sqlite3_column_text(stmt.get(),0);
		proxy.broker = (const char *)sqlite3_column_text(stmt.get(),1);
		proxy.email = (const char *)sqlite3_column_text(stmt.get(),2);
		proxy.user_id = (const char *)sqlite3_column_text(stmt.get(),3);
		proxy.account_id = (const char *)sqlite3_column_text(stmt.get(),4);
		proxy.timestamp = sqlite3_column_int64(stmt.get(),5);

              err = sqlite3_step(stmt.get());
              if (err == SQLITE_ROW) {
                  break;
              } else
              if(err == SQLITE_DONE) {
                  sqlite3_reset(stmt.get());
                  sqlite3_clear_bindings(stmt.get());
                  break;
              } else
              if(err == SQLITE_BUSY) {
                  sqlite3_reset(stmt.get());
                  sqlite3_clear_bindings(stmt.get());
                  proxy = Proxy();
                  std::cout << "error in [file " << __FILE__ << ", line " << __LINE__ << ", func " << __FUNCTION__ << "], message: sqlite3_step return SQLITE_BUSY" << std::endl;
                  std::this_thread::sleep_for(std::chrono::milliseconds(1));
                  continue;
              }
              break;
          }
          return std::move(proxy);
}
```

**Comment by fnc12** [comment]
you can handle busy error using `storage.busy_handler` call. It forwards `sqlite3_busy_handler` call. Probably it can help you. Or you can handle `SQLITE_BUSY` manually catching exception and checking its error code

**Comment by fnc12** [comment]
@NewYaroslav I examined your code. You can perform a similar logic using `sqlite_orm` with prepared statements.
```c++
auto statement = storage.prepare(update(myObject));
while (true) {
    try{
        storage.execute(statement);
        break;
    } catch(const std::system_error &error) {
        //    inspect error here...
        continue;
    }
}
```
You can get error code from `std::system_error` to understand whether error happened due to busy status or anything else. All SQLite codes are passed right into `std::system_error` from storage

**Comment by jagerman** [comment]
> sqlite_orm does nothing about multithreading. If you have multithreaded issues using sqlite_orm then you'd have the same issues if you use raw libsqlite3 library.

This is not exactly true, because sqlite_orm is doing some thread-unsafe calls, and could definitely use some improvement in this area.  For example, there is *lots* of code that looks like this:
```C++
if(sqlite3_step(stmt) == SQLITE_DONE) {
    //  done..
} else {
    throw std::system_error(std::error_code(sqlite3_errcode(db), get_sqlite_error_category()),
                            sqlite3_errmsg(db));
}
```
which isn't thread safe because there's a race condition between the `sqlite3_step(stmt)` and the `sqlite3_errcode(db)/sqlite3_errmsg(db)` calls, which means the code and message in the exception aren't reliable when used multithreaded.

If I was writing it using raw libsqlite3, then I would write it to be thread-safe by writing it as:
```C++
auto rc = sqlite3_step(stmt);
if (rc == SQLITE_DONE) {
    // done..
} else {
    throw std::system_error(std::error_code(rc, get_sqlite_error_category()), sqlite3_errstr(rc));
}
```
but I *can't* currently get that thread safety with sqlite_orm.

Another thread-unsafe call is using `sqlite3_last_insert_rowid(db)`, which can be avoided (at least for sqlite3 3.35+, admittedly quite recent) by using `INSERT INTO .... RETURNING id` and retrieving the id from the query results.

I really want to be able to use this library, but it seems that it is not thread safe and that's a problem that requires me either to put a big mutex around any use of sqlite_orm code, or to use a separate connection for each and every thread, and neither of those is desirable.

**Comment by fnc12** [comment]
@jagerman you are right. `sqlite3_step(stmt)` can be refactored easily. About `sqlite3_last_insert_rowid` call: you can use explicit insert or `replace` instead.

**Comment by fnc12** [comment]
@jagerman fix is here https://github.com/fnc12/sqlite_orm/pull/736

**Comment by fnc12** [comment]
@jagerman merged into `dev` branch. Please check it out

**Comment by fnc12** [comment]
@jagerman are you there?

**Comment by jagerman** [comment]
Yes, thank you, that will help.

**Comment by fnc12** [comment]
@jagerman @NewYaroslav is there anything else I can help you with related to muti-threaded mode?

**Comment by jagerman** [comment]
I'll have to experiment further and will get back if I have trouble; at the moment I'm not actively working on our database code.

**Comment by fnc12** [comment]
@jagerman let me close this issue/ If you have any problems please feel free to reopen it at any time
