### ISSUE TITLE
Please help on downloading dev branch

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#710]
Please help as to downloading dev branch.
So far I do 

```
git clone https://github.com/fnc12/sqlite_orm.git dev_sqlite_orm
cd dev_sqlite_orm
git checkout dev
```

but I get 

C:\Components\dev_sqlite_orm>git checkout dev
fatal: 'dev' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate

**Comment by fnc12** [comment]
run `git checkout origin/dev` instead. This happens for the first time cause `dev` is a folder and `dev` is a branch
