### ISSUE TITLE
Downloaded dev branch - where is the sample code for added support?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#711]
Hi,

What is the sqlite_orm version of 

```SQL
select fkey_INSResponse = 1, number from Invoices
```

?

Thanks!!
Juan

**Comment by fnc12** [comment]
please don't ask the same question three times in three different places. This does not make me or anyone else respoding quicker but increases the mess

**Comment by juandent** [comment]
I apologize

**Comment by fnc12** [comment]
does everything work?

**Comment by juandent** [comment]
yes everything works
