### ISSUE TITLE
Split the header file.

### ISSUE THREAD

**Issue by DerShokus** [fnc12/sqlite_orm#72]
Hello,

What do you think about splitting the 6600 lines file into smaller headers and provide sqlite_orm.h which just includes all internal headers?

**Comment by fnc12** [comment]
Hello. Thanks for the issue. What is the main purpose of doing this? I mean what benefits developers get in this case?

**Comment by DerShokus** [comment]
The single-header approach is more convenient for a user (as a form of package delivery), but it's inconvenient for developers.

The project could use the approach of Catch2. They have a special python script to construct a general header: https://github.com/catchorg/Catch2/blob/master/scripts/generateSingleHeader.py.

**Comment by fnc12** [comment]
Catch2 is an external script so we could avoid it I guess. Anyway I was inspired by [this](https://github.com/nlohmann/json) lib during creation of mine. So I don't think it is too difficult to switch between classes within single file. I think that it is more difficult to remember where certain class is located when all classes are divided by separated files. I mean: is it such and important thing? There are a lot of single header libraries nowadays and these libs also being well developed by people just like others. Also my personal opinion is that single file is easier (if we are talking about a small lib/project, not World of Tanks)

**Comment by DerShokus** [comment]
Yes, you are right, it isn't WoT :)

But I've found out the [json](https://github.com/nlohmann/json/) project uses [amalgamate.py](https://www.sqlite.org/amalgamation.html) for building a single-header. It's described in the [CONTRIBUTING.md](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

**Comment by fnc12** [comment]
Hm, this is very interesting. I didn't know about this. If so let's divide source by classes/functions/namespaces and unite it all with amalgamaty python script

**Comment by fnc12** [comment]
Please checkout the latest commit. Especially [dev](https://github.com/fnc12/sqlite_orm/tree/master/dev) folder. Is it ok for you? If everything is cool I'll add an amalgamation script and test it

**Comment by Chemrat** [comment]
Merged `sqlite_orm1.h` seems to be missing includes for `map` and `regex` now

**Comment by fnc12** [comment]
fixed

**Comment by fnc12** [comment]
@DerShokus please checkout new branch `https://github.com/fnc12/sqlite_orm/tree/feature/72-split-the-header-file` for this feature. I need some help there. If I `cd` into root of the repo and execute `python third_party/amalgamate/amalgamate.py -c third_party/amalgamate/config.json -s dev/` command fails with error:
```python
Creating amalgamation:
 - processing "aggregate_functions/aggregate_functions.h"
 - processing "conditions/conditions.h"
 - processing "core_functions/core_functions.h"
 - processing "field_printer.h"
 - processing "internal/collate_argument.h"
 - processing "internal/column_result.h"
 - processing "internal/column.h"
 - processing "internal/constraints/constraints.h"
 - processing "internal/default_value_extractor.h"
 - processing "internal/index.h"
 - processing "internal/internal.h"
 - processing "internal/join_iterator.h"
 - processing "internal/sqlite_type.h"
 - processing "internal/storage_impl.h"
 - processing "internal/storage.h"
 - processing "internal/table.h"
 - processing "not_found_exception.h"
 - processing "row_extractor.h"
 - processing "sqlite_orm.h"
Traceback (most recent call last):
  File "third_party/amalgamate/amalgamate.py", line 299, in <module>
    main()
  File "third_party/amalgamate/amalgamate.py", line 295, in main
    amalgamation.generate()
  File "third_party/amalgamate/amalgamate.py", line 94, in generate
    t = TranslationUnit(file_path, self, True)
  File "third_party/amalgamate/amalgamate.py", line 267, in __init__
    self._process()
  File "third_party/amalgamate/amalgamate.py", line 252, in _process
    self._process_includes()
  File "third_party/amalgamate/amalgamate.py", line 240, in _process_includes
    t = TranslationUnit(found_included_path, self.amalgamation, False)
  File "third_party/amalgamate/amalgamate.py", line 267, in __init__
    self._process()
  File "third_party/amalgamate/amalgamate.py", line 251, in _process
    self._process_pragma_once()
  File "third_party/amalgamate/amalgamate.py", line 203, in _process_pragma_once
    tmp_content += self.content[prev_end:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 101: ordinal not in range(128)
```

Looks like the source `dev/sqlite_orm.h` contains 0xc2 non-ascii char but I checked it out and it doesn't contain and non-ascii characters at all.

**Comment by DerShokus** [comment]
@fnc12 , I will check it, but at the weekend.

**Comment by fnc12** [comment]
@DerShokus I need more time to make it - I've removed `dev` folder for now. Later I'll make it in a new branch and will perform it step by step

**Comment by fnc12** [comment]
@DerShokus done. Please check out `dev` branch
