### ISSUE TITLE
[Bug] It seems impossible to chain where clauses in `update_all()`

### ISSUE THREAD

**Issue by ShredAstaire** [fnc12/sqlite_orm#723]
This compiles:
```c++
storage.update_all(set(c(&Fragment::composedOrder) = id),
                                where( c(&Fragment::base) = "C"));
```

Yet this does not
```c++
storage.update_all(set(c(&Fragment::composedOrder) = id),
                                where(     c(&Fragment::base) = "C"
                                      and (c(&Fragment::base) = "C") ));
```

On macOS Clang 11

**Comment by ShredAstaire** [comment]
```
error: no viable conversion from 'assign_t<std::__1::basic_string<char> Fra
gment::*, const char *>' (aka 'binary_operator<std::__1::basic_string<char> Fragment::*, const char *, sqlite_orm::internal::assign_string>') to 'bool'
                                      and (c(&Fragment::base) = "C") ));
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ShredAstaire** [comment]
I just noticed that replacing the first `=` condition by `>=` would fix the compilation. There is something fishy going on in the land of template instantiations!

**Comment by ShredAstaire** [comment]
The README doc mentions the single version for conditions:
> You also can select objects with custom where conditions with =, !=, >, >=, <, <=, IN, BETWEEN and LIKE.

So I thought the syntax was single `=`.

---

Anyway, with double `==`, I cannot even get the single clause version to compile:

```
    mImpl->storage.update_all(set(c(&Fragment::composedOrder) = id),
                              where(c(&Fragment::base) == std::string{"C"}));
```
Which produces error:

```
error: invalid operands to binary expression ('internal::expression_t<basic_string<char> Fragment::*>' and 'std::string' (a   ka 'basic_string<char, char_traits<char>, allocator<char> >'))
                              where(c(&Fragment::base) == std::string{"C"}));
                                    ~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~

```
As you can see from the error, `Fragment::base` is a `std::string` data member.

**Comment by fnc12** [comment]
ok. Did you try `is_equal`?

**Comment by ShredAstaire** [comment]
`is_equal`  does compile when replacing the first `=`, thank you!

Is it not strange that some operators do not work in first position though?

**Comment by fnc12** [comment]
no. Don't touch the first `=` cause it is ok. Replace operators with `is_equal` only inside `where`. `set` function has assign and `where` has comparison. That is why `set` has single `=` and `where` has double. I know that SQL has these operators look the same but we use C++ so I made it in C++ style. You use single `=` inside where cause it is serialized the same way. But assign operator is not designed to be used with `and` operator.

**Comment by ShredAstaire** [comment]
It feels like we are not understanding each other. I will try to give several examples showing why I think there are bugs 
(and why I think the `where` clause accept only single `=`, but not double `==`, contrarily to what you wrote above).

----

This code **does** compile, and it does what I expect (only update fragments where `base` is equal to `"C"`):

```
storage.update_all(set(c(&Fragment::composedOrder) = id),
                   where(c(&Fragment::base) = "C" )); // SINGLE
```
Let me insist that this codes uses **SINGLE** `=` and it compile and works as expected.

Yet this codes does **NOT** compile:

```
storage.update_all(set(c(&Fragment::composedOrder) = id),
                   where(c(&Fragment::base) == "C" ));  // DOUBLE
```

With error:
```
error: invalid operands to binary expression ('internal::expression_t<basic_string<char> Fragment::*>' and 'const char [2]'    )
                   where(c(&Fragment::base) == "C" ));
                          ~~~~~~~~~~~~~~~~~~ ^  ~~~
```

Because of that, I do **NOT** think it is possible to use double `==` for comparison in `where`. I think the comparison only works with simple `=`. 

You don't have any code with double `==` [in the examples folder](https://github.com/fnc12/sqlite_orm/tree/master/examples), I think you should try and see for yourself!

----

This **does** compiles:

```
storage.update_all(set(c(&Fragment::composedOrder) = id),
                   where(c(&Fragment::base) >= "C" )); // operator >=
```

But this does **NOT** compile:

```
storage.update_all(set(c(&Fragment::composedOrder) = id),
                   where(c(&Fragment::base) != "C")); // operator !=
```

With error:

```
error: invalid operands to binary expression ('internal::expression_t<basic_string<char> Fragment::*>' and 'const char [2]'    )
                    where(c(&Fragment::base) != "C"));
                          ~~~~~~~~~~~~~~~~~~ ^  ~~~
```

Simply replacing the operator `>=` with the operator `!=` breaks the compilation. Nothing else changed.
Because of that, I think there is a problem with the operator `!=`, because it cannot be used where the operator `>=` is accepted.

----

This **does** compile:
```
storage.update_all(set(c(&Fragment::composedOrder) = id),
                   where(c(&Fragment::base) = "C")); // SINGLE =, only one clause in where.
```

But this does **NOT** compile:
```
storage.update_all(set(c(&Fragment::composedOrder) = id),
                   where(    c(&Fragment::base) = "C" // SAME FIRST CONDITION AS ABOVE!
                         and (c(&Fragment::base) = "C")));
```
With error
```
error: no viable conversion from 'assign_t<std::__1::basic_string<char> ad::tradebot::Fragment::*, const char *>' (aka 'bin    ary_operator<std::__1::basic_string<char> ad::tradebot::Fragment::*, const char *, sqlite_orm::internal::assign_string>') to 'bool'
                          and (c(&Fragment::base) = "C")));
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

But if I replace the first `=` with a `<=`, it works again. Note that the second comparison is a single `= ` (to insist, it does **NOT** compile if I replace any single `=` with a double `==`). So this **does** compile:

```
storage.update_all(set(c(&Fragment::composedOrder) = id),
                   where(    c(&Fragment::base) <= "C" // SAME FIRST CONDITION AS ABOVE!
                         and (c(&Fragment::base) = "C")));
```

So, single `=` works fine when it is the only clause, or when it is the second clause. But it does **NOT** work only when it is the first clause of a chain.

Because of that, I think some operators are failing to compile **when they are in the first position of a chained clause**, but they compile just fine when they appear later in the chain!

**Comment by fnc12** [comment]
`update_all` with `==` exists in unit tests [here](https://github.com/fnc12/sqlite_orm/blob/master/tests/tests3.cpp#L123) and [here](https://github.com/fnc12/sqlite_orm/blob/master/tests/tests2.cpp#L252). Also exampled folder also contains it [here](https://github.com/fnc12/sqlite_orm/blob/master/examples/foreign_key.cpp#L72) and more in the same file. I understand what you are saying and all I am saying is how API is designed. I understand that you found a cheat in using assignment instead of comparison and I understand how it works. Storage constructs a string query from objects you specified and forwards it to SQLite engine. So both assignment operator and equal comparison operator have the same syntax in SQL and SQLite. That is why assign operator cannot compile with `and` operator - it is not designed like that cause SQLite has no cases where you chain assignment using `AND`.
About bug - let me check it out today. I'll write you back. Thanks for the note.

**Comment by fnc12** [comment]
fix is here https://github.com/fnc12/sqlite_orm/pull/728

**Comment by fnc12** [comment]
@ShredAstaire merged. Please check out `dev` branch

**Comment by fnc12** [comment]
@ShredAstaire is everything ok?

**Comment by fnc12** [comment]
@ShredAstaire is the issue actual?

**Comment by fnc12** [comment]
@ShredAstaire is the issue actual?

**Comment by fnc12** [comment]
fixed and closed due to inactivity
