### ISSUE TITLE
copy to MEMORY DB to FILE DB

### ISSUE THREAD

**Issue by gfzgfz** [fnc12/sqlite_orm#724]
I want Memory DB to File DB.

After creating the memory db repository, should I create the same file db repository?
i.e)
```c++
    auto memoryStor = make_storage(":memory:",
                                make_table("contacts",
                                           make_column("contact_id", &Contact::id, primary_key()),
                                           make_column("first_name", &Contact::firstName),
                                           make_column("last_name", &Contact::lastName)));

    auto fileStor = make_storage("file.db",
                                make_table("contacts",
                                           make_column("contact_id", &Contact::id, primary_key()),
                                           make_column("first_name", &Contact::firstName),
                                           make_column("last_name", &Contact::lastName)));
```
Would this be the best? 
because my storage is big.

Thank you.

**Comment by fnc12** [comment]
You did right. Next call backup API:
`memoryStor.backup_to(fileStor);`

**Comment by gfzgfz** [comment]
Thanks for the quick help every time.
Thank you for creating such a good library.

**Comment by gfzgfz** [comment]
I confirmed that the backup_to operation puts all the contents in the memory db into the file db.
However, what I want is not to overwrite the file db, but to put it in the file db cumulatively.
Is it possible to use this function?

**Comment by fnc12** [comment]
oh I understand. You need to attach one database to another and then insert data from the first database to the second. More info https://www.sqlitetutorial.net/sqlite-attach-database/. Unfortunately `ATTACH` feature is not supported right now in `sqlite_orm` but it exists in the [TODO list](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md) and also in issues https://github.com/fnc12/sqlite_orm/issues/578. It will be implemented in the next month or two. Or you can implement it on your own if you want.

**Comment by gfzgfz** [comment]
Okay. I appreciate you responding so quickly to my request.
