### ISSUE TITLE
Possibility of using `std::string_view` (or even `char const *`) to avoid heap allocation to/from a text column?

### ISSUE THREAD

**Issue by NickStrupat** [fnc12/sqlite_orm#729]
For example...

```cpp
class Foo {
    int id;
    string_view name;
};
```

The `string_view` instance would point to the raw text data in the row.

**Comment by fnc12** [comment]
@NickStrupat you need to add bindings for custom types. Please look through enum binding example

**Comment by fnc12** [comment]
@NickStrupat I did not add `std::string_view` support out of box cause IDK how to implement getting data from database to `std::string_view`. Case is that string obtained from database is dynamic so it needs to be stored somewhere cause `std::string_view` cannot store dynamic string but it can only store a pointer to dynamic string which must be stored somewhere else.

**Comment by NickStrupat** [comment]
You're right! I just tried it with this:

```cpp
namespace sqlite_orm {
	template<>
	struct type_printer<string_view> : public text_printer {};

	template<>
	struct statement_binder<string_view> {
		int bind(sqlite3_stmt* stmt, int index, const string_view& value) {
			return sqlite3_bind_text(stmt, index++, value.data(), value.length(), SQLITE_TRANSIENT);
		}
	};

	template<>
	struct field_printer<string_view> {
		std::string operator()(const string_view& t) const {
			return string(t);
		}
	};

	template<>
	struct row_extractor<string_view> {
		string_view extract(const char* row_value) {
			return string_view(row_value);
		}

		string_view extract(sqlite3_stmt* stmt, int columnIndex) {
			auto str = sqlite3_column_text(stmt, columnIndex);
			return this->extract((const char*)str);
		}
	};
}
```

...but it appears that `sqlite` moves/destroys the string data by the time `get_all` returns its vector of objects.

I also just tried `storage.iterate` and it worked. I assume that's because `sqlite` is moving the raw internal data into some line of memory to be read from by `sqlite3_step` and to give the client code a chance to work with the raw data.

I can see now why you don't want to include `string_view` in the library. It would basically only work with your `iterate` method.

Thank you kindly for the amazing work on this library. It is a work of art!

**Comment by fnc12** [comment]
Probably your code performs UB. Can you please show it? I am just curious.

**Comment by NickStrupat** [comment]
Sure. I derived my code from https://github.com/fnc12/sqlite_orm/blob/master/examples/in_memory.cpp

```cpp
#include <cassert>
#include <iostream>
#include <string_view>
using namespace std;

#include <sqlite_orm.h>
using namespace sqlite_orm;

namespace sqlite_orm {
	template<>
	struct type_printer<string_view> : public text_printer {};

	template<>
	struct statement_binder<string_view> {
		int bind(sqlite3_stmt* stmt, int index, const string_view& value) {
			return sqlite3_bind_text(stmt, index++, value.data(), value.length(), SQLITE_TRANSIENT);
		}
	};

	template<>
	struct field_printer<string_view> {
		std::string operator()(const string_view& t) const {
			return string(t);
		}
	};

	template<>
	struct row_extractor<string_view> {
		string_view extract(const char* row_value) {
			return string_view(row_value);
		}

		string_view extract(sqlite3_stmt* stmt, int columnIndex) {
			auto str = sqlite3_column_text(stmt, columnIndex);
			return this->extract((const char*)str);
		}
	};
}

struct RapArtist {
	int id;
	string_view name;
};

int main()
{
	auto storage = make_storage(":memory:",
		make_table("rap_artists",
			make_column("id", &RapArtist::id, primary_key()),
			make_column("name", &RapArtist::name)
		)
	);
	cout << "in memory db opened" << endl;
	storage.sync_schema();

	assert(!storage.count<RapArtist>());

	storage.insert(RapArtist{ -1, "The Weeknd" });

	storage.transaction([&] {
		storage.insert(RapArtist{ -1, "Drake" });
		return true;
		});

	cout << "rap artists count = " << storage.count<RapArtist>() << endl;

	//  transaction also work in memory..
	storage.transaction([&] {
		storage.insert(RapArtist{ -1, "Kanye West" });
		return false;
		});
	storage.vacuum();

	cout << "rap artists count = " << storage.count<RapArtist>() << " (no Kanye)" << endl;

	// this doesn't work
	auto rappers = storage.get_all<RapArtist>(where(length(&RapArtist::name) > 3 and c(&RapArtist::id) > 0));
	for (auto const & rapper : rappers)
		cout << rapper.name << endl; // garbage

	// this works
	for (auto const & rapper : storage.iterate<RapArtist>(where(length(&RapArtist::name) > 3 and c(&RapArtist::id) > 0)))
		cout << rapper.name << endl; // good

	/*auto file_storage = make_storage("wow.db");
	storage.backup_to(file_storage);*/

	return 0;
}
```

**Comment by fnc12** [comment]
Oh I see. You are right: `iterate` works and does not produce UB cause storage connection is opened and statement is alive until loop is finished. But in `get_all` case statement is killed right after `get_all` call finished. Thank you for providing the code.
Can I help you with anything else?

**Comment by NickStrupat** [comment]
That's all I wanted to ask. Thank you again for your timely help.

**Comment by fnc12** [comment]
@NickStrupat I'd like to know: what project you use `sqlite_orm` for? I'd like to make a list of project using this lib.
Also let me introduce you SQLite GUI app made by me https://sqliteman.dev

**Comment by NickStrupat** [comment]
I'm using it in a compiler I'm building. For my own programming language. It's in very early stages of development still, but my plan is to use SQLite and your library to store all the tokens, AST elements, symbols, etc.

**Comment by fnc12** [comment]
sounds great! Good luck!
