### ISSUE TITLE
Types for Storage, Table and Column

### ISSUE THREAD

**Issue by SimantoR** [fnc12/sqlite_orm#737]
# Description
`sqlite_orm` provides examples for almost everything that can be done using Sqlite but it doesn't show any example for types for tables/columns/storage. Without types it's hard to store or reuse storage across different contexts. Just the column type is a very complicated type to declare. Does that type propagate all the way up to a storage? It seems so. In such cases, it would be ridiculously hard to figure out types to store as fields.

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/wiki/FAQ

**Comment by SimantoR** [comment]
Thank you for the link. May i suggest returning a unique pointer for it? I created an identical one for this purpose.

**Comment by fnc12** [comment]
You can return a unique pointer. 

> I created an identical one for this purpose.

What are talking about?

**Comment by fnc12** [comment]
> May i suggest returning a unique pointer for it?

Yes you can. It can be done the same way you make unique pointer for other types. All you need is to get the type using code example from the link above.

**Comment by fnc12** [comment]
@SimantoR is the issue actual?

**Comment by SimantoR** [comment]
Resolved the issue. I created a function that returns the DB object as unique pointer. But yes definitely resolved. Thank you for the support
