### ISSUE TITLE
cmake -B build error

### ISSUE THREAD

**Issue by numb0824** [fnc12/sqlite_orm#739]
hi,i follow the step compile sqlite_orm,but find this error:
"
whx@whx-pc:~$ git clone https://github.com/fnc12/sqlite_orm.git sqlite_orm
正克隆到 'sqlite_orm'...
remote: Enumerating objects: 9536, done.
remote: Counting objects: 100% (628/628), done.
remote: Compressing objects: 100% (326/326), done.
remote: Total 9536 (delta 345), reused 396 (delta 184), pack-reused 8908
接收对象中: 100% (9536/9536), 4.15 MiB | 98.00 KiB/s, 完成.
处理 delta 中: 100% (5727/5727), 完成.
whx@whx-pc:~$ cd sqlite_orm/
whx@whx-pc:~/sqlite_orm$ cmake -B build
CMake Error: The source directory "/home/whx/sqlite_orm/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI."
could someone can help me ?

**Comment by fnc12** [comment]
try
```
cd sqlite_orm/
mkdir build
cd build
cmake ..
```

**Comment by numb0824** [comment]
thaks! 
it really helps me
