### ISSUE TITLE
string primary key

### ISSUE THREAD

**Issue by tatraian** [fnc12/sqlite_orm#74]
Hello!

I tried to create a table with string (text) primary key. I always get
```
terminating with uncaught exception of type std::runtime_error: NOT NULL constraint failed: counters.key
```
error when I try to insert an element. I tested this on the command line of sqlite3 and it worked without error.
I printed out the sql querry from ```insert``` function. I get the next:
```
INSERT INTO 'counters' ("value") VALUES (?)
```

looks like it drops the key part of the insert statement.

And here is my example code:
```
#include <sqlite_orm.h>

using namespace sqlite_orm;

struct Counter {
    std::string key;
    uint32_t    value;
};

int main()
{
    auto storage = make_storage("./db.sqlite",
                                make_table("counters",
                                           make_column("key", &Counter::key, primary_key()),
                                           make_column("value", &Counter::value)));
    storage.sync_schema(true);

    Counter c = {"/hardware/a4printer/printed_pages", 3};
    std::cout << "key: " << c.key << ": " << c.value << std::endl;
    storage.insert(c);

    return 0;
}
```

The output of command line test:
```
sqlite> .schema counters
CREATE TABLE IF NOT EXISTS 'counters' ( 'key' TEXT PRIMARY KEY NOT NULL , 'value' INTEGER NOT NULL );
sqlite> insert into counters VALUES("/hardware/a4printer/printed_pages", 3);
sqlite> select * from counters;
/hardware/a4printer/printed_pages|3
```

If I just simple use ```unique``` for key, I have the next table:
```
CREATE TABLE IF NOT EXISTS 'counters' ( 'key' TEXT UNIQUE NOT NULL , 'value' INTEGER NOT NULL );
```
and the program works. The insert statement will be:
```
INSERT INTO 'counters' ("key", "value") VALUES (?, ?)
```

**Comment by fnc12** [comment]
Hello. Thanks for using the lib. 
If you want to `INSERT` a row (object) without creating id for you use `replace` instead of `insert`. `insert` skips primary key column and returns `last_insert_rowid`. It is used for creating new objects with new ids. More details in the [wiki](https://github.com/fnc12/sqlite_orm/wiki/storage_t%3A%3Ainsert).

**Comment by tatraian** [comment]
Thanks the fast answer and the library too:)
Next I read more, sorry...

**Comment by fnc12** [comment]
You're welcome. It's not obvious but it is SQLite specific thing (I'm talking about `REPLACE INTO` query type) so `insert` and `replace` are the best way IMHO to provide both functionalities.

**Comment by tatraian** [comment]
Yes, you are right, and this is in the first section of the linked documentation. So this is absolutely OK.
