### ISSUE TITLE
"cmake --build build --target install" error

### ISSUE THREAD

**Issue by numb0824** [fnc12/sqlite_orm#740]
hi,when i do this step "cmake --build build --target install",i found a error:
"
cd /home/whx/sqlite_orm/build/tests/third_party/sqlite && /usr/local/bin/cmake -DSQLITE3_ARCH_NAME=/home/whx/sqlite_orm/build/tests/third_party/sqlite/sqlite.zip -DSQLITE3_LINK=https://www.sqlite.org/2020/sqlite-amalgamation-3320300.zip -DSQLITE3_ARCH_SHA1=0c805bea134712a903290a26b2a61c3a8a3bd8cc -P /home/whx/sqlite_orm/tests/third_party/sqlite/DownloadSqlite3.cmake
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
CMake Error at /home/whx/sqlite_orm/tests/third_party/sqlite/DownloadSqlite3.cmake:15 (message):
  Invalid hash: c0e8c1d694b82dd8c11e7105908e12a8e8a57067 !=
  0c805bea134712a903290a26b2a61c3a8a3bd8cc

tests/third_party/sqlite/CMakeFiles/sqlite3.dir/build.make:74: recipe for target 'tests/third_party/sqlite/sqlite.zip' failed
"
could someone can help me? thanks a lot

**Comment by fnc12** [comment]
what branch do you use? if `master` please try `dev` instead. There was some kind of hash bug

**Comment by numb0824** [comment]
@fnc12 thanks for your reply! 
I tried both master and dev branch again and again,finally it can compile successfully.
This error  is judt about a network's problem in my country,so it's not the branch problem.
