### ISSUE TITLE
how to open a sqlite db file using make_storage?

### ISSUE THREAD

**Issue by jojogh** [fnc12/sqlite_orm#741]
As the former issue mentioned about the database connection, i used the following way to open the database, but i can not get any expecting result. How can I open and query data with the correct way? Thanks!
```c++
struct User {
  int id;
  std::string name;
 };

 auto teststorage = make_storage("test.db", 
  make_table("user",make_column("id", &User::id),make_column("name", &User::name)));
 teststorage.sync_schema();
 auto allusers = teststorage.get_all<User>();
 cout << allusers.size() << endl;
 for (int i = 0; i < allusers.size(); i++) {
  cout << "user["<< i <<"] = " << teststorage.dump(allusers[i]) << endl;
 }
```

**Comment by fnc12** [comment]
Looks like everything is correct.
What result do you get and what result do you expect?

**Comment by fnc12** [comment]
@jojogh are you there?

**Comment by jojogh** [comment]
Hi sorry can not access github time to time, I have fixed this issue, by convert the db file to .sqlite format, everthing is ok now. Thanks!

**Comment by fnc12** [comment]
@jojogh good! Also please tell me what project do you use this lib for. I am curious and want to make a list of project that use `sqlite_orm`
