### ISSUE TITLE
Add github actions for unit tests and examples

### ISSUE THREAD

**Issue by fnc12** [fnc12/sqlite_orm#746]
I've started this https://github.com/fnc12/sqlite_orm/pull/745 but I cannot figure out how to fix windows and ubuntu builds. Probably windows is missing sqlite lib but IDK how to install it. Ubuntu fails with segfault. Probably ubuntu need to increase template recursion depth compilation argument but I also don't know how to do it

**Comment by data-man** [comment]
> Probably windows is missing sqlite lib but IDK how to install it.

Put sqlite's sources to third_party dir?

**Comment by fnc12** [comment]
@data-man sqlite receives updates regularly so it is not a good idea. The best way is to download it every time

**Comment by data-man** [comment]
Ok.
Try switch to https://github.com/cpm-cmake/CPM

**Comment by fnc12** [comment]
the link gives 404

**Comment by data-man** [comment]
Sorry :)
https://github.com/cpm-cmake/CPM.cmake

**Comment by eclarkso** [comment]
I am just reading documentation and not actually running anything, but are you sure the Ubuntu issue is hitting the template recursion depth?  https://stackoverflow.com/questions/52171430/how-to-avoid-gcc-crash-due-to-lack-of-memory suggests it's pretty easy to hit 6-8GB RAM usage with sufficiently complicated templates, and GitHub runners only have 7GB.  

Moreover, if you were hitting the default depth limit, I would have expected a compiler message and not a segfault (like https://bugs.launchpad.net/ubuntu/+source/gcc-4.6/+bug/1063415).

No good suggestions on how to solve it though.  Use clang instead?

**Comment by fnc12** [comment]
@eclarkso I am not sure about that. To be sure we need to implement Ubuntu with GCC first

**Comment by fnc12** [comment]
so a friend of mine tried to add it for ubuntu but compilation fails with memory overflow

**Comment by fnc12** [comment]
I have a better idea how to implement it

**Comment by trueqbit** [comment]
> I have a better idea how to implement it

Apart from even more room for improvement, I just want to mention that sqlite_orm has a very nice appveyor test matrix, and that the template instantiation depth/memory exhaustion problem no longer exists since the use of tuples and fold expressions.
