### ISSUE TITLE
i want change filename

### ISSUE THREAD

**Issue by gfzgfz** [fnc12/sqlite_orm#752]
it's my code.
```
  using storage = decltype(initProfileStorage(""));
  std::unique_ptr<storage> Profile;
  
  void makeProfiledb(std::string filename)
  {
    Profile = std::make_unique<storage>(initProfileStorage(filename));
    ....
  }
```
i want change filename.
i think close "Profile" and then recall makeProfiledb()
so how can i close profile??

Or is there a better way to rename the file?

**Comment by fnc12** [comment]
after destroying a storage connection will be closed fo sure. So to use a storage with a different filename just recreate it using `makeProfiledb` function with a different argument

**Comment by gfzgfz** [comment]
How can i destroying a storage connection?
Which function should I call?
Thank you

**Comment by fnc12** [comment]
nothing explicit. Just destroy the object

**Comment by gfzgfz** [comment]
Well resolved. Thank you.
