### ISSUE TITLE
a question about the has_every method of column_t

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#758]
I am learning from your source code, it is so fine!! 

I have a question about has_every:

```C++
            template<class Opt>
            constexpr bool has() const {
                return tuple_helper::tuple_contains_type<Opt, constraints_type>::value;
            }

            template<class O1, class O2, class... Opts>
            constexpr bool has_every() const {
                if (has<O1>() && has<O2>()) {
                    return true;
                }
                else {
                    return has_every<Opts...>();
                }
            }

            template<class O1>
            constexpr bool has_every() const {
                return has<O1>();
            }
```

I don't understand the recursion that tests has<O1>()  && has<O2>() but does not take into account the variadic Opts...
If we want to ensure every constraint satisfies 'has'....

Some light or example will be greatly appreciated!

Cheers,
Juan Dent

**Comment by juandent** [comment]
I have understood your other recursions but I have trouble with this one ... 

Shouldn't the first has_every be:

```C++
template<class O1, class O2, class... Opts>
            constexpr bool has_every() const {
                if (has<O1>() && has<O2>() && has_every<Opts...>) {
                    return true;
                }
                else {
                    return has_every<Opts...>();
                }
            }
``` 

what is your intent? For each On it is true that has<On> is true?

**Comment by fnc12** [comment]
probably some if these functions are not used anymore and are legacy

**Comment by juandent** [comment]
I have found the correct implementation as follows:

```C++
     template<class O1>
    constexpr bool has_every() const
    {
        return has<O1>();
    }
    template<class O1, class... Opts, std::enable_if_t<(sizeof...(Opts) > 0), int > =0>
        constexpr bool has_every()  const {
        return has<O1>() && has_every<Opts...>();
    }
```

I tested this

:-)
Regards,
Juan Dent

**Comment by fnc12** [comment]
what do you mean 'you found'? You found it inside the lib or you've implemented this by yourself?

**Comment by juandent** [comment]
I moved the function templates outside of column_t and removed the constness of the functions (since they are no longer members) and I tried them like so:

```C++
    struct X1 {};
    struct X2 {};
    struct X3 {};
    struct X4 {};
    struct X5 {};
	
    using types = decltype(::std::tuple<X1, X2, X3, X4>{});

    template<class Opt, class ...Args>
    constexpr bool has() {
        return ::sqlite_orm::tuple_helper::tuple_contains_type<Opt, types>::value;
    }
void use()
{    
    constexpr bool res = has_every<X1, X2, X3, X4>();   // true
    constexpr bool res2 = has_every<X1, X2, X3>();       // true
    constexpr bool res3 = has_every<X1, X2, X5>();       // false
}
```

So I implemented this...
it works nicely

**Comment by juandent** [comment]
do you want to update this legacy code so it does what it should or is this code not used at all?

Happy to be of any help John!!

**Comment by fnc12** [comment]
@juandent I'd like to remove this code if it is never used. Why do you need it?

**Comment by juandent** [comment]
no I don't need it! Actually I have been studying your excellent code and stumbled into this particular section that did not seem to work correctly... go ahead and remove it

**Comment by juandent** [comment]
thanks!!

**Comment by fnc12** [comment]
thank you. You are welcome
