### ISSUE TITLE
Autoincrement error

### ISSUE THREAD

**Issue by PonyMcTail** [fnc12/sqlite_orm#76]
I experimenting with this ORM and for now i can tell that is very nice documented and provided with lots of examples. I'm heaving some issue with "unique.cpp" example. Compiling example works fine but when run program i got error:

> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  near "AUTOINCREMENT": syntax error

"unique.sqlite" was created but without any table and column. It is completely empty.

I'm using Eclipse CDT Oxygen.1a Release (4.7.1a) on windows 7, with mingw64
gcc version 6.3.0 (x86_64-posix-seh-rev1, Built by MinGW-W64 project)

**Comment by PonyMcTail** [comment]
When i put in make storage autoincrement() before primary_key() example works.

> UNIQUE constraint failed: unique_test.unique_text
> inserted { id : '1', unique_text : 'Bebe Rexha', nullable_text : 'The way I are' }

Should i close this issue or you will explore this behavior and then close.

**Comment by fnc12** [comment]
Hey thanks for using the lib. I'm glad it is useful for you. You dod quite right - relative order of `primary_key` and `autoincrement` matters in SQLite schema. And looks like `unique.cpp` example is incorrect and I also forgot to include it to travis script. I've fixed it all in the latest commit. Thanks you much. Please feel free open any issue if you got one
