### ISSUE TITLE
[request] Specify custom SQLite3 (.c and .h) files, or amalgamation folder

### ISSUE THREAD

**Issue by Lokotito** [fnc12/sqlite_orm#763]
Really new in c++ and SQLite, find this project and like to test it.
I'm using Visual Studio 2019 as environment, and like to simplify my project with only amalgamation source code for SQLite3 (.h and .lib files).

It's possible to implement a folder where sqlite_orm search for SQLite3 files (.c and .h)?, or is any way to configure this in actual CMakeLists.txt?

Thanks.

**Comment by fnc12** [comment]
sqlite_orm searches using `#include <sqlite3.h>` preprocessor directive just as any other C/C++ source files. So al you need is to add your amalgamation source to your project and add `.h` file's path to project header search path

**Comment by fnc12** [comment]
@Lokotito is the issue actual?

**Comment by Lokotito** [comment]
In windows10 I have to Add a reference folder with sqlite3 amalgamation files (.c and .h files) in Environment Variables->System Variables, after that I can run 'cmake -B build' command inside "Developer Command Prompt for VS 2019".
But I did'nt find a way to implement de amalgamation files directly in sqlite_orm git clone folder, even I try copy .c and .h files in 'sqlite_orm\dependencies' folder.
All this past week.

**Comment by fnc12** [comment]
just add `sqlite3.h` and `sqlite3.c` wherever you want then add `sqlite3.c` as a source into your project and add `sqlite3.h`path into include directories

**Comment by fnc12** [comment]
@Lokotito is the issue actual?

**Comment by Lokotito** [comment]
All works OK, thank you for all.
