### ISSUE TITLE
support for u8 strings is incomplete

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#765]
I just downloaded the dev branch today and it does not compile. I get the error:

> >C:\Components\sqlite_orm_dev_26_july_2021\include\sqlite_orm/sqlite_orm.h(11366,39): error C2079: 'serializator' uses undefined struct 'sqlite_orm::internal::statement_serializator<T,void>'
1>        with
1>        [
1>            T=const char8_t *const
1>        ]

when I remove the u8 prefix from the strings in tests2.cpp the problem goes away... I believe we are missing a specialization for char8_t for  the statement_serializator function template.

**Comment by fnc12** [comment]
PR is here https://github.com/fnc12/sqlite_orm/pull/768

**Comment by fnc12** [comment]
@juandent what is your OS and compiler?

**Comment by fnc12** [comment]
@juandent merged into `dev`

**Comment by juandent** [comment]
My OS is Windows 10 and compiler is VS 2019 v16.10.4

**Comment by juandent** [comment]
is integration into dev complete as far as char8_t is concerned?

**Comment by fnc12** [comment]
ok thanks. Is everything ok now?

**Comment by juandent** [comment]
do I have to git clone again? or just do a Pull Request?
How so? cmd line?

**Comment by fnc12** [comment]
don't do git clone if you have already done clone once. Just open terminal, go to `sqlite_orm` folder and run `git pull` command. It will pull the latest changes of the current branch. Also you must be on `dev` branch. Type `git branch` to view your current branch

**Comment by juandent** [comment]
everything is ok now!!
