### ISSUE TITLE
How can I get size of a table in bytes? (DbStat question)

### ISSUE THREAD

**Issue by vrakesh** [fnc12/sqlite_orm#766]
Hello, 
   New user of sqlite_orm here. I would like to find the current size of database table , This can be done with dbstat
```
SELECT SUM("pgsize") FROM "dbstat" WHERE name='TABLENAME';
```
https://www.sqlite.org/dbstat.html
If it compile SQLite with dbstat, how would I execute the above command with sqlite_orm?

**Comment by fnc12** [comment]
Hello. This feature must be added. We need to think about API for it. I see it like this: `sqlite_orm` will have a dedicated struct `dbstat` with fields mapped to columns of `dbstat` table so one can make queries:
```c++
auto countValue = storage.sum(&dbstat::pgsize, where(is_equal(&dbstat::name, "TABLENAME")));
```
Of course this struct will be covered with `#ifdef SQLITE_ENABLE_DBSTAT_VTAB`.

What do you think?

**Comment by vrakesh** [comment]
This sounds perfect, would love the feature . The dedicated struct makes sense. Thanks for accepting this as a feature request.

**Comment by fnc12** [comment]
@vrakesh almost done https://github.com/fnc12/sqlite_orm/pull/901

**Comment by fnc12** [comment]
merged. Please check out `dev` branch

**Comment by fnc12** [comment]
closing cause it is done
