### ISSUE TITLE
support c++11 compilation

### ISSUE THREAD

**Issue by zhang-chuanfeng** [fnc12/sqlite_orm#774]
Can it support c + + 11 compile

**Comment by fnc12** [comment]
now. It uses template lambdas which appeared at C++14

**Comment by zhang-chuanfeng** [comment]
Other projects that use c++11 cannot compile with sqlite_orm. The previous project has always used c++11. Compatible with c++11 is better, otherwise you must use a compiler version of c++14 or higher .

**Comment by zhang-chuanfeng** [comment]
ok,thank you.
