### ISSUE TITLE
Running queries directly on the SQLite database

### ISSUE THREAD

**Issue by PandarinDev** [fnc12/sqlite_orm#782]
While the interface exposed by sqlite_orm is great, sometimes it'd be nice to run direct SQL on the database opened by sqlite_orm. As far I know there is no way currently to directly run a query, or to get a handle to the opened database. I understand these calls might invalidate state managed by sqlite_orm so they're not safe, but currently I have to open my database directly with SQLite's C API,  run my queries, close the DB and open it again in sqlite_orm which is rather inconvenient.

**Comment by fnc12** [comment]
all you can do is access `sqlite3 *db` handle using `on_open` storage's member:
```c++
storage.on_open([](sqlite3* db) {
    // do what you want once open happened
});
```
Direct SQL is not available by design cause main goal if this lib is making great DSL API which will replace raw string queries in 100% cases.

**Comment by PandarinDev** [comment]
That's good enough for me now, thanks!

**Comment by fnc12** [comment]
@PandarinDev I've added a new entry in FAQ [here](https://github.com/fnc12/sqlite_orm/wiki/FAQ) to make it clear for people who faces the same issue in future (item 2)
