### ISSUE TITLE
Creation of indexes not including order or collation 

### ISSUE THREAD

**Issue by freakstatic** [fnc12/sqlite_orm#784]
For example:

```c++
    auto storage = make_storage("db.sqlite",
                                make_index("idx_users_first_name", indexed_column(&User::first_name).desc()),
                                make_index("idx_users_first_name_2", indexed_column(&User::first_name).collate("BINARY").desc()),
                                make_index("idx_users_nr", indexed_column(&User::nr).desc()),
                            make_table("users",
                                       make_column("id", &User::id, autoincrement(), primary_key()),
                                       make_column("first_name", &User::first_name),
                                       make_column("nr", &User::nr)
                                           ));

```
    
I'm getting: 
```
CREATE INDEX IF NOT EXISTS 'idx_users_nr' ON 'users' ('nr')
CREATE INDEX IF NOT EXISTS 'idx_users_first_name_2' ON 'users' ('first_name')
CREATE INDEX IF NOT EXISTS 'idx_users_first_name' ON 'users' ('first_name')
```

The "descending order" and the "collate" aren't being included in the query.
I'm missing something?
I'm using v1.6 and compiling with Apple clang version 12.0.5

**Comment by fnc12** [comment]
Hi. Let me check it. I'll write you back

**Comment by fnc12** [comment]
@freakstatic it is a bug. I am fixing it right now

**Comment by fnc12** [comment]
the fix is here https://github.com/fnc12/sqlite_orm/pull/789

**Comment by freakstatic** [comment]
Hi @fnc12!
I can confirm that #789 fixes it
Thank you very much, keep your great work!

**Comment by fnc12** [comment]
@freakstatic can you tell me please in what project you use `sqlite_orm`?

**Comment by freakstatic** [comment]
since it hasn't been released yet I can't discuss much about it but I can say that it's an application to manage audio files. It uses a SQLite database for that, so sqlite_orm fits really great for CRUD operations! :)

**Comment by fnc12** [comment]
wow sounds nice. I'd like to make a list of projects that use `sqlite_orm` here in this repo. Can you send me a link to your app once it is released please?

**Comment by freakstatic** [comment]
Should I post on #783?

**Comment by fnc12** [comment]
yeah. Thanks

**Comment by freakstatic** [comment]
Btw are you thinking of creating a hot fix for v1.6 with this fix or are you planning to wait for the new version?

**Comment by fnc12** [comment]
I am planning to wait for a new version

**Comment by freakstatic** [comment]
Ok, thanks for letting me know
