### ISSUE TITLE
Can you update the VCPKG  

### ISSUE THREAD

**Issue by liwei1024** [fnc12/sqlite_orm#792]

**Comment by fnc12** [comment]
I never did it. I don't know how to do it. All previous times it was done by people who needed it like you. I've added 'help wanted' label here

**Comment by longnguyen2004** [comment]
@liwei1024 Please make an issue at https://github.com/microsoft/vcpkg/issues

**Comment by longnguyen2004** [comment]
@fnc12 Also, will there be another tagged version, or is it rolling now?

**Comment by fnc12** [comment]
@longnguyen2004 1.7 will appear soon. During a month for sure

**Comment by fnc12** [comment]
<img width="1347" alt="Снимок экрана 2021-12-15 в 13 57 27" src="https://user-images.githubusercontent.com/6009640/146174355-e937d981-4ab8-49c0-b063-777bf5da0c3a.png">
