### ISSUE TITLE
Cant add `noexcept` to setters & getters

### ISSUE THREAD

**Issue by define-private-public** [fnc12/sqlite_orm#794]
I know that I can have sqlite_orm serialize my enums, but I wanted to do something a little simpler in the meantime and just cast them to/from `int`.  I tried adding this:

```
    int get_status() const noexcept
        { return static_cast<int>(status); }
    void set_status(const int s) noexcept
        { status = static_cast<Status>(s); }
````

But when I added those functions to the `make_column()` call compilation failed.  Right now I'm just removing use of the statement.  But it would be nice to be able to use this keyboard.  If not, then adding a note in the docs would be appreciated.

**Comment by fnc12** [comment]
@define-private-public yes you right - it is got to be fixed. Actually it is a very rare case and nobody asked for it and I did not add `noexcept` support by myself. I'll fix it soon. Thank you

**Comment by fnc12** [comment]
@define-private-public damn looks like it is not supported in VC++ https://ci.appveyor.com/project/fnc12/sqlite-orm/builds/40961551/job/v0o7dmiby35wysl9. What compiler do you use?

**Comment by define-private-public** [comment]
Well that sucks.  Could be a little different for C++17 (https://docs.microsoft.com/en-us/cpp/build/reference/zc-noexcepttypes?view=msvc-160). I use GCC (mostly) and clang.

You could do something like this: https://stackoverflow.com/a/18387764

But I think you then need all of your users to use this `NOEXCEPT` macro to keep their code portable between compilers/platforms.  You could also do this devilish thing:

```
#ifdef _MSC_VER
#define noexcept
#endif
```

Then MSVC would see that as simply nothing.

**Comment by fnc12** [comment]
Ok let me try. Also there are some errors with includes. I'll try to fix it all. Thanks for advices

**Comment by fnc12** [comment]
I've fixed include errors https://ci.appveyor.com/project/fnc12/sqlite-orm/builds/40967896 and now C++14 builds only fail. My idea is to avoid `NOEXCEPT` ugly macro but use `#ifdef C++17`. What do you think? @define-private-public  Do you use C++17 or higher?

**Comment by define-private-public** [comment]
I use C++17, but I think there is still enough people on C++14 though.

I think what you could do something like this:
```
#ifdef _MSC_VER  && C++14
#define noexcept
#endif
```

That way for C++14 on MSVC, the `noexcept` statements will be ignored by the compiler.  I do suggest making a note of this somewhere in the documentation that you are redefining C++ keywords, but make sure to mention why.

**Comment by fnc12** [comment]
I'd like to avoid redefining C++ keywords. Let's try to make this feature for C++17 only. If a lot of people start asking to make it available for C++14 then I'll change it. Also it will motivate people to move from C++14 to C++17

**Comment by fnc12** [comment]
@define-private-public I've merged the PR a minute ago into `dev` branch. Please check it out

**Comment by define-private-public** [comment]
It works! (Thanks!)

Checking the bottom of the readme, you need to update it to say C++17 is now a requirement.

**Comment by fnc12** [comment]
No C++17 is not a requirement cause one can use this lib with C++14. This is the same way how std::optional support works: if you enable C++17 then you have std::optional support in this lib. Otherwise everything works just like std::optional does not exist.
