### ISSUE TITLE
Method update(), cannot compile

### ISSUE THREAD

**Issue by Pwera** [fnc12/sqlite_orm#8]
Playing around API, found new issue.
Method update(), cannot compile on gcc 6.3, Windows 7

I used subentites.cpp from examples code.

https://gist.github.com/Pwera/a6ee8f93db5e24fa02a94393953b8321

**Comment by Pwera** [comment]
**EDIT** Ok, when i remove const declaration it compiles..

**Comment by fnc12** [comment]
@Pwera from where did you removed `const`?

**Comment by Pwera** [comment]
` void update( O &o, sqlite3 *db, typename std::enable_if<std::is_same<O, HH>::value>::type * = nullptr) `
and
`void update( O &o) `

**Comment by fnc12** [comment]
@Pwera this is incorrect - you have to keep library code immutable within your project. I met this error before - I need to remember how I fixed it that time

**Comment by fnc12** [comment]
@Pwera check out the latest commit - bug must be fixed
