### ISSUE TITLE
`sqlite_sequence` table cleared out when doing `sync_schema()`

### ISSUE THREAD

**Issue by define-private-public** [fnc12/sqlite_orm#806]
Right now I've been working on a test application so I can iron out how I'm going to use sqlite_orm in one of my larger projects.  This includes figuring out how to do migrations.  V1 of my DB schema had a table with a `PRIMARY_KEY AUTOINCRMENT` on it.  So I would see a `sqlite_sequence` table generated in the DB.

The issue arose when in V2 of my DB schema, I changed a column in that table, thus making the old rows invalid.  And then In another function I was going to migrate the data by loading a backup V1, re-inserting each row into V2 with the updated data.

Part of the issue is that I noticed the `sqlite_sequence` table was cleared out after the migration.  Shouldn't this be preserved doing a `sync_schema()`?

**Comment by fnc12** [comment]
IDK. How does it work with raw SQLite? `sqlite_orm` does not operate with `sqlite_sequence` straightly. So probably you'll face the same issue with raw SQLite

**Comment by fnc12** [comment]
@define-private-public is the issue actual?

**Comment by define-private-public** [comment]
I think it's worth considering.

**Comment by fnc12** [comment]
as I said everything must work if you use `autoincrement`. Did you try it?

**Comment by define-private-public** [comment]
I don't think I did.  I'm a bit busy with other projects at the moment so I
can't spend time on testing this.  When I do (much later), I'll get back to
you on this.

**Comment by fnc12** [comment]
@define-private-public is the issue actual?

**Comment by fnc12** [comment]
@define-private-public is the issue actual?

**Comment by define-private-public** [comment]
Hi,  what do you mean by " is the issue actual?"  I have not done anything with sqlite_orm in the past few month, as I've been focused on other projects.  I do plan to get back to it.

**Comment by fnc12** [comment]
It was just a bumping. Please write back when you get results. Thanks
