### ISSUE TITLE
MSVC 2015 with c++14

### ISSUE THREAD

**Issue by rocaalc** [fnc12/sqlite_orm#809]
Hi,

Only there are two compiler error if it is used the compiler of visual studio 2015 with /std:c++14 flag.
In master or V1.6:

sqlite_orm-1.6\include\sqlite_orm/sqlite_orm.h(2348): error C2661: 'sqlite_orm::internal::order_by_base::order_by_base': no overloaded function takes 2 arguments
sqlite_orm-1.6\include\sqlite_orm/sqlite_orm.h(6374): error C2440: 'initializing': cannot convert from 'initializer list' to 'sqlite_orm::table_info'

Best

**Comment by fnc12** [comment]
Hi. Can you reproduce it with `dev` branch?

**Comment by rocaalc** [comment]
Fix with --> below:

First compiler error:
Add constructor in order_by_base:
order_by_base(int asc_desc_, std::string _collate_argument_):asc_desc(asc_desc_), _collate_argument(std::move(_collate_argument_)){}


Second compiler error:
Add constructor in table_info:
table_info(decltype(cid) cid_, decltype(name) name_, decltype(type) type_, decltype(notnull) notnull_, decltype(dflt_value) dflt_value_, decltype(pk) pk_):
            cid(cid_), name(std::move(name_)), type(std::move(type_)), notnull(notnull_), dflt_value(std::move(dflt_value_)), pk(pk_) {}

And remove:
res.push_back(table_info{cid, name, type, notnull, dflt_value, pk});
Replaced by:
typedef sqlite_orm::table_info ret_type;
res.push_back(ret_type(cid, name, type, notnull, dflt_value, pk));

**Comment by rocaalc** [comment]
The closed issue #525 is also caused by a necessary constructor in msvc 2015.

**Comment by rocaalc** [comment]
I don't know. Only I reproduce this bug in master branch.
But, it takes me 5 minutes to see the dev branch, I'll see. And... YES! in dev branch is the same issue.

**Comment by fnc12** [comment]
Ok I'll fix it today later. Thanks

**Comment by rocaalc** [comment]
One thing, in dev branch, there is a new function_base without constructor.

**Comment by fnc12** [comment]
@rocaalc the fix is here https://github.com/fnc12/sqlite_orm/pull/812
