### ISSUE TITLE
handling of busy/lock

### ISSUE THREAD

**Issue by tatraian** [fnc12/sqlite_orm#81]
Hello,

I got `std::runtime_error` when on other process also uses the database (read only) and I want to commit my changes. This is absolutely OK according the sqlite3 specification. But I would like to get an interface that gives a way to retry the commit in this case.

I write it and send you a pull request, just I don't know what should be the good solution(s)?
Currently `sqlite_orm` starts deferred transactions (all lock get as late as possible). So you will get exception at commit.

As a first draft, I intoroduced a new exception (`database_locked_exception`) and commit throws this exception if the error code is `SQLITE_LOCKED` or `SQLITE_BUSY`. In this case I get the next user code:

```
auto guard = storage.transaction_guard();
...
for(;;) {
    try {
        guard.commit();
        break;
    } catch(const sqlite_orm::database_locked_exception& ex) {
        LOG("Database busy, wait a bit and retry");
        //sleep or usleep here
    }
}
```

This is very ugly in the view of users, furthermore you use `std::runtime_error` everywhere so probably in this case would be nice to define a root exception for `sqlite_orm` and the locked can inherit from that.

An alternative solution for this (and I think it is better) that `commit` can get a timeout parameter, and this retrying is done by commit itself. If time spent and the commit failed all times then we send the exception.

My problem with the two solutions above that I don't see what helps to avoid the starvation (||: reader arrives, we try -> error, sleep, reader gone :||). I think nothing.

An other solution for this (but I don't deeply understand the description of sqlite3), that `sqlite_orm` enable to set the type of the transaction (deferred, Immediate, exclusive). But I'm not sure that we will blocked until we can acquire the lock or we get busy in the same way.

Maybe you have better general idea for proper handling of this locking. But I think using specialized exceptions makes the library better since there can be situation when you would like to do other things in case of sql error.

**Comment by fnc12** [comment]
Hello. Thats for using the lib. Exceptions will be refactored soon like as described [here](https://github.com/fnc12/sqlite_orm/issues/46). Your problem can be solved with a busy handler which is written down in [todo](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md). Please read about it and tell me whether or not it is ok for you.

**Comment by tatraian** [comment]
Hello,
I think that implementing a `commit_timeout` function should be enough for first time. That simply calls `sqlite3_busy_timeout` (https://sqlite.org/c3ref/busy_timeout.html). Is this OK in this way?

**Comment by fnc12** [comment]
@tatraian what do you mean saying `commit_timeout` function?

**Comment by fnc12** [comment]
@tatraian I got you. `sqlite3_busy_timeout` can be implemented easily but the name will be `busy_timeout` to look similar to sqlite3 C API

**Comment by fnc12** [comment]
@tatraian please check out the latest commit

**Comment by tatraian** [comment]
Thanks a lot! I update my version:)
