### ISSUE TITLE
iterate-like interface but for select with columns

### ISSUE THREAD

**Issue by allspark** [fnc12/sqlite_orm#815]
Hi,

from the join example
```c++
auto rows = storage2.select(columns(&Doctor::id, &Doctor::name, &Visit::patientName, &Visit::vdate),
                            left_join<Visit>(on(c(&Doctor::id) == &Visit::doctorId)));  
for(auto &row : rows) {
    cout << std::get<0>(row) << '\t' << std::get<1>(row) << '\t' << std::get<2>(row) << '\t' << std::get<3>(row) << endl;
}
cout << endl;
```
rows is a `std::vector<std::tuple<Columns...>>`. it would be nice if the same query would be possible with `iterate` to get a view over `std::tuple<Columns...>` instead.

**Comment by juandent** [comment]
Hi!
Are you planning to implement it?

**Comment by trueqbit** [comment]
@allspark If you have the opportunity to test it, this feature has made it into the dev branch.

**Comment by fnc12** [comment]
@allspark I am confirming that @trueqbit merged this feature not so long ago. Please check. I am closing the issue. Please feel free to reopen if something doesn't work the way you expect
