### ISSUE TITLE
build errors from raw insert

### ISSUE THREAD

**Issue by khgreav** [fnc12/sqlite_orm#820]
Hi, I've noticed that a new release is out and wanted to check it out, but I'm getting the following build errors:

```
sqlite_orm.h:10124:25: error: ‘sqlite_orm::internal::is_upsert_clause’ has not been declared
10124 |         using internal::is_upsert_clause;

sqlite_orm.h:10146:68: error: ‘is_upsert_clause’ was not declared in this scope
10146 |         constexpr int upsertClausesCount = count_tuple<args_tuple, is_upsert_clause>::value;

sqlite_orm.h:10146:84: error: template argument 2 is invalid
10146 |         constexpr int upsertClausesCount = count_tuple<args_tuple, is_upsert_clause>::value;

sqlite_orm.h:10147:42: error: non-constant condition for static assertion
10147 |         static_assert(upsertClausesCount <= 2, "Raw insert can contain 2 instances of upsert clause maximum");

sqlite_orm.h:10147:42: error: the value of ‘upsertClausesCount’ is not usable in a constant expression
```

Do I need to take any extra steps from the 1.6 release or is this not on my end?

**Comment by fnc12** [comment]
Hi. Let me check it

**Comment by fnc12** [comment]
Yes looks like a bug. It is strange that appveyor CI passed the checks. You can use not header only version from `not_single_header_include` folder. it works. Header only will be fixed right now in `dev` branch

**Comment by fnc12** [comment]
here is the fix https://github.com/fnc12/sqlite_orm/pull/821. It will be merged today

**Comment by khgreav** [comment]
Thanks, I'll check it out and let ya know.

**Comment by khgreav** [comment]
Adding the forward declarations was enough to make the build pass.

**Comment by fnc12** [comment]
merged to `dev`. Please check it out

**Comment by khgreav** [comment]
Yep, it's fine now, thanks!
