### ISSUE TITLE
updating nullable columns

### ISSUE THREAD

**Issue by khgreav** [fnc12/sqlite_orm#822]
Hi, another quick question.

I prefer the private class members approach and one of the properties is a shared_ptr, when inserting a new record, there is no issue and the nullable value is added. Is it possible to update the value later using the code below or do I have to build a proper statement?

```
auto record = storage.get_all<Class>(constraints...);
record[0].setVal(x);
storage.update(record[0]);
```

The above did not work, but I did not catch any errors. I should also say that this particular table has a 3-column composite key.

**Comment by fnc12** [comment]
Hi. What do you mean 'did not work'? What did you expect and what did you get instead?

**Comment by khgreav** [comment]
So, when I orignally added a new record, it was inserted with a value, then I tried to update the value, but it hasn't changed.

**Comment by fnc12** [comment]
Please provide `make_storage` call and your data model class to be able to reproduce it

**Comment by khgreav** [comment]
```
#include <sqlite_orm/sqlite_orm.h>
#include <iostream>
#include <memory>

using namespace sqlite_orm;

class A {
public:
	A() = default;
	A(const uint8_t &address, const uint8_t &type, const uint8_t &idx, std::shared_ptr<double> value) : address(address), type(type), idx(idx), value(std::move(value)) {};

	const uint8_t& getAddress() const {
		return this->address;
	}

	void setAddress(const uint8_t &address) {
		this->address = address;
	}

	const uint8_t& getType() const {
		return this->type;
	}

	void setType(const uint8_t &type) {
		this->type = type;
	}

	const uint8_t& getIndex() const {
		return this->idx;
	}

	void setIndex(const uint8_t &index) {
		this->idx = index;
	}

	std::shared_ptr<double> getValue() const {
		return this->value;
	}

	void setValue(std::shared_ptr<double> value) {
		this->value = std::move(value);
	}
private:
    uint8_t address;
	uint8_t type;
	uint8_t idx;
	std::shared_ptr<double> value;
};

static auto initExample(const std::string &file) {
	return make_storage(file,
		make_table("A",
			make_column("address", &A::getAddress, &A::setAddress),
			make_column("type", &A::getType, &A::setType),
			make_column("idx", &A::getIndex, &A::setIndex),
			make_column("value", &A::getValue, &A::setValue),
			primary_key(&A::getAddress, &A::getType, &A::getIndex)
		)
	);
}

using Db = decltype(initExample(""));

static void example(const std::string &path) {
	std::unique_ptr<Db> db = std::make_unique<Db>(initExample(path));
	auto res = db->sync_schema();
	db->replace(A(1, 1, 0, std::make_shared<double>(55.5)));
	auto records = db->get_all<A>(
		where(
			c(&A::getAddress) == 1
			and c(&A::getType) == 1
			and c(&A::getIndex) == 0
		)
	);
	if (records.size() != 0) {
		A a = records[0];
		a.setValue(std::make_shared<double>(10));
		db->update(a);
	}
}
```
Here's the full example, just call the example function with a path. I remember some struggles back when I first tried to use pointers here for nullable columns, but it was fine since then.

**Comment by fnc12** [comment]
@khgreav let me try to reproduce it

**Comment by fnc12** [comment]
yeah it reproduced the bug. Give me some time to find a clue

**Comment by fnc12** [comment]
I found a bug inside `update` function. It works incorrectly. Please use `update_all` instead until this bug is fixed. Thank you for reporting

**Comment by khgreav** [comment]
`update_all` works, thanks.

**Comment by fnc12** [comment]
@khgreav fix is here https://github.com/fnc12/sqlite_orm/pull/827

**Comment by fnc12** [comment]
merged into `dev` branch

**Comment by khgreav** [comment]
The provided example still does not work. Value hasn't changed.

I made sure I have a clean build and the latest commit.

`commit 93dd20bb0ca495344cc7578a9ac2407eaf730bda (HEAD, origin/dev)
`

**Comment by fnc12** [comment]
damn. Let me check it out

**Comment by fnc12** [comment]
fix is here https://github.com/fnc12/sqlite_orm/pull/828

**Comment by fnc12** [comment]
merged

**Comment by khgreav** [comment]
Looking good, provided example working as expected now. Thanks.
