### ISSUE TITLE
Tuple passed to scalar/aggregate function should be moved

### ISSUE THREAD

**Issue by trueqbit** [fnc12/sqlite_orm#829]
The tuple from column values extracted by the create_scalar_function()/create_aggregate_function() callbacks are moved up to `call_impl`, but then it is treated as an lvalue, see [tuple_helper.h](https://github.com/fnc12/sqlite_orm/blob/0e32154ae52a1d8cfe1d3f2dd2e293e4c315ea67/dev/tuple_helper/tuple_helper.h#L138).

Shouldn't the tuple be moved again, such that a function could potentially consume the arguments?
The function would look like this:
```C++
        template<class Function, class FunctionPointer, class Tuple, size_t... I>
        auto call_impl(Function& f, FunctionPointer functionPointer, Tuple t, std::index_sequence<I...>) {
            return (f.*functionPointer)(std::get<I>(move(t))...);
        }
```

I discovered this issue because of a custom function where I tried to take the value by rvalue-reference.

**Comment by fnc12** [comment]
Do you want to make a PR with this improvement?

**Comment by fnc12** [comment]
I guess we can close this issue
