### ISSUE TITLE
Amalgamation script must normalize file paths

### ISSUE THREAD

**Issue by trueqbit** [fnc12/sqlite_orm#830]
The amalgamation python script is keeping a list of already included files in order to determine whether it needs to paste an include into the target file _sqlite_orm.h_.
For this to function properly the script must normalize the paths, otherwise the key for the path list might differ during the amalgamation process even when referring to the same file. This leads to files being pasted multiple times.

Consider:
- Differing include paths depending on the directory structure (`#include "../serialize_result_type.h"` vs `#include "serialize_result_type.h"`)
- Combining the include with configured source/include paths leads to a mix of '/' and '\\' path separators on Windows.

Also, an early normalization leads to verbose output being more natural on Windows.

**Comment by fnc12** [comment]
@trueqbit can we close it already?
