### ISSUE TITLE
is there a way to have a sqlite db encrypted?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#838]
I am building a database which has sensitive information. I don't want anyone to be able to read the contents... Is there a way to encrypt the sqlite3 database?

**Comment by fnc12** [comment]
Yes. There is plenty of ways to encrypt your database. You can find a list if them on [SO](https://stackoverflow.com/questions/5669905/sqlite-with-encryption-password-protection). To work with those extensions with `sqlite_orm` storage class has `on_open` member field which is called every time your database is opened and has one argument: a database holder `sqlite3 *db` which can be passed into any encryption functions.
```c++
storage.on_open = [](sqlite3 *db) {
    // call extensions functions here
};
```

**Comment by juandent** [comment]
Can you give an example of how to use on_open to encrypt a db?

**Comment by juandent** [comment]
Does sqlite_orm work with wxSQLite3?

What is needed to configure this?

Regards
Juan

**Comment by fnc12** [comment]
I a not sure about wxSQLite3 cause it collides with `sqlite_orm`. But you can use [SEE](http://www.hwaci.com/sw/sqlite/see.html). All you need to do is to call `sqlite3_key` right after database is open. This is where `on_open` can be useful. Just call `sqlite3_key` right inside `on_open` and everything is done.

**Comment by juandent** [comment]
Unfortunately SEE has a $2000 cost -- do you know of any open source equivalent?

**Comment by fnc12** [comment]
[SQLCipher](https://www.zetetic.net/sqlcipher/sqlcipher-api/) works the same way: call `sqlite3_key` inside `on_open` with a database and your key and that is all.

**Comment by juandent** [comment]
same issue here -- it costs $499 / developer

**Comment by fnc12** [comment]
[botansqlite3
](https://github.com/OlivierJG/botansqlite3/blob/master/test_sqlite.cpp) works the same way and has no license. IDK why.

**Comment by fnc12** [comment]
@juandent did it work?

**Comment by fnc12** [comment]
@juandent did it work?

**Comment by fnc12** [comment]
@juandent did it work?

**Comment by juandent** [comment]
I decided to postpone using the encrypted options so I have no information based on experience. Will let you know if I change my mind

**Comment by fnc12** [comment]
Ok. I bet there is nothing to fix so I'll close the issue

**Comment by juandent** [comment]
I downloaded sqleet and tested it with sqlite_orm and had ONE problem and some learning of the configuration required to make it work. I will explain so it can be easier for another user of sqlite_orm can make it work...

The MAIN problem is that you  have to set the value of storage.on_open BEFORE opening the database which means before calling storage.sync_schema(true or false). Otherwise you get an error and the db is not encrypted!!

Also, you need to clone the github for sqleet say to "C:\\Components\\sqleet" and place this path BEFORE the path for sqlite_orm so the appropiated version of sqlite3.h is used (currently version 3.31.1) and you have to write something like this:

```C++
#define SQLITE_HAS_CODEC 1
#include <sqlite_orm/sqlite_orm.h>
```

so that the special sqlite3.h conditionally defines the keying functions like:

```C++
int rc = sqlite3_key(db, key, keylen);
```

Finally there is the need to link the keying functions which can be easily done by linking sqleet3.c which depends on other sources but are all defined in "C:\\Components\\sqleet"  so can be found by compiler with no problem.

There is NO need at all to #include "sqleet3.h" or any other sqleet component as everything works in the background like a charm (as long as the correct sqlite3.h is compiled with the #define mentioned above).


That's All!!
Now you can encrypt the databases easily!!


Hope this helps!

Regards,
Juan
