### ISSUE TITLE
Request: pragma.application_id

### ISSUE THREAD

**Issue by jahnf** [fnc12/sqlite_orm#839]
Since `get_pragma` and `set_pragma` is private in newer versions of the library, please add support for `application_id`

See: https://www.sqlite.org/pragma.html#pragma_application_id

Thanks for this great library 👍

**Comment by fnc12** [comment]
will be added soon

**Comment by fnc12** [comment]
the feature is [here](https://github.com/fnc12/sqlite_orm/pull/840). Once CI is built successfully I'll merge it

**Comment by fnc12** [comment]
@jahnf BTW what project do you use this lib for?

**Comment by jahnf** [comment]
> the feature is [here](https://github.com/fnc12/sqlite_orm/pull/840). Once CI is built successfully I'll merge it

Awesome, then I don't have to patch the the library locally 👍 

> @jahnf BTW what project do you use this lib for?

It's a non-public project. I am using _sqlite_orm_ in the data management backend of my little pet project "monkey-server", an (automated) trading server that gets data from _Metatrader_. All kinds of data is stored in the backend (historical financial data, trades, users, configurations...)

**Comment by fnc12** [comment]
Wow. Your project sounds very nice. Good luck with it. If you do something public with `sqlite_orm` I'd like you to add your project into project list https://github.com/fnc12/sqlite_orm/issues/783.
Also please consider the license of the library. It was changed since v1.7 https://github.com/fnc12/sqlite_orm/releases/tag/v1.7

**Comment by jahnf** [comment]
> `sqlite_orm` I'd like you to add your project into project list #783. Also please consider the license of the library. It was changed since v1.7 

Understood, my plan is to put parts of the project (the server and utilities part) public (as soon it reaches a code and documentation quality that I feel comfortable publishing)

**Comment by fnc12** [comment]
@jahnf actually it is not necessary to have a public project. I was telling you that using `sqlite_orm` for close source projects costs 50$🤷‍♂️

**Comment by jahnf** [comment]
> @jahnf actually it is not necessary to have a public project. I was telling you that using `sqlite_orm` for close source projects costs 50$🤷‍♂️

Yes, that is understandable - even my small open source project [Projecteur](https://github.com/jahnf/Projecteur) is a lot of work. Will consider this (license and/or put my library parts public) when the private project is at a real usable stage - currently I'm still developing basics of the infrastructure most of the time.

**Comment by fnc12** [comment]
@jahnf of course. Everything is ok. Please take your time. It was just a reminder. Thanks for a feature request.

**Comment by fnc12** [comment]
@jahnf merged into `dev` branch

**Comment by fnc12** [comment]
@jahnf I am closing this issue. If you have any questions or issues please feel free to reopen it or to open a new one. Also if you are not sure whether you must post a new issue you can make a new [discussion](https://github.com/fnc12/sqlite_orm/discussions). It is a stackoverflow like questions feature here on github
