### ISSUE TITLE
Compiling error: error: ‘sqlite_orm::internal::is_upsert_clause’ has not been declared #814 or higher 

### ISSUE THREAD

**Issue by jairoareyes** [fnc12/sqlite_orm#841]
Hi, I'm having problems compiling the recent versions. It works well for me until Merge [#813](https://github.com/fnc12/sqlite_orm/pull/813), the higher versions throws me this error: `sqlite_orm/sqlite_orm.h:10077:25: error: sqlite_orm::internal::is_upsert_clause’ has not been declared
using `internal::is_upsert_clause;`

It seems to be related to the upsert feature, that is indeed what I'm trying to test on my project. What should I do? Is there any other approach to meet upsert? Thanks for your support and your amazing work.

**Comment by fnc12** [comment]
it is fixed in `dev`. Please use `dev` branch

**Comment by jairoareyes** [comment]
`dev` branch shows this error: `sqlite_orm/sqlite_orm.h:6776:28: error: ‘is_convertible_v’ is not a member of ‘std’
         static_assert(std::is_convertible_v<typename T::value_type, const char*>,`

**Comment by fnc12** [comment]
what compiler do you use?

**Comment by jairoareyes** [comment]
I'm using this: `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`

**Comment by fnc12** [comment]
weird things: clang and vc++ works well. Let me fix it

**Comment by fnc12** [comment]
fix is [here](https://github.com/fnc12/sqlite_orm/pull/842). It will be merged into `dev` once CI builds are over with success

**Comment by jairoareyes** [comment]
I'm trying the `on_conflict` but it throws an exception: `near "ON": syntax error: SQL logic error`. I just followed the example.

**Comment by fnc12** [comment]
3.24.0 and higher as it told here https://www.sqlite.org/lang_conflict.html. Probably I need to add `#ifdef`s around `on_conflict` function to prevent events like this in future

**Comment by jairoareyes** [comment]
I updated my sqlite3 version and it worked. Thanks for your kindly support!

**Comment by fnc12** [comment]
Ok nice. I'll add `#ifdef SQLITE_VERSION_NUMBER >= 3024000` anyway to prevent such errors in future

**Comment by juno12560** [comment]
hi, with dev branch, unit_tests fails,
/Users/lishenglong/Code/sqlite_orm/tests/pragma_tests.cpp:38: FAILED:
  REQUIRE( jm == decltype(jm)::OFF )
with expansion:
  3 == 5

btw how long will the stable version be released?

**Comment by fnc12** [comment]
Hi. Looks like journal mode is altered inside a database file in your file system. Check out that file using other SQLite clients. Filename is `journal_mode.sqlite`

**Comment by juno12560** [comment]
`journal_mode.sqlite` was an empty file, I cleared the build dir and recompile again, the issue remains.
