### ISSUE TITLE
update appveyor builds

### ISSUE THREAD

**Issue by trueqbit** [fnc12/sqlite_orm#845]
I have a few points that I'd like to address in regard to appveyor builds that came to my attention.
(I didn't find any suitable category in 'discussions'. Also let me know whether this should be split up in multiple tickets.)

1. @fnc12 Are you set on using Visual C++ 2017 for test builds? Versions up until Visual C++ 2019 16.4 (which is msvc v19.24, toolchain v14.24) have problems forming an integral_constant from a template function specialization, which I wanted to use in the unit tests for the 'pointer passing interface' (see code example on [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:19,endLineNumber:7,positionColumn:19,positionLineNumber:7,selectionStartColumn:19,selectionStartLineNumber:7,startColumn:19,startLineNumber:7),source:'%23include+%3Ctype_traits%3E%0A%23include+%3Cmemory%3E%0A%0A//+Wrap+std::default_delete+in+a+function%0Atemplate%3Ctypename+T%3E%0Avoid+delete_default(std::conditional_t%3Cstd::is_array%3CT%3E::value,+std::decay_t%3CT%3E,+T+*%3E+o)+noexcept(%0A++++noexcept(std::default_delete%3CT%3E%7B%7D(o)))+%7B%0A++++std::default_delete%3CT%3E%7B%7D(o)%3B%0A%7D%0A%0A//+Integral+function+constant+for+default+deletion%0Atemplate%3Ctypename+T%3E%0Ausing+delete_default_t+%3D+std::integral_constant%3Cdecltype(%26delete_default%3CT%3E),+delete_default%3CT%3E%3E%3B%0A%0Aint+main()+%7B%0A++++return+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:vcpp_v19_24_x86,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86+msvc+v19.24+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,fontUsePx:'0',tree:'1',wrap:'1'),l:'5',n:'0',o:'Output+of+x86+msvc+v19.24+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)) - the Visual C++ team addressed many template conformance issues in later version.
2. Macro `_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING` should be passed to the compiler, in order to reduce the unnecessary lengthy multiple warnings in the log output.
3. Since I have introduced conditional C++20 code parts in the 'pointer passing interface' feature - especially the much easier to read concept constraints - I suggest we should add a build environment for C++20 using Visual C++ 2019?
4. Are there any real benefits in having test builds in 'debug' mode?

**Comment by fnc12** [comment]
1. Actually I don't use VS at all. I use Xcode and feel fine. If you can improve VS builds then it will be ok;
2. In what builds? In every build?
3. Yes we should add C++20 using VC++ 2019;
4. No. It was added just in case. We can remove it to increase CI work time

**Comment by trueqbit** [comment]
2. Yes, in every build.
`std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>>` is deprecated since C++17, but there's no replacement yet. There occurs following warning:
> C:\projects\sqlite-orm\include\sqlite_orm/sqlite_orm.h(7643): warning C4996: 'std::codecvt_utf8_utf16<wchar_t,1114111,0>': warning STL4017: std::wbuffer_convert, std::wstring_convert, and the <codecvt> header (containing std::codecvt_mode, std::codecvt_utf8, std::codecvt_utf16, and std::codecvt_utf8_utf16) are deprecated in C++17. (The std::codecvt class template is NOT deprecated.) The C++ Standard doesn't provide equivalent non-deprecated functionality; consider using MultiByteToWideChar() and WideCharToMultiByte() from <Windows.h> instead. You can define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

Do you know how to pass additional compiler macros in _appveyor.yml_?

**Comment by fnc12** [comment]
I guess we can add compiler flags to this line:
`  - cmake %SQLITE_ORM_CXX_STANDARD% -DSqliteOrm_BuildTests=ON .. -G %generator% -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake` using `-DFLAG`

**Comment by trueqbit** [comment]
All points were integrated into the #844 pointer-passing_examples PR. If you agree we can close this ticket.
