### ISSUE TITLE
Bindable expressions in order-by clauses don't get bound

### ISSUE THREAD

**Issue by trueqbit** [fnc12/sqlite_orm#847]
Bindable expressions in order-by clauses are serialized correctly but don't get bound when executing the statement.
This is because `ast_iterator<order_by_t>` is missing, which I assume is an oversight?

Consider this simple example for exposition:
> auto stmt = storage.prepare(
>     select(c(&Result::errorValue) == 0, order_by(c(&Result::errorValue) == 0))
> );

**Comment by fnc12** [comment]
Yes it is an oversight
