### ISSUE TITLE
[Question] Keeping reference to object returned by make_storage?

### ISSUE THREAD

**Issue by CarvellWakeman** [fnc12/sqlite_orm#85]
I've been trying to use this ORM in a system I'm working on. It has a handful of objects and an API which is used to get and set them. I have a static class set up which will manage the database and provide public functions for the API to call. Is there any way to call make_storage to build/read the database when the program starts, but maintain a reference to it for use in my static class?

Or should I be calling make_storage every time I want to access the database?

Example:
```
auto DataParser::get_database()
{
    // Build schema
    return make_storage("db.sqlite",
        make_table("zones",
            make_column("id",
                        &Zone::id,
                        primary_key()),
            make_column("name",
                        &Zone::name))); // Missing profile table to keep example short
}
void DataParser::write_zone(Zone* z)
{
    // Get database object
    auto db = get_database();

    // Write data
    int id = storage.insert(*z);
}
void DataParser::write_profile(Profile* p)
{
    // Get database object
    auto db = get_database();

    // Write data
    int id = storage.insert(*p);
}
```

I am unsure of the best practices here. I would appreciate any insight.

Thanks

**Comment by fnc12** [comment]
Yes you can keep a value of storage. It is simple. Please look through [update.cpp](https://github.com/fnc12/sqlite_orm/blob/master/examples/update.cpp) example

**Comment by CarvellWakeman** [comment]
Thank you, that helps!
