### ISSUE TITLE
Validating pointer value types

### ISSUE THREAD

**Issue by trueqbit** [fnc12/sqlite_orm#851]
Now that sqlite_orm features the neat 'pointer-passing interface' a bonus would be to validate the bound pointer types against the function arguments.

In order to prevent pointer leaks, the sqlite engine itself checks whether a bound pointer's type string equals a function argument's pointer type string.

We can achieve this at compilation time when creating the `function_call<>` node.

**Comment by fnc12** [comment]
@trueqbit is this issue actual?

**Comment by trueqbit** [comment]
Since the PR has been merged we can close this issue, unless you have experienced other compilation issues...
