### ISSUE TITLE
how use sqlite_orm in singleton class

### ISSUE THREAD

**Issue by perfeshnal** [fnc12/sqlite_orm#862]
hello
Thanks you for this great library.
I have issue in my singleton class and i can't find any solution

**this is my class header**

```
class AppDb
{
private:
    AppDb() {}
    auto IOpenConnection();

public:
    AppDb(const AppDb&) = delete;
    AppDb(AppDb&&) = delete;
    AppDb& operator=(const AppDb&) = delete;
    AppDb& operator=(AppDb&&) = delete;

    static AppDb& Get()
    {
        static AppDb instance;
        return instance;
    }

    static auto OpenConnection() { return Get().IOpenConnection(); };
};
```
**and this is cpp file**
```
auto AppDb::IOpenConnection()
{
	auto storage = make_storage("db.sqlite",
		make_table("UserTbl",
			make_column("Id", &User::Id, primary_key()),
			make_column("Name", &User::Name),
			make_column("Family", &User::Family))
	);

	if (std::filesystem::exists("db.sqlite")) {
		return storage;

	}
	else {
		storage.sync_schema();
		return storage;
	}
}
```
```
cannot deduce the return type of function "AppDb::IOpenConnection" (declared at line 50); it has not been defined
'AppDb::IOpenConnection': a function that returns 'auto' cannot be used before it is defined
```
I have these errors
sorry, I'm very new in c++
Thank you for your help

**Comment by fnc12** [comment]
`auto IOpenConnection();` is not a valid expression. You need to replace `auto` with a type. To know how to get a type you have to read [FAQ](https://github.com/fnc12/sqlite_orm/wiki/FAQ) first

**Comment by perfeshnal** [comment]
thanks for your response. I read this FAQ before but I don't know how I should use it in my situation.
can you guide me or change my code please?

**Comment by fnc12** [comment]
of course I can. But tell me first what project do you use this lib for.

**Comment by perfeshnal** [comment]
It is currently a project to learn how to use SQLite in c++ and get information from the user

**Comment by fnc12** [comment]
ok nice. So answering your question: the simplest way of getting storage type is moving `make_storage` inside `initStorage` function and getting its' return type using `decltype` operator:
```c++
struct Employee {
    int id;
    std::string name;
    int age;
    std::string address;
    double salary;
};

inline auto initStorage(const std::string &path) {
    using namespace sqlite_orm;
    return make_storage(path,
                        make_table("COMPANY",
                                   make_column("ID",
                                               &Employee::id,
                                               primary_key()),
                                   make_column("NAME",
                                               &Employee::name),
                                   make_column("AGE",
                                               &Employee::age),
                                   make_column("ADDRESS",
                                               &Employee::address),
                                   make_column("SALARY",
                                               &Employee::salary)));
}

using Storage = decltype(initStorage(""));

Storage storage = initStorage("storage.sqlite");
```

**Comment by perfeshnal** [comment]
You repeated the same FAQ
I don't know how to use it in my class

**Comment by fnc12** [comment]
Yes I did cause it is the best way of describing the solution. Do you have a `make_storage` call in your code?

**Comment by perfeshnal** [comment]
I put all the code to use for create database in above 
statically call AppDb::OpenConnection in the main file of the program to create a database
I used "sqlite3.h" like this before

**Comment by perfeshnal** [comment]
I think I should go back to using "sqlite3.h" directly again

**Comment by fnc12** [comment]
ok. If you'll change your mind you'd better learn about function `auto` return type in C++. It will help
