### ISSUE TITLE
`C2039`: `is_upsert_clause` - is not a member of `sqlite_orm::internal`

### ISSUE THREAD

**Issue by ay0ks** [fnc12/sqlite_orm#874]
(File: https://github.com/fnc12/sqlite_orm/blob/master/include/sqlite_orm/sqlite_orm.h, Line: 10177)
```c++
...
10170 |    internal::insert_raw_t<Args...> insert(Args... args) {
10171 |        using args_tuple = std::tuple<Args...>;
10172 |        using internal::count_tuple;
10173 |        using internal::is_columns;
10174 |        using internal::is_insert_constraint;
10175 |        using internal::is_into;
10176 |        using internal::is_select;
10177 |------> using internal::is_upsert_clause; <---------------
10178 |        using internal::is_values;
...
```

**Comment by ay0ks** [comment]
Also found out that problem is only in `include/sea_orm/sea_orm.h` file, `not_single_header_include/sqlite_orm/sea_orm.h` with `dev` files work normally.

**Comment by fnc12** [comment]
what is `sea_orm`?

**Comment by fnc12** [comment]
yes there was a bug. BTW this is third or even fourth same issue. Please pull `master` again or use `dev`. I've made a patch release https://twitter.com/sqlite_orm/status/1475170380423782400?s=21
