### ISSUE TITLE
Will you have releases?

### ISSUE THREAD

**Issue by stevebroshar** [fnc12/sqlite_orm#88]
We are very interested in using this. We would feel more comfortable using a release -- a set of code that draws a line in the sand WRT development/testing... Will you have releases?

**Comment by fnc12** [comment]
Yes, I'm going to add releases and post 1.0 release in the nearest future. But first I need to perform a stabilization and break compatibility with current version in `update_all` and exceptions. Once it's done version 1.0 will be released and next features a going to be created using branches and other 'by the book' stuff.
Thanks for using it.

**Comment by stevebroshar** [comment]
Cool. The timing may work out well. We have to upgrade our compiler before we can use this. And that will take some time. Hopefully, you'll have a release by the time we've upgraded our compiler.

**Comment by fnc12** [comment]
@stevebroshar I'll try to perform release ASAP

**Comment by fnc12** [comment]
@stevebroshar  https://github.com/fnc12/sqlite_orm/releases
