### ISSUE TITLE
storage.has_dependent_rows(rec) does not compile for rec having one foreign key!

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#880]
For a class R with one foreign key referencing a class Fondo, the call:

```C++
R r;
storage.has_dependent_rows(r);
```

compiles with these errors:

```C++
sqlite_orm.h(18200,93): error C2440: '.*': cannot convert from 'const O *' to 'const Fondo *'
with
        [
            O=R
       ]
error C2647: '.*': cannot dereference a '_T39' on a 'const O'

 with
        [
            _T39=int Fondo::* const
        ]
        and
        [
            O=R
        ]
```

Please try this on any class R with one foreign key referencing a class Fondo. It should be inmediate!

I suspect that the const on the pointer in the line with _T39 is to blame...

The other possibility is that in the first error Fondo should be R!! Of course cannot convert const O* to const Fondo* since O is R!! This is probably a typo...

BTW I think this function has some bugs because it has had very little use... please confirm

Thanks,
Juan Dent

**Comment by fnc12** [comment]
Please add your schema and structs code. I need to repro it. Thanks

**Comment by juandent** [comment]
just try this with any table R with foreign keys:

```C++
R r;
storage.has_dependent_rows(r);
```

and compile ... you will see the problem immediately

**Comment by juandent** [comment]
```C++
struct Fondo
{
	int id;
	std::string abreviacion;
	std::string nombre;
	int tipo_cupon;

	enum TipoCupon
	{
		mensual = 1, trimestral = 3
	};


	std::string simple_dump() const
	{
		std::string str = std::to_string(id) + " - "s + abreviacion + " - "s + nombre + " "s + std::to_string(tipo_cupon);
		return str;
	}
};


struct Inversion
{
	int id;
	int num_participaciones;
	std::chrono::sys_days beginning_date;
	int fkey_fondo;

	std::string simple_dump() const
	{
		std::string str = std::to_string(id) + " - "s + std::to_string(fkey_fondo) + " "s + Util::to_string(beginning_date) + " "s + std::to_string(num_participaciones);
		return str;
	}

	static int num_participaciones_en(int fondo, std::chrono::year_month_day fecha) noexcept;
};

struct Rendimiento
{
	int id;
	int fkey_fondo;
	double rendimiento_unitario;
	std::chrono::sys_days fecha;

	std::string simple_dump() const
	{
		std::string str = std::to_string(id) + " - "s + std::to_string(fkey_fondo) + " "s + Util::to_string(fecha) + " "s + std::to_string(rendimiento_unitario);
		return str;
	}


	static double get_rendimiento_unitario(int fondo, std::chrono::year_month_day fecha) noexcept;

};


static auto storage =
		make_storage(db_name,
			make_table("Fondos",
				make_column("id_fondo", &Fondo::id, autoincrement(), primary_key()),
				make_column("nombre", &Fondo::nombre),
				make_column("abrev", &Fondo::abreviacion),
				make_column("tipo_cupon", &Fondo::tipo_cupon)),
			make_table("Inversiones",
				make_column("id_inversion", &Inversion::id, autoincrement(), primary_key()),
				make_column("fkey_fondo", &Inversion::fkey_fondo),
				make_column("begin_date", &Inversion::beginning_date),
				make_column("num_participaciones", &Inversion::num_participaciones),
				foreign_key(&Inversion::fkey_fondo).references(&Fondo::id)),
			make_table("Rendimientos",
				make_column("id_rendimiento", &Rendimiento::id, autoincrement(), primary_key()),
				make_column("fecha", &Rendimiento::fecha),
				make_column("rend_unitario", &Rendimiento::rendimiento_unitario),
				make_column("fkey_fondo", &Rendimiento::fkey_fondo),
				foreign_key(&Rendimiento::fkey_fondo).references(&Fondo::id)));
```

**Comment by fnc12** [comment]
IDK why it doesn't work. This code works for me:
```c++
struct Fondo
        {
            int id;
            std::string abreviacion;
            std::string nombre;
            int tipo_cupon;

            enum TipoCupon
            {
                mensual = 1, trimestral = 3
            };


            std::string simple_dump() const
            {
                using namespace std::string_literals;
                std::string str = std::to_string(id) + " - "s + abreviacion + " - "s + nombre + " "s + std::to_string(tipo_cupon);
                return str;
            }
        };


        struct Inversion
        {
            int id;
            int num_participaciones;
//            std::chrono::sys_days beginning_date;
            int fkey_fondo;

            std::string simple_dump() const
            {
                using namespace std::string_literals;
                std::string str = std::to_string(id) + " - "s + std::to_string(fkey_fondo) + " "s/* + Util::to_string(beginning_date) + " "s*/ + std::to_string(num_participaciones);
                return str;
            }

//            static int num_participaciones_en(int fondo, std::chrono::year_month_day fecha) noexcept;
        };

        struct Rendimiento
        {
            int id;
            int fkey_fondo;
            double rendimiento_unitario;
//            std::chrono::sys_days fecha;

            std::string simple_dump() const
            {
                using namespace std::string_literals;
                std::string str = std::to_string(id) + " - "s + std::to_string(fkey_fondo) + " "s + /*Util::to_string(fecha) + " "s +*/ std::to_string(rendimiento_unitario);
                return str;
            }


//            static double get_rendimiento_unitario(int fondo, std::chrono::year_month_day fecha) noexcept;

        };


        auto storage =
                make_storage({},
                    make_table("Fondos",
                        make_column("id_fondo", &Fondo::id, autoincrement(), primary_key()),
                        make_column("nombre", &Fondo::nombre),
                        make_column("abrev", &Fondo::abreviacion),
                        make_column("tipo_cupon", &Fondo::tipo_cupon)),
                    make_table("Inversiones",
                        make_column("id_inversion", &Inversion::id, autoincrement(), primary_key()),
                        make_column("fkey_fondo", &Inversion::fkey_fondo),
//                        make_column("begin_date", &Inversion::beginning_date),
                        make_column("num_participaciones", &Inversion::num_participaciones),
                        foreign_key(&Inversion::fkey_fondo).references(&Fondo::id)),
                    make_table("Rendimientos",
                        make_column("id_rendimiento", &Rendimiento::id, autoincrement(), primary_key()),
//                        make_column("fecha", &Rendimiento::fecha),
                        make_column("rend_unitario", &Rendimiento::rendimiento_unitario),
                        make_column("fkey_fondo", &Rendimiento::fkey_fondo),
                        foreign_key(&Rendimiento::fkey_fondo).references(&Fondo::id)));
        storage.sync_schema();
        Fondo fondo;
        storage.has_dependent_rows(fondo);
```
I've commented std::chrono stuff cause Xcode doesn't have it

**Comment by juandent** [comment]
Yes but try the function call with inversion or rendimiento not with fondo!!

Fondo works because it does not have foreign keys!!

The others don’t work

Regards
Juan Dent

**Comment by fnc12** [comment]
Ok. But why do you call `has_dependent_rows` with `Inversion` and `Rendimiento`? There is no table referencing to `Inversion` and `Rendimiento` so you do not have to check whether something have references to it. You need to call `has_dependent_rows` with el fondo cause you need to check whether any `Inversion` or `Rendimiento` have any references to specified fondo before removal.

**Comment by juandent** [comment]
What happens if Rendimiento::fkey_fondo is a dangling reference? How do we know if it is safe to store Rendimiento?
Also, what if there was another table X that referenced Rendimiento? Since Rendimiento has a foreign key it is not going to allow function storage.has_dependent_rows(rendimiento) to compile!!

**Comment by fnc12** [comment]
> What happens if Rendimiento::fkey_fondo is a dangling reference?

Same that happens if some FK equals not existing ID in raw SQLite. You will get 0 rows if you try to get el fondo with id stored inside `Rendimiento::fkey_fondo` column.

Actually you must not get any invalid FK value while you use `sqlite_orm` cause `storage` enabled `PRAGMA foreign_key = 1` on every connection opening if your schema has at least on FK. So if you try to insert a `Rendimiento` with invalid FK you will get an exception instead of inserting. The database is protected well.

> Also, what if there was another table X that referenced Rendimiento?

Then it will compile well. It doesn't compile cause it doesn't have any FKs.

**Comment by juandent** [comment]
>what if there was another table X that referenced Rendimiento?
Then it will compile well. It doesn't compile cause it doesn't have any FKs.

Id does not. Lets add a table X for class X that has a foreign_key to Rendimiento::id. Compiler error occurs when doing

```C++
X x;
storage.has_dependent_rows(x);
```

To verify it add the following struct X:

```C++
struct X
{
	int id;
	int fkey_Rendimiento;
};
```

and add the following to make_storage():

```C++
			make_table("X",
				make_column("id_X", &X::id, autoincrement(), primary_key()),
				make_column("fkey_rendimiento", &X::fkey_Rendimiento),
				foreign_key(&X::fkey_Rendimiento).references(&Rendimiento::id))
```


You can now verify that it is impossible to check dependent rows for X since the function does not compile!

Also, has_dependent_rows does not test existence of target of FK (i.e. Rendimiento::id for X::fkey_rendimiento), while my code did this (in a function called foreignKeysExist()  of class TableConnections) so your function does  not have 100% of my needs as you claimed...

Can you confirm this?

Thanks

**Comment by fnc12** [comment]
Hmmm. Looks like `has_dependent_rows` works only for the first table. Let me check it

**Comment by juandent** [comment]
It works on the first table because it has no foreign keys....

**Comment by fnc12** [comment]
Ok looks like the bug exist. But I cannot understand why do you call `storage.has_dependent_rows(x);`? What do you expect to get? I mean there are zero tables with FKs with references to X but you are checking whether someone has references to X. Probably we have different understanding in how `has_dependent_rows` must work

**Comment by juandent** [comment]
My conceptuial mistake because of my impatience. You are correct... The point I was trying to make is that the moment a table has at least one FK, then instances of that table's class cannot be called as arguments to ```has_dependent_rows``` (i.e. ```X x; storage.has_dependent_rows(x);``` does not compile. Of course we need at least another table that references X to make calling the function a logical choice. You are completely correct... I thought your function would verify the validity of X::fkey_rendimiento existing as a record in Rendimiento but your function's name is very clear so that's my mistake...

I wanted has_dependent_rows to do something else aside from checking dependent rows: to check that the FKs in the record passed have valid targets in the corresponding PKs. Your title makes sense because it says "dependent_rows" but I wanted to verify the FKs were not dangling - something your function does not test and shouldn't because its name is very clear.

Sorry again for the mistake here.... at least I proved what I wanted: that presence of at least one FK in a table makes it impossible to check dependent rows for that table cause it does not compile.

Thanks

**Comment by fnc12** [comment]
Ok thanks for describing our thoughts. One more question: why are you talking about dangling references? How do you expect them to appear in your database? AFAIK the only way dangling references (invalid FKs) can appear if you open your database with any SQLite client (not `sqlite_orm`), forget to enable `PRAGMA foreign_keys` and add invalid FK manually.

**Comment by juandent** [comment]
Well if you make a mistake assigning a FK from something different than a PK of the target table's records - pretty unlikely I must admit! I now realize there is no reason to worry about this happening since it should be caught in the early stages of development

Oh well, we learn something every day: Thanks indeed!!

**Comment by fnc12** [comment]
Thanks to you - your issues make this lib even better! I am going on with the bug right now.

**Comment by fnc12** [comment]
@juandent I've fixed compilation. Please check out `dev` branch

**Comment by juandent** [comment]
Just did!!! Great work, thank you!!
