### ISSUE TITLE
Error in tests\select_constraints_tests.cpp

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#888]
Hi Eugene,

I believe I  have found an error in the above test file... The code is in TEST_CASE("Exists"):

```C++
auto rows = storage.select(
    &User::id,
    where(exists(select(&Visit::id, where(c(&Visit::time) == 200000 and eq(&Visit::userId, &User::id))))));
```

which generates a valid but semantically incorrect SQL query:

```SQL
SELECT "users"."id" 
FROM 'users', 'visits' 
WHERE (EXISTS (
    SELECT "visits"."id" 
    FROM 'users', 'visits' 
    WHERE ((("visits"."time" = 20000) AND ("visits"."userId" = "users"."id")))))
```

which does a cross join since users and visits are not joined not even via a WHERE statement!
The result is that rows is a vector with 10 elements (2 Users X 5 Visits) and I think your idea was to get only the users.id where 
they had a visits.time == 20000 which should return only 1 row!!

Only user.id == 1 has a visit with time 20000

```C++
storage.replace(Visit{4, 1, 200000});
```

The error is in the generation of the query...

I tried this but returns both user rows so it doesn't filter anything: (as if exists returns true always)

```C++
    using als_v_o = alias_a<Visit>;   // outer SQL
    using als_u_o = alias_b<User>;    // outer SQL
    using als_v_i = alias_c<Visit>;   // inner SQL
    using als_u_i = alias_z<User>;    // inner SQL

    auto rr = storage.select(
        columns(alias_column<als_u_o>(&User::id),
                alias_column<als_v_o>(&Visit::id),
                alias_column<als_v_o>(&Visit::time)),
        from<als_u_o, als_v_o>(),
        where(exists(select(alias_column<als_v_i>(&Visit::id),
                            from<als_v_i, als_u_i>(),
                            where(c(alias_column<als_v_i>(&Visit::time)) == 200000 and
                                  eq(alias_column<als_v_i>(&Visit::userId), alias_column<als_u_i>(&User::id)) and
                                  eq(alias_column<als_v_o>(&Visit::id), alias_column<als_v_i>(&Visit::id)))))));
```

Please help!

Regards,
Juan

**Comment by fnc12** [comment]
Hi Juan. Let me check it

**Comment by juandent** [comment]
great!!
thank you!

**Comment by juandent** [comment]
any progress?

**Comment by fnc12** [comment]
I need some time.
You can include selects inside selects by any amount of levels

**Comment by juandent** [comment]
but if this 2 levels doesn't work I would abtain from trying more levels...

> I need some time

certainly!!

**Comment by fnc12** [comment]
Yeah I need to investigate it. BTW you can use explicit `from` in case implicit works not as expected

**Comment by juandent** [comment]
I am using  explicit from in the 2 levels...

**Comment by fnc12** [comment]
Juan, code 
```c++
    auto rows = storage.select(
        &User::id,
        where(exists(select(&Visit::id, where(c(&Visit::time) == 200000 and eq(&Visit::userId, &User::id))))));
```
is intended to generate SQL query like this:
```sql
SELECT "users"."id" 
FROM 'users', 'visits' 
WHERE (EXISTS (SELECT "visits"."id" FROM 'users', 'visits' WHERE ((("visits"."time" = 20000) AND ("visits"."userId" = "users"."id")))))
```
because implicit from algorithm collects all table included in all select arguments. It does not look like a bug

**Comment by juandent** [comment]
I disagree... the inner selects is incorrectly independent from the outer and is always true!!

**Comment by juandent** [comment]
the correct SQL in slite_orm is:

```C++
    auto rr = storage.select(
        columns(alias_column<als_u_o>(&User::id),
                alias_column<als_v_o>(&Visit::id),
                alias_column<als_v_o>(&Visit::time)),
        from<als_u_o>(), join<als_v_o>(on(is_equal(alias_column<als_v_o>(&Visit::userId ), alias_column<als_u_o>(&User::id)))),
        where(exists(select(alias_column<als_v_i>(&Visit::id),
                            from<als_v_i, als_u_i>(),
                            where(c(alias_column<als_v_i>(&Visit::time)) == 200000 and
                                  eq(alias_column<als_v_i>(&Visit::userId), alias_column<als_u_i>(&User::id)) and
                                  eq(alias_column<als_v_o>(&Visit::id), alias_column<als_v_i>(&Visit::id)))))));
```
rr has only one row as expected...

However the produced SQL string is: 

```SQL
SELECT 'b'."id", 'a'."id", 'a'."time" FROM 'users' 'b' JOIN  'visits' 'a' ON ('a'."userId" = 'b'."id")  WHERE (EXISTS (SELECT 'c'."id" FROM 'visits' 'c', 'users' 'z' WHERE (((('c'."time" = ?) AND ('c'."userId" = 'z'."id")) AND ('a'."id" = 'c'."id")))))
```

which does not return any rows by using DB Browser for SQLITE (so??? its wrong then...)
sqlite_orm works fine but the created SQL string does not return any rows when executed in sqlite client such as sqlite3.exe


?

**Comment by fnc12** [comment]
> I disagree... the inner selects is incorrectly independent from the outer and is always true!! It should return only one row the user with visit.time == 20000

It is not about what it returns cause `sqlite_orm` doesn't control what SQLite engine returns. It is about how queries are serialized. So serialization of 
```c++
auto rows = storage.select(
    &User::id,
    where(exists(select(&Visit::id, where(c(&Visit::time) == 200000 and eq(&Visit::userId, &User::id))))));
```
to
```sql
SELECT "users"."id" 
FROM 'users', 'visits' 
WHERE (EXISTS (
    SELECT "visits"."id" 
    FROM 'users', 'visits' 
    WHERE ((("visits"."time" = 20000) AND ("visits"."userId" = "users"."id")))))
```
is correct. If you want to replace `FROM 'users', 'visits' ` to `FROM 'users'` on top level the write
```c++
auto rows = storage.select(
    &User::id,
    from<User>(),
    where(exists(select(&Visit::id, where(c(&Visit::time) == 200000 and eq(&Visit::userId, &User::id))))));
``` 
instead.

Same with the inner select.
```c++
select(&Visit::id, where(c(&Visit::time) == 200000 and eq(&Visit::userId, &User::id)))
```
means
```sql
SELECT "visits"."id" 
FROM 'users', 'visits' 
WHERE ((("visits"."time" = 20000) AND ("visits"."userId" = "users"."id")))
```
because line of code `select(&Visit::id, where(c(&Visit::time) == 200000 and eq(&Visit::userId, &User::id)))` includes both `User` and `Visit`. If you want this query to have only one from please use explicit from:
```c++
select(&Visit::id, from<User>(), where(c(&Visit::time) == 200000 and eq(&Visit::userId, &User::id)))
```
which will produce SQL like this:
```sql
SELECT "visits"."id" 
FROM 'users'
WHERE ((("visits"."time" = 20000) AND ("visits"."userId" = "users"."id")))
```

> Besides SELECT "users"."id" FROM 'users', 'visits' is a CROSS JOIN, tables are not joined anywhere thus it returns 10 rows (2 users X 5 visits) which is incorrect!

Yes it is a cross join. It is intended to be like this if you omit explicit from.

**Comment by juandent** [comment]
I understand ... it was my mistake putting Visit::time == 20000 instead of 200000 - that's why the SQL did not return rows when outside of sqlite_orm.
However i don't think it is logical for 
```SQL
auto rows = storage.select(
    &User::id,
    where(exists(select(&Visit::id, where(c(&Visit::time) == 200000 and eq(&Visit::userId, &User::id))))));
```
to serialize to:
```SQL
SELECT "users"."id" 
FROM 'users', 'visits' 
WHERE (EXISTS (
    SELECT "visits"."id" 
    FROM 'users', 'visits' 
    WHERE ((("visits"."time" = 20000) AND ("visits"."userId" = "users"."id")))))
```

because there is no mention of visits columns in the outer select, only in the inner. So the default should be 

```SQL
SELECT "users"."id" 
FROM 'users' 
WHERE (EXISTS (
    SELECT "visits"."id" 
    FROM 'users', 'visits' 
    WHERE ((("visits"."time" = 20000) AND ("visits"."userId" = "users"."id")))))
```

As to the intended behavior I already corrected it. So, there is no bug per se, only an unintuitive serialization involving a table not being used in the outer select... we shouldn't need to use an explicit form if the serialization did not include unused tables... do you see my point?

Regards,
Juan

**Comment by fnc12** [comment]
Yeah I see your point. It seems right from the first sight but initially it worked as you say and there was a bug about that - user could not make a correct serialization cause one of tables was not included in `FROM` section. The bug was related to implicit `FROM` algorithm: it did not search inside subselects. So I fixed it to make it work and added explicit from later. So this is the only way I see of making everyone feel good. If you know another way please share it with me.

**Comment by juandent** [comment]
> The bug was related to implicit FROM algorithm: it did not search inside subselects.

but my point is it shouldn't search inside subselects!! they are independent

**Comment by fnc12** [comment]
> but my point is it shouldn't search inside subselects!! they are independent -- if you want to search subselects then apply the from algorithm to the subselect serialization not the outer select!

yeah and it leads to another bug

**Comment by juandent** [comment]
May i suggest you change the example for the EXISTS Test Case in tests\select_constraints_tests.cpp to something that makes more sense like:

```C++
    auto rows = storage.select(
        &User::id,
        from<User>(), join<als_v_o>(on(is_equal(alias_column<als_v_o>(&Visit::userId), &User::id))),
        where(exists(select(&Visit::id,
            from<Visit, User>(),
            where(c(&Visit::time) == 200000 and
                eq(&Visit::userId, &User::id) and
                eq(alias_column<als_v_o>(&Visit::id), &Visit::id))))));
```

the problem with your current example is that the exists subselect always returns true while this one only returns true for Visit.time == 200000

It illustrates the reason for an exists subselect rather just some correct syntax but pointless semantic...

**Comment by fnc12** [comment]
Ok. I'll do it. Thanks

**Comment by fnc12** [comment]
@juandent what is `als_v_o`? I get compilation errors about it

**Comment by juandent** [comment]
It's just:

```C++
using als_v_o = alias_a<Visit>;   // outer SQL
```

sorry!!
