### ISSUE TITLE
How declare a variable for a storage?

### ISSUE THREAD

**Issue by stevebroshar** [fnc12/sqlite_orm#89]
First, this seems like an awesome library.

I am struggling with how to declare a variable for a storage.  I can create a storage with make_storage. And I've used that to create/access a DB file. Now, I want to create my storage and cache it as a private in my class. Like this:

```
  class DataAccess{
    private:
      Storage _storage;
  }
```

And I found an example for declaring a type like this:

```
typedef decltype(CreateStorage("")) Storage;
```

But, to do that I have to put my CreateStorage() into the header -- which seems undesirable. And, the compiler complains anyway that the type cannot be declared like that. Consider this code:

```
class OrmTest{
    struct Thing {
        long long ID;
        int Count;
    };
    static auto CreateStorage(const std::string& filePath)
    {
        auto storage = make_storage(filePath,
            make_table("Thing",
                make_column("ThingID",
                    &Thing::ID,
                    autoincrement(),
                    primary_key()),
                make_column("Count",
                    &Thing::Count)));
        return storage;
    };

    typedef decltype(CreateStorage("")) Storage;
};
```

I get this from the compiler:

> g++ -std=c++1y -I"/home/user/workspace/sqlite-test/src/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/orm-class-test.d" -MT"src/orm-class-test.d" -o "src/orm-class-test.o" "../src/orm-class-test.cpp"
> ../src/orm-class-test.cpp:28:22: error: use of ‘static auto OrmTest::CreateStorage(const string&)’ before deduction of ‘auto’
>      typedef decltype(CreateStorage("")) Storage;
>                       ^
> ../src/orm-class-test.cpp:28:22: error: use of ‘static auto OrmTest::CreateStorage(const string&)’ before deduction of ‘auto’

**Comment by fnc12** [comment]
`auto` static function works pretty badly with non-clang compilers (g++ & vc++). So the best option is using raw global function marked as `inline`. For example:
```c++
inline auto initStorage(const std::string &path){
    using namespace sqlite_orm;
    return make_storage(path, make_table(...), ...);
}

using Storage = decltype(initStorage(""));
```

This code snippet can be located in a separate file called `Storage.hpp` if you wish.

**Comment by fnc12** [comment]
@stevebroshar I've added article with this case in [FAQ](https://github.com/fnc12/sqlite_orm/wiki/FAQ). Is the issue clear?
