### ISSUE TITLE
can't put like inside a check clause!

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#890]
Hi Eugene,

Looking at your file: tests\constraints\check.cpp a check with like inside throws an exception on sync_schema:

```C++
        auto storage = make_storage({},
                                    make_table("BOOK",
                                               make_column("Book_id", &Book::id, primary_key()),
                                               make_column("Book_name", &Book::name),
                                               make_column("Pub_name", &Book::pubName),
                                               make_column("PRICE", &Book::price, check(c(&Book::price) > 0)),
                                               check(like(&Book::pubName, "M%"))));
        storage.sync_schema();       // throws exception here!!!
```

is this intended?? is there a workaround? are there other limitations as to what operator you can use in a check clause?

I am going through all your tests because I am creating a course about sqlite_orm!!

Regards,
Juan

**Comment by fnc12** [comment]
Hi Juan. Let me check it. It must work.

Course is nice. Where are you going to publish it?

**Comment by juandent** [comment]
I was going to publish it in a Costa Rican academic magazine but the document is large (some 30+ pages) so I decided that a set of 3 small courses would be a better way and I have the support of the founders of the most important computer science private university in the country so I expect an impact will be felt! Your beautiful library will go 1st place if I make it!! I want to ask for some support in this endeavor, if I may... BTW when are you coming to Costa Rica? for how long and where?

**Comment by fnc12** [comment]
Wow it sounds very nice! I'd love to provide support for you. What support so you need?

Situation with Costa Rica is still undefined. Wither I go in one or two months or at the end of the year. It depends on whether I will do all my stuff in Almaty before rainy season starts at Costa Rica.

**Comment by juandent** [comment]
some insight as to the general architecture of the library, so i could explain how it works at least a little bit! and probably more questions that will be arising as i go further into the creation of the first course... the second course will deal with template metaprogramming an area of C++ i am still entering although i have made a lot of progress..... my C++ experience was with pre C++11 object oriented style of programming and only in the last 5 years have I entered into modern C++ currently managing some C++20 aspects (such as concepts, some modules - although I would love to have some literature on how to mix includes with modules, fold expressions etc etc)...

**Comment by juandent** [comment]
maybe a UML based picture of the architecture plus some explanation of technical implementation details...

**Comment by juandent** [comment]
BTW do you know of a tool I can get that allows debugging of sqlite triggers? ------ sorry out of context

**Comment by fnc12** [comment]
> BTW do you know of a tool I can get that allows debugging of sqlite triggers? ------ sorry out of context

What do you mean by 'debugging'? If you want to get a notification that trigger was fired then just add insert command to trigger command list with insert into some log table you've created before.

P.S. Probably it will be more comfortable for you to post dedicate questions as discussions here on github. Please check 'Discussions' tab

**Comment by juandent** [comment]
by debugging I mean being able to trace through its statements like one can do in SQLSERVER from MS

**Comment by fnc12** [comment]
I never faced such a task. But I am sure you'll find some useful info here https://www.sqlite.org/debugging.html. I am also reading it right now cause I am interested to find out the answer

**Comment by juandent** [comment]
like works inside a check clause if ANDed with true just as generated_always_as works if we add 0 (any number) to it:

workaround the check clause:
```C++
        auto storage = make_storage({},
                                    make_table("BOOK",
                                               make_column("Book_id", &Book::id, primary_key()),
                                               make_column("Book_name", &Book::name),
                                               make_column("Pub_name", &Book::pubName),
                                               make_column("PRICE", &Book::price, check(c(&Book::price) > 0)),
                                               check(true && like(&Book::pubName, "M%"))));
```

workaround the generated_always_as:
```C++
    auto storage = make_storage("",
                                make_table("objects",
                                           make_column("name", &Object::name),
                                           make_column("name_len", &Object::nameLen, generated_always_as(length(&Object::name)+0)),
                                           make_column("number", &Object::number)));
    storage.sync_schema();
```

The cause of the bug is the same!!

Right?

**Comment by fnc12** [comment]
looks like `CHECK` is serialized incorrectly in case of table level. I've fixed it and going to merge it today. Thanks for reporting!

**Comment by fnc12** [comment]
the fix is here https://github.com/fnc12/sqlite_orm/pull/894. I'll merge it once CI is finished successfully

**Comment by fnc12** [comment]
merged. Please check out `dev` branch

**Comment by fnc12** [comment]
does it work?

**Comment by juandent** [comment]
Will check ASAP I have some trouble just yet

Thank you for correcting it so fast!!

**Comment by juandent** [comment]
yes it works!!! Great job!!
