### ISSUE TITLE
post-increment operator for statement_binder<T>

### ISSUE THREAD

**Issue by elwinarens** [fnc12/sqlite_orm#9]
First off, thanks for the work you've put in so far! I'm having a stab at using this project as the lib for implementing sqlite into a side project.

The statement_binder struct templates bind functions do a post-increment on `int index` that's passed by value:

https://github.com/fnc12/sqlite_orm/blob/master/include/sqlite_orm/sqlite_orm.h#L1358-#L1423

So aren't all these post-incremented values of index not used, or is it late and am i seeing things not clearly?

**Comment by fnc12** [comment]
@elwinarens thanks for using the lib. It turned out I forgot to add postincrement operator. I'll fix it.

**Comment by fnc12** [comment]
@elwinarens fixed it in 1b1bdd9b8380a767e07c07d9e72f6be1c8d12de9.
The goal of `statement_binder` is described in [enum_binding.cpp](https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp) example. There is no need to increment index inside `statement_binder` - `sqlite_orm` does it for you inside `storage`'s functions. Thanks for the notice and please feel free to ask any questions.

**Comment by elwinarens** [comment]
Awesome, thanks!
