### ISSUE TITLE
SQLITE_ENABLE_MATH_FUNCTIONS defined but many functions throws exception

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#902]
In file tests\built_in_functions_tests\math_functions.cpp, I am getting exceptions for many of the math functions... is this file supposed to work? 
I defined SQLITE_ENABLE_MATH_FUNCTIONS in the preprocessor.

What can be happening?

Regards,
Juan

**Comment by fnc12** [comment]
It happens cause you need to compile SQLite with `SQLITE_ENABLE_MATH_FUNCTIONS` also

**Comment by juandent** [comment]
Hi Eugene,

I downloaded the sqlite-amalgamation-3370200 from the sqlite.org site and tried building the DLL and import lib but the produced files are very very small compared with the ones I got already built.

I used 

> cl sqlite3.c -link -dll -out:sqlite3.dll -implib:slqite3.lib

to compile with MS VC++ 2022 64bits. What am I doing wrong?

**Comment by juandent** [comment]
Sorry I am missing a file with the exports of the sqlite3.dll!!!
I tried producing the file with 

> lib /DEF sqlite3.obj 

to no avail.
What #defines are normally defined when compiling the dll?

Please help I am at a loss here

**Comment by fnc12** [comment]
I am not familiar with Windows command line. I can tell you for sure that there is no common set of defines. All defined are defined manually when they are required. I can tell you how it is done on mac/linux:
```
clang -o sqlite sqlite3.c -DSQLITE_ENABLE_MATH_FUNCTIONS`
```
Note `-DSQLITE_ENABLE_MATH_FUNCTIONS`. It is added manually by me. This flag means `hey compiler, please enable flag SQLITE_ENABLE_MATH_FUNCTIONS for me during sqlite3.c compilation`. I am sure there is a way to define a compilation flag on windows also. Try to google it 'cl define compilation flag' or similar

**Comment by fnc12** [comment]
I know how to specify compilation flags inside visual studio projects (no command line). I can tell you how to do it instead

**Comment by fnc12** [comment]
Have a good time!

**Comment by juandent** [comment]
Got my solution.. the command line for Windows and Visual C++ is:

cl sqlite3.c  -DSQLITE_API=__declspec(dllexport) -DSQLITE_ENABLE_MATH_FUNCTIONS /Zi  -link -dll -out:sqlite3.dll

**Comment by fnc12** [comment]
great. Does everything work?
