### ISSUE TITLE
Incorrect response for case_ in tests\unique_cases\prepare_get_all_with_case.cpp

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#903]
Hi Eugene,

Just found incorrect response in TEST_CASE("Prepare with case") in tests\unique_cases\prepare_get_all_with_case.cpp.

In particular the following code does not filter at all:

```C++
    const std::string name = "Iggy";
// Juan added these inserts
    storage.insert(UserProfile{ 1, "Iggy" });
    storage.insert(UserProfile{ 2, "I%" });

        auto statement = storage.prepare(get_all<UserProfile>(where(is_equal(
            &UserProfile::firstName,
            case_<std::string>(name).when((length(name) > 0), then(name)).else_(&UserProfile::firstName).end()))));
        // Juan added this next:
        auto t = storage.execute(statement);
// t returns 2 rows -- i.e. the first when is never selected and the return from the case_ is &UserProfile::firstName which
// of course matches every row in the table!!
```

To get the desired behavior we have to eliminate the "name" following <std::string> like this:

```C++
        auto statement0 = storage.prepare(get_all<UserProfile>(where(is_equal(
            &UserProfile::firstName,
            case_<std::string>().when((length(name) > 0), then(name)).else_(&UserProfile::firstName).end()))));
        auto t0 = storage.execute(statement0);  // returns only row with id 1 as it should!
```

Can you confirm this?
You need more info?

Regards,
Juan

**Comment by juandent** [comment]
I also recommend to add this test after inserting a couple of UserProfiles which illustrates multiple WHEN clauses:

```C++
    auto rows = storage.get_all<UserProfile>();
        auto statement3 = storage.prepare(get_all<UserProfile>(where(is_equal(
            &UserProfile::id,
            case_<int>(c(&UserProfile::id) * 2).when(2, then(1)).when(4, then(2)).else_(3).end()))));
        auto r2 = storage.execute(statement3);
        REQUIRE(r2.size() == rows.size());  // does not filter at all
```

What do you think ? Like it?

Regards,
Juan

**Comment by fnc12** [comment]
> In particular the following code does not filter at all:

It is not intended to filter anything. It is just a test code. I written it right after `CASE` feature appearance. How tests like these appear? Once new feature appears I write tests for all options. `case_` function has two options: `case_()` and `cast_(something)`. And these calls must not throw exceptions. It is not intended to construct correct SQL query. It is intended to send syntactically correct SQL but doesn't guarantee any meaning. Why I add tests like these? Cause if `case_` once becomes serialize incorrectly these tests will fire. It is important. Tests are not intended to contain meaningful queries. Examples must have meaningful queries. Examples are located at 'examples' folder.

> I also recommend to add this test after inserting a couple of UserProfiles which illustrates multiple WHEN clauses:

I'll add this. Your tests is meaningful so it is more valuable. Thank you, Juan.
