### ISSUE TITLE
Does sqlite_orm support the ALL operator?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#916]
I have this code that compiles but throws an exception on execution:

```C++
        auto rows = storage.select(
            columns(&Employee::firstName, &Employee::lastName, &Employee::salary),
            where(greater_than(&Employee::salary,
                               all(select(&Employee::salary, where(is_equal(&Employee::firstName, "Alexander")))))));
```
it was taken from examples\subquery.cpp and I added the all. Funny thing, I could not find the ANY operator.
Am I using ALL incorrectly?  Is ANY part of SQLITE?

Is the ALL redundant? Is the behavior of the subquery taken equally with or without the ALL?

The subquery returns 2 rows, thus the where(greater_than(&Employee::salary means that it must be greater than each and every row in the subquery? Isn't this the intent of the ALL operator anyway? What if I wanted greater than to be compared with any of the rows in the subquery? Without the ANY keyword (which I did not find in SQLITE.org) how would I do it?

**Comment by fnc12** [comment]
What is ANY operator? Do you have SQLite doc link about it?
`ALL` exists as `all` function in `sqlite_orm`. If you want to use it you need to write:
```c++
storage.select(all(avg(&User::id)))
```

**Comment by juandent** [comment]
Forget about ANY it is not supported by SQLITE

**Comment by juandent** [comment]
the ALL must precede the subquery select in standard SQL
For op being > in the where clause of the outer select, then 

where Employee::salary > ALL (table expression)

evaluates to true if Employee::salary > y for any y in the result set of the subquery (here table expression)...

whereas 

where Employee::salary > ANY (table expression)
evaluates to true if Employee::salary > y for at least one y in the result set of the subquery (table-expression)

**Comment by fnc12** [comment]
I don't understand why ALL must precede the subquery select. As far as I know `ALL` must be located right after `SELECT` and no other way. Please show me docs about preceding order.

**Comment by juandent** [comment]
[https://www.w3resource.com/sql/special-operators/sql_all.php](url)

**Comment by fnc12** [comment]
Ok I see. Looks like these operators are not supported in SQLite at all. If there are please show me cause I never saw it existing in SQLite docs.

**Comment by juandent** [comment]
Ok - now omitting ALL and ANY, how does the condition behave: as if ALL had been used or as if ANY had been used?
Again my SQL code being:

```C++
auto rows = storage.select(
            columns(&Employee::firstName, &Employee::lastName, &Employee::salary),
            where(greater_than(&Employee::salary,
                               select(&Employee::salary, where(is_equal(&Employee::firstName, "Alexander"))))));
```

salary must be greater than every y in the subquery? or salary must be greater than at least 1 y in the subquery??

**Comment by juandent** [comment]
from my tests it seems it is behaving as if ALL had been in use

**Comment by fnc12** [comment]
this query shows first name, last name and salary of employees who has salary greater than salary of a person with first name 'Alexander'

**Comment by juandent** [comment]
No, the query shows data for employees who have salary greater than EVERY person with first name "Alexander"
The DB has 2 Alexanders so salary must be greater than the greater salary of these Alexanders...
