### ISSUE TITLE
optional escape for the like operator in trigger does not work

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#917]
Modified this trigger in examples\triggers.cpp to use the escape option but it does not work:

```C++
make_trigger("validate_email_before_insert_leads",
                                             before()
                                                 .insert()
                                                 .on<Lead>()
                                                 .begin(select(case_<int>()
                                                                   .when(not like(new_(&Lead::email), "AA").escape("A"), 
                                                                         then(raise_abort("Invalid email address")))
                                                                   .end()))
                                                 .end())
```

Changed the code after storage.sync_schema() to:

```C++
    try {
        storage.insert(Lead{0, "John", "Doe", "jjj", "A"});  // "4089009334"
    } catch(const std::system_error &systemError) {
        cout << "error: " << systemError.what() << endl;
    }
```

This insert should not break the trigger since like expects a literal A. But it does!

Am i doing something wrong?

Regards,
Juan

**Comment by juandent** [comment]
Yes I tried this from client:

select * from employees e where e.first_name like "AA%" escape "A"

and it returns all first_names that start with A.

**Comment by fnc12** [comment]
damn looks like the the third argument cannot be bound. I need to check it. SQLite may have such exceptions. Or the reason is different. Anyway et me put 'investigation' label here and check it out soon.

**Comment by juandent** [comment]
High Eugene!
Its not a bug!! I am sorry... 
See:
```C++
    //  INSERT INTO leads (first_name, last_name, email, phone)
    //  VALUES('John', 'Doe', 'jjj', '4089009334');
    try {
        storage.insert(Lead{ 0, "John", "Doe", "A", "4089009334" });
    }
```

Got confused between phone and email - thought email was last!!!

You can forget about it now!

Real sorry...

Juan
