### ISSUE TITLE
Cannot order_by a union_all statement

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#920]
Please help with this query:

```C++
        auto rows = storage.select(
            union_all(select(columns(&Department::employeeId, &Employee::name, &Department::dept),
                inner_join<Department>(on(is_equal(&Employee::id, &Department::employeeId)))),
                select(columns(&Department::employeeId, &Employee::name, &Department::dept),
                    left_outer_join<Department>(on(is_equal(&Employee::id, &Department::employeeId))))), order_by(&Employee::name));
```

It compiles fine without the order_by. Example taken from examples\union.cpp

I get this error in VStudio 2022:

> error C2338: Cannot use args with a compound operator

The order_by works fine if I place it in the subqueries like so:
```C++
            auto left = select(columns(&Department::employeeId, &Employee::name, &Department::dept),
                inner_join<Department>(on(is_equal(&Employee::id, &Department::employeeId))), order_by(&Employee::name));
            auto right = select(columns(&Department::employeeId, &Employee::name, &Department::dept),
                left_outer_join<Department>(on(is_equal(&Employee::id, &Department::employeeId))), order_by(&Employee::name));
            auto rows = storage.select(union_all(left, right));
```

Thanks!

**Comment by juandent** [comment]
Nor can i order_by an intersect statement as in:  (taken from examples\except_intersection.cpp)

```C++
auto rows = storage.select(intersect(select(&DeptMaster::deptId), select(&EmpMaster::deptId)), order_by(&DeptMaster::deptName));
```

**Comment by fnc12** [comment]
How would you write this in raw SQL?

**Comment by juandent** [comment]
SELECT EMP_ID, NAME, DEPT
         FROM COMPANY
        INNER JOIN DEPARTMENT
        ON COMPANY.ID = DEPARTMENT.EMP_ID
        UNION ALL
        SELECT EMP_ID, NAME, DEPT
        FROM COMPANY
        LEFT OUTER JOIN DEPARTMENT
        ON COMPANY.ID = DEPARTMENT.EMP_ID
        ORDER BY NAME

**Comment by fnc12** [comment]
your `order_by(&Employee::name)` is located outside of `select` parentheses. Move `order_by(&Employee::name)` inside parentheses

**Comment by juandent** [comment]
got it!! thanks
