### ISSUE TITLE
No member named 'column_name' when using child classes

### ISSUE THREAD

**Issue by jdrempel** [fnc12/sqlite_orm#925]
Hi there, first let me say that I really love and appreciate this ORM. It's fairly intuitive to use while giving the user a lot of control. Thanks!

My problem is related to #632 and #854 (or at least appears similar) but I haven't had success even after following the advice from those discussions.

I have a base class `Record` from which `UserRecord` and `AccountRecord` both inherit. `Record` contains the `pk` member. The child classes contain more detailed info (shown later on below). Compilation fails on `database.sync_schema();`, with the message:
`‘struct sqlite_orm::internal::storage_impl<>’ has no member named ‘column_name’`.

Here is my storage construction:
```cpp
inline auto createDatabase(const std::string &dbFilename) {
    using namespace sqlite_orm;

    return make_storage(
            dbFilename,
            make_table<UserRecord>(
                    "users",
                    make_column("ID", &UserRecord::pk, autoincrement(), primary_key()),
                    make_column("first_name", &UserRecord::firstName),
                    make_column("last_name", &UserRecord::lastName),
                    make_column("key_hash", &UserRecord::keyHash)
            ),
            make_table<AccountRecord>(
                    "accounts",
                    make_column("ID", &AccountRecord::pk, autoincrement(), primary_key()),
                    make_column("label", &AccountRecord::label),
                    make_column("username", &AccountRecord::username),
                    make_column("key_hash", &AccountRecord::keyHash),
                    make_column("url", &AccountRecord::url),
                    make_column("created", &AccountRecord::created),
                    make_column("last_accessed", &AccountRecord::lastAccessed),
                    make_column("last_modified", &AccountRecord::lastModified),
                    make_column("expiry", &AccountRecord::expiry),
                    make_column("userID", &AccountRecord::userID),
                    foreign_key(&AccountRecord::userID).references(&UserRecord::pk)
            )
    );
}
```

And my struct definitions:
```cpp
struct Record {
    virtual ~Record() = default;

    int pk;

    explicit Record(int id) : pk(id) { }
    Record() : Record(-1) { }
};

struct UserRecord : public Record {
    enum class UserType {
        Normal = 1,
        Admin = 2,
        SuperAdmin = 3
    };

    std::string firstName;
    std::string lastName;
    std::string keyHash;
    UserType typeID;

    UserRecord() : Record(), typeID(UserType::Normal) { }
};

struct AccountRecord : public Record {
    std::string label;
    std::string username;
    std::string keyHash;
    std::string url;
    long created;
    long lastAccessed;
    long lastModified;
    long expiry;
    int userID;

    AccountRecord() : Record(), created(0), lastAccessed(0), lastModified(0), expiry(0), userID(-1) { }
};
```

Any ideas what I am doing wrong here? As per the other threads I have explicitly stated what types I want to use for my tables.

**Update**

I see now that removing the `foreign_key(&AccountRecord::userID).references(&UserRecord::pk)` line from the "accounts" table causes the problem to go away. But I need this foreign key... what's the best way around this? I've tried changing the reference to `references(&Record::pk)` but that does not help.

**Comment by fnc12** [comment]
Hi. Thanks for such nice words about this lib. I really appreciate it.

Yes the problem is related to foreign key. You do everything right. Either we'll find a way to handle it or I will fix it. Please try to replace 
```c++
foreign_key(&AccountRecord::userID).references(&UserRecord::pk)
```
with
```c++
foreign_key(&AccountRecord::userID).references(column<UserRecord>(&UserRecord::pk))
```
If it doesn't work I'll make a fix.

**Comment by jdrempel** [comment]
That works, thank you for your help!
