### ISSUE TITLE
can't create an update based on a select

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#926]
Hi Eugene,

Please help! I have this update_all based on a select -- it is for the course I want to show how powerful sqlite_orm is!

My statement is like this and I am working in examples\core_functions.cpp:

```C++
storage.update_all(set(c(&Contact::phone) = select(&Customer::phone,from<Customer>(), 
    where(c(&Customer::id) == 1))));
```
I get an exception saying "too many tables specified"...

I am trying to show that it is possible to create an UPDATE where the column's new value is taken from a SELECT...
I have tried this SQL code in a client when connected to database core_functions.sqlite:

```SQL
UPDATE contacts 
SET phone =(
    SELECT phone 
    FROM customers 
    WHERE customers.CustomerId = contacts.contact_id);
``` 

and it updates 24 rows so it is  possible in SQLITE...

Never mind the semantics... this is a serialization problem I believe

Please copy the C++ statement above into core_functions.cpp and test yourself...

Regards,
Juan

**Comment by juandent** [comment]
there is an example in https://www.w3resource.com/sqlite/sqlite-update.php where 

```SQL
Update using multiple tables
UPDATE orders SET item_name=(SELECT prod_name FROM prod_mast WHERE prod_id = item_id);
```

**Comment by fnc12** [comment]
Hi Juan. Let me try to find out the clue. Thanks

**Comment by juandent** [comment]
Hi Eugene,

Not to rush you but have you had some time regarding this issue?

Regards,
Juan

**Comment by juandent** [comment]
It is a very important non-trivial SQL that I want to present to my students!!
I am sure they will be impressed by sqlite_orm

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/pull/930

**Comment by juandent** [comment]
great!
