### ISSUE TITLE
Allow `nullptr` to be bindable to a function expecting a 'pointer argument'

### ISSUE THREAD

**Issue by trueqbit** [fnc12/sqlite_orm#928]
When using the 'pointer-passing interface' feature, I'd like to be able to just pass a `nullptr` to a function expecting a 'pointer argument' instead of going through the cumbersome effort of creating typed 'null pointers'. This is also a C++ programmer's natural expectation.

E.g., given
```
struct remember_fn {
    int64 operator()(int64 value, carray_pointer_arg<int64> pv) const {
        if(int64* observer = pv) {
            *observer = value;
        }
        return value;
    }

    static constexpr const char* name() {
        return "remember";
    }
};
```
Use nullptr
```
select(func<remember_fn(&Object::id, nullptr))
```
instead of 
```
select(func<remember_fn(&Object::id, statically_bindable_pointer<carray_pvt>(nullptr))
```

**Comment by fnc12** [comment]
Hi Klaus. Sounds nice. Can you implement this or you expecting me to implement this?

**Comment by trueqbit** [comment]
I already implemented it (and I wouldn't expect you to do it 😉)!

However while I was writing unit tests to test the serialization when dumping a statement, I discovered inconsistencies, which I summarized in #929.
