### ISSUE TITLE
Serializer for explicit column dosn't find correct column

### ISSUE THREAD

**Issue by trueqbit** [fnc12/sqlite_orm#933]
There's a line for the statement serializer of a column_pointer that tries to get the column name like this:
```c++
std::string statement_serializator<column_pointer<T, F>>::operator()(const column_pointer<T, F>& cp, const C& context) const {
    // ...
    if(auto columnNamePointer = context.impl.column_name_simple(cp.field)) {
    }
    // ...
}
```
This however is wrong for two reasons:
1. `storage_impl<>::column_name_simple()` doesn't walk the 'table storage chain'
2. the serializer should actually call `storage_impl<>::column_name(cp)`

I guess this was just an oversight in the first place as `column_name(column_pointer<>)` exists but remained unused, and the original intention was to use it.

**Comment by fnc12** [comment]
yeah looks like an oversight
