### ISSUE TITLE
compiler error when "remove" called twice on MSVC

### ISSUE THREAD

**Issue by jmorrill** [fnc12/sqlite_orm#94]
Related to: [issue #84](https://github.com/fnc12/sqlite_orm/issues/84
)

I ran into this issue and I believe the "remove" method need to be modified also.

example:

**current**: _impl.table.for_each_column([&] (auto c) {_

vs.

**fixed** :   _impl.table.for_each_column([this, &primaryKeyColumnNames](auto c) {_

**Comment by fnc12** [comment]
Hi. Thanks for using the lib. Sorry for these silly windows errors: case is that I don't use c++ for windows and don't have CI host with windows. I guess I'll work it out with getting a windows host for CI (and not only windows I hope). Please wait ten minutes - I'll create a fix branch and merge it.

**Comment by fnc12** [comment]
which visual studio du you use?

**Comment by jmorrill** [comment]
I use VS 2017 15.5.5

**Comment by jmorrill** [comment]
Gave a slightly bad comment:

This line gives a warning in clang:
impl.table.for_each_column([this, &primaryKeyColumnNames](auto c) {
**warning: lambda capture 'this' is not used [-Wunused-lambda-capture]**

So I guess you don't need to capture 'this'

**Comment by fnc12** [comment]
please provide line numbers

**Comment by jmorrill** [comment]
[4916](https://github.com/fnc12/sqlite_orm/blob/3b457a23e73936121f9c81faf4544c0a44a53234/include/sqlite_orm/sqlite_orm.h#L4916)

**Comment by fnc12** [comment]
@jmorrill please check out the latest commit and close the issue if everything is fine or provide new error info if there are some. Thanks

**Comment by jmorrill** [comment]
Works great!  Thanks for the great library and support!!
