### ISSUE TITLE
can't compile with aarch64-linux-gnu-gcc (Linaro GCC 6.3-2017.05) 6.3.1

### ISSUE THREAD

**Issue by vjeson** [fnc12/sqlite_orm#940]
code from exmaple ,can be compile with x64 gcc ,but not work with aarch64-linux-gnu-gcc  (Linaro GCC 6.3-2017.05) 6.3.1
`
 User user{-1, "Jonh", "Doe", 664416000, std::make_unique<std::string>("url_to_heaven"), 3 };

 auto insertedId = storage.insert(user);
        cout << "insertedId = " << insertedId << endl;      //  insertedId = 8
        user.id = insertedId;
`
`
# throw exception here
 using table_type = typename std::decay<decltype(tImpl.table)>::type;
                using columns_type = typename std::decay<decltype(tImpl.table.columns)>::type;
`
include/sqlite_orm/sqlite_orm.h:14193:71: error: 'const struct sqlite_orm::internal::column_t<AlarmDb::User, int, const int& (AlarmDb::User::*)() const, void (AlarmDb::User::*)(int)>' has no member named 'table'
                 using table_type = typename std::decay<decltype(tImpl.table)>::type;

**Comment by fnc12** [comment]
what branch do you use?

**Comment by vjeson** [comment]
master, also tested with other release verson

**Comment by vjeson** [comment]
It's gcc version issue , when I upgrade to gcc aarch64-linux-gnu-gcc (Linaro GCC 7.5-2019.12) 7.5.0 ,it's ok
