### ISSUE TITLE
Bulk Insert/Replace

### ISSUE THREAD

**Issue by lasyakoechlin** [fnc12/sqlite_orm#946]
Hi there,

I am using v1.7.1. I have a local sqlite database file and I'm trying to merge data from another sqlite database file which is supplied at runtime. In general, there could be multiple such files that need to be merged.

In general, the number of rows to be merged would be ~20. But occasionally, I get large updates ~20,000 rows.

I was trying to use the bulk-replace feature.
```
auto new_data = new_storage.get_all<Data>();

storage.replace_range(new_data .begin(), new_data.end());
```

When I run the above, I get the following error:
```
too many SQL variables: SQL logic error or missing database
```

I have also tried something similar, such as:
```
for(auto& d : new_storage.iterate<Data>()) {
       storage.replace(d);
}
```
which also resulted in the specific error.

I opened up the file manually using an sqlite database viewer and the `new_storage`-based appears to have the correct data.

As well, when searching through sqlite3's code, I see the following error, which reflects what I am seeing:
![image](https://user-images.githubusercontent.com/60749601/157332513-528d67c9-0d86-45e5-aeea-20a57676408d.png)

**Comment by fnc12** [comment]
yes SQLite has `SQLITE_LIMIT_VARIABLE_NUMBER` limit. You can get it at runtime using
```c++
auto variableNumber = storage.limit.variable_number();    //  decltype(variableNumber) is int
```
Just limit amount if inserts with it and everything will go fine.

**Comment by lasyakoechlin** [comment]
Thanks for the quick response! So, I have tried limiting the number of inserts.

I am fetching the variable number and limiting as follows:

```
for(int i = 0 ; i < datas.size() ; i += max_num_inserts) {

                    int start_idx = i * max_num_inserts;
                    int end_idx = start_idx + max_num_inserts - 1;

                    auto start_iter = datas.begin() + start_idx;
                    auto end_iter = end_idx < new_map_tile_datas.size()
                                    ? datas.begin() + end_idx
                                    : datas.end();

                   // Added log here for max_num_inserts, i, start_idx, end_idx

                    storage.replace_range(start_iter, end_iter);
}
```

Based on my log, I get:
```
max_num_inserts = 999
i: 0, start_idx: 0, end_idx: 998
```
immediately followed by a crash.

Again the same crash about `too many SQL variables`

**Comment by fnc12** [comment]
probably you read the limit incorrectly. Try to reduce it (`max_num_inserts` var) just for tests and run this code again.

BTW what are you doing? I mean is this a migration of the same table from one db to another or is this a data transformation?

**Comment by lasyakoechlin** [comment]
So, I'm a bit confused. I used:

`int max_num_inserts = storage.limit.variable_number();`

When debugging, this gives me 999.

However, it seemed like if I used a value greater than 100, I get that too many SQL variables error.

Will this differ depending on the specific hardware? I'm concerned that hard-coding, say 100, will lead to some devices failing and others working.

As well, I would ideally like to do the maximum bulk-insert.

So, I guess my question is what exactly does this variable represent? Is it the total amount of rows that can inserted at once? Or if one row has 2 columns, is it actually `storage.limit.variable_number() / num_columns` ?

Thanks for the clarification!

**Comment by lasyakoechlin** [comment]
Also, can you please clarify the usage of insert_range vs. replace_range?

**Comment by fnc12** [comment]
as far as I know `storage.limit.variable_number()` or `SQLITE_LIMIT_VARIABLE_NUMBER` stands for amount of rows that can be inserted within one query. I may be wrong. I recommend you to perform the same operations with raw SQLite skipping `sqlite_orm` just for testing cause looks like the issue is not related to `sqlite_orm`.

`insert_range` and `replace_range` perform bulk insert/replace within one query like this:
```sql
INSERT INTO users (id, name)
VALUES (1, 'Calvin'), (2, 'Alex), ...
```
This type of query is related to `SQLITE_LIMIT_VARIABLE_NUMBER`.

BTW what are you doing? I mean is this a migration of the same table from one db to another or is this a data transformation?

**Comment by fnc12** [comment]
@lasyakoechlin are you there?

**Comment by fnc12** [comment]
@lasyakoechlin are you there?

**Comment by fnc12** [comment]
@lasyakoechlin are you there?

**Comment by fnc12** [comment]
closed due to inactivity
