### ISSUE TITLE
MSVC 2015 Compile Error

### ISSUE THREAD

**Issue by iGwkang** [fnc12/sqlite_orm#957]
1. Initialize struct with { } initialization list 
2. error C2672: “static_if”

**Comment by fnc12** [comment]
1) what is your branch
2) please pass the whole error text here

**Comment by iGwkang** [comment]
> 1. what is your branch
> 2. please pass the whole error text here

release 1.7.1

**Comment by fnc12** [comment]
IDK Chinese so this text cannot help me to find a clue. Anyway check your C++ standard: try to enable C++17 or switch to vs2019 or vs2022

**Comment by fnc12** [comment]
@iGwkang did it work?

**Comment by iGwkang** [comment]
@fnc12 sorry, I can only use vs2015 due to the project

**Comment by fnc12** [comment]
probably some of C++14 features are not supported in vs2015 https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170. I reckon it is either [N3652 Extended constexpr](https://wg21.link/n3652) or [N3653 Default member initializers for aggregates](https://wg21.link/n3653)

**Comment by fnc12** [comment]
@iGwkang are you there?

**Comment by fnc12** [comment]
@iGwkang are you there?

**Comment by iGwkang** [comment]
> @iGwkang are you there?

sorry, since my project has to use vs2015, I gave up using sqlite_orm.

**Comment by njchim** [comment]
i know this has been marked closed, but i am stuck using 2015 for a legacy project and would love to use sqlite_orm. is there any workaround at all for these static_if errors??

**Comment by juandent** [comment]
I have VS 2015 and it compiles the unit tests without problems - there are some features that are not available in VS2015... have you downloaded the latest dev branch?
I am part of the team of collaborators for sqlite_orm

**Comment by juandent** [comment]
Forget about vcpkg for now
Create a directory c:\Components
in the command line at the root of C:\Components write:
`git clone https://github.com/fnc12/sqlite_orm.git`
`git checkout dev`

**Comment by njchim** [comment]
ok. i'll give that a shot

**Comment by juandent** [comment]
Download the documentation PDF from https://sqliteorm.com/docs
go to **Installing the sqlite_orm library and DSL**

**Comment by juandent** [comment]
Also follow the instructions to build the C++ projects in the section **To build the C++ projects for unit-testing in Windows OS do the following:**

**Comment by njchim** [comment]
grabbing from dev fixed it. thanks!

**Comment by juandent** [comment]
assuming it id 64bit platform, download 
![image](https://user-images.githubusercontent.com/5367573/172905754-8aeec4f8-8b66-464f-a67f-45b974008687.png)

**Comment by juandent** [comment]
then follow the steps in the PDF to build the C++ projects for unit-testing in Windows OS

**Comment by juandent** [comment]
Great!

But don't stop there, install using CMAKE-GUI

**Comment by juandent** [comment]
> grabbing from dev fixed it. thanks!

did you do the `git clone ....` before checking out dev?

**Comment by njchim** [comment]
yeah. im good with cmake workflow. everything is working. thanks!

**Comment by juandent** [comment]
great! Any problems please write here 👍
