### ISSUE TITLE
Many to Many relationships

### ISSUE THREAD

**Issue by CarvellWakeman** [fnc12/sqlite_orm#96]
I think I'm starting to get the hang of this ORM and it has proven to be quite useful.

I have a system which has two many-to-many relationships. I've looked through the examples, and the subentities example mentions one-to-many examples, but I was not able to find any mention of Many to Many. Does this ORM have a way to accomplish that?

I would be able to create relationship tables that map objects together, but I was curious if there was a built  in convention already.

**Comment by fnc12** [comment]
Please describe your schema and I'll give you an answer. Thanks

**Comment by CarvellWakeman** [comment]
My system may not make much sense without the entire context. If that is the case I can make an analogy that may make more sense.

I have 7 objects in my system: Profile, Zone, Schedule, LED, LEDState, DailyState, and Controller.
Each object has an ID, and pointers to other objects in the system.

There are a few one-to-many relationships, a one-to-one relationship, and two many-to-many relationships.

**One-to-One**:
- Zone has one Schedule, Schedule has one Zone

**One-to-Many**:
- Profile has many Zones, Zone has one Profile
- Controller has many LEDs, LED has one Controller

**Many-to-Many**:
- Zone has many LEDs, LED has many Zones (each profile defines a set of zones, LED can only be in one of these zones, but can be in multiple zones system wide).
- Schedule has many (7) DailyStates, DailyStates can be part of many schedules.
- DailyState has many LEDStates, LEDStates can be part of many DailyStates (DailyStates have a map of int time, LEDState*)

I am trying to design a system for the three Many-to-Many relationships for my system.
Normally I would do this by making a relationship table between the two objects, but I am wondering if the ORM has a built in method of accomplishing this.

EX: Schedule_DailyState
      Column: Schedule_id
      Column: DailyState_id

I would build a class which holds these two values and create a table with two foreign keys, and after loading the DB I would process these relationship objects and build my system.

**Comment by fnc12** [comment]
There is no built in functionality for implicit accomplishing of many-to-many relations cause lib isn't about implicit things at all. The goal of the lib is a transparency of your schema. So to create many-to-many relations you have to create a third struct/class that holds pair of ids of paired objects. For example:
```c++
struct DailyState {
    int id;
    std::string name;
};

struct LEDState {
    int id;
    std::string name;
};

struct DailyStateToLEDState {
    int dailyStateId;
    int ledStateId;
};

auto storage = make_storage("many_to_many.sqlite",
             make_table("daily_states",
                          make_column("id", &DailyState::id, primary_key()),
                          make_column("name", &DailyState::name)),
             make_table("led_states",
                          make_column("id", &LEDState::id, primary_key()),
                          make_column("name", & LEDState::name)),
             make_table("daily_state_to_led_state",
                          make_column("id", &DailyStateToLEDState::dailyStateId),
                          make_column("name", &DailyStateToLEDState:: ledStateId),
                          primary_key(&DailyStateToLEDState::dailyStateId, &DailyStateToLEDState:: ledStateId)));
```

To add pair just `insert` new `DailyStateToLEDState` into your storage: 
```c++
storage.insert(DailyState{1, "Nickelback"});
storage.insert(LEDState{100, "Together"});
storage.insert(DailyStateToLEDState{1, 100});
// etc
```

And then you can select it with `JOIN` or whatever. If you have any issue please feel free to ask.

**Comment by CarvellWakeman** [comment]
That is what I assumed may be the case. I think that solution will work fine though.

Thank you for your lib and very quick responses!
