### ISSUE TITLE
sync_schema(true) does  not realize when a check clause is added or removed and thus does not update the corresponding table

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#965]
Hi,

I have a schema with a CHECK clause in one of the tables. The constraint is created perfectly the first time one generates the schema with sync_schema(). But then if you remove the CHECK clause in C++, and try to sync the changes into the table, sync_schema does not recognize that there has been a change (an important change!) and thus does not update the corresponding table.

I have tried with sync_schema(true) and sync_schema(false) and the result is the same!

**Comment by juandent** [comment]
the schema and code to reproduce the problem is:

```C++
struct User {
    int64 id;
    std::string name;
};

struct UserView {
    std::string name;
};

inline
decltype(auto) makeSqliteOrm(const char * dbFilePath)
{
    static auto storage = make_storage(dbFilePath,
        make_table("user_table",
            make_column("id", &User::id, primary_key()),
            make_column("name", &User::name)),
            //check(length(&User::name) > 2)),
        make_table("user_view",
            make_column("name", &UserView::name)));

        auto m = storage.sync_schema();
        std::ostringstream oss;
        for (auto& n : m) {
            oss << n.first << " " << n.second << "\t";
        }
        auto s = oss.str();
        std::ignore = s;
    return storage;
}

void useViewSimulation() {
    auto storage = makeSqliteOrm("view_simulation.sqlite");
    storage.insert(User{ .id = -1, .name = "Ln" });
    auto rows = storage.select(columns(&UserView::name));
}
```

**Comment by fnc12** [comment]
yes it does because I did not find a way of checking that `CHECK` constraint exists or not inside database. If you know how to do it please tell me. Usually `sync_schema` compares `PRAGMA table_info` with a schema provided in storage creation

**Comment by juandent** [comment]
so the problem is not knowing if the database table has the constraint or not -- there does not seem to be an API for this... what would happen if we made a column unique after it existed? Does it try to keep the data and only throws if there is a uniqueness violation? or does it not update the column at all or does it drop the table and loose all its data?

**Comment by fnc12** [comment]
nothing will be changed in that case cause storage doesn't see the different between a column and a column with unique constraint. They are equal

**Comment by juandent** [comment]
sorry, what do you mean they are equal? after the uniqueness constraint it will be checked at every insert/update for uniqueness and it did not do that before...

**Comment by juandent** [comment]
BTW can you have a unique column that is also nullable?

**Comment by fnc12** [comment]
> sorry, what do you mean they are equal?

They are equal for algorithm which works inside `sync_schema`.

> can you have a unique column that is also nullable?

Dunno. Depends whether SQLite allows it. `sqlite_orm` allows constructing such a combination

**Comment by juandent** [comment]
Workaround: for a table where you add a CHECK or remove a CHECK, add a column with default value or a nullable column so you force dropping the table and thus updating the CHECK's presence. Then remove the column... all inside sqlite_orm. Let me try it to confirm it works...

**Comment by juandent** [comment]
It does not work! the add column doesn't drop the table -- the CHECK is not added

**Comment by juandent** [comment]
how can I force sync_schema to drop/recreate a table without loosing its data?

**Comment by fnc12** [comment]
actually if `sync_schema` is not enough you can use manual migrations logic: storage has `storage.pragma.user_version` function which stores `int` with schema version. If you need to alter a table and you know that `sync_schema` will not help you then do this:
- on the very first launch make sure that `user_version` is 1. It means that schema version is 1
- later when you need to alter a schema manually check that `user_version` is not equal 2. If yes then call `storage.drop_table`, call `sync_schema` and set `user_version` to 2

You can repeat it again and again with increasing `user_version`. It is called manual migration: you do some things manually but most of things are performed by storage anyway by calling `sync_schema`.

**Comment by juandent** [comment]
but we would loose all data in that table ?

**Comment by juandent** [comment]
check my Data Migration section of the guide
