### ISSUE TITLE
when you add a column to a table, sync_schema(true) drops and recreates the table and looses all its rows!!

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#967]
sync_schema(true) looses all rows from a table when you add a column. If the new column is nullable this shouldn't happen... or if it had a default it should also preserve data.

This uncertainty makes me afraid to make schema changes and i end up implementing an old to new data migration programming it via 2 storages..... data migration is promised by sync_schema but it can end up loosing a whole lot of data if one is not very careful...

**Comment by fnc12** [comment]
please give me a repro example. `sync_schema(true)` must preserve data

**Comment by juandent** [comment]
Start with this:

```C++
struct User {
    int64 id;
    std::string name;
};

void use()
{
    static auto storage = make_storage(dbFilePath,
        make_table("user_table",
            make_column("id", &User::id, primary_key()),
            make_column("name", &User::name),
            
        make_table("user_view",
            make_column("name", &UserView::name)));
        auto m = storage.sync_schema(true);
}
```
Then fill some rows and redefine the user_table by adding a column:

```C++
    static auto storage = make_storage(dbFilePath,
        make_table("user_table",
            make_column("id", &User::id, primary_key()),
            make_column("name", &User::name),
            make_column("born", &User::born)),
        make_table("user_view",
            make_column("name", &UserView::name)));
        auto m = storage.sync_schema(true);
```

the surprise will be that you loose all your data in user_table!!

**Comment by fnc12** [comment]
everything is correct because storage doesn't know what value `born` column must have inside existing rows. If you specify a `default_value` then rows will not be removed

**Comment by juandent** [comment]
ok!! Great Eugene! you solved my headache -- I did not know the code was that smart...

**Comment by jimmy930513** [comment]
@fnc12 In another case also could make tables clear.
1.Init a db and schema
    auto storage = make_storage("test.db",
                                make_table("users",
                                           make_column("id", &User::id, primary_key()),
                                           make_column("name", &User::name),
                                           make_column("age", &User::age)  
                                ));
    storage.sync_schema(true);
2.When I wan't to add a default_value to name, i change my defination to
    auto storage = make_storage("test.db",
                                make_table("users",
                                           make_column("id", &User::id, primary_key()),
                                           make_column("name", &User::name,default_value("")),
                                           make_column("age", &User::age)  
                                ));

It will clear table created by step1. And i debuged it shows default value length different (step 1 default value length is 0,step 2 defult value length is 2) in method <get_remove_add_columns>.

How can i set up a default value to a exsit column and do not occur table drop?
