### ISSUE TITLE
IN throws exception 'near "SELECT": syntax error: SQL logic error'

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#969]
Hi Eugene,
 I thought I better put this as a new issue since you solved the current issue already.

These 2 selects throw exceptions  'near "SELECT": syntax error: SQL logic error'

```C++
auto statement = storage.prepare(select(columns(&Employee::m_empno, &Employee::m_ename, &Employee::m_job, &Employee::m_salary, &Employee::m_deptno),
			where(in(std::make_tuple(&Employee::m_ename, &Employee::m_job, &Employee::m_salary),
				select(intersect(
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary)),
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary), where(c(&Employee::m_job) == "Clerk")
					)))))));
```

and 

```C++
auto statement = storage.prepare(select(columns(&Employee::m_empno, &Employee::m_ename, &Employee::m_job, &Employee::m_salary, &Employee::m_deptno),
			where(c(std::make_tuple(&Employee::m_ename, &Employee::m_job, &Employee::m_salary)).in(
				select(intersect(
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary)),
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary), where(c(&Employee::m_job) == "Clerk")
					)))))));
```

Need schema?

_Originally posted by @juandent in https://github.com/fnc12/sqlite_orm/issues/953#issuecomment-1070851827_

**Comment by fnc12** [comment]
looks like there is parenthesis messing around `INTERSECT` compound operator

**Comment by juandent** [comment]
where exactly?

**Comment by fnc12** [comment]
<img width="1037" alt="Снимок экрана 2022-03-23 в 01 24 41" src="https://user-images.githubusercontent.com/6009640/159559859-8959c826-fdc2-4eee-9d6d-f74423f6d2ef.png">

**Comment by juandent** [comment]
where in this:

```C++
auto statement = storage.prepare(select(columns(&Employee::m_empno, &Employee::m_ename, &Employee::m_job, &Employee::m_salary, &Employee::m_deptno),
			where(in(std::make_tuple(&Employee::m_ename, &Employee::m_job, &Employee::m_salary),
				select(intersect(
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary)),
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary), where(c(&Employee::m_job) == "Clerk")
					)))))));
```

**Comment by juandent** [comment]
I was very careful with the parenthesis: don't see anyone missing - besides the compiler would complain right??

**Comment by fnc12** [comment]
it is serialization issue

**Comment by trueqbit** [comment]
Hi @juandent This is the issue you created out of testing tuples in a subquery, issue #941, right?

I replied there, but repeating on this continuing ticket:

The logic error is a result of the serializer not enclosing the intersect compound in parentheses ([see condition](https://github.com/fnc12/sqlite_orm/blob/02ddef391c13ec9fe552ab2aa6a24fbe29090a45/dev/statement_serializator.h#L1736)).

BTW, in the latest dev branch you can dump an expression before preparing it, such that you can investigate the resulting SQL string more easily, w/o debugging internal sqlite_orm functions. E.g.
```c++
auto expression = select(...);
std::string sql = storage.dump(expression);
auto statement = storage.prepare(expression);
```

**Comment by fnc12** [comment]
I'll fix it today

**Comment by fnc12** [comment]
@juandent code
```c++
auto statement = storage.prepare(select(columns(&Employee::m_empno, &Employee::m_ename, &Employee::m_job, &Employee::m_salary, &Employee::m_deptno),
			where(in(std::make_tuple(&Employee::m_ename, &Employee::m_job, &Employee::m_salary),
				select(intersect(
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary)),
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary), where(c(&Employee::m_job) == "Clerk")
					)))))));
```
is not correct cause it has one redundant `select` call (look for SELECT):
```c++
auto statement = storage.prepare(select(columns(&Employee::m_empno, &Employee::m_ename, &Employee::m_job, &Employee::m_salary, &Employee::m_deptno),
			where(in(std::make_tuple(&Employee::m_ename, &Employee::m_job, &Employee::m_salary),
				SELECT(intersect(
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary)),
					select(columns(&Employee::m_ename, &Employee::m_job, &Employee::m_salary), where(c(&Employee::m_job) == "Clerk")
					)))))));
```
Please note that amount of 'select' must be the same as original SQL query has. It will help you avoiding such error next time.
But bug also exists. The fix is here https://github.com/fnc12/sqlite_orm/pull/980

**Comment by fnc12** [comment]
go to PR page, copy branch name, run
`git fetch origin` to download latest info about branches
`git checkout %branch-name%` to go to required branch
done. Please note that it is the third time I repeat this instruction 🙂

**Comment by juandent** [comment]
No no Eugene it was just the Pull release before merging into dev - it was different than other times ... I apologize my memory is not as good as it used  to be..... please understand this: I have bipolar disorder and that makes me very anxious and have mood swings and the medications affect my memory. I am creating a document called GIT Commands Eugene.docx to store your instructions.. need to ask please some patience and understanding. it is important that you know that it is not always a negative condition, often it gives me a lot of energy and clarity of mind and I can do more than the "normal" person.
But the world of git is new to me and I didn't want to make any mistake...

sorry again...

**Comment by fnc12** [comment]
merged. @juandent please check it out

**Comment by juandent** [comment]
It works like a charm!!

Thank you 🙏 
Juan Dent
