### ISSUE TITLE
Ability to dump expressions

### ISSUE THREAD

**Issue by trueqbit** [fnc12/sqlite_orm#975]
I found it useful to dump not on only a prepared statement, but also an expression.
This is especially useful for investigating an expression if it is  wrong and a call to `storage.prepare(expression)` throws an exception.

So, all in all, I think that the following variants of dumping a statement are nice to have, also because it allows one to understand at a high level how sqlite_orm serializes a statement:

1. Expression before preparing it
  a. parametrized SQL string
  b. unparametrized SQL string
1. Prepared statement
  a. parametrized SQL string
  b. unparametrized SQL string

If you agree there's PR #974 for you to look at.

**Comment by fnc12** [comment]
a very nice a minor feature. Merged. Thanks Klaus

**Comment by fnc12** [comment]
I ran it on my machine before merging. I reckon it is enough. Thanks
