### ISSUE TITLE
use primary_key without autoincrement, the behavior is wrong

### ISSUE THREAD

**Issue by yushb0602** [fnc12/sqlite_orm#982]
I have migrated my project from sqlitecpp into sqlite_orm. But meet two issues when using primary_key.

1.  could set id from my code.

When I'm map AlarmRecord::id to database without autoincrement as the following: 
`make_column("id", &AlarmRecord::id, primary_key())`

my test code:
```
  AlarmRecord alm;
  alm.id = 6666;
  alm.msg = "kkkkk";
  auto t = db.insert(alm);  
  auto a = db.get_all<AlarmRecord>();
  //the insserted object's id is not 666
```

2.  could not update.

When I removed primary_key as the following:
`make_column("id", &AlarmRecord::id)`
The id is controlled by my code without autoincrement feature. But when I use the update, it It popup an exception. it looks like we need primary_key.
` db.update(alm);//`
 
 It is a bug?  Is there a workaroud?

**Comment by fnc12** [comment]
no it is not a bug. `insert` doesn't insert primary primary key column. You can read in the comment of `insert` function. If you want to insert primary key column use `storage.replace` instead.

Also you can update any record with and without PK using `storage.update_all` function.

**Comment by fnc12** [comment]
@yushb0602 did it work?

**Comment by yushb0602** [comment]
Yes, It works well.    I should understand much more about it

**Comment by fnc12** [comment]
https://github.com/fnc12/sqlite_orm/wiki/storage_t%3A%3Ainsert
`storage.insert` is used to insert and obtain new id from database. Some people don't want to create id on their own. That is why API may look strange
