### ISSUE TITLE
Quoting of table identifiers is wrong

### ISSUE THREAD

**Issue by trueqbit** [fnc12/sqlite_orm#989]
The SQLite grammar dictates that identifiers must be quoted using double-quotes; [reference](https://www.sqlite.org/lang_keywords.html).

This is done correctly for column identifiers but not for table identifiers or aliases.

Additionally:
- SQLite recommends quoting all identifiers, such that possible conflicts with current and future keywords are avoided.
- when dumping a statement we must properly escape single-quotes of strings. The serializer for 'bindables' currently doesn't do that [see e.g. C string](https://github.com/fnc12/sqlite_orm/blob/e43103aade8c3bcb693bf677b3a3cbf48bd1b8e5/dev/statement_serializator.h#L91).

An example out of unit tests:
```sql
REPLACE INTO users SELECT 'users_backup'."id", 'users_backup'."name" FROM 'users_backup'
```
must be corrected to
```sql
REPLACE INTO "users" SELECT "users_backup"."id", "users_backup"."name" FROM "users_backup"
```

While we are at it, I highly recommend using utility functions for quoting and escaping.

**Comment by fnc12** [comment]
Yes Klaus you are right. Incorrect quotes is one more topic of legacy. It is got to be fixed. Utility functions is also a good idea.
