### ISSUE TITLE
get usage does support std::optional condition?

### ISSUE THREAD

**Issue by tocky0** [fnc12/sqlite_orm#994]
`auto notJohn2 = storage.get_all<User>(where(not (c(&User::firstName) == "John")));`
but if the condition use optional like this,
```
std::optional<std::string>  opt_name;   
auto notJohn2 = storage.get_all<User>(where(not (c(&User::firstName) == opt_name)));
```
does support this usage? because optional maybe has not value.

**Comment by fnc12** [comment]
it must work out of box. Did you try it?

**Comment by tocky0** [comment]
> 

Yes, I have tried.  as condition, if std::optional has not value, this can not get any result. 
because I want if the std::optional is null, this condition can be ignore.
so the get_all maybe result of `John,  Bill,  Bob, etc`

**Comment by fnc12** [comment]
what SQL query do you expect to call with this statement?

**Comment by tocky0** [comment]
> what SQL query do you expect to call with this statement?

Concern about this, have a wrapper function like this,
```
auto getUser(std::string  first, std::optional<std::string>  last){
    
    // If the `last` param has not value,
     if(!last.has_value()) {
      auto res = storage.get_all<User>(where(c(&User::firstName) == first)
        // here, we can comment this statement. because if not pass a value, will return all rows.
        // and c(&User::lastName) == last)
     );
    } else { // have value 
         auto res = storage.get_all<User>(where(c(&User::firstName) == first)
               and c(&User::lastName) == last)
        );
   }
    return res;
}
```

Use ` if `statement can work, but too redundancy.

**Comment by fnc12** [comment]
or I see. you need a parametrized where condition. Take a look at this https://github.com/fnc12/sqlite_orm/issues/272

**Comment by fnc12** [comment]
@tocky0 is it done?

**Comment by tocky0** [comment]
Yes, it is work.
```
auto result_set = storage.get_all<StatementLine>(where(( not filterCat or (c(&StatementLine::m_category_fid) == category) 
&& ( not filterConcept or  c (&StatementLine::m_concept_fid ) == concept)));
```

by the way, if code like this,
```
auto result_set = storage.get_all<StatementLine>(where(( not filterCat or (c(&StatementLine::m_category_fid) == category) 
// here, replace in `not x0 or x1` with `x0 and x1` ,  not work.
&& ( filterConcept and  c (&StatementLine::m_concept_fid ) == concept)));
```

So, am i missing anything?

**Comment by fnc12** [comment]
no looks like everything is ok. If it is ok I am closing the issue. If you have any issues please feel free to post it here at any time
